from .provider import TrainingPeaksProvider as TrainingPeaksProvider
from _typeshed import Incomplete
from allauth.socialaccount import app_settings as app_settings
from allauth.socialaccount.providers.oauth2.views import OAuth2Adapter as OAuth2Adapter, OAuth2CallbackView as OAuth2CallbackView, OAuth2LoginView as OAuth2LoginView

class TrainingPeaksOAuth2Adapter(OAuth2Adapter):
    provider_id: Incomplete
    def get_settings(self): ...
    def get_hostname(self): ...
    @property
    def access_token_url(self): ...
    @property
    def authorize_url(self): ...
    @property
    def profile_url(self): ...
    @property
    def api_hostname(self): ...
    scope_delimiter: str
    def complete_login(self, request, app, token, **kwargs): ...

oauth2_login: Incomplete
oauth2_callback: Incomplete
