from .utils import AXAttribute as AXAttribute, OldAXAttribute as OldAXAttribute, SRegField as SRegField, get_email_from_response as get_email_from_response, get_value_from_response as get_value_from_response
from _typeshed import Incomplete
from allauth.socialaccount.providers.base import Provider as Provider, ProviderAccount as ProviderAccount

class OpenIDAccount(ProviderAccount):
    def get_brand(self): ...
    def to_str(self): ...

class OpenIDProvider(Provider):
    id: str
    name: str
    account_class = OpenIDAccount
    def get_login_url(self, request, **kwargs): ...
    def get_brands(self): ...
    def get_server_settings(self, endpoint): ...
    def extract_extra_data(self, response): ...
    def extract_uid(self, response): ...
    def extract_common_fields(self, response): ...

provider_classes: Incomplete
