from . import app_settings as app_settings
from django.db import models

class EmailAddressManager(models.Manager):
    def can_add_email(self, user): ...
    def add_email(self, request, user, email, confirm: bool = ..., signup: bool = ...): ...
    def get_primary(self, user): ...
    def get_users_for(self, email): ...
    def fill_cache_for_user(self, user, addresses) -> None: ...
    def get_for_user(self, user, email): ...

class EmailConfirmationManager(models.Manager):
    def all_expired(self): ...
    def all_valid(self): ...
    def expired_q(self): ...
    def delete_expired_confirmations(self) -> None: ...
