version: 2
updates:
  - package-ecosystem: 'yarn'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'poetry'
    directory: '/'
    schedule:
      interval: 'weekly'

  - package-ecosystem: 'docker'
    directory: '/'
    schedule:
      interval: 'weekly'

  # App Level Scanning
  - package-ecosystem: 'docker'
    directory: '/apps/nginx'
    schedule:
      interval: 'weekly'
