from django.db import models
from django.utils.translation import gettext_lazy as _

"""
Historical enums preserved for old migrations.
DO NOT USE IN NEW CODE - these are maintained only for migration compatibility.
"""


class PopulationChoices(models.TextChoices):
    ADULTS = "adults", _("Adults")
    BOYS = "boys", _("Boys")
    CHILDREN = "children", _("Children")
    DOMESTIC_VIOLENCE = "domestic_violence", _("Domestic Violence (DV/IPV)")
    ENHANCED_BRIDGE_HOUSING_FOR_OLDER_ADULTS = "enhanced_bridge_housing_older_adults", _(
        "Enhanced Bridge Housing for Older Adults"
    )
    ENHANCED_BRIDGE_HOUSING_FOR_WOMEN = "enhanced_bridge_housing_women", _("Enhanced Bridge Housing for Women")
    FAMILIES = "families", _("Families")
    GIRLS = "girls", _("Girls")
    HIV_AND_AIDS = "hiv_and_aids", _("HIV/AIDS")
    HUMAN_TRAFFICKING = "human_trafficking", _("Human Trafficking")
    JUSTICE_SYSTEM_EXITING = "justice_system_exiting", _(
        "B7 Bridge Housing for Persons Exiting Justice System Institutions"
    )
    LGBTQ = "lgbtq", _("LGBTQ")
    MEN = "men", _("Men")
    SENIORS = "seniors", _("Seniors (55+)")
    VETERANS = "veterans", _("Veterans")
    WOMEN = "women", _("Women")
    YOUTH = "youth", _("Youth (TAY)")


class SleepingChoices(models.TextChoices):
    BUNK_BEDS = "bunk_beds", _("Bunk beds")
    DORMITORY = "dormitory", _("Dormitory")
    LOW_BARRIER = "low_barrier", _("Low Barrier")
    MOTEL = "motel", _("Motel")
    SHARED_ROOMS = "shared_rooms", _("Shared Rooms")
    SINGLE_ROOM = "single_room", _("Single Room")


class CityChoices(models.TextChoices):
    """DEPRECATED: Kept only for historical migrations. City is now a user-editable string field."""

    AGOURA_HILLS = "agoura_hills", _("Agoura Hills")
    ALHAMBRA = "alhambra", _("Alhambra")
    ARCADIA = "arcadia", _("Arcadia")
    ARTESIA = "artesia", _("Artesia")
    AVALON = "avalon", _("Avalon")
    AZUSA = "azusa", _("Azusa")
    BALDWIN_PARK = "baldwin_park", _("Baldwin Park")
    BELL = "bell", _("Bell")
    BELLFLOWER = "bellflower", _("Bellflower")
    BELL_GARDENS = "bell_gardens", _("Bell Gardens")
    BEVERLY_HILLS = "beverly_hills", _("Beverly Hills")
    BRADBURY = "bradbury", _("Bradbury")
    BURBANK = "burbank", _("Burbank")
    CALABASAS = "calabasas", _("Calabasas")
    CARSON = "carson", _("Carson")
    CERRITOS = "cerritos", _("Cerritos")
    CLAREMONT = "claremont", _("Claremont")
    COMMERCE = "commerce", _("Commerce")
    COMPTON = "compton", _("Compton")
    COVINA = "covina", _("Covina")
    CUDAHY = "cudahy", _("Cudahy")
    CULVER_CITY = "culver_city", _("Culver City")
    DIAMOND_BAR = "diamond_bar", _("Diamond Bar")
    DOWNEY = "downey", _("Downey")
    DUARTE = "duarte", _("Duarte")
    EL_MONTE = "el_monte", _("El Monte")
    EL_SEGUNDO = "el_segundo", _("El Segundo")
    GARDENA = "gardena", _("Gardena")
    GLENDALE = "glendale", _("Glendale")
    GLENDORA = "glendora", _("Glendora")
    HAWAIIAN_GARDENS = "hawaiian_gardens", _("Hawaiian Gardens")
    HAWTHORNE = "hawthorne", _("Hawthorne")
    HERMOSA_BEACH = "hermosa_beach", _("Hermosa Beach")
    HIDDEN_HILLS = "hidden_hills", _("Hidden Hills")
    HOLLYWOOD = "hollywood", _("Hollywood")
    HUNTINGTON_PARK = "huntington_park", _("Huntington Park")
    INDUSTRY = "industry", _("Industry")
    INGLEWOOD = "inglewood", _("Inglewood")
    IRWINDALE = "irwindale", _("Irwindale")
    LA_CANADA_FLINTRIDGE = "la_canada_flintridge", _("La Canada Flintridge")
    LA_HABRA_HEIGHTS = "la_habra_heights", _("La Habra Heights")
    LA_MIRADA = "la_mirada", _("La Mirada")
    LA_PUENTE = "la_puente", _("La Puente")
    LA_VERNE = "la_verne", _("La Verne")
    LAKEWOOD = "lakewood", _("Lakewood")
    LANCASTER = "lancaster", _("Lancaster")
    LAWNDALE = "lawndale", _("Lawndale")
    LOMITA = "lomita", _("Lomita")
    LONG_BEACH = "long_beach", _("Long Beach")
    LOS_ANGELES = "los_angeles", _("Los Angeles")
    LYNWOOD = "lynwood", _("Lynwood")
    MALIBU = "malibu", _("Malibu")
    MANHATTAN_BEACH = "manhattan_beach", _("Manhattan Beach")
    MAYWOOD = "maywood", _("Maywood")
    MONROVIA = "monrovia", _("Monrovia")
    MONTEBELLO = "montebello", _("Montebello")
    MONTEREY_PARK = "monterey_park", _("Monterey Park")
    NORWALK = "norwalk", _("Norwalk")
    PALMDALE = "palmdale", _("Palmdale")
    PALOS_VERDES_ESTATES = "palos_verdes_estates", _("Palos Verdes Estates")
    PARAMOUNT = "paramount", _("Paramount")
    PASADENA = "pasadena", _("Pasadena")
    PICO_RIVERA = "pico_rivera", _("Pico Rivera")
    POMONA = "pomona", _("Pomona")
    RANCHO_PALOS_VERDES = "rancho_palos_verdes", _("Rancho Palos Verdes")
    REDONDO_BEACH = "redondo_beach", _("Redondo Beach")
    ROLLING_HILLS = "rolling_hills", _("Rolling Hills")
    ROLLING_HILLS_ESTATES = "rolling_hills_estates", _("Rolling Hills Estates")
    ROSEMEAD = "rosemead", _("Rosemead")
    SAN_DIMAS = "san_dimas", _("San Dimas")
    SAN_FERNANDO = "san_fernando", _("San Fernando")
    SAN_GABRIEL = "san_gabriel", _("San Gabriel")
    SAN_MARINO = "san_marino", _("San Marino")
    SANTA_CLARITA = "santa_clarita", _("Santa Clarita")
    SANTA_FE_SPRINGS = "santa_fe_springs", _("Santa Fe Springs")
    SANTA_MONICA = "santa_monica", _("Santa Monica")
    SIERRA_MADRE = "sierra_madre", _("Sierra Madre")
    SIGNAL_HILL = "signal_hill", _("Signal Hill")
    SOUTH_EL_MONTE = "south_el_monte", _("South El Monte")
    SOUTH_GATE = "south_gate", _("South Gate")
    SOUTH_PASADENA = "south_pasadena", _("South Pasadena")
    TEMPLE_CITY = "temple_city", _("Temple City")
    TORRANCE = "torrance", _("Torrance")
    VERNON = "vernon", _("Vernon")
    VENICE = "venice", _("Venice")
    WALNUT = "walnut", _("Walnut")
    WEST_COVINA = "west_covina", _("West Covina")
    WEST_HOLLYWOOD = "west_hollywood", _("West Hollywood")
    WESTLAKE_VILLAGE = "westlake_village", _("Westlake Village")
    WEST_LOS_ANGELES = "west_los_angeles", _("West Los Angeles")
    WHITTIER = "whittier", _("Whittier")
    WILMINGTON = "wilmington", _("Wilmington")
