# Generated by Django 6.1 on 2026-08-31 22:19

import django.core.validators
from django.db import migrations, models

from reports.models import ScheduledReport


def reschedule_active_reports(apps, schema_editor):
    """Recompute ``next_run_at`` onto the operating zone's calendar.

    Stored values were placed on UTC's, so an active monthly report is due at 5pm
    local on the last day of the month.  ``set_next_run`` only corrects itself
    *after* a send, which is one wrong-month email too late.
    """
    for report in apps.get_model("reports", "ScheduledReport").objects.filter(is_active=True):
        ScheduledReport.set_next_run(report)
        report.save(update_fields=["next_run_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='hour',
            field=models.IntegerField(default=0, help_text='Hour of the day to send the report (0-23), in the operating time zone', validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.RunPython(reschedule_active_reports, migrations.RunPython.noop),
    ]
