# Generated by Django 5.2.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reports", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="scheduledreport",
            options={
                "ordering": ["-created_at"],
                "permissions": [("view_reports", "Can view reports")],
                "verbose_name": "Scheduled Report",
                "verbose_name_plural": "Scheduled Reports",
            },
        ),
    ]
