# Generated by Django 6.1 on 2026-08-31 22:19

import django.core.validators
from dateutil.relativedelta import relativedelta
from django.db import migrations, models
from django.utils import timezone


def reschedule_active_reports(apps, schema_editor):
    """Recompute ``next_run_at`` onto the site zone's calendar.

    Stored values were placed on UTC's, so an active monthly report is due at 5pm
    local on the last day of the month.  The recompute is anchored on the stored
    run so that only its wall clock moves:

    * a future value keeps its month — rebasing it from ``now`` alone could move
      it backwards onto a period that was already sent;
    * an overdue value stays due — the dispatcher then delivers it late rather
      than the month being silently skipped.

    The logic is inlined rather than calling ``ScheduledReport.set_next_run`` so
    replaying this migration keeps computing what it did the day it shipped.
    """
    scheduled_report = apps.get_model("reports", "ScheduledReport")
    tz = timezone.get_default_timezone()
    now = timezone.now()

    for report in scheduled_report.objects.filter(is_active=True):
        anchor = (report.next_run_at or now).astimezone(tz)

        candidate = anchor + relativedelta(
            day=report.day_of_month,
            hour=report.hour,
            minute=0,
            second=0,
            microsecond=0,
        )
        if candidate < anchor:
            candidate += relativedelta(months=1) + relativedelta(day=report.day_of_month)

        report.next_run_at = candidate
        report.save(update_fields=["next_run_at"])


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scheduledreport',
            name='hour',
            field=models.IntegerField(default=0, help_text="Hour of the day to send the report (0-23), in the site's time zone", validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(23)]),
        ),
        migrations.RunPython(reschedule_active_reports, migrations.RunPython.noop),
    ]
