alias ynx-check-migrations="yarn nx affected -t check-migrations"
alias ynx-generate-types="yarn nx affected -t generate-graphql-types"
alias ynx-generate-schema="yarn nx affected -t generate-graphql-schema"
alias ynx-generate="ynx-generate-types && ynx-generate-types"
alias ynx-lint="yarn nx affected -t lint"
alias ynx-lint-be="yarn nx lint betterangels-backend"
alias ynx-lint-fe="yarn nx lint betterangels"
alias ynx-makemigrations="yarn nx run betterangels-backend:makemigrations"
alias ynx-migrate="yarn nx run betterangels-backend:migrate"
alias ynx-reset_db="yarn nx run betterangels-backend:reset_db"
alias ynx-start-be="yarn nx start betterangels-backend"
alias ynx-start-fe="yarn nx start betterangels"
alias ynx-test-be="yarn nx test betterangels-backend"
alias ynx-test-fe="yarn nx test betterangels"
alias ynx-typecheck="yarn nx affected -t typecheck"
alias ynx-validate-schema="yarn nx affected -t validate-graphql-schema"
alias ynx-poetry-add="yarn nx run betterangels-backend:add --name"

alias ynx-precommit="ynx-lint && ynx-check-migrations && ynx-validate-schema && ynx-typecheck"

alias rebash="source .bash_aliases"
