nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.6.1.cjs

npmScopes:
  fortawesome:
    npmRegistryServer: 'https://npm.fontawesome.com'
    npmAuthToken: '5844477E-077A-4B7E-ACD8-B09D467F2C3B'
