services:
  better-angels:
    image: ${MONOREPO_IMAGE}:${DOCKER_TAG}
    volumes:
      - ${GITHUB_WORKSPACE}:/workspace # Mounts the full repository
      - ${HOME}/.docker/:/home/betterangels/.docker/
      - ${GITHUB_EVENT_PATH}:${GITHUB_EVENT_PATH}:ro
    # Pass in GitHub Actions Envs into the container
    environment:
      - AWS_REGION
      - AWS_ACCOUNT_ID
      - ASSUMED_ROLE
      - ECR_REGISTRY
      - NX_BASE
      - NX_HEAD
      - BRANCH_NAME
      - SHORT_SHA
      - IMAGE_TAG_PREFIX
      - DOCKER_TAG
      - GITHUB_ACTIONS
      - GITHUB_EVENT_PATH
      - GITHUB_REPOSITORY
      - GITHUB_TOKEN
      - MONOREPO_IMAGE
      - AWS_DEFAULT_REGION
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - AWS_SESSION_TOKEN
      - INPUT_GITHUB_TOKEN
      # App Secrets
      - VITE_SHELTER_GOOGLE_MAPS_API_KEY
