// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { ShelterOrganizationsQuery } from './useShelterOrganizations.generated';

export const shelterOrganizationsOperationKey: keyof Omit<ShelterOrganizationsQuery, '__typename'> = 'shelterOrganizations';
export const shelterOrganizationsSuccessTypename: Extract<
  NonNullable<ShelterOrganizationsQuery['shelterOrganizations']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<ShelterOrganizationsQuery['shelterOrganizations']>,
  { __typename: 'OrganizationTypeOffsetPaginated' }
>['__typename'] = 'OrganizationTypeOffsetPaginated';

export const shelterOrganizationsMeta = {
  operationKey: shelterOrganizationsOperationKey,
  successTypename: shelterOrganizationsSuccessTypename,
} as const;
