from _typeshed import Incomplete
from allauth.socialaccount.adapter import get_adapter as get_adapter
from allauth.socialaccount.providers.oauth2.client import OAuth2Client as OAuth2Client, OAuth2Error as OAuth2Error

def jwt_encode(*args, **kwargs): ...

class Scope:
    EMAIL: str
    NAME: str

class AppleOAuth2Client(OAuth2Client):
    def generate_client_secret(self): ...
    def get_client_id(self): ...
    def get_access_token(self, code, pkce_code_verifier: Incomplete | None = ...): ...
    def get_redirect_url(self, authorization_url, extra_params): ...
