// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { UpdateClientProfileMutation } from './clientProfile.generated';
import type { DeleteClientProfileMutation } from './clientProfile.generated';
import type { GetClientProfileQuery } from './clientProfile.generated';

export const updateClientProfileOperationKey: keyof Omit<UpdateClientProfileMutation, '__typename'> = 'updateClientProfile';
export const updateClientProfileSuccessTypename: Extract<
  NonNullable<UpdateClientProfileMutation['updateClientProfile']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<UpdateClientProfileMutation['updateClientProfile']>,
  { __typename: 'ClientProfileType' }
>['__typename'] = 'ClientProfileType';

export const updateClientProfileMeta = {
  operationKey: updateClientProfileOperationKey,
  successTypename: updateClientProfileSuccessTypename,
} as const;

export const deleteClientProfileOperationKey: keyof Omit<DeleteClientProfileMutation, '__typename'> = 'deleteClientProfile';
export const deleteClientProfileSuccessTypename: Extract<
  NonNullable<DeleteClientProfileMutation['deleteClientProfile']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<DeleteClientProfileMutation['deleteClientProfile']>,
  { __typename: 'DeletedObjectType' }
>['__typename'] = 'DeletedObjectType';

export const deleteClientProfileMeta = {
  operationKey: deleteClientProfileOperationKey,
  successTypename: deleteClientProfileSuccessTypename,
} as const;

export const getClientProfileOperationKey: keyof Omit<GetClientProfileQuery, '__typename'> = 'clientProfile';
export const getClientProfileSuccessTypename: Extract<
  NonNullable<GetClientProfileQuery['clientProfile']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<GetClientProfileQuery['clientProfile']>,
  { __typename: 'ClientProfileType' }
>['__typename'] = 'ClientProfileType';

export const getClientProfileMeta = {
  operationKey: getClientProfileOperationKey,
  successTypename: getClientProfileSuccessTypename,
} as const;
