// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { GetRoomQuery } from './roomQueries.generated';
import type { GetRoomsQuery } from './roomQueries.generated';

export const getRoomOperationKey: keyof Omit<GetRoomQuery, '__typename'> = 'room';
export const getRoomSuccessTypename: Extract<
  NonNullable<GetRoomQuery['room']>,
  { __typename: 'RoomType' }
>['__typename'] = 'RoomType';

export const getRoomMeta = {
  operationKey: getRoomOperationKey,
  successTypename: getRoomSuccessTypename,
} as const;

export const getRoomsOperationKey: keyof Omit<GetRoomsQuery, '__typename'> = 'rooms';
export const getRoomsSuccessTypename: Extract<
  NonNullable<GetRoomsQuery['rooms']>,
  { __typename: 'RoomTypeOffsetPaginated' }
>['__typename'] = 'RoomTypeOffsetPaginated';

export const getRoomsMeta = {
  operationKey: getRoomsOperationKey,
  successTypename: getRoomsSuccessTypename,
} as const;
