from _typeshed import Incomplete
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth.provider import OAuthProvider as OAuthProvider

class FlickrAccount(ProviderAccount):
    def get_profile_url(self): ...
    def get_avatar_url(self): ...
    def to_str(self): ...

class FlickrProvider(OAuthProvider):
    id: str
    name: str
    account_class = FlickrAccount
    def get_default_scope(self): ...
    def get_auth_params(self, request, action): ...
    def get_profile_fields(self): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...

provider_classes: Incomplete
