// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { GetBaFeatureControlsQuery } from './featureControls.generated';

export const getBaFeatureControlsOperationKey: keyof Omit<GetBaFeatureControlsQuery, '__typename'> = 'featureControls';
export const getBaFeatureControlsSuccessTypename: Extract<
  NonNullable<GetBaFeatureControlsQuery['featureControls']>,
  { __typename: 'FeatureControlData' }
>['__typename'] = 'FeatureControlData';

export const getBaFeatureControlsMeta = {
  operationKey: getBaFeatureControlsOperationKey,
  successTypename: getBaFeatureControlsSuccessTypename,
} as const;
