"""
This type stub file was generated by pyright.
"""

import gevent.resolver.thread as _thread
from gevent.resolver.thread import *

"""Backwards compatibility alias for :mod:`gevent.resolver.thread`.

.. deprecated:: 1.3
   Use :mod:`gevent.resolver.thread`
"""
__all__ = _thread.__all__
