// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { GenerateClientDocumentUploadsMutation } from './clientDocumentUploads.generated';
import type { ResolveClientDocumentUploadsMutation } from './clientDocumentUploads.generated';

export const generateClientDocumentUploadsOperationKey: keyof Omit<GenerateClientDocumentUploadsMutation, '__typename'> = 'generateClientDocumentUploads';
export const generateClientDocumentUploadsSuccessTypename: Extract<
  NonNullable<GenerateClientDocumentUploadsMutation['generateClientDocumentUploads']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<GenerateClientDocumentUploadsMutation['generateClientDocumentUploads']>,
  { __typename: 'AuthorizedPresignedS3UploadsType' }
>['__typename'] = 'AuthorizedPresignedS3UploadsType';

export const generateClientDocumentUploadsMeta = {
  operationKey: generateClientDocumentUploadsOperationKey,
  successTypename: generateClientDocumentUploadsSuccessTypename,
} as const;

export const resolveClientDocumentUploadsOperationKey: keyof Omit<ResolveClientDocumentUploadsMutation, '__typename'> = 'resolveClientDocumentUploads';
export const resolveClientDocumentUploadsSuccessTypename: Extract<
  NonNullable<ResolveClientDocumentUploadsMutation['resolveClientDocumentUploads']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<ResolveClientDocumentUploadsMutation['resolveClientDocumentUploads']>,
  { __typename: 'ClientDocumentUploadsType' }
>['__typename'] = 'ClientDocumentUploadsType';

export const resolveClientDocumentUploadsMeta = {
  operationKey: resolveClientDocumentUploadsOperationKey,
  successTypename: resolveClientDocumentUploadsSuccessTypename,
} as const;
