from _typeshed import Incomplete
from allauth.socialaccount.providers.base import Provider as Provider, ProviderAccount as ProviderAccount

class DraugiemAccount(ProviderAccount):
    def get_avatar_url(self): ...
    def to_str(self): ...

class DraugiemProvider(Provider):
    id: str
    name: str
    account_class = DraugiemAccount
    def get_login_url(self, request, **kwargs): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...
    def extract_extra_data(self, data): ...

provider_classes: Incomplete
