// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { DeleteHmisProfileMutation } from './deleteHmisProfile.generated';

export const deleteHmisProfileOperationKey: keyof Omit<DeleteHmisProfileMutation, '__typename'> = 'deleteHmisProfile';
export const deleteHmisProfileSuccessTypename: Extract<
  NonNullable<DeleteHmisProfileMutation['deleteHmisProfile']>,
  { __typename: 'HmisProfileType' }
>['__typename'] = 'HmisProfileType';

export const deleteHmisProfileMeta = {
  operationKey: deleteHmisProfileOperationKey,
  successTypename: deleteHmisProfileSuccessTypename,
} as const;
