from _typeshed import Incomplete
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth.provider import OAuthProvider as OAuthProvider

class BitbucketAccount(ProviderAccount):
    def get_profile_url(self): ...
    def get_avatar_url(self): ...
    def get_username(self): ...
    def to_str(self): ...

class BitbucketProvider(OAuthProvider):
    id: str
    name: str
    account_class = BitbucketAccount
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...

provider_classes: Incomplete
