// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { ClientCaliforniaUniqueCheckQuery } from './ClientCaliforniaUniqueCheck.generated';

export const clientCaliforniaUniqueCheckOperationKey: keyof Omit<ClientCaliforniaUniqueCheckQuery, '__typename'> = 'clientProfiles';
export const clientCaliforniaUniqueCheckSuccessTypename: Extract<
  NonNullable<ClientCaliforniaUniqueCheckQuery['clientProfiles']>,
  { __typename: 'ClientProfileTypeOffsetPaginated' }
>['__typename'] = 'ClientProfileTypeOffsetPaginated';

export const clientCaliforniaUniqueCheckMeta = {
  operationKey: clientCaliforniaUniqueCheckOperationKey,
  successTypename: clientCaliforniaUniqueCheckSuccessTypename,
} as const;
