from ..serialize import deserialize as deserialize, serialize as serialize

class CassetteNotFoundError(FileNotFoundError): ...
class CassetteDecodeError(ValueError): ...

class FilesystemPersister:
    @classmethod
    def load_cassette(cls, cassette_path, serializer): ...
    @staticmethod
    def save_cassette(cassette_path, cassette_dict, serializer) -> None: ...
