// Mirrors backend APIErrorCodes
export const BE_PROTOCOL_ERROR_CODE = {
  UNAUTHENTICATED: 'UNAUTHENTICATED',
  NOT_FOUND: 'NOT_FOUND',
} as const;

// Mirrors backend ErrorCodeEnum
export const BE_VALIDATION_ERROR_CODE = {
  CA_ID_INVALID: 'CA_ID_INVALID',
  CA_ID_IN_USE: 'CA_ID_IN_USE',
  EMAIL_INVALID: 'EMAIL_INVALID',
  EMAIL_IN_USE: 'EMAIL_IN_USE',
  HMIS_ID_IN_USE: 'HMIS_ID_IN_USE',
  HMIS_ID_NOT_PROVIDED: 'HMIS_ID_NOT_PROVIDED',
  NAME_NOT_PROVIDED: 'NAME_NOT_PROVIDED',
  PHONE_NUMBER_INVALID: 'PHONE_NUMBER_INVALID',
} as const;
