// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { ClientReferralsQuery } from './Referrals.generated';
import type { CreateReferralMutation } from './Referrals.generated';

export const clientReferralsOperationKey: keyof Omit<ClientReferralsQuery, '__typename'> = 'referrals';
export const clientReferralsSuccessTypename: Extract<
  NonNullable<ClientReferralsQuery['referrals']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<ClientReferralsQuery['referrals']>,
  { __typename: 'ReferralTypeOffsetPaginated' }
>['__typename'] = 'ReferralTypeOffsetPaginated';

export const clientReferralsMeta = {
  operationKey: clientReferralsOperationKey,
  successTypename: clientReferralsSuccessTypename,
} as const;

export const createReferralOperationKey: keyof Omit<CreateReferralMutation, '__typename'> = 'createReferral';
export const createReferralSuccessTypename: Extract<
  NonNullable<CreateReferralMutation['createReferral']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<CreateReferralMutation['createReferral']>,
  { __typename: 'ReferralType' }
>['__typename'] = 'ReferralType';

export const createReferralMeta = {
  operationKey: createReferralOperationKey,
  successTypename: createReferralSuccessTypename,
} as const;
