# Generated by Django 4.2.9 on 2024-02-14 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="location",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shelters.location",
            ),
        ),
    ]
