# Generated by Django 6.0.4 on 2026-05-26 02:38

import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_unhoused_start_date"),
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0001_squashed_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BedEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("bed_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("available", "Available"),
                            ("occupied", "Occupied"),
                            ("reserved", "Reserved"),
                            ("out_of_service", "Out-of-Service"),
                        ],
                        max_length=14,
                        null=True,
                    ),
                ),
                ("status_notes", models.TextField(blank=True, null=True)),
                (
                    "bed_type",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("twin", "Twin"), ("bunk", "Bunk"), ("rollaway", "Rollaway"), ("other", "Other")],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("storage", models.BooleanField(blank=True, default=False)),
                ("maintenance_flag", models.BooleanField(blank=True, default=False)),
                ("last_cleaned_inspected", models.DateTimeField(blank=True, null=True)),
                (
                    "medical_needs",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("erc", "ERC (Enrich Residential Care)"),
                            ("dmh", "DMH Beds (Dept of Mental Health)"),
                            ("oxygen", "Oxygen"),
                            ("dialysis", "Dialysis"),
                        ],
                        max_length=8,
                        null=True,
                    ),
                ),
                ("b7", models.BooleanField(blank=True, default=False)),
                ("fees", models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ReservationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("check_in_overdue", "Check-in Overdue"),
                        ],
                        default="confirmed",
                        max_length=16,
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("duration", models.PositiveIntegerField(blank=True, help_text="Duration in days", null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "bed_name", "bed_type", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "medical_needs", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "updated_at") VALUES (NEW."b7", NEW."bed_name", NEW."bed_type", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."medical_needs", NEW."occupant_id", _pgh_attach_context(), NOW(), \'bed.add\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status", NEW."status_notes", NEW."storage", NEW."updated_at"); RETURN NULL;',
                    hash="143f49ef29990a8693958beca14e22fab220f2a0",
                    operation="INSERT",
                    pgid="pgtrigger_bed_add_insert_eb0c2",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "bed_name", "bed_type", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "medical_needs", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "updated_at") VALUES (OLD."b7", OLD."bed_name", OLD."bed_type", OLD."created_at", OLD."fees", OLD."id", OLD."last_cleaned_inspected", OLD."maintenance_flag", OLD."medical_needs", OLD."occupant_id", _pgh_attach_context(), NOW(), \'bed.remove\', OLD."id", OLD."room_id", OLD."shelter_id", OLD."status", OLD."status_notes", OLD."storage", OLD."updated_at"); RETURN NULL;',
                    hash="be0fe049f69df16b841382ddf9e731d74cbadc7c",
                    operation="DELETE",
                    pgid="pgtrigger_bed_remove_delete_506ff",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_status_change_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "shelters_bedevent" ("b7", "bed_name", "bed_type", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "medical_needs", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "updated_at") VALUES (NEW."b7", NEW."bed_name", NEW."bed_type", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."medical_needs", NEW."occupant_id", _pgh_attach_context(), NOW(), \'bed.status_change\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status", NEW."status_notes", NEW."storage", NEW."updated_at"); RETURN NULL;',
                    hash="fd97014993b2eea4176d1953e22051f8ce7d16bf",
                    operation="UPDATE",
                    pgid="pgtrigger_bed_status_change_update_0d1c0",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reservation",
            trigger=pgtrigger.compiler.Trigger(
                name="reservation_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_reservationevent" ("bed_id", "checked_in_at", "checked_out_at", "created_at", "created_by_id", "duration", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "start_date", "status", "updated_at") VALUES (NEW."bed_id", NEW."checked_in_at", NEW."checked_out_at", NEW."created_at", NEW."created_by_id", NEW."duration", NEW."id", NEW."notes", _pgh_attach_context(), NOW(), \'reservation.add\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."start_date", NEW."status", NEW."updated_at"); RETURN NULL;',
                    hash="f91f7f3d3fd672a8f076751e8e590c3023e79b43",
                    operation="INSERT",
                    pgid="pgtrigger_reservation_add_insert_2140a",
                    table="shelters_reservation",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reservation",
            trigger=pgtrigger.compiler.Trigger(
                name="reservation_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_reservationevent" ("bed_id", "checked_in_at", "checked_out_at", "created_at", "created_by_id", "duration", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "start_date", "status", "updated_at") VALUES (OLD."bed_id", OLD."checked_in_at", OLD."checked_out_at", OLD."created_at", OLD."created_by_id", OLD."duration", OLD."id", OLD."notes", _pgh_attach_context(), NOW(), \'reservation.remove\', OLD."id", OLD."room_id", OLD."shelter_id", OLD."start_date", OLD."status", OLD."updated_at"); RETURN NULL;',
                    hash="47a12135416afaa1182b80772544e32dc3399277",
                    operation="DELETE",
                    pgid="pgtrigger_reservation_remove_delete_62bf2",
                    table="shelters_reservation",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="reservation",
            trigger=pgtrigger.compiler.Trigger(
                name="reservation_status_change_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "shelters_reservationevent" ("bed_id", "checked_in_at", "checked_out_at", "created_at", "created_by_id", "duration", "id", "notes", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "start_date", "status", "updated_at") VALUES (NEW."bed_id", NEW."checked_in_at", NEW."checked_out_at", NEW."created_at", NEW."created_by_id", NEW."duration", NEW."id", NEW."notes", _pgh_attach_context(), NOW(), \'reservation.status_change\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."start_date", NEW."status", NEW."updated_at"); RETURN NULL;',
                    hash="5bf311b9d4ea30f7327fdaf7ada9d1eda4d12905",
                    operation="UPDATE",
                    pgid="pgtrigger_reservation_status_change_update_4a420",
                    table="shelters_reservation",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="occupant",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="clients.clientprofile",
            ),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="shelters.bed",
            ),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="room",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.room",
            ),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="bed",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.bed",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="shelters.reservation",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="room",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.room",
            ),
        ),
        migrations.AddField(
            model_name="reservationevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
    ]
