# Generated by Django 6.0.4 on 2026-05-19 17:54

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0001_squashed_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "non_restricted_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of non-restricted beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restricted_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of restricted beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restriction_notes",
                    models.TextField(
                        blank=True, default="", help_text="Global restriction note for this availability record."
                    ),
                ),
                (
                    "shelter",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, related_name="availability", to="shelters.shelter"
                    ),
                ),
            ],
            options={
                "verbose_name": "Shelter Availability",
                "verbose_name_plural": "Shelter Availabilities",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelterAvailabilityEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "non_restricted_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of non-restricted beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restricted_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of restricted beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restriction_notes",
                    models.TextField(
                        blank=True, default="", help_text="Global restriction note for this availability record."
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="shelters.shelteravailability",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.shelter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restricted_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restricted_beds", "restriction_notes", "shelter_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."non_restricted_beds", _pgh_attach_context(), NOW(), \'shelter.availability.add\', NEW."id", NEW."restricted_beds", NEW."restriction_notes", NEW."shelter_id", NEW."updated_at"); RETURN NULL;',
                    hash="82f18916194831b4295d8335ab9e212da204bdc0",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_availability_add_insert_81322",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restricted_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restricted_beds", "restriction_notes", "shelter_id", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."non_restricted_beds", _pgh_attach_context(), NOW(), \'shelter.availability.update\', NEW."id", NEW."restricted_beds", NEW."restriction_notes", NEW."shelter_id", NEW."updated_at"); RETURN NULL;',
                    hash="b37c36b9eaae6f4d9703cc0b28899ce9e65a8577",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_availability_update_update_9991b",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restricted_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restricted_beds", "restriction_notes", "shelter_id", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."non_restricted_beds", _pgh_attach_context(), NOW(), \'shelter.availability.remove\', OLD."id", OLD."restricted_beds", OLD."restriction_notes", OLD."shelter_id", OLD."updated_at"); RETURN NULL;',
                    hash="7454e1621a2216693972df1faa9839a3aa4ed35e",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_availability_remove_delete_d7472",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
    ]
