# Generated by Django 5.0.6 on 2024-07-10 03:43

import django.db.models.deletion
import django_choices_field.fields
import phonenumber_field.modelfields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_attachment_mime_type"),
        ("shelters", "0002_shelter_organization_alter_population_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Wheelchair Accessible", "Wheelchair Accessible"),
                            ("Medical Equipment Permitted", "Medical Equipment Permitted"),
                        ],
                        choices_enum=shelters.enums.AccessibilityEnum,
                        db_index=True,
                        max_length=27,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Job Training", "Job Training"),
                            ("Tutoring", "Tutoring"),
                            ("Life Skills Training", "Life Skills Training"),
                        ],
                        choices_enum=shelters.enums.CareerServiceEnum,
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Photo ID", "Photo ID"),
                            ("Medicaid or Medicare", "Medicaid or Medicare"),
                            ("Reservation", "Reservation"),
                            ("Referral", "Referral"),
                        ],
                        choices_enum=shelters.enums.EntryRequirementEnum,
                        db_index=True,
                        max_length=20,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Mail", "Mail"),
                            ("Phone", "Phone"),
                            ("Computers", "Computers"),
                            ("Legal Assistance", "Legal Assistance"),
                            ("Transportation", "Transportation"),
                            ("Case Management", "Case Management"),
                            ("Money Management", "Money Management"),
                        ],
                        choices_enum=shelters.enums.GeneralServiceEnum,
                        db_index=True,
                        max_length=16,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Medication Monitoring", "Medication Monitoring"),
                            ("Medication Administration", "Medication Administration"),
                            ("Mental Health", "Mental Health"),
                            ("Drug Treatment", "Drug Treatment"),
                        ],
                        choices_enum=shelters.enums.HealthServiceEnum,
                        db_index=True,
                        max_length=25,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImmediateNeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("Food", "Food"), ("Showers", "Showers"), ("Clothing", "Clothing")],
                        choices_enum=shelters.enums.ImmediateNeedEnum,
                        db_index=True,
                        max_length=8,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Auto or Small Truck", "Auto or Small Truck"),
                            ("Bicycle", "Bicycle"),
                            ("Motor Cycle", "Motor Cycle"),
                            ("RV", "RV"),
                        ],
                        choices_enum=shelters.enums.ParkingEnum,
                        db_index=True,
                        max_length=19,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Storage", "Storage"),
                            ("Lockers", "Lockers"),
                            ("Amnesty Lockers", "Amnesty Lockers"),
                        ],
                        choices_enum=shelters.enums.StorageEnum,
                        db_index=True,
                        max_length=15,
                        null=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="service",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="title",
        ),
        migrations.RemoveField(
            model_name="population",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="population",
            name="title",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="average_bed_rate",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="typical_stay_description",
        ),
        migrations.RemoveField(
            model_name="sheltertype",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="sheltertype",
            name="title",
        ),
        migrations.AddField(
            model_name="funder",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("LAHSA", "LAHSA"),
                    ("DMH", "DMH"),
                    ("DHS", "DHS"),
                    ("Private", "Private"),
                    ("Federal Funding", "Federal Funding"),
                    ("HOPWA", "HOPWA"),
                ],
                choices_enum=shelters.enums.FunderEnum,
                db_index=True,
                max_length=15,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Adults", "Adults"),
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Families", "Families"),
                    ("Youth (TAY)", "Youth (TAY)"),
                    ("Boys", "Boys"),
                    ("Girls", "Girls"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("LGBTQ", "LGBTQ"),
                    ("HIV/AIDS", "HIV/AIDS"),
                ],
                choices_enum=shelters.enums.PopulationEnum,
                db_index=True,
                max_length=13,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="funders",
            field=models.ManyToManyField(to="shelters.funder"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="hero_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_image_shelter",
                to="common.attachment",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="intake_process",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="populations",
            field=models.ManyToManyField(to="shelters.population"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="shelter_types",
            field=models.ManyToManyField(to="shelters.sheltertype"),
        ),
        migrations.AddField(
            model_name="sheltertype",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Faith Based", "Faith Based"),
                    ("Interim Housing", "Interim Housing"),
                    ("Permanent Housing", "Permanent Housing"),
                    ("A Bridge Home", "A Bridge Home"),
                    ("Project Home Key (PHK)", "Project Home Key (PHK)"),
                    ("Tiny Home Village", "Tiny Home Village"),
                    ("Winter Shelter", "Winter Shelter"),
                    ("Emergency Shelter", "Emergency Shelter"),
                    ("Crisis Housing", "Crisis Housing"),
                    ("Recuperative Care", "Recuperative Care"),
                    ("Transitional Housing", "Transitional Housing"),
                    ("Roadmap Home", "Roadmap Home"),
                    ("Rapid Rehousing", "Rapid Rehousing"),
                    ("Sober Living", "Sober Living"),
                    ("Safe Park LA", "Safe Park LA"),
                ],
                choices_enum=shelters.enums.ShelterTypeEnum,
                db_index=True,
                max_length=22,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AddField(
            model_name="shelter",
            name="accessibility",
            field=models.ManyToManyField(to="shelters.accessibility"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="career_services",
            field=models.ManyToManyField(to="shelters.careerservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="entry_requirements",
            field=models.ManyToManyField(to="shelters.entryrequirement"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="general_services",
            field=models.ManyToManyField(to="shelters.generalservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="health_services",
            field=models.ManyToManyField(to="shelters.healthservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="imeediate_needs",
            field=models.ManyToManyField(to="shelters.immediateneed"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="parking",
            field=models.ManyToManyField(to="shelters.parking"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="storage",
            field=models.ManyToManyField(to="shelters.storage"),
        ),
        migrations.DeleteModel(
            name="HowToEnter",
        ),
        migrations.DeleteModel(
            name="Requirement",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
