# Generated by Django 5.0.6 on 2024-07-10 22:29

import django.core.validators
import django.db.models.deletion
import django_choices_field.fields
import django_ckeditor_5.fields
import phonenumber_field.modelfields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_address_confidential_attachment_mime_type_and_more"),
        ("shelters", "0002_shelter_organization_alter_population_title_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accessibility",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Medical Equipment Permitted", "Medical Equipment Permitted"),
                            ("Wheelchair Accessible", "Wheelchair Accessible"),
                        ],
                        choices_enum=shelters.enums.AccessibilityChoices,
                        max_length=27,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CareerService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Job Training", "Job Training"),
                            ("Life Skills Training", "Life Skills Training"),
                            ("Tutoring", "Tutoring"),
                        ],
                        choices_enum=shelters.enums.CareerServiceChoices,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="City",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Agoura Hills", "Agoura Hills"),
                            ("Alhambra", "Alhambra"),
                            ("Arcadia", "Arcadia"),
                            ("Artesia", "Artesia"),
                            ("Avalon", "Avalon"),
                            ("Azusa", "Azusa"),
                            ("Baldwin Park", "Baldwin Park"),
                            ("Bell", "Bell"),
                            ("Bellflower", "Bellflower"),
                            ("Bell Gardens", "Bell Gardens"),
                            ("Beverly Hills", "Beverly Hills"),
                            ("Bradbury", "Bradbury"),
                            ("Burbank", "Burbank"),
                            ("Calabasas", "Calabasas"),
                            ("Carson", "Carson"),
                            ("Cerritos", "Cerritos"),
                            ("Claremont", "Claremont"),
                            ("Commerce", "Commerce"),
                            ("Compton", "Compton"),
                            ("Covina", "Covina"),
                            ("Cudahy", "Cudahy"),
                            ("Culver City", "Culver City"),
                            ("Diamond Bar", "Diamond Bar"),
                            ("Downey", "Downey"),
                            ("Duarte", "Duarte"),
                            ("El Monte", "El Monte"),
                            ("El Segundo", "El Segundo"),
                            ("Gardena", "Gardena"),
                            ("Glendale", "Glendale"),
                            ("Glendora", "Glendora"),
                            ("Hawaiian Gardens", "Hawaiian Gardens"),
                            ("Hawthorne", "Hawthorne"),
                            ("Hermosa Beach", "Hermosa Beach"),
                            ("Hidden Hills", "Hidden Hills"),
                            ("Huntington Park", "Huntington Park"),
                            ("Industry", "Industry"),
                            ("Inglewood", "Inglewood"),
                            ("Irwindale", "Irwindale"),
                            ("La Canada Flintridge", "La Canada Flintridge"),
                            ("La Habra Heights", "La Habra Heights"),
                            ("La Mirada", "La Mirada"),
                            ("La Puente", "La Puente"),
                            ("La Verne", "La Verne"),
                            ("Lakewood", "Lakewood"),
                            ("Lancaster", "Lancaster"),
                            ("Lawndale", "Lawndale"),
                            ("Lomita", "Lomita"),
                            ("Long Beach", "Long Beach"),
                            ("Los Angeles", "Los Angeles"),
                            ("Lynwood", "Lynwood"),
                            ("Malibu", "Malibu"),
                            ("Manhattan Beach", "Manhattan Beach"),
                            ("Maywood", "Maywood"),
                            ("Monrovia", "Monrovia"),
                            ("Montebello", "Montebello"),
                            ("Monterey Park", "Monterey Park"),
                            ("Norwalk", "Norwalk"),
                            ("Palmdale", "Palmdale"),
                            ("Palos Verdes Estates", "Palos Verdes Estates"),
                            ("Paramount", "Paramount"),
                            ("Pasadena", "Pasadena"),
                            ("Pico Rivera", "Pico Rivera"),
                            ("Pomona", "Pomona"),
                            ("Rancho Palos Verdes", "Rancho Palos Verdes"),
                            ("Redondo Beach", "Redondo Beach"),
                            ("Rolling Hills", "Rolling Hills"),
                            ("Rolling Hills Estates", "Rolling Hills Estates"),
                            ("Rosemead", "Rosemead"),
                            ("San Dimas", "San Dimas"),
                            ("San Fernando", "San Fernando"),
                            ("San Gabriel", "San Gabriel"),
                            ("San Marino", "San Marino"),
                            ("Santa Clarita", "Santa Clarita"),
                            ("Santa Fe Springs", "Santa Fe Springs"),
                            ("Santa Monica", "Santa Monica"),
                            ("Sierra Madre", "Sierra Madre"),
                            ("Signal Hill", "Signal Hill"),
                            ("South El Monte", "South El Monte"),
                            ("South Gate", "South Gate"),
                            ("South Pasadena", "South Pasadena"),
                            ("Temple City", "Temple City"),
                            ("Torrance", "Torrance"),
                            ("Vernon", "Vernon"),
                            ("Walnut", "Walnut"),
                            ("West Covina", "West Covina"),
                            ("West Hollywood", "West Hollywood"),
                            ("Westlake Village", "Westlake Village"),
                            ("Whittier", "Whittier"),
                        ],
                        choices_enum=shelters.enums.CityChoices,
                        max_length=21,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EntryRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Medicaid or Medicare", "Medicaid or Medicare"),
                            ("Photo ID", "Photo ID"),
                            ("Referral", "Referral"),
                            ("Reservation", "Reservation"),
                        ],
                        choices_enum=shelters.enums.EntryRequirementChoices,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GeneralService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Case Management", "Case Management"),
                            ("Computers", "Computers"),
                            ("Legal Assistance", "Legal Assistance"),
                            ("Mail", "Mail"),
                            ("Money Management", "Money Management"),
                            ("Phone", "Phone"),
                            ("Transportation", "Transportation"),
                        ],
                        choices_enum=shelters.enums.GeneralServiceChoices,
                        max_length=16,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="HealthService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Drug Treatment", "Drug Treatment"),
                            ("Medication Administration", "Medication Administration"),
                            ("Medication Monitoring", "Medication Monitoring"),
                            ("Mental Health", "Mental Health"),
                        ],
                        choices_enum=shelters.enums.HealthServiceChoices,
                        max_length=25,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ImmediateNeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("Clothing", "Clothing"), ("Food", "Food"), ("Showers", "Showers")],
                        choices_enum=shelters.enums.ImmediateNeedChoices,
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Parking",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Auto or Small Truck", "Auto or Small Truck"),
                            ("Bicycle", "Bicycle"),
                            ("Motorcycle", "Motorcycle"),
                            ("RV", "RV"),
                        ],
                        choices_enum=shelters.enums.ParkingChoices,
                        max_length=19,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Cats", "Cats"),
                            ("Dogs >25lbs", "Dogs >25lbs"),
                            ("Dogs <25lbs", "Dogs <25lbs"),
                            ("Emotional Support", "Emotional Support"),
                            ("Exotics", "Exotics"),
                            ("Service Animal", "Service Animal"),
                        ],
                        choices_enum=shelters.enums.PetChoices,
                        max_length=17,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SleepingOption",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Bed Layout Description", "Bed Layout Description"),
                            ("Bunk beds", "Bunk beds"),
                            ("Dormitory", "Dormitory"),
                            ("Low Barrier", "Low Barrier"),
                            ("Motel", "Motel"),
                            ("Shared Rooms", "Shared Rooms"),
                            ("Single Room", "Single Room"),
                        ],
                        choices_enum=shelters.enums.SleepingChoices,
                        max_length=22,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Storage",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Amnesty Lockers", "Amnesty Lockers"),
                            ("Lockers", "Lockers"),
                            ("Storage", "Storage"),
                        ],
                        choices_enum=shelters.enums.StorageChoices,
                        max_length=15,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="location",
        ),
        migrations.RemoveField(
            model_name="requirement",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="service",
            name="shelter",
        ),
        migrations.RenameField(
            model_name="shelter",
            old_name="title",
            new_name="name",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="funder",
            name="title",
        ),
        migrations.RemoveField(
            model_name="population",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="population",
            name="title",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="available_beds",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="average_bed_rate",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="bed_layout_description",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="confidential",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="image_url",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="private_beds",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="typical_stay_description",
        ),
        migrations.RemoveField(
            model_name="sheltertype",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="sheltertype",
            name="title",
        ),
        migrations.AddField(
            model_name="funder",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("DHS", "DHS"),
                    ("DMH", "DMH"),
                    ("Federal Funding", "Federal Funding"),
                    ("HOPWA", "HOPWA"),
                    ("LAHSA", "LAHSA"),
                    ("Private", "Private"),
                ],
                choices_enum=shelters.enums.FunderChoices,
                max_length=15,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="population",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Adults", "Adults"),
                    ("Boys", "Boys"),
                    ("Families", "Families"),
                    ("Girls", "Girls"),
                    ("HIV/AIDS", "HIV/AIDS"),
                    ("LGBTQ", "LGBTQ"),
                    ("Men", "Men"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("Women", "Women"),
                    ("Youth (TAY)", "Youth (TAY)"),
                ],
                choices_enum=shelters.enums.PopulationChoices,
                max_length=13,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="address",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelter",
                to="common.address",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="city_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(15)],
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="curfew",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="drugs",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="fees",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="funders",
            field=models.ManyToManyField(to="shelters.funder"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="hero_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_image_shelter",
                to="common.attachment",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="how_to_enter",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="mandatory_worship_attendance",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="populations",
            field=models.ManyToManyField(to="shelters.population"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="program_fees",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="shelter_types",
            field=models.ManyToManyField(to="shelters.sheltertype"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="supervisorial_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)],
            ),
        ),
        migrations.AddField(
            model_name="sheltertype",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("A Bridge Home", "A Bridge Home"),
                    ("Crisis Housing", "Crisis Housing"),
                    ("Emergency Shelter", "Emergency Shelter"),
                    ("Faith Based", "Faith Based"),
                    ("Interim Housing", "Interim Housing"),
                    ("Permanent Housing", "Permanent Housing"),
                    ("Project Home Key (PHK)", "Project Home Key (PHK)"),
                    ("Rapid Rehousing", "Rapid Rehousing"),
                    ("Recuperative Care", "Recuperative Care"),
                    ("Roadmap Home", "Roadmap Home"),
                    ("Safe Park LA", "Safe Park LA"),
                    ("Sober Living", "Sober Living"),
                    ("Tiny Home Village", "Tiny Home Village"),
                    ("Transitional Housing", "Transitional Housing"),
                    ("Winter Shelter", "Winter Shelter"),
                ],
                choices_enum=shelters.enums.ShelterChoices,
                max_length=22,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="spa",
            field=models.PositiveSmallIntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(8)],
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="total_beds",
            field=models.PositiveIntegerField(default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="shelter",
            name="accessibility",
            field=models.ManyToManyField(to="shelters.accessibility"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="career_services",
            field=models.ManyToManyField(to="shelters.careerservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="cities",
            field=models.ManyToManyField(to="shelters.city"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="entry_requirements",
            field=models.ManyToManyField(to="shelters.entryrequirement"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="general_services",
            field=models.ManyToManyField(to="shelters.generalservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="health_services",
            field=models.ManyToManyField(to="shelters.healthservice"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="imeediate_needs",
            field=models.ManyToManyField(to="shelters.immediateneed"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="parking",
            field=models.ManyToManyField(to="shelters.parking"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="pets",
            field=models.ManyToManyField(to="shelters.pet"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="sleeping_options",
            field=models.ManyToManyField(to="shelters.sleepingoption"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="storage",
            field=models.ManyToManyField(to="shelters.storage"),
        ),
        migrations.DeleteModel(
            name="HowToEnter",
        ),
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.DeleteModel(
            name="Requirement",
        ),
        migrations.DeleteModel(
            name="Service",
        ),
    ]
