# Generated by Django 5.0.6 on 2024-07-04 18:14

import django.db.models.deletion
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_location_point"),
        ("shelters", "0002_shelter_organization_alter_population_title_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="hero_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hero_image_shelter",
                to="common.attachment",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None),
        ),
    ]
