# Generated by Django 6.1 on 2026-10-01 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0002_shelter_schedule_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shelter',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='shelterevent',
            name='instagram',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
