# Generated by Django 5.0.6 on 2024-07-16 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0003_accessibility_careerservice_city_entryrequirement_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelter",
            name="security",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
