# Generated by Django 4.2.9 on 2024-02-27 04:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0003_remove_location_coordinates_location_latitude_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelters",
                to="shelters.location",
            ),
        ),
    ]
