# Generated by Django 4.2.11 on 2024-04-16 20:36

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import shelters.enums


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0003_alter_shelter_organization"),
    ]

    operations = [
        migrations.CreateModel(
            name="Funder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("MPP", "MPP"),
                            ("LAHSA", "LAHSA"),
                            ("DMH", "DMH"),
                            ("DHS", "DHS"),
                        ],
                        choices_enum=shelters.enums.FunderEnum,
                        max_length=5,
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="funders",
                        to="shelters.shelter",
                    ),
                ),
            ],
        ),
    ]
