# Generated by Django 5.0.6 on 2024-07-17 16:41

import django_choices_field.fields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_shelter_security"),
    ]

    operations = [
        migrations.AlterField(
            model_name="generalservice",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Case Management", "Case Management"),
                    ("Childcare", "Childcare"),
                    ("Computers", "Computers"),
                    ("Housing Navigation", "Housing Navigation"),
                    ("Legal Assistance", "Legal Assistance"),
                    ("Mail", "Mail"),
                    ("Money Management", "Money Management"),
                    ("Phone", "Phone"),
                    ("Transportation", "Transportation"),
                ],
                choices_enum=shelters.enums.GeneralServiceChoices,
                max_length=18,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Adults", "Adults"),
                    ("Boys", "Boys"),
                    ("Domestic Violence (DV/IPV)", "Domestic Violence (DV/IPV)"),
                    ("Families", "Families"),
                    ("Girls", "Girls"),
                    ("HIV/AIDS", "HIV/AIDS"),
                    ("Human Trafficking", "Human Trafficking"),
                    ("LGBTQ", "LGBTQ"),
                    ("Men", "Men"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("Women", "Women"),
                    ("Youth (TAY)", "Youth (TAY)"),
                ],
                choices_enum=shelters.enums.PopulationChoices,
                max_length=26,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="total_beds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
