# Generated by Django 5.0.6 on 2024-07-17 18:58

import django_choices_field.fields
import shelters.enums
from django.db import migrations, models

from ..deprecated import deprecated_enums


def update_enum_values_forward(apps, schema_editor):
    # Use raw SQL to update the enum values directly in the database
    schema_editor.execute(
        "UPDATE shelters_healthservice SET name = 'Substance Use Treatment' WHERE name = 'Drug Treatment'"
    )
    schema_editor.execute(
        "UPDATE shelters_generalservice SET name = 'Financial Literacy/Assistance' WHERE name = 'Money Management'"
    )


def migrate_spa_field(apps, schema_editor):
    Shelter = apps.get_model("shelters", "Shelter")
    SPA = apps.get_model("shelters", "spa")

    # Create SPA instances for existing SPA field values in Shelter
    for shelter in Shelter.objects.all():
        if shelter.spa:
            spa_instance, created = SPA.objects.get_or_create(name=shelter.spa)
            shelter.spa_new.add(spa_instance)


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_shelter_security"),
    ]

    operations = [
        migrations.CreateModel(
            name="SPA",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.IntegerChoicesField(
                        blank=True,
                        choices=[
                            (1, "1 - Antelope Valley"),
                            (2, "2 - San Fernando"),
                            (3, "3 - San Gabriel"),
                            (4, "4 - Metro"),
                            (5, "5 - West"),
                            (6, "6 - South"),
                            (7, "7 - East"),
                            (8, "8 - South Bay/Harbor"),
                        ],
                        choices_enum=shelters.enums.SPAChoices,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AlterField(
            model_name="generalservice",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Case Management", "Case Management"),
                    ("Childcare", "Childcare"),
                    ("Computers", "Computers"),
                    ("Financial Literacy/Assistance", "Financial Literacy/Assistance"),
                    ("Housing Navigation", "Housing Navigation"),
                    ("Legal Assistance", "Legal Assistance"),
                    ("Mail", "Mail"),
                    ("Phone", "Phone"),
                    ("Transportation", "Transportation"),
                ],
                choices_enum=shelters.enums.GeneralServiceChoices,
                max_length=29,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="population",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Adults", "Adults"),
                    ("Boys", "Boys"),
                    ("Domestic Violence (DV/IPV)", "Domestic Violence (DV/IPV)"),
                    ("Families", "Families"),
                    ("Girls", "Girls"),
                    ("HIV/AIDS", "HIV/AIDS"),
                    ("Human Trafficking", "Human Trafficking"),
                    ("LGBTQ", "LGBTQ"),
                    ("Men", "Men"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("Women", "Women"),
                    ("Youth (TAY)", "Youth (TAY)"),
                ],
                choices_enum=deprecated_enums.PopulationChoices,
                max_length=26,
                null=True,
                unique=True,
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="spa_new",
            field=models.ManyToManyField(to="shelters.spa"),
        ),
        migrations.RunPython(migrate_spa_field),
        migrations.RemoveField(
            model_name="shelter",
            name="spa",
        ),
        migrations.RenameField(
            model_name="shelter",
            old_name="spa_new",
            new_name="spa",
        ),
        migrations.AlterField(
            model_name="shelter",
            name="total_beds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.RunPython(update_enum_values_forward),
    ]
