# Generated by Django 4.2.9 on 2024-02-27 04:30

from django.db import migrations, models
import django_choices_field.fields
import shelters.enums


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0004_alter_shelter_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="location",
            name="zip_code",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="population",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("Adults", "Adults"),
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Families", "Families"),
                    ("Youth", "Youth"),
                    ("Boys", "Boys"),
                    ("Girls", "Girls"),
                    ("Seniors", "Seniors"),
                    ("Veterans", "Veterans"),
                    ("LGBTQ", "LGBTQ"),
                ],
                choices_enum=shelters.enums.PopulationEnum,
                max_length=8,
            ),
        ),
        migrations.AlterField(
            model_name="requirement",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("Photo ID", "Photo ID"),
                    ("Medicaid or Medicare", "Medicaid or Medicare"),
                    ("Veteran", "Veteran"),
                    ("Reservation", "Reservation"),
                    ("Referral", "Referral"),
                ],
                choices_enum=shelters.enums.RequirementEnum,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("Food", "Food"),
                    ("Shower", "Shower"),
                    ("Clothing", "Clothing"),
                    ("Mail", "Mail"),
                    ("Phone", "Phone"),
                    ("Computers", "Computes"),
                    ("Job Training", "Job Training"),
                    ("Tutoring", "Tutoring"),
                    ("Life Skills Training", "Life Skills Training"),
                    ("Medical Services", "Medical Services"),
                    ("Mental Health", "Mental Health"),
                    ("Drug Treatment", "Drug Treatment"),
                    ("Financial Planning", "Financial Planning"),
                    ("Legal Assistance", "Legal Assistance"),
                    ("Transportation", "Transportation"),
                ],
                choices_enum=shelters.enums.ServiceEnum,
                max_length=20,
            ),
        ),
    ]
