# Generated by Django 5.0.6 on 2024-07-09 21:10

import django_choices_field.fields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0004_remove_requirement_shelter_remove_shelter_image_url_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopulationTest",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("Service Animal", "Service Animal"),
                            ("Cats", "Cats"),
                            ("Emotional Support", "Emotional Support"),
                            ("Dogs <25lbs", "Dogs <25lbs"),
                            ("Dogs >25lbs", "Dogs >25lbs"),
                            ("Exotics", "Exotics"),
                        ],
                        choices_enum=shelters.enums.PetsAllowedEnum,
                        max_length=17,
                    ),
                ),
            ],
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="average_bed_rate",
        ),
        migrations.AddField(
            model_name="shelter",
            name="testing_populations",
            field=models.ManyToManyField(to="shelters.populationtest"),
        ),
    ]
