# Generated by Django 6.0.4 on 2026-06-03 20:07

import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_unhoused_start_date"),
        ("shelters", "0004_bedevent_reservationevent_bed_bed_add_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MedicalNeed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("erc", "ERC (Enrich Residential Care)"),
                            ("dmh", "DMH Beds (Dept of Mental Health)"),
                            ("oxygen", "Oxygen"),
                            ("dialysis", "Dialysis"),
                        ],
                        max_length=8,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_remove_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_status_change_update",
        ),
        migrations.RemoveConstraint(
            model_name="room",
            name="unique_room_per_shelter",
        ),
        migrations.RenameField(
            model_name="bed",
            old_name="bed_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="bed",
            old_name="bed_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="bedevent",
            old_name="bed_name",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="bedevent",
            old_name="bed_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="room_identifier",
            new_name="name",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="room_type",
            new_name="type",
        ),
        migrations.RenameField(
            model_name="room",
            old_name="room_type_other",
            new_name="type_other",
        ),
        migrations.RemoveField(
            model_name="bedevent",
            name="medical_needs",
        ),
        migrations.RemoveField(
            model_name="bed",
            name="medical_needs",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "name", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "type", "updated_at") VALUES (NEW."b7", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."name", NEW."occupant_id", _pgh_attach_context(), NOW(), \'bed.add\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status", NEW."status_notes", NEW."storage", NEW."type", NEW."updated_at"); RETURN NULL;',
                    hash="b2602241dd71e7309c546ef39189035f81acf987",
                    operation="INSERT",
                    pgid="pgtrigger_bed_add_insert_eb0c2",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "name", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "type", "updated_at") VALUES (OLD."b7", OLD."created_at", OLD."fees", OLD."id", OLD."last_cleaned_inspected", OLD."maintenance_flag", OLD."name", OLD."occupant_id", _pgh_attach_context(), NOW(), \'bed.remove\', OLD."id", OLD."room_id", OLD."shelter_id", OLD."status", OLD."status_notes", OLD."storage", OLD."type", OLD."updated_at"); RETURN NULL;',
                    hash="8e2fbef2dd54583c758dbf888d62eb28c2b7bfbf",
                    operation="DELETE",
                    pgid="pgtrigger_bed_remove_delete_506ff",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_status_change_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."status" IS DISTINCT FROM (NEW."status"))',
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned_inspected", "maintenance_flag", "name", "occupant_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status", "status_notes", "storage", "type", "updated_at") VALUES (NEW."b7", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."name", NEW."occupant_id", _pgh_attach_context(), NOW(), \'bed.status_change\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status", NEW."status_notes", NEW."storage", NEW."type", NEW."updated_at"); RETURN NULL;',
                    hash="5a132c2afd611ef2f8203f3cf901cf07aceaad14",
                    operation="UPDATE",
                    pgid="pgtrigger_bed_status_change_update_0d1c0",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="room",
            constraint=models.UniqueConstraint(fields=("shelter", "name"), name="unique_room_per_shelter"),
        ),
        migrations.AddField(
            model_name="bed",
            name="medical_needs",
            field=models.ManyToManyField(blank=True, to="shelters.medicalneed"),
        ),
    ]
