# Generated by Django 4.2.11 on 2024-04-16 20:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0004_funder"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="spa",
            field=models.PositiveSmallIntegerField(
                blank=True, null=True, verbose_name="SPA"
            ),
        ),
    ]
