# Generated by Django 4.2.9 on 2024-02-27 20:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0005_alter_location_zip_code_alter_population_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="average_bed_rate",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="bed_layout_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="max_stay",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="population",
            field=models.ManyToManyField(blank=True, to="shelters.population"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="requirements",
            field=models.ManyToManyField(blank=True, to="shelters.requirement"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="services",
            field=models.ManyToManyField(blank=True, to="shelters.service"),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="typical_stay_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="website",
            field=models.URLField(blank=True, null=True),
        ),
    ]
