# Generated by Django 5.0.6 on 2024-07-09 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0006_alter_populationtest_name_alter_sheltertype_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="populationtest",
            name="name",
            field=models.CharField(
                choices=[
                    ("Adults", "Adults"),
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Families", "Families"),
                    ("Youth (TAY)", "Youth (TAY)"),
                    ("Boys", "Boys"),
                    ("Girls", "Girls"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("LGBTQ", "LGBTQ"),
                    ("HIV/AIDS", "HIV/AIDS"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="testing_populations",
            field=models.ManyToManyField(
                choices=[
                    ("Adults", "Adults"),
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Families", "Families"),
                    ("Youth (TAY)", "Youth (TAY)"),
                    ("Boys", "Boys"),
                    ("Girls", "Girls"),
                    ("Seniors (55+)", "Seniors (55+)"),
                    ("Veterans", "Veterans"),
                    ("LGBTQ", "LGBTQ"),
                    ("HIV/AIDS", "HIV/AIDS"),
                ],
                to="shelters.populationtest",
            ),
        ),
    ]
