# Generated by Django 5.0.6 on 2024-07-10 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0006_alter_shelter_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="total_beds",
            field=models.PositiveIntegerField(default=1),
            preserve_default=False,
        ),
    ]
