# Generated by Django 6.0.6 on 2026-06-16 17:05

import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_unhoused_start_date"),
        ("shelters", "0007_add_shelteravailability_group_permissions"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_remove_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="bed",
            name="bed_status_change_update",
        ),
        migrations.RemoveIndex(
            model_name="bed",
            name="shelters_be_shelter_cd7c2c_idx",
        ),
        migrations.RemoveIndex(
            model_name="room",
            name="shelters_ro_shelter_d19bd5_idx",
        ),
        migrations.RemoveField(
            model_name="bedevent",
            name="occupant",
        ),
        migrations.RemoveField(
            model_name="bedevent",
            name="status",
        ),
        migrations.AddField(
            model_name="bed",
            name="last_cleaned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="bedevent",
            name="last_cleaned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="room",
            name="last_cleaned",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("check_in_overdue", "Check-in Overdue"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.AlterField(
            model_name="reservationevent",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("check_in_overdue", "Check-in Overdue"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
        migrations.AddIndex(
            model_name="bed",
            index=models.Index(fields=["shelter"], name="shelters_be_shelter_7e57a9_idx"),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned", "last_cleaned_inspected", "maintenance_flag", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status_notes", "storage", "type", "updated_at") VALUES (NEW."b7", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."name", _pgh_attach_context(), NOW(), \'bed.add\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status_notes", NEW."storage", NEW."type", NEW."updated_at"); RETURN NULL;',
                    hash="7e704cdc8ab3ebc000648f400fbcddc171ddca7b",
                    operation="INSERT",
                    pgid="pgtrigger_bed_add_insert_eb0c2",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned", "last_cleaned_inspected", "maintenance_flag", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status_notes", "storage", "type", "updated_at") VALUES (OLD."b7", OLD."created_at", OLD."fees", OLD."id", OLD."last_cleaned", OLD."last_cleaned_inspected", OLD."maintenance_flag", OLD."name", _pgh_attach_context(), NOW(), \'bed.remove\', OLD."id", OLD."room_id", OLD."shelter_id", OLD."status_notes", OLD."storage", OLD."type", OLD."updated_at"); RETURN NULL;',
                    hash="07040a31106e91b46994de39caf6560e0b5a184b",
                    operation="DELETE",
                    pgid="pgtrigger_bed_remove_delete_506ff",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="bed",
            trigger=pgtrigger.compiler.Trigger(
                name="bed_maintenance_flag_change_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition='WHEN (OLD."maintenance_flag" IS DISTINCT FROM (NEW."maintenance_flag"))',
                    func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned", "last_cleaned_inspected", "maintenance_flag", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status_notes", "storage", "type", "updated_at") VALUES (NEW."b7", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."name", _pgh_attach_context(), NOW(), \'bed.maintenance_flag_change\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status_notes", NEW."storage", NEW."type", NEW."updated_at"); RETURN NULL;',
                    hash="05ae938ec39facad071ad0bc9c73cfabf0338881",
                    operation="UPDATE",
                    pgid="pgtrigger_bed_maintenance_flag_change_update_ca631",
                    table="shelters_bed",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status__in", {"checked_in", "check_in_overdue", "confirmed"})),
                fields=("bed",),
                name="unique_active_reservation_per_bed",
            ),
        ),
        migrations.AddConstraint(
            model_name="reservation",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("bed__isnull", True), ("status__in", {"checked_in", "check_in_overdue", "confirmed"})
                ),
                fields=("room",),
                name="unique_active_reservation_per_room",
            ),
        ),
        migrations.RemoveField(
            model_name="bed",
            name="occupant",
        ),
        migrations.RemoveField(
            model_name="bed",
            name="status",
        ),
        migrations.RemoveField(
            model_name="room",
            name="occupants",
        ),
        migrations.RemoveField(
            model_name="room",
            name="status",
        ),
    ]
