# Generated by Django 4.2.9 on 2024-03-08 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0007_sheltertype_shelter_shelter_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="program",
            name="catchment_zones",
        ),
        migrations.RemoveField(
            model_name="program",
            name="requirements",
        ),
        migrations.RemoveField(
            model_name="programbedallocation",
            name="program",
        ),
        migrations.RemoveField(
            model_name="programbedallocation",
            name="shelter",
        ),
        migrations.RemoveField(
            model_name="room",
            name="population",
        ),
        migrations.RemoveField(
            model_name="room",
            name="shelter",
        ),
        migrations.AddField(
            model_name="shelter",
            name="max_day",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="private_beds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="total_beds",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="Bed",
        ),
        migrations.DeleteModel(
            name="CatchmentZone",
        ),
        migrations.DeleteModel(
            name="Program",
        ),
        migrations.DeleteModel(
            name="ProgramBedAllocation",
        ),
        migrations.DeleteModel(
            name="Room",
        ),
    ]
