# Generated by Django 6.0.6 on 2026-06-23 16:10

from django.db import migrations


def _backfill(apps, schema_editor):
    """Populate ``start_week_minutes`` and ``duration_minutes`` for existing rows."""
    from shelters.models.schedule import _duration_minutes, _start_week_minutes

    Schedule = apps.get_model("shelters", "Schedule")
    to_update = []
    for obj in Schedule.objects.iterator():
        obj.start_week_minutes = _start_week_minutes(obj.day, obj.start_time)
        obj.duration_minutes = _duration_minutes(obj.start_time, obj.end_time)
        to_update.append(obj)
    Schedule.objects.bulk_update(to_update, fields=["start_week_minutes", "duration_minutes"])


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0008_add_schedule_cyclic_columns"),
    ]

    operations = [
        migrations.RunPython(_backfill, reverse_code=migrations.RunPython.noop),
    ]

