# Generated by Django 5.1.2 on 2024-11-05 03:32

import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_phonenumber"),
        ("organizations", "0006_alter_organization_slug"),
        ("pghistory", "0006_delete_aggregateevent"),
        ("shelters", "0009_remove_common_attachment_from_shelter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterAccessibilityEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterCareerServicesEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterCitiesEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterEntryRequirementsEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", django_ckeditor_5.fields.CKEditor5Field(null=True)),
                ("how_to_enter", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("mandatory_worship_attendance", models.BooleanField(blank=True, null=True)),
                (
                    "city_district",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(15),
                        ],
                        verbose_name="LA City Council District (1-15)",
                    ),
                ),
                (
                    "supervisorial_district",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Supervisorial District (1-5)",
                    ),
                ),
                ("curfew", models.TimeField(blank=True, null=True)),
                ("max_stay", models.PositiveIntegerField(blank=True, null=True, verbose_name="Max Stay (days)")),
                ("security", models.BooleanField(blank=True, null=True)),
                ("drugs", models.BooleanField(blank=True, null=True)),
                ("program_fees", models.BooleanField(blank=True, null=True)),
                ("fees", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("total_beds", models.PositiveIntegerField(blank=True, null=True)),
                ("is_reviewed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterFundersEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterGeneralServicesEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterHealthServicesEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterImmediateNeedsEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterParkingEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterPetsEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterPopulationsEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterShelterTypesEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterSleepingOptionsEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterSPAEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterStorageEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterAccessibility",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_accessibility",),
        ),
        migrations.CreateModel(
            name="ShelterCareerServices",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_career_services",),
        ),
        migrations.CreateModel(
            name="ShelterCities",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_cities",),
        ),
        migrations.CreateModel(
            name="ShelterEntryRequirements",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_entry_requirements",),
        ),
        migrations.CreateModel(
            name="ShelterFunders",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_funders",),
        ),
        migrations.CreateModel(
            name="ShelterGeneralServices",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_general_services",),
        ),
        migrations.CreateModel(
            name="ShelterHealthServices",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_health_services",),
        ),
        migrations.CreateModel(
            name="ShelterImmediateNeeds",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_immediate_needs",),
        ),
        migrations.CreateModel(
            name="ShelterParking",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_parking",),
        ),
        migrations.CreateModel(
            name="ShelterPets",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_pets",),
        ),
        migrations.CreateModel(
            name="ShelterPopulations",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_populations",),
        ),
        migrations.CreateModel(
            name="ShelterShelterTypes",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_shelter_types",),
        ),
        migrations.CreateModel(
            name="ShelterSleepingOptions",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_sleeping_options",),
        ),
        migrations.CreateModel(
            name="ShelterSPA",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_spa",),
        ),
        migrations.CreateModel(
            name="ShelterStorage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_storage",),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("address_id", "city_district", "created_at", "curfew", "description", "drugs", "email", "fees", "how_to_enter", "id", "is_reviewed", "mandatory_worship_attendance", "max_stay", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "security", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."address_id", NEW."city_district", NEW."created_at", NEW."curfew", NEW."description", NEW."drugs", NEW."email", NEW."fees", NEW."how_to_enter", NEW."id", NEW."is_reviewed", NEW."mandatory_worship_attendance", NEW."max_stay", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."security", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="715c0b0fbe8ababd5270683927fc1ed62e1b8bf6",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("address_id", "city_district", "created_at", "curfew", "description", "drugs", "email", "fees", "how_to_enter", "id", "is_reviewed", "mandatory_worship_attendance", "max_stay", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "security", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."address_id", NEW."city_district", NEW."created_at", NEW."curfew", NEW."description", NEW."drugs", NEW."email", NEW."fees", NEW."how_to_enter", NEW."id", NEW."is_reviewed", NEW."mandatory_worship_attendance", NEW."max_stay", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."security", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="3247c7dbc1ecb3f26fa9778fb47a75d9100bd174",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("address_id", "city_district", "created_at", "curfew", "description", "drugs", "email", "fees", "how_to_enter", "id", "is_reviewed", "mandatory_worship_attendance", "max_stay", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "security", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (OLD."address_id", OLD."city_district", OLD."created_at", OLD."curfew", OLD."description", OLD."drugs", OLD."email", OLD."fees", OLD."how_to_enter", OLD."id", OLD."is_reviewed", OLD."mandatory_worship_attendance", OLD."max_stay", OLD."name", OLD."organization_id", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."security", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."website"); RETURN NULL;',
                    hash="b2d79b22ae13b34e9c7d6111535d4edc328d741a",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="shelteraccessibilityevent",
            name="accessibility",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.accessibility",
            ),
        ),
        migrations.AddField(
            model_name="shelteraccessibilityevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelteraccessibilityevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltercareerservicesevent",
            name="careerservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.careerservice",
            ),
        ),
        migrations.AddField(
            model_name="sheltercareerservicesevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="sheltercareerservicesevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltercitiesevent",
            name="city",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.city",
            ),
        ),
        migrations.AddField(
            model_name="sheltercitiesevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="sheltercitiesevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterentryrequirementsevent",
            name="entryrequirement",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.entryrequirement",
            ),
        ),
        migrations.AddField(
            model_name="shelterentryrequirementsevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterentryrequirementsevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="address",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="common.address",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterfundersevent",
            name="funder",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.funder",
            ),
        ),
        migrations.AddField(
            model_name="shelterfundersevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterfundersevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltergeneralservicesevent",
            name="generalservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.generalservice",
            ),
        ),
        migrations.AddField(
            model_name="sheltergeneralservicesevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="sheltergeneralservicesevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterhealthservicesevent",
            name="healthservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.healthservice",
            ),
        ),
        migrations.AddField(
            model_name="shelterhealthservicesevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterhealthservicesevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterimmediateneedsevent",
            name="immediateneed",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.immediateneed",
            ),
        ),
        migrations.AddField(
            model_name="shelterimmediateneedsevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterimmediateneedsevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterparkingevent",
            name="parking",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.parking",
            ),
        ),
        migrations.AddField(
            model_name="shelterparkingevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterparkingevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterpetsevent",
            name="pet",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.pet",
            ),
        ),
        migrations.AddField(
            model_name="shelterpetsevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterpetsevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterpopulationsevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterpopulationsevent",
            name="population",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.population",
            ),
        ),
        migrations.AddField(
            model_name="shelterpopulationsevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltersheltertypesevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="sheltersheltertypesevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltersheltertypesevent",
            name="sheltertype",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.sheltertype",
            ),
        ),
        migrations.AddField(
            model_name="sheltersleepingoptionsevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="sheltersleepingoptionsevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="sheltersleepingoptionsevent",
            name="sleepingoption",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.sleepingoption",
            ),
        ),
        migrations.AddField(
            model_name="shelterspaevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterspaevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterspaevent",
            name="spa",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.spa",
            ),
        ),
        migrations.AddField(
            model_name="shelterstorageevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterstorageevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelterstorageevent",
            name="storage",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.storage",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteraccessibility",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_accessibility_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteraccessibilityevent" ("accessibility_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."accessibility_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_accessibility.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="f21026427e7b8ae1db5d2f3a7be70b2186ff2b14",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_accessibility_add_insert_d99c3",
                    table="shelters_shelter_accessibility",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteraccessibility",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_accessibility_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteraccessibilityevent" ("accessibility_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."accessibility_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_accessibility.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="c905c660278937dd6d635f16fd75953b129ec79f",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_accessibility_remove_delete_7b253",
                    table="shelters_shelter_accessibility",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltercareerservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_career_services_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltercareerservicesevent" ("careerservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."careerservice_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_career_services.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="f68280c65d452731825ac556c2e5531dcaec7bf8",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_career_services_add_insert_2275c",
                    table="shelters_shelter_career_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltercareerservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_career_services_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltercareerservicesevent" ("careerservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."careerservice_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_career_services.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="88dbb5d166d7afa7cfd48fc2f071424956a04f63",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_career_services_remove_delete_8b163",
                    table="shelters_shelter_career_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltercities",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_cities_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltercitiesevent" ("city_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."city_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_cities.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="a4a64e25da05ddb640eb25ca38d6cd912313afff",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_cities_add_insert_5ea8e",
                    table="shelters_shelter_cities",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltercities",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_cities_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltercitiesevent" ("city_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."city_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_cities.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="a50d8f7f87c91f14ca1b029febe52fcfdf71d0be",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_cities_remove_delete_05600",
                    table="shelters_shelter_cities",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterentryrequirements",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_entry_requirements_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterentryrequirementsevent" ("entryrequirement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."entryrequirement_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_entry_requirements.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="d9247e57eb6c3c79627f365148e1fd6874218ab5",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_entry_requirements_add_insert_54c4d",
                    table="shelters_shelter_entry_requirements",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterentryrequirements",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_entry_requirements_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterentryrequirementsevent" ("entryrequirement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."entryrequirement_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_entry_requirements.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="fb1eace900656f5bedad84ed4cd2055149d08f6b",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_entry_requirements_remove_delete_c6e2d",
                    table="shelters_shelter_entry_requirements",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterfunders",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_funders_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterfundersevent" ("funder_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."funder_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_funders.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="24c1ca83ea0ccd3473103e583573dee7c920725f",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_funders_add_insert_062d2",
                    table="shelters_shelter_funders",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterfunders",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_funders_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterfundersevent" ("funder_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."funder_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_funders.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="564994d6b9da49778102204a3cde645d4d15d652",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_funders_remove_delete_36b1b",
                    table="shelters_shelter_funders",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltergeneralservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_general_services_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltergeneralservicesevent" ("generalservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."generalservice_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_general_services.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="ec7e1047ab3bc2c1c51c4373bb70bb9a03d72bb9",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_general_services_add_insert_926a7",
                    table="shelters_shelter_general_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltergeneralservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_general_services_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltergeneralservicesevent" ("generalservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."generalservice_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_general_services.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="3580ea119563aa7e6dd56a513a1e107b4699c422",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_general_services_remove_delete_4151c",
                    table="shelters_shelter_general_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterhealthservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_health_services_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterhealthservicesevent" ("healthservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."healthservice_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter_health_services.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="ec8065a4e5072dc4f60043a97635cad14a58b7eb",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_health_services_add_insert_d5cb4",
                    table="shelters_shelter_health_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterhealthservices",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_health_services_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterhealthservicesevent" ("healthservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."healthservice_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter_health_services.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="7d58257a53d5523713be6a00030e7dc48ca03393",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_health_services_remove_delete_cd826",
                    table="shelters_shelter_health_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterimmediateneeds",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_immediate_needs_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterimmediateneedsevent" ("id", "immediateneed_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."immediateneed_id", _pgh_attach_context(), NOW(), \'shelter_immediate_needs.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="25c8354007e817d2d234e44093034a9bc72aecdb",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_immediate_needs_add_insert_9fe18",
                    table="shelters_shelter_immediate_needs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterimmediateneeds",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_immediate_needs_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterimmediateneedsevent" ("id", "immediateneed_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."immediateneed_id", _pgh_attach_context(), NOW(), \'shelter_immediate_needs.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="77ad3e895b6f6de07c5627946516c81f191ea893",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_immediate_needs_remove_delete_664c2",
                    table="shelters_shelter_immediate_needs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterparking",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_parking_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterparkingevent" ("id", "parking_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."parking_id", _pgh_attach_context(), NOW(), \'shelter_parking.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="352bcc9f4222f36be3ce9ff11ef4d3edaf3c1ce9",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_parking_add_insert_0ad2c",
                    table="shelters_shelter_parking",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterparking",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_parking_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterparkingevent" ("id", "parking_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."parking_id", _pgh_attach_context(), NOW(), \'shelter_parking.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="da97b8e21cf5722c72fa9d04ef5d6aee52a39f6f",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_parking_remove_delete_2fcd1",
                    table="shelters_shelter_parking",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterpets",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_pets_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterpetsevent" ("id", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."pet_id", _pgh_attach_context(), NOW(), \'shelter_pets.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="32187bec44f2ce72841c48e14dc85b83a6111a8d",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_pets_add_insert_d259a",
                    table="shelters_shelter_pets",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterpets",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_pets_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterpetsevent" ("id", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."pet_id", _pgh_attach_context(), NOW(), \'shelter_pets.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="de6fd7da398dd3a94a3d78b58965fd30f87869ed",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_pets_remove_delete_6e337",
                    table="shelters_shelter_pets",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterpopulations",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_populations_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterpopulationsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "population_id", "shelter_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter_populations.add\', NEW."population_id", NEW."shelter_id"); RETURN NULL;',
                    hash="6539d060819fd257584dc025eb6d999f6f53d210",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_populations_add_insert_7d96f",
                    table="shelters_shelter_populations",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterpopulations",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_populations_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterpopulationsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "population_id", "shelter_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter_populations.remove\', OLD."population_id", OLD."shelter_id"); RETURN NULL;',
                    hash="5df532c5e0d7199cdaef9703646e5c23d0312f14",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_populations_remove_delete_186ba",
                    table="shelters_shelter_populations",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltersheltertypes",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_types_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltersheltertypesevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sheltertype_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter_shelter_types.add\', NEW."shelter_id", NEW."sheltertype_id"); RETURN NULL;',
                    hash="b872ffe314b57c6ee080f3f16737086ec6ea2585",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_shelter_types_add_insert_0f4bb",
                    table="shelters_shelter_shelter_types",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltersheltertypes",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_types_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltersheltertypesevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sheltertype_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter_shelter_types.remove\', OLD."shelter_id", OLD."sheltertype_id"); RETURN NULL;',
                    hash="ae5984a584723e7cdd2ae5a2c8f822c78e62eb3a",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_shelter_types_remove_delete_32460",
                    table="shelters_shelter_shelter_types",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltersleepingoptions",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_sleeping_options_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltersleepingoptionsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sleepingoption_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter_sleeping_options.add\', NEW."shelter_id", NEW."sleepingoption_id"); RETURN NULL;',
                    hash="a1bb656ae8fb786611d4e1547734b36288076bd9",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_sleeping_options_add_insert_8698a",
                    table="shelters_shelter_sleeping_options",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="sheltersleepingoptions",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_sleeping_options_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_sheltersleepingoptionsevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sleepingoption_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter_sleeping_options.remove\', OLD."shelter_id", OLD."sleepingoption_id"); RETURN NULL;',
                    hash="284b8d0e91ef31287ca4e62d41e36503b9e19103",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_sleeping_options_remove_delete_3562a",
                    table="shelters_shelter_sleeping_options",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterspa",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_spa_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterspaevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "spa_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter_spa.add\', NEW."shelter_id", NEW."spa_id"); RETURN NULL;',
                    hash="3b1d541aab3df7b75ce57f3b4d0ad856273d3fb3",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_spa_add_insert_bd800",
                    table="shelters_shelter_spa",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterspa",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_spa_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterspaevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "spa_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter_spa.remove\', OLD."shelter_id", OLD."spa_id"); RETURN NULL;',
                    hash="6b729a9600113737b84ef1076157cee051937fcb",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_spa_remove_delete_0b273",
                    table="shelters_shelter_spa",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterstorage",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_storage_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterstorageevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "storage_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter_storage.add\', NEW."shelter_id", NEW."storage_id"); RETURN NULL;',
                    hash="0f07a1a47e726758ee6aaf9f9b365dd126b1b9f7",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_storage_add_insert_e62ab",
                    table="shelters_shelter_storage",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelterstorage",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_storage_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterstorageevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "storage_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter_storage.remove\', OLD."shelter_id", OLD."storage_id"); RETURN NULL;',
                    hash="5ad93b58401b962c8511e054be8315e6dfad7979",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_storage_remove_delete_55cb7",
                    table="shelters_shelter_storage",
                    when="AFTER",
                ),
            ),
        ),
    ]
