# Generated by Django 6.0.6 on 2026-07-14 18:26

"""Replace the conditional bed.maintenance_flag_change trigger with a general bed.update trigger.

The previous trigger only fired on ``maintenance_flag`` changes.  The new
trigger fires on *any* column change (``WHEN (OLD.* IS DISTINCT FROM NEW.*)``)
and emits a ``bed.update`` event.  This is required by
:func:`~shelters.selectors.reports.report_bed_status_counts`, which uses the
full ``bed.update`` event stream to reconstruct historical ``maintenance_flag``
and ``last_cleaned`` state at arbitrary points in time.

.. note::

    This increases the ``BedEvent`` table write volume — every ``Bed.save()``
    that changes any field now produces a row.  The condition still prevents
    no-op saves from emitting spurious events.
"""

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0009_remove_reservation_unique_active_reservation_per_bed_and_more'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='bed',
            name='bed_maintenance_flag_change_update',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='bed',
            trigger=pgtrigger.compiler.Trigger(name='bed_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "shelters_bedevent" ("b7", "created_at", "fees", "id", "last_cleaned", "last_cleaned_inspected", "maintenance_flag", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "room_id", "shelter_id", "status_notes", "storage", "type", "updated_at") VALUES (NEW."b7", NEW."created_at", NEW."fees", NEW."id", NEW."last_cleaned", NEW."last_cleaned_inspected", NEW."maintenance_flag", NEW."name", _pgh_attach_context(), NOW(), \'bed.update\', NEW."id", NEW."room_id", NEW."shelter_id", NEW."status_notes", NEW."storage", NEW."type", NEW."updated_at"); RETURN NULL;', hash='f7a88f83357b5d1efa7dbee7f6c9315d1e932085', operation='UPDATE', pgid='pgtrigger_bed_update_update_1a0e7', table='shelters_bed', when='AFTER')),
        ),
    ]
