# Generated by Django 5.1.3 on 2024-11-18 18:57

import admin_async_upload.models
import django.db.models.deletion
import django_choices_field.fields
import django_ckeditor_5.fields
import pgtrigger.compiler
import pgtrigger.migrations
import phonenumber_field.modelfields
import places.fields
import shelters.enums
import shelters.models
from django.db import migrations, models


class RoomStyleChoicesV14(models.TextChoices):
    CONGREGANT = "congregant", ("Congregant (Open)")
    CUBICLE_LOW_WALLS = "cubicle_low_walls", ("Cubicle (Low Walls)")
    CUBICLE_HIGH_WALLS = "cubicle_high_walls", ("Cubicle (High Walls)")
    HIGH_BUNK = "high_bunk", ("High Bunk")
    LOW_BUNK = "low_bunk", ("Low Bunk")
    SHARED_ROOMS = "shared_rooms", ("Shared Rooms")
    SINGLE_ROOM = "single_room", ("Single Room")
    MOTEL_ROOM = "motel_room", ("Motel Room")
    OTHER = "other", ("Other")


def clean_altered_fields(apps, schema_editor):
    """
    Cleans invalid entries for fields that were altered in this migration to use defined choices.
    """
    # Models and their altered fields with valid choices
    altered_fields = {
        "Demographic": ["all", "single_men", "single_women", "tay_teen", "seniors", "families", "single_moms", "other"],
        "RoomStyle": [
            "congregant",
            "cubicle_low_walls",
            "cubicle_high_walls",
            "shared_rooms",
            "single_room",
            "motel_room",
            "other",
        ],
        "ShelterProgram": [
            "bridge_home",
            "crisis_housing",
            "emergency_shelter",
            "faith_based",
            "interim_housing",
            "permanent_housing",
            "project_home_key",
            "rapid_rehousing",
            "recuperative_care",
            "roadmap_home",
            "safe_park_la",
            "sober_living",
            "tiny_home_village",
            "transitional_housing",
            "winter_shelter",
            "other",
        ],
        "SpecialSituationRestriction": [
            "none",
            "domestic_violence",
            "hiv_aids",
            "human_trafficking",
            "lgbtq_plus",
            "justice_systems",
            "veterans",
        ],
        "TrainingService": ["job_training", "life_skills_training", "tutoring"],
        "HealthService": ["dental", "medical", "mental_health", "substance_use_treatment"],
        "Parking": ["bicycle", "motorcycle", "automobile", "rv", "no_parking"],
        "Storage": ["amnesty_lockers", "standard_lockers", "shared_storage", "no_storage"],
        "ShelterType": [
            "building",
            "church",
            "hotel_motel",
            "safe_parking",
            "single_family_house",
            "tiny_homes",
            "other",
        ],
    }

    # Fields in the Shelter model
    shelter_fields = {
        "status": ["draft", "pending", "approved", "inactive"],
        "city_council_district": list(range(1, 16)),  # [1, 2, ..., 15]
        "supervisorial_district": list(range(1, 6)),  # [1, 2, ..., 5]
    }

    # Clean ManyToMany or ForeignKey models
    for model_name, valid_choices in altered_fields.items():
        model = apps.get_model("shelters", model_name)
        model.objects.exclude(name__in=valid_choices).delete()

    # Clean Shelter fields with choices
    shelter_model = apps.get_model("shelters", "Shelter")
    for field_name, valid_choices in shelter_fields.items():
        shelter_model.objects.exclude(**{f"{field_name}__in": valid_choices}).update(**{field_name: None})


class Migration(migrations.Migration):

    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("pghistory", "0006_delete_aggregateevent"),
        ("shelters", "0009_remove_common_attachment_from_shelter"),
    ]

    operations = [
        migrations.CreateModel(
            name="ContactInfo",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("contact_name", models.CharField(max_length=255, verbose_name="Contact Name")),
                (
                    "contact_number",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None, verbose_name="Contact Number"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Demographic",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("all", "All"),
                            ("single_men", "Single Men"),
                            ("single_women", "Single Women"),
                            ("tay_teen", "TAY/Teen"),
                            ("seniors", "Seniors"),
                            ("families", "Families"),
                            ("single_moms", "Single Moms"),
                            ("other", "Other"),
                        ],
                        choices_enum=shelters.enums.DemographicChoices,
                        max_length=12,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ExteriorPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", admin_async_upload.models.AsyncFileField(upload_to=shelters.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name="InteriorPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", admin_async_upload.models.AsyncFileField(upload_to=shelters.models.upload_path)),
            ],
        ),
        migrations.CreateModel(
            name="RoomStyle",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("congregant", "Congregant (Open)"),
                            ("cubicle_low_walls", "Cubicle (Low Walls)"),
                            ("cubicle_high_walls", "Cubicle (High Walls)"),
                            ("shared_rooms", "Shared Rooms"),
                            ("single_room", "Single Room"),
                            ("motel_room", "Motel Room"),
                            ("other", "Other"),
                        ],
                        choices_enum=RoomStyleChoicesV14,
                        max_length=18,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ShelterEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("location", places.fields.PlacesField(blank=True, max_length=255, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ("website", models.URLField(blank=True, null=True)),
                ("description", django_ckeditor_5.fields.CKEditor5Field()),
                ("demographics_other", models.CharField(blank=True, max_length=255, null=True)),
                ("shelter_types_other", models.CharField(blank=True, max_length=255, null=True)),
                ("total_beds", models.PositiveIntegerField(blank=True, null=True)),
                ("room_styles_other", models.CharField(blank=True, max_length=255, null=True)),
                ("max_stay", models.PositiveIntegerField(blank=True, null=True, verbose_name="Max Stay (days)")),
                ("curfew", models.TimeField(blank=True, null=True)),
                ("on_site_security", models.BooleanField(blank=True, null=True)),
                ("other_rules", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("other_services", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("entry_info", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("bed_fees", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                ("program_fees", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                (
                    "city_council_district",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[
                            (1, "1"),
                            (2, "2"),
                            (3, "3"),
                            (4, "4"),
                            (5, "5"),
                            (6, "6"),
                            (7, "7"),
                            (8, "8"),
                            (9, "9"),
                            (10, "10"),
                            (11, "11"),
                            (12, "12"),
                            (13, "13"),
                            (14, "14"),
                            (15, "15"),
                        ],
                        null=True,
                        verbose_name="LA City Council District",
                    ),
                ),
                (
                    "supervisorial_district",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                        null=True,
                        verbose_name="Supervisorial District",
                    ),
                ),
                ("shelter_programs_other", models.CharField(blank=True, max_length=255, null=True)),
                ("funders_other", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "overall_rating",
                    models.PositiveSmallIntegerField(
                        blank=True, choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
                    ),
                ),
                ("subjective_review", django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True)),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("draft", "Draft"),
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("inactive", "Inactive"),
                        ],
                        choices_enum=shelters.enums.StatusChoices,
                        default="draft",
                        max_length=8,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ShelterProgram",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("bridge_home", "Bridge Home"),
                            ("crisis_housing", "Crisis Housing"),
                            ("emergency_shelter", "Emergency Shelter"),
                            ("faith_based", "Faith Based"),
                            ("interim_housing", "Interim Housing"),
                            ("permanent_housing", "Permanent Housing"),
                            ("project_home_key", "Project Home Key (PHK)"),
                            ("rapid_rehousing", "Rapid Rehousing"),
                            ("recuperative_care", "Recuperative Care"),
                            ("roadmap_home", "Roadmap Home"),
                            ("safe_park_la", "Safe Park LA"),
                            ("sober_living", "Sober Living"),
                            ("tiny_home_village", "Tiny Home Village"),
                            ("transitional_housing", "Transitional Housing"),
                            ("winter_shelter", "Winter Shelter"),
                            ("other", "Other"),
                        ],
                        choices_enum=shelters.enums.ShelterProgramChoices,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SpecialSituationRestriction",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("none", "None"),
                            ("domestic_violence", "Domestic Violence (DV/IPV)"),
                            ("hiv_aids", "HIV/AIDS"),
                            ("human_trafficking", "Human Trafficking"),
                            ("lgbtq_plus", "LGBTQ+"),
                            ("justice_systems", "Persons Exiting Justice Systems"),
                            ("veterans", "Veterans"),
                        ],
                        choices_enum=shelters.enums.SpecialSituationRestrictionChoices,
                        max_length=17,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrainingService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("job_training", "Job Training"),
                            ("life_skills_training", "Life Skills Training"),
                            ("tutoring", "Tutoring"),
                        ],
                        choices_enum=shelters.enums.TrainingServiceChoices,
                        max_length=20,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("file", admin_async_upload.models.AsyncFileField(upload_to=shelters.models.upload_path)),
            ],
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="career_services",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="populations",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="sleeping_options",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="address",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="city_district",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="drugs",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="fees",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="how_to_enter",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="is_reviewed",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="mandatory_worship_attendance",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="security",
        ),
        migrations.AddField(
            model_name="shelter",
            name="bed_fees",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="city_council_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                ],
                db_index=True,
                null=True,
                verbose_name="LA City Council District",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="demographics_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="entry_info",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="funders_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="location",
            field=places.fields.PlacesField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="on_site_security",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="other_rules",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="other_services",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="overall_rating",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")], null=True
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="room_styles_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="shelter_programs_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="shelter_types_other",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("draft", "Draft"),
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("inactive", "Inactive"),
                ],
                choices_enum=shelters.enums.StatusChoices,
                default="draft",
                max_length=8,
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="subjective_review",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="healthservice",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("dental", "Dental"),
                    ("medical", "Medical"),
                    ("mental_health", "Mental Health"),
                    ("substance_use_treatment", "Substance Use Treatment"),
                ],
                choices_enum=shelters.enums.HealthServiceChoices,
                max_length=23,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="parking",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("bicycle", "Bicycle"),
                    ("motorcycle", "Motorcycle"),
                    ("automobile", "Automobile"),
                    ("rv", "RV"),
                    ("no_parking", "No Parking"),
                ],
                choices_enum=shelters.enums.ParkingChoices,
                max_length=10,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="description",
            field=django_ckeditor_5.fields.CKEditor5Field(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="shelter",
            name="program_fees",
            field=django_ckeditor_5.fields.CKEditor5Field(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="supervisorial_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[(1, "1"), (2, "2"), (3, "3"), (4, "4"), (5, "5")],
                db_index=True,
                null=True,
                verbose_name="Supervisorial District",
            ),
        ),
        migrations.AlterField(
            model_name="sheltertype",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("building", "Building"),
                    ("church", "Church"),
                    ("hotel_motel", "Hotel/Motel"),
                    ("safe_parking", "Safe Parking"),
                    ("single_family_house", "Single Family House"),
                    ("tiny_homes", "Tiny Homes"),
                    ("other", "Other"),
                ],
                choices_enum=shelters.enums.ShelterChoices,
                max_length=19,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="storage",
            name="name",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("amnesty_lockers", "Amnesty Lockers"),
                    ("standard_lockers", "Standard Lockers"),
                    ("shared_storage", "Shared Storage"),
                    ("no_storage", "No Storage"),
                ],
                choices_enum=shelters.enums.StorageChoices,
                max_length=16,
                null=True,
                unique=True,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="insert_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'insert\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="7acf2f75848459021c4951d3b589d7994a42c1d8",
                    operation="INSERT",
                    pgid="pgtrigger_insert_insert_35491",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="0ccec664fd9c26742487ea7c29ee04a1e857cd91",
                    operation="UPDATE",
                    pgid="pgtrigger_update_update_87957",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="additional_contacts", to="shelters.shelter"
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="demographics",
            field=models.ManyToManyField(to="shelters.demographic"),
        ),
        migrations.AddField(
            model_name="exteriorphoto",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="exterior_photos", to="shelters.shelter"
            ),
        ),
        migrations.AddField(
            model_name="interiorphoto",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="interior_photos", to="shelters.shelter"
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="room_styles",
            field=models.ManyToManyField(to="shelters.roomstyle"),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="organizations.organization",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="shelter_programs",
            field=models.ManyToManyField(to="shelters.shelterprogram"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="special_situation_restrictions",
            field=models.ManyToManyField(to="shelters.specialsituationrestriction"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="training_services",
            field=models.ManyToManyField(to="shelters.trainingservice"),
        ),
        migrations.AddField(
            model_name="video",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="videos", to="shelters.shelter"
            ),
        ),
        migrations.DeleteModel(
            name="CareerService",
        ),
        migrations.DeleteModel(
            name="Population",
        ),
        migrations.DeleteModel(
            name="SleepingOption",
        ),
        migrations.RunPython(clean_altered_fields),
    ]
