# Generated by Django 5.1.3 on 2024-11-19 22:36

import common.history
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0006_delete_aggregateevent"),
        ("shelters", "0010_contactinfo_demographic_exteriorphoto_interiorphoto_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrackedAccessibilityEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedCityEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedDemographicEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedEntryRequirementEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedFunderEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedGeneralServiceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedHealthServiceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedImmediateNeedEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedParkingEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedPetEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedRoomStyleEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedShelterProgramEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedShelterTypeEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedSPAEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedSpecialSituationRestrictionEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedStorageEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedTrainingServiceEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TrackedAccessibility",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_accessibility", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedCity",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_cities", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedDemographic",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_demographics", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedEntryRequirement",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_entry_requirements", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedFunder",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_funders", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedGeneralService",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_general_services", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedHealthService",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_health_services", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedImmediateNeed",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_immediate_needs", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedParking",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_parking", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedPet",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_pets", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedRoomStyle",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_room_styles", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedShelterProgram",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_shelter_programs", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedShelterType",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_shelter_types", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedSPA",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_spa", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedSpecialSituationRestriction",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_special_situation_restrictions", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedStorage",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_storage", common.history.RevertibleTrackedModel),
        ),
        migrations.CreateModel(
            name="TrackedTrainingService",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_training_services", common.history.RevertibleTrackedModel),
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="insert_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="update_update",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="83e3485b300a9118eaa2012ceba22aaa731e4d28",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="bd874a60df3bdef508062ce4b88886d4da64c432",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (OLD."bed_fees", OLD."city_council_district", OLD."created_at", OLD."curfew", OLD."demographics_other", OLD."description", OLD."email", OLD."entry_info", OLD."funders_other", OLD."id", OLD."location", OLD."max_stay", OLD."name", OLD."on_site_security", OLD."organization_id", OLD."other_rules", OLD."other_services", OLD."overall_rating", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."room_styles_other", OLD."shelter_programs_other", OLD."shelter_types_other", OLD."status", OLD."subjective_review", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."website"); RETURN NULL;',
                    hash="ac5683d29a56c63c9065c74902b9cfc216b4f447",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="trackedaccessibilityevent",
            name="accessibility",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.accessibility",
            ),
        ),
        migrations.AddField(
            model_name="trackedaccessibilityevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedaccessibilityevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedcityevent",
            name="city",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.city",
            ),
        ),
        migrations.AddField(
            model_name="trackedcityevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedcityevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackeddemographicevent",
            name="demographic",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.demographic",
            ),
        ),
        migrations.AddField(
            model_name="trackeddemographicevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackeddemographicevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedentryrequirementevent",
            name="entryrequirement",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.entryrequirement",
            ),
        ),
        migrations.AddField(
            model_name="trackedentryrequirementevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedentryrequirementevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedfunderevent",
            name="funder",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.funder",
            ),
        ),
        migrations.AddField(
            model_name="trackedfunderevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedfunderevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedgeneralserviceevent",
            name="generalservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.generalservice",
            ),
        ),
        migrations.AddField(
            model_name="trackedgeneralserviceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedgeneralserviceevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedhealthserviceevent",
            name="healthservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.healthservice",
            ),
        ),
        migrations.AddField(
            model_name="trackedhealthserviceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedhealthserviceevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedimmediateneedevent",
            name="immediateneed",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.immediateneed",
            ),
        ),
        migrations.AddField(
            model_name="trackedimmediateneedevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedimmediateneedevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedparkingevent",
            name="parking",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.parking",
            ),
        ),
        migrations.AddField(
            model_name="trackedparkingevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedparkingevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedpetevent",
            name="pet",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.pet",
            ),
        ),
        migrations.AddField(
            model_name="trackedpetevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedpetevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedroomstyleevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedroomstyleevent",
            name="roomstyle",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.roomstyle",
            ),
        ),
        migrations.AddField(
            model_name="trackedroomstyleevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedshelterprogramevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedshelterprogramevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedshelterprogramevent",
            name="shelterprogram",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelterprogram",
            ),
        ),
        migrations.AddField(
            model_name="trackedsheltertypeevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedsheltertypeevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedsheltertypeevent",
            name="sheltertype",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.sheltertype",
            ),
        ),
        migrations.AddField(
            model_name="trackedspaevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedspaevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedspaevent",
            name="spa",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.spa",
            ),
        ),
        migrations.AddField(
            model_name="trackedspecialsituationrestrictionevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedspecialsituationrestrictionevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedspecialsituationrestrictionevent",
            name="specialsituationrestriction",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.specialsituationrestriction",
            ),
        ),
        migrations.AddField(
            model_name="trackedstorageevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedstorageevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedstorageevent",
            name="storage",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.storage",
            ),
        ),
        migrations.AddField(
            model_name="trackedtrainingserviceevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="trackedtrainingserviceevent",
            name="shelter",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelter",
            ),
        ),
        migrations.AddField(
            model_name="trackedtrainingserviceevent",
            name="trainingservice",
            field=models.ForeignKey(
                db_constraint=False,
                db_tablespace="",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.trainingservice",
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedaccessibility",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_accessibility_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedaccessibilityevent" ("accessibility_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."accessibility_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.accessibility.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="95d0d75352cc91c0d03ee9a4d1d79fd667f1a8c2",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_accessibility_add_insert_34c8d",
                    table="shelters_shelter_accessibility",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedaccessibility",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_accessibility_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedaccessibilityevent" ("accessibility_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."accessibility_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.accessibility.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="774b550db1a281de1b1d4b79d8a8ad6cc8219564",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_accessibility_remove_delete_74d75",
                    table="shelters_shelter_accessibility",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedcity",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_city_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedcityevent" ("city_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."city_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.city.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="b05ff10d3d7278c0b5379eaf2f97991304c0a313",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_city_add_insert_a0b38",
                    table="shelters_shelter_cities",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedcity",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_city_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedcityevent" ("city_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."city_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.city.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="dbf22de2ffc991132f4a26e5f167d5d4c3ae8b35",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_city_remove_delete_ccaa8",
                    table="shelters_shelter_cities",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackeddemographic",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_demographic_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackeddemographicevent" ("demographic_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."demographic_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.demographic.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="5f3b28b1031bcd58c36264e8fbab47923e105b47",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_demographic_add_insert_9489d",
                    table="shelters_shelter_demographics",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackeddemographic",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_demographic_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackeddemographicevent" ("demographic_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."demographic_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.demographic.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="d691772064b89d79fd999c380a1f1ce3b79e1f2c",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_demographic_remove_delete_0dbba",
                    table="shelters_shelter_demographics",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedentryrequirement",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_entry_requirement_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedentryrequirementevent" ("entryrequirement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."entryrequirement_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.entry_requirement.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="07de451bb1f8e489433a95c21e599ef8c4ea9567",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_entry_requirement_add_insert_e186e",
                    table="shelters_shelter_entry_requirements",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedentryrequirement",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_entry_requirement_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedentryrequirementevent" ("entryrequirement_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."entryrequirement_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.entry_requirement.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="7c65e81436db4eba6b38fa7316cb1328e0c91f80",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_entry_requirement_remove_delete_1b995",
                    table="shelters_shelter_entry_requirements",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedfunder",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_funder_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedfunderevent" ("funder_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."funder_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.funder.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="cb54d7780dd1bfba920cd6cb00f3c6c3b70c77a3",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_funder_add_insert_e2d7b",
                    table="shelters_shelter_funders",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedfunder",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_funder_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedfunderevent" ("funder_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."funder_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.funder.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="6f799a89ed47562ee964a3872a6a789a857ccee8",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_funder_remove_delete_8c37c",
                    table="shelters_shelter_funders",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedgeneralservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_general_service_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedgeneralserviceevent" ("generalservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."generalservice_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.general_service.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="aeaab390287c7dfa49251a811b656d195467544c",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_general_service_add_insert_1ad19",
                    table="shelters_shelter_general_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedgeneralservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_general_service_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedgeneralserviceevent" ("generalservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."generalservice_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.general_service.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="761c3529033aca72275c2c8faa09b9fdb1830768",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_general_service_remove_delete_a562f",
                    table="shelters_shelter_general_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedhealthservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_health_service_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedhealthserviceevent" ("healthservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."healthservice_id", NEW."id", _pgh_attach_context(), NOW(), \'shelter.health_service.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="75be5d974a0a2974566b5c8cc73961a6140759a1",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_health_service_add_insert_eb4e6",
                    table="shelters_shelter_health_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedhealthservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_health_service_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedhealthserviceevent" ("healthservice_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."healthservice_id", OLD."id", _pgh_attach_context(), NOW(), \'shelter.health_service.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="65dfa1e1ba2a180d0b61bff7e37620a24055c464",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_health_service_remove_delete_fa760",
                    table="shelters_shelter_health_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedimmediateneed",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_immediate_need_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedimmediateneedevent" ("id", "immediateneed_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."immediateneed_id", _pgh_attach_context(), NOW(), \'shelter.immediate_need.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="79ddb3f2e06bf67ea617256ea2f25383b96852d5",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_immediate_need_add_insert_4ba75",
                    table="shelters_shelter_immediate_needs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedimmediateneed",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_immediate_need_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedimmediateneedevent" ("id", "immediateneed_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."immediateneed_id", _pgh_attach_context(), NOW(), \'shelter.immediate_need.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="d2d1e3b8ed7f48c2ff81e48cd526d2f5330e7333",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_immediate_need_remove_delete_44203",
                    table="shelters_shelter_immediate_needs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedparking",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_parking_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedparkingevent" ("id", "parking_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."parking_id", _pgh_attach_context(), NOW(), \'shelter.parking.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="4a87ca22e425bf41fdc9ab7194817956f87edd75",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_parking_add_insert_ed255",
                    table="shelters_shelter_parking",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedparking",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_parking_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedparkingevent" ("id", "parking_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."parking_id", _pgh_attach_context(), NOW(), \'shelter.parking.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="83e104b16e4bd6f69150144493ba14d310381364",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_parking_remove_delete_ff50a",
                    table="shelters_shelter_parking",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedpet",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_pet_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedpetevent" ("id", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (NEW."id", NEW."pet_id", _pgh_attach_context(), NOW(), \'shelter.pet.add\', NEW."shelter_id"); RETURN NULL;',
                    hash="c20d8b4966e98019b0178c2fedd76eb89000ac02",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_pet_add_insert_29229",
                    table="shelters_shelter_pets",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedpet",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_pet_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedpetevent" ("id", "pet_id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id") VALUES (OLD."id", OLD."pet_id", _pgh_attach_context(), NOW(), \'shelter.pet.remove\', OLD."shelter_id"); RETURN NULL;',
                    hash="48318468c41143eeb9e57b957b87e8d05c6a3751",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_pet_remove_delete_d29b3",
                    table="shelters_shelter_pets",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedroomstyle",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_room_style_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedroomstyleevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "roomstyle_id", "shelter_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.room_style.add\', NEW."roomstyle_id", NEW."shelter_id"); RETURN NULL;',
                    hash="2f73054d51d32faaaf834401fc31b6f2bbd6093e",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_room_style_add_insert_17737",
                    table="shelters_shelter_room_styles",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedroomstyle",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_room_style_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedroomstyleevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "roomstyle_id", "shelter_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.room_style.remove\', OLD."roomstyle_id", OLD."shelter_id"); RETURN NULL;',
                    hash="1f04a813cb26745d54d38dca8066e988311f90d7",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_room_style_remove_delete_2ce2f",
                    table="shelters_shelter_room_styles",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedshelterprogram",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_program_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedshelterprogramevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "shelterprogram_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.shelter_program.add\', NEW."shelter_id", NEW."shelterprogram_id"); RETURN NULL;',
                    hash="ddbdb13a47496a38f82768981ec87aba5180841c",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_shelter_program_add_insert_b786c",
                    table="shelters_shelter_shelter_programs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedshelterprogram",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_program_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedshelterprogramevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "shelterprogram_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.shelter_program.remove\', OLD."shelter_id", OLD."shelterprogram_id"); RETURN NULL;',
                    hash="ddad1943e597b09efd729199e74bd46bdaad8165",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_shelter_program_remove_delete_f9fc9",
                    table="shelters_shelter_shelter_programs",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedsheltertype",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_type_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedsheltertypeevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sheltertype_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.shelter_type.add\', NEW."shelter_id", NEW."sheltertype_id"); RETURN NULL;',
                    hash="a7bda54615d1270975b9c0c29d8ba8f9df064dfb",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_shelter_type_add_insert_1f524",
                    table="shelters_shelter_shelter_types",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedsheltertype",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_shelter_type_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedsheltertypeevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "sheltertype_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.shelter_type.remove\', OLD."shelter_id", OLD."sheltertype_id"); RETURN NULL;',
                    hash="b7e308f3c97b6e46b6fd6fca92863d56ef5822f8",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_shelter_type_remove_delete_c47b0",
                    table="shelters_shelter_shelter_types",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedspa",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_spa_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedspaevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "spa_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.spa.add\', NEW."shelter_id", NEW."spa_id"); RETURN NULL;',
                    hash="fd9fd467a110042f8fa5eac2fdf36fa4f03004fd",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_spa_add_insert_beb19",
                    table="shelters_shelter_spa",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedspa",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_spa_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedspaevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "spa_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.spa.remove\', OLD."shelter_id", OLD."spa_id"); RETURN NULL;',
                    hash="4e6ce039af6413fc3c04c58666daf8a770c09acd",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_spa_remove_delete_f8757",
                    table="shelters_shelter_spa",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedspecialsituationrestriction",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_special_restriction_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedspecialsituationrestrictionevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "specialsituationrestriction_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.special_restriction.add\', NEW."shelter_id", NEW."specialsituationrestriction_id"); RETURN NULL;',
                    hash="0561aefd8b52d8456356c9762c6c2cf8a6f7663e",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_special_restriction_add_insert_24722",
                    table="shelters_shelter_special_situation_restrictions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedspecialsituationrestriction",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_special_restriction_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedspecialsituationrestrictionevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "specialsituationrestriction_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.special_restriction.remove\', OLD."shelter_id", OLD."specialsituationrestriction_id"); RETURN NULL;',
                    hash="49b6a28e5387ee882a816cda450b4a68acd21364",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_special_restriction_remove_delete_7e7ba",
                    table="shelters_shelter_special_situation_restrictions",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedstorage",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_storage_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedstorageevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "storage_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.storage.add\', NEW."shelter_id", NEW."storage_id"); RETURN NULL;',
                    hash="a54cfb0f3846e719f16015d103aace66a771f0c8",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_storage_add_insert_c7f3d",
                    table="shelters_shelter_storage",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedstorage",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_storage_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedstorageevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "storage_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.storage.remove\', OLD."shelter_id", OLD."storage_id"); RETURN NULL;',
                    hash="9bd146b2b9f52c2ea0bfa0d3e5f9abd8795d3edb",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_storage_remove_delete_520a9",
                    table="shelters_shelter_storage",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedtrainingservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_training_service_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedtrainingserviceevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "trainingservice_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.training_service.add\', NEW."shelter_id", NEW."trainingservice_id"); RETURN NULL;',
                    hash="2e05c479526c5ddd8be6809ba868d968e9393257",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_training_service_add_insert_ec98c",
                    table="shelters_shelter_training_services",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedtrainingservice",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_training_service_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedtrainingserviceevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "trainingservice_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.training_service.remove\', OLD."shelter_id", OLD."trainingservice_id"); RETURN NULL;',
                    hash="3f1068f9607ccac4c53f17144ce723dd62f302f1",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_training_service_remove_delete_6694d",
                    table="shelters_shelter_training_services",
                    when="AFTER",
                ),
            ),
        ),
    ]
