# Generated by Django 4.2.9 on 2024-03-14 03:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0010_alter_population_title_alter_requirement_title_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="how_to_enter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Call", "Call"),
                    ("Referral", "Referral"),
                    ("Walk-In", "Walk-In"),
                ],
                null=True,
            ),
        ),
    ]
