# Generated by Django 6.0.6 on 2026-07-15 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelters', '0011_add_schedule_cyclic_columns'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('end_time__isnull', True), ('start_time__isnull', True)), models.Q(('end_time__isnull', False), ('start_time__isnull', False)), _connector='OR'), name='schedule_times_both_or_neither'),
        ),
        migrations.AddConstraint(
            model_name='schedule',
            constraint=models.CheckConstraint(condition=models.Q(('start_date__isnull', True), ('end_date__isnull', True), ('start_date__lte', models.F('end_date')), _connector='OR'), name='schedule_start_date_lte_end_date'),
        ),
    ]
