# Generated by Django 5.1.3 on 2024-12-10 17:11

import django.contrib.gis.db.models.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0012_basemodel_for_photos_and_video"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_remove_delete",
        ),
        migrations.AddField(
            model_name="shelter",
            name="geolocation",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="geolocation",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "geolocation", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."geolocation", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="99bab7731831296ded8d2fbf9619a24c936cb2a9",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "geolocation", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."entry_info", NEW."funders_other", NEW."geolocation", NEW."id", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."website"); RETURN NULL;',
                    hash="dc107a2b4815070a8d988602461a40830f8651b0",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "entry_info", "funders_other", "geolocation", "id", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "website") VALUES (OLD."bed_fees", OLD."city_council_district", OLD."created_at", OLD."curfew", OLD."demographics_other", OLD."description", OLD."email", OLD."entry_info", OLD."funders_other", OLD."geolocation", OLD."id", OLD."location", OLD."max_stay", OLD."name", OLD."on_site_security", OLD."organization_id", OLD."other_rules", OLD."other_services", OLD."overall_rating", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."room_styles_other", OLD."shelter_programs_other", OLD."shelter_types_other", OLD."status", OLD."subjective_review", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."website"); RETURN NULL;',
                    hash="f9d44d1e71c3b524121ed9fc4358123a0b42a1cd",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
    ]
