# Generated by Django 4.2.9 on 2024-03-14 23:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0012_remove_shelter_max_day_alter_shelter_max_stay"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="address",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="city",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="how_to_enter",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Call", "Call"),
                    ("Referral", "Referral"),
                    ("Walk-In", "Walk-In"),
                ],
                default="",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="phone",
            field=models.CharField(default="", max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="spa",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="state",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
    ]
