# Generated by Django 4.2.9 on 2024-03-14 23:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0013_alter_shelter_address_alter_shelter_city_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="spa",
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
