# Generated by Django 5.1.6 on 2025-02-26 01:46

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0015_remove_shelter_shelter_add_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_remove_delete",
        ),
        migrations.AddField(
            model_name="shelter",
            name="intake_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelter",
            name="intake_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="intake_hours_end",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="intake_hours_start",
            field=models.TimeField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "funders_other", "geolocation", "id", "intake_hours_end", "intake_hours_start", "location", "max_stay", "name", "on_site_security", "operating_hours_end", "operating_hours_start", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."funders_other", NEW."geolocation", NEW."id", NEW."intake_hours_end", NEW."intake_hours_start", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."operating_hours_end", NEW."operating_hours_start", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="f21fc09e39ff583a8bdd86feeee57f84cc5ec4b2",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "funders_other", "geolocation", "id", "intake_hours_end", "intake_hours_start", "location", "max_stay", "name", "on_site_security", "operating_hours_end", "operating_hours_start", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."funders_other", NEW."geolocation", NEW."id", NEW."intake_hours_end", NEW."intake_hours_start", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."operating_hours_end", NEW."operating_hours_start", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="d0eef5e1fe67b30419e9618ee8f4951d16f60790",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "funders_other", "geolocation", "id", "intake_hours_end", "intake_hours_start", "location", "max_stay", "name", "on_site_security", "operating_hours_end", "operating_hours_start", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (OLD."add_notes_shelter_details", OLD."add_notes_sleeping_details", OLD."bed_fees", OLD."city_council_district", OLD."created_at", OLD."curfew", OLD."demographics_other", OLD."description", OLD."email", OLD."emergency_surge", OLD."entry_info", OLD."funders_other", OLD."geolocation", OLD."id", OLD."intake_hours_end", OLD."intake_hours_start", OLD."location", OLD."max_stay", OLD."name", OLD."on_site_security", OLD."operating_hours_end", OLD."operating_hours_start", OLD."organization_id", OLD."other_rules", OLD."other_services", OLD."overall_rating", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."room_styles_other", OLD."shelter_programs_other", OLD."shelter_types_other", OLD."status", OLD."subjective_review", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."visitors_allowed", OLD."website"); RETURN NULL;',
                    hash="5acff919a04b233ba18ee694b67186fe36198e0f",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
    ]
