# Generated by Django 5.1.6 on 2025-02-26 22:01

import django_choices_field.fields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0016_remove_shelter_shelter_add_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExitPolicy",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("mia", "Exit after 72 hours of being MIA"),
                            ("violence", "Exit due to violence to self or others"),
                            ("mitigation", "30 Days Mitigation plan prior to exits"),
                            ("other", "Other"),
                        ],
                        choices_enum=shelters.enums.ExitPolicyChoices,
                        max_length=10,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shelter",
            name="exit_policy",
            field=models.ManyToManyField(to="shelters.exitpolicy"),
        ),
    ]
