# Generated by Django 4.2.9 on 2024-03-21 04:06

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import shelters.enums


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0017_remove_shelter_population_shelter_population"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelter",
            name="population",
        ),
        migrations.AddField(
            model_name="population",
            name="shelter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="populations",
                to="shelters.shelter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="population",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Adults", "Adults"),
                    ("Men", "Men"),
                    ("Women", "Women"),
                    ("Families", "Families"),
                    ("Youth", "Youth"),
                    ("Boys", "Boys"),
                    ("Girls", "Girls"),
                    ("Seniors", "Seniors"),
                    ("Veterans", "Veterans"),
                    ("LGBTQ", "LGBTQ"),
                    ("", ""),
                ],
                choices_enum=shelters.enums.PopulationEnum,
                default="",
                max_length=8,
            ),
        ),
    ]
