# Generated by Django 5.1.6 on 2025-02-26 23:25

import django_choices_field.fields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0018_remove_shelter_shelter_add_insert_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="MatchedReferralRequirement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("service_provider_submission", "Service Provider Submission"),
                            ("self_referral", "Self Referral Option"),
                            ("same_day_intake", "Same Day Intake"),
                        ],
                        choices_enum=shelters.enums.MatchedReferralRequirementChoices,
                        max_length=27,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MealService",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("breakfast", "Breakfast"), ("lunch", "Lunch"), ("dinner", "Dinner")],
                        choices_enum=shelters.enums.MealServiceChoices,
                        max_length=9,
                        null=True,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="shelter",
            name="matched_referral",
            field=models.ManyToManyField(to="shelters.matchedreferralrequirement"),
        ),
        migrations.AddField(
            model_name="shelter",
            name="meal_services",
            field=models.ManyToManyField(to="shelters.mealservice"),
        ),
    ]
