# Generated by Django 4.2.9 on 2024-03-21 04:35

from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import shelters.enums


class Migration(migrations.Migration):
    dependencies = [
        ("shelters", "0019_remove_shelter_requirements_requirement_shelter_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="shelter",
            name="how_to_enter",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="services",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="shelter_type",
        ),
        migrations.AddField(
            model_name="service",
            name="shelter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="services",
                to="shelters.shelter",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="sheltertype",
            name="shelter",
            field=models.ForeignKey(
                default=None,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="shelter_type",
                to="shelters.shelter",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="service",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Food", "Food"),
                    ("Shower", "Shower"),
                    ("Clothing", "Clothing"),
                    ("Mail", "Mail"),
                    ("Phone", "Phone"),
                    ("Computers", "Computes"),
                    ("Job Training", "Job Training"),
                    ("Tutoring", "Tutoring"),
                    ("Life Skills Training", "Life Skills Training"),
                    ("Medical Services", "Medical Services"),
                    ("Mental Health", "Mental Health"),
                    ("Drug Treatment", "Drug Treatment"),
                    ("Financial Planning", "Financial Planning"),
                    ("Legal Assistance", "Legal Assistance"),
                    ("Transportation", "Transportation"),
                ],
                choices_enum=shelters.enums.ServiceEnum,
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sheltertype",
            name="title",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("Interim Housing", "Interim Housing"),
                    ("Permanent Housing", "Permanent Housing"),
                    ("A Bridge Home (ABH)", "A Bridge Home"),
                    ("Project Homekey (PHK)", "Project Homekey (PHK)"),
                    ("Tiny Home Village", "Tiny Home Village"),
                    ("Winter Shelter", "Winter Shelter"),
                    ("Emergency Shelter", "Emergency Shelter"),
                    ("Crisis Housing", "Crisis Housing"),
                    ("Recuperative Care", "Recuperative Care"),
                    ("Transitional Housing", "Transitional Housing"),
                    ("Roadmap Home", "Roadmap Home"),
                    ("Rapid Re-housing", "Rapid Re-housing"),
                    ("Sober Living", "Sober Living"),
                ],
                choices_enum=shelters.enums.ShelterTypeEnum,
                max_length=21,
            ),
        ),
        migrations.CreateModel(
            name="HowToEnter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("Call", "Call"),
                            ("Referral", "Referral"),
                            ("Walk-In", "Walk-In"),
                        ],
                        choices_enum=shelters.enums.HowToEnterEnum,
                        max_length=8,
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="how_to_enter",
                        to="shelters.shelter",
                    ),
                ),
            ],
        ),
    ]
