# Generated by Django 5.2.4 on 2025-07-29 19:42

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("shelters", "0019_alter_demographic_name_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_remove_delete",
        ),
        migrations.AddField(
            model_name="shelter",
            name="hero_image_content_type",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="contenttypes.contenttype"
            ),
        ),
        migrations.AddField(
            model_name="shelter",
            name="hero_image_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="hero_image_content_type",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="hero_image_object_id",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_content_type_id", "hero_image_object_id", "id", "intake_hours", "location", "max_stay", "name", "on_site_security", "operating_hours", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."exit_policy_other", NEW."funders_other", NEW."geolocation", NEW."hero_image_content_type_id", NEW."hero_image_object_id", NEW."id", NEW."intake_hours", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."operating_hours", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="884de11f55480030da7a4485a4e5bd2e8d9a39a4",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_content_type_id", "hero_image_object_id", "id", "intake_hours", "location", "max_stay", "name", "on_site_security", "operating_hours", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."exit_policy_other", NEW."funders_other", NEW."geolocation", NEW."hero_image_content_type_id", NEW."hero_image_object_id", NEW."id", NEW."intake_hours", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."operating_hours", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="89edf35d230423903bbfc3560c53bb8128e1d85f",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_content_type_id", "hero_image_object_id", "id", "intake_hours", "location", "max_stay", "name", "on_site_security", "operating_hours", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (OLD."add_notes_shelter_details", OLD."add_notes_sleeping_details", OLD."bed_fees", OLD."city_council_district", OLD."created_at", OLD."curfew", OLD."demographics_other", OLD."description", OLD."email", OLD."emergency_surge", OLD."entry_info", OLD."exit_policy_other", OLD."funders_other", OLD."geolocation", OLD."hero_image_content_type_id", OLD."hero_image_object_id", OLD."id", OLD."intake_hours", OLD."location", OLD."max_stay", OLD."name", OLD."on_site_security", OLD."operating_hours", OLD."organization_id", OLD."other_rules", OLD."other_services", OLD."overall_rating", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."room_styles_other", OLD."shelter_programs_other", OLD."shelter_types_other", OLD."status", OLD."subjective_review", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."visitors_allowed", OLD."website"); RETURN NULL;',
                    hash="7ade2b5763471c9667a31c3c7e415b8d8b6724e1",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
    ]
