# Generated by Django 5.2.3 on 2025-07-01 00:07

import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0020_shelter_operating_hours_field"),
    ]

    operations = [
        migrations.CreateModel(
            name="OperatingHour",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "day_of_week",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        choices_enum=shelters.enums.DayOfWeekChoices,
                        max_length=9,
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="operating_hours",
                        to="shelters.shelter",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="OperatingHourEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "day_of_week",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        choices_enum=shelters.enums.DayOfWeekChoices,
                        max_length=9,
                    ),
                ),
                ("opens_at", models.TimeField()),
                ("closes_at", models.TimeField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="shelters.operatinghour",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.shelter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="operatinghour",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_operating_hour_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_operatinghourevent" ("closes_at", "day_of_week", "id", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (NEW."closes_at", NEW."day_of_week", NEW."id", NEW."opens_at", _pgh_attach_context(), NOW(), \'shelter.operating_hour.add\', NEW."id", NEW."shelter_id"); RETURN NULL;',
                    hash="ca0faa4e80559ae1f581ba6e13cd283fe3185684",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_operating_hour_add_insert_1bf7f",
                    table="shelters_operatinghour",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="operatinghour",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_operating_hour_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_operatinghourevent" ("closes_at", "day_of_week", "id", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (NEW."closes_at", NEW."day_of_week", NEW."id", NEW."opens_at", _pgh_attach_context(), NOW(), \'shelter.operating_hour.update\', NEW."id", NEW."shelter_id"); RETURN NULL;',
                    hash="a00ff6738b137cab166df1498baaffe817b1d1e6",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_operating_hour_update_update_6da40",
                    table="shelters_operatinghour",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="operatinghour",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_operating_hour_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_operatinghourevent" ("closes_at", "day_of_week", "id", "opens_at", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (OLD."closes_at", OLD."day_of_week", OLD."id", OLD."opens_at", _pgh_attach_context(), NOW(), \'shelter.operating_hour.remove\', OLD."id", OLD."shelter_id"); RETURN NULL;',
                    hash="4216ff035d170a5559849716aaae473dc0092c52",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_operating_hour_remove_delete_bac2d",
                    table="shelters_operatinghour",
                    when="AFTER",
                ),
            ),
        ),
    ]
