# Generated by Django 5.2.5 on 2025-10-24 01:14

import django.db.models.deletion
import django_choices_field.fields
import shelters.enums
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0021_add_shelter_hero_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bed",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[("available", "Available"), ("reserved", "Reserved")],
                        choices_enum=shelters.enums.BedStatusChoices,
                        max_length=9,
                        null=True,
                        unique=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("shelter_id", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="shelters.shelter")),
            ],
            options={
                "indexes": [models.Index(fields=["shelter_id", "status"], name="shelters_be_shelter_eaa435_idx")],
            },
        ),
    ]
