# Generated by Django 5.2.9 on 2026-01-12 06:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0023_migrate_display_name_to_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="city_council_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Unincorporated"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                ],
                db_index=True,
                null=True,
                verbose_name="LA City Council District",
            ),
        ),
        migrations.AlterField(
            model_name="shelterevent",
            name="city_council_district",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (0, "Unincorporated"),
                    (1, "1"),
                    (2, "2"),
                    (3, "3"),
                    (4, "4"),
                    (5, "5"),
                    (6, "6"),
                    (7, "7"),
                    (8, "8"),
                    (9, "9"),
                    (10, "10"),
                    (11, "11"),
                    (12, "12"),
                    (13, "13"),
                    (14, "14"),
                    (15, "15"),
                ],
                null=True,
                verbose_name="LA City Council District",
            ),
        ),
    ]
