# Generated by Django 6.0.1 on 2026-01-21 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0025_remove_shelter_shelter_add_insert_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="declined_ba_visit",
            field=models.BooleanField(default=False, verbose_name="Declined BA Visit"),
        ),
        migrations.AlterField(
            model_name="shelterevent",
            name="declined_ba_visit",
            field=models.BooleanField(default=False, verbose_name="Declined BA Visit"),
        ),
    ]
