# Generated by Django 6.0.2 on 2026-02-19 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0006_alter_organization_slug"),
        ("shelters", "0027_add_bed"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shelter",
            index=models.Index(fields=["status"], name="shelters_sh_status_54715e_idx"),
        ),
    ]
