# Generated by Django 6.0.3 on 2026-03-05 22:08

import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0029_add_room"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("operating", "Operating Hours"),
                            ("intake", "Intake Hours"),
                            ("meal_service", "Meal Service Hours"),
                            ("staff_availability", "Staff Availability"),
                        ],
                        default="operating",
                        max_length=18,
                    ),
                ),
                (
                    "day",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        help_text="Day of week. Leave blank for date-range entries that apply every day.",
                        max_length=9,
                        null=True,
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(blank=True, default=False)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start of date range (or the single date for one-day overrides).",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End of date range. Leave blank if same as start date.", null=True
                    ),
                ),
                (
                    "condition",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("heat", "Heat"),
                            ("fire", "Fire"),
                            ("rain_severe_weather", "Rain / Severe Weather"),
                            ("wind", "Wind"),
                            ("air_quality_smoke", "Air Quality / Smoke"),
                            ("public_health_emergency", "Public Health Emergency"),
                            ("emergency_evacuation", "Emergency Evacuation"),
                        ],
                        max_length=23,
                        null=True,
                    ),
                ),
                ("is_exception", models.BooleanField(blank=True, default=False)),
                (
                    "demographic",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="schedules",
                        to="shelters.demographic",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="schedules", to="shelters.shelter"
                    ),
                ),
            ],
            options={
                "ordering": ["schedule_type", "day", "open_time"],
            },
        ),
        migrations.CreateModel(
            name="ScheduleEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "schedule_type",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("operating", "Operating Hours"),
                            ("intake", "Intake Hours"),
                            ("meal_service", "Meal Service Hours"),
                            ("staff_availability", "Staff Availability"),
                        ],
                        default="operating",
                        max_length=18,
                    ),
                ),
                (
                    "day",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("monday", "Monday"),
                            ("tuesday", "Tuesday"),
                            ("wednesday", "Wednesday"),
                            ("thursday", "Thursday"),
                            ("friday", "Friday"),
                            ("saturday", "Saturday"),
                            ("sunday", "Sunday"),
                        ],
                        help_text="Day of week. Leave blank for date-range entries that apply every day.",
                        max_length=9,
                        null=True,
                    ),
                ),
                ("open_time", models.TimeField(blank=True, null=True)),
                ("close_time", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(blank=True, default=False)),
                (
                    "start_date",
                    models.DateField(
                        blank=True,
                        help_text="Start of date range (or the single date for one-day overrides).",
                        null=True,
                    ),
                ),
                (
                    "end_date",
                    models.DateField(
                        blank=True, help_text="End of date range. Leave blank if same as start date.", null=True
                    ),
                ),
                (
                    "condition",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("heat", "Heat"),
                            ("fire", "Fire"),
                            ("rain_severe_weather", "Rain / Severe Weather"),
                            ("wind", "Wind"),
                            ("air_quality_smoke", "Air Quality / Smoke"),
                            ("public_health_emergency", "Public Health Emergency"),
                            ("emergency_evacuation", "Emergency Evacuation"),
                        ],
                        max_length=23,
                        null=True,
                    ),
                ),
                ("is_exception", models.BooleanField(blank=True, default=False)),
                (
                    "demographic",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.demographic",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="shelters.schedule",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.shelter",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="schedule",
            constraint=models.UniqueConstraint(
                fields=("shelter", "schedule_type", "day", "open_time", "start_date"),
                name="unique_schedule_per_shelter_type_day_time_date",
                nulls_distinct=False,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="schedule",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_schedule_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_scheduleevent" ("close_time", "condition", "created_at", "day", "demographic_id", "end_date", "id", "is_closed", "is_exception", "open_time", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "schedule_type", "shelter_id", "start_date", "updated_at") VALUES (NEW."close_time", NEW."condition", NEW."created_at", NEW."day", NEW."demographic_id", NEW."end_date", NEW."id", NEW."is_closed", NEW."is_exception", NEW."open_time", _pgh_attach_context(), NOW(), \'shelter.schedule.add\', NEW."id", NEW."schedule_type", NEW."shelter_id", NEW."start_date", NEW."updated_at"); RETURN NULL;',
                    hash="75f075116872ab88e0958472bdfef73d2ebe8302",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_schedule_add_insert_5e92d",
                    table="shelters_schedule",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="schedule",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_schedule_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_scheduleevent" ("close_time", "condition", "created_at", "day", "demographic_id", "end_date", "id", "is_closed", "is_exception", "open_time", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "schedule_type", "shelter_id", "start_date", "updated_at") VALUES (NEW."close_time", NEW."condition", NEW."created_at", NEW."day", NEW."demographic_id", NEW."end_date", NEW."id", NEW."is_closed", NEW."is_exception", NEW."open_time", _pgh_attach_context(), NOW(), \'shelter.schedule.update\', NEW."id", NEW."schedule_type", NEW."shelter_id", NEW."start_date", NEW."updated_at"); RETURN NULL;',
                    hash="f7665aba91c1ab2611c6f1f6dedd88df97e53bb3",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_schedule_update_update_362b8",
                    table="shelters_schedule",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="schedule",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_schedule_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_scheduleevent" ("close_time", "condition", "created_at", "day", "demographic_id", "end_date", "id", "is_closed", "is_exception", "open_time", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "schedule_type", "shelter_id", "start_date", "updated_at") VALUES (OLD."close_time", OLD."condition", OLD."created_at", OLD."day", OLD."demographic_id", OLD."end_date", OLD."id", OLD."is_closed", OLD."is_exception", OLD."open_time", _pgh_attach_context(), NOW(), \'shelter.schedule.remove\', OLD."id", OLD."schedule_type", OLD."shelter_id", OLD."start_date", OLD."updated_at"); RETURN NULL;',
                    hash="5ba3f37664fb37915059925ca804d3ea003b0212",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_schedule_remove_delete_d5ab4",
                    table="shelters_schedule",
                    when="AFTER",
                ),
            ),
        ),
    ]
