# Generated by Django 6.0.2 on 2026-03-01 03:15

import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_remove_clientprofile_client_profile_add_insert_and_more"),
        ("shelters", "0029_add_room"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reservation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "status",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("open", "Open"),
                            ("confirmed", "Confirmed"),
                            ("checked_in", "Checked In"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                            ("no_show", "No Show"),
                        ],
                        default="open",
                        max_length=10,
                    ),
                ),
                ("start_date", models.DateField()),
                ("duration", models.DurationField()),
                ("notes", models.TextField(blank=True, null=True)),
                ("checked_in_at", models.DateTimeField(blank=True, null=True)),
                ("checked_out_at", models.DateTimeField(blank=True, null=True)),
                (
                    "bed",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="shelters.bed",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reservations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reservations",
                        to="shelters.room",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="reservations", to="shelters.shelter"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ReservationClient",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("is_primary", models.BooleanField(default=False)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_clients",
                        to="clients.clientprofile",
                    ),
                ),
                (
                    "reservation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reservation_clients",
                        to="shelters.reservation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="reservation",
            name="clients",
            field=models.ManyToManyField(
                related_name="reservations", through="shelters.ReservationClient", to="clients.clientprofile"
            ),
        ),
        migrations.AddConstraint(
            model_name="reservationclient",
            constraint=models.UniqueConstraint(
                fields=("reservation", "client_profile"), name="unique_client_per_reservation"
            ),
        ),
        migrations.AddIndex(
            model_name="reservation",
            index=models.Index(fields=["shelter", "status"], name="shelters_re_shelter_a0226b_idx"),
        ),
    ]
