# Generated by Django 6.0.2 on 2026-03-02 23:16

import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0030_reservation_reservationclient_reservation_clients_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="reservation",
            name="status",
            field=django_choices_field.fields.TextChoicesField(
                choices=[
                    ("open", "Open"),
                    ("confirmed", "Confirmed"),
                    ("checked_in", "Checked In"),
                    ("completed", "Completed"),
                    ("cancelled", "Cancelled"),
                    ("check_in_overdue", "Check-in Overdue"),
                ],
                default="confirmed",
                max_length=16,
            ),
        ),
    ]
