# Generated by Django 6.0.2 on 2026-03-03 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_remove_clientprofile_client_profile_add_insert_and_more"),
        ("shelters", "0031_alter_reservation_status"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="reservationclient",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_primary", True)),
                fields=("reservation",),
                name="unique_primary_client_per_reservation",
            ),
        ),
    ]
