# Generated by Django 6.0.3 on 2026-03-13 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0033_remove_contactinfo_shelter_contact_info_add_insert_and_more"),
        ("shelters", "0034_alter_pet_name"),
    ]

    operations = []
