# Generated by Django 6.0.3 on 2026-03-27 01:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0031_remove_clientprofile_client_profile_add_insert_and_more"),
        ("shelters", "0041_update_service_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="bed",
            name="room",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="beds",
                to="shelters.room",
            ),
        ),
        migrations.AddField(
            model_name="room",
            name="accessibility",
            field=models.ManyToManyField(blank=True, to="shelters.accessibility"),
        ),
        migrations.AddField(
            model_name="room",
            name="demographics",
            field=models.ManyToManyField(blank=True, to="shelters.demographic"),
        ),
        migrations.AddField(
            model_name="room",
            name="funders",
            field=models.ManyToManyField(blank=True, to="shelters.funder"),
        ),
        migrations.AddField(
            model_name="room",
            name="maintenance_flag",
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AddField(
            model_name="room",
            name="occupants",
            field=models.ManyToManyField(blank=True, related_name="occupied_rooms", to="clients.clientprofile"),
        ),
        migrations.AddField(
            model_name="room",
            name="pets",
            field=models.ManyToManyField(blank=True, to="shelters.pet"),
        ),
        migrations.AddField(
            model_name="room",
            name="storage",
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
