# Generated by Django 6.0.3 on 2026-04-15 19:00

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0042_bed_room_room_accessibility_room_demographics_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="contactinfo",
            name="shelter_contact_info_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="contactinfo",
            name="shelter_contact_info_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="contactinfo",
            name="shelter_contact_info_remove_delete",
        ),
        migrations.AddField(
            model_name="contactinfo",
            name="is_claimant",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="contactinfoevent",
            name="is_claimant",
            field=models.BooleanField(default=False),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contactinfo",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_contact_info_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_contactinfoevent" ("contact_email", "contact_name", "contact_number", "contact_title", "id", "is_claimant", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (NEW."contact_email", NEW."contact_name", NEW."contact_number", NEW."contact_title", NEW."id", NEW."is_claimant", _pgh_attach_context(), NOW(), \'shelter.contact_info.add\', NEW."id", NEW."shelter_id"); RETURN NULL;',
                    hash="c79f72ce5046a455afa90d1fd2a57b09eae94af0",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_contact_info_add_insert_6a367",
                    table="shelters_contactinfo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contactinfo",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_contact_info_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_contactinfoevent" ("contact_email", "contact_name", "contact_number", "contact_title", "id", "is_claimant", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (NEW."contact_email", NEW."contact_name", NEW."contact_number", NEW."contact_title", NEW."id", NEW."is_claimant", _pgh_attach_context(), NOW(), \'shelter.contact_info.update\', NEW."id", NEW."shelter_id"); RETURN NULL;',
                    hash="16c4e96702d41ef30cf1447eee0c96f56eb5c254",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_contact_info_update_update_c3902",
                    table="shelters_contactinfo",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="contactinfo",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_contact_info_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_contactinfoevent" ("contact_email", "contact_name", "contact_number", "contact_title", "id", "is_claimant", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id") VALUES (OLD."contact_email", OLD."contact_name", OLD."contact_number", OLD."contact_title", OLD."id", OLD."is_claimant", _pgh_attach_context(), NOW(), \'shelter.contact_info.remove\', OLD."id", OLD."shelter_id"); RETURN NULL;',
                    hash="68eba5371c6600a5fe268617a13019138b33301d",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_contact_info_remove_delete_8eb42",
                    table="shelters_contactinfo",
                    when="AFTER",
                ),
            ),
        ),
    ]
