# Generated by Django 6.0.3 on 2026-04-15 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0042_add_youtube_link"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="YouTubeLink",
            new_name="MediaLink",
        ),
        migrations.AddField(
            model_name="medialink",
            name="media_type",
            field=models.CharField(choices=[("youtube", "YouTube")], default="youtube", max_length=50),
        ),
        migrations.AlterField(
            model_name="medialink",
            name="shelter",
            field=models.ForeignKey(
                on_delete=models.CASCADE,
                related_name="media_links",
                to="shelters.shelter",
            ),
        ),
    ]
