# Generated by Django 6.0.4 on 2026-04-29 05:37

import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0043_contactinfo_is_claimant"),
    ]

    operations = [
        migrations.CreateModel(
            name="Vaccination",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "name",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("tb", "TB"), ("flu", "Flu"), ("covid_19", "COVID-19")], max_length=8, unique=True
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TrackedVaccinationEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_constraint=False,
                        db_tablespace="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.shelter",
                    ),
                ),
                (
                    "vaccination",
                    models.ForeignKey(
                        db_constraint=False,
                        db_tablespace="",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.vaccination",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="shelter",
            name="vaccination_requirement",
            field=models.ManyToManyField(to="shelters.vaccination"),
        ),
        migrations.CreateModel(
            name="TrackedVaccination",
            fields=[],
            options={
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelter_vaccination_requirement",),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedvaccination",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_vaccination_requirement_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedvaccinationevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "vaccination_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'shelter.vaccination_requirement.add\', NEW."shelter_id", NEW."vaccination_id"); RETURN NULL;',
                    hash="658e13e61f9249bb8c1274a084281d4f0a2e0e8f",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_vaccination_requirement_add_insert_a56c8",
                    table="shelters_shelter_vaccination_requirement",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="trackedvaccination",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_vaccination_requirement_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_trackedvaccinationevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "shelter_id", "vaccination_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'shelter.vaccination_requirement.remove\', OLD."shelter_id", OLD."vaccination_id"); RETURN NULL;',
                    hash="48bc5c7e821db7f46578ffa64b7dd7aa3dee248f",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_vaccination_requirement_remove_delete_e19ee",
                    table="shelters_shelter_vaccination_requirement",
                    when="AFTER",
                ),
            ),
        ),
    ]
