# Generated by Django 6.0.3 on 2026-04-16 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0043_contactinfo_is_claimant"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaLink",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("url", models.URLField(max_length=255)),
                ("title", models.CharField(blank=True, max_length=255)),
                ("media_type", models.CharField(choices=[("youtube", "YouTube")], default="youtube", max_length=50)),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="media_links", to="shelters.shelter"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
