# Generated by Django 6.0.4 on 2026-05-05 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0044_vaccination_requirement"),
        ("shelters", "0046_add_view_private_shelter_to_caseworker"),
    ]

    operations = []
