# Generated by Django 6.0.4 on 2026-05-04 18:00

import admin_async_upload.models
import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
import shelters.models.media
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0046_add_view_private_shelter_to_caseworker"),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterPhoto",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", admin_async_upload.models.AsyncFileField(upload_to=shelters.models.media.upload_path)),
                (
                    "type",
                    django_choices_field.fields.TextChoicesField(
                        choices=[("interior", "Interior"), ("exterior", "Exterior")], max_length=8
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="shelter",
            name="shelter_remove_delete",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="hero_image_content_type",
        ),
        migrations.RemoveField(
            model_name="shelter",
            name="hero_image_object_id",
        ),
        migrations.RemoveField(
            model_name="shelterevent",
            name="hero_image_content_type",
        ),
        migrations.RemoveField(
            model_name="shelterevent",
            name="hero_image_object_id",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "declined_ba_visit", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_id", "id", "instagram", "is_private", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."declined_ba_visit", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."exit_policy_other", NEW."funders_other", NEW."geolocation", NEW."hero_image_id", NEW."id", NEW."instagram", NEW."is_private", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.add\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="30ba75cc699fa72300fb211d1a7028cbe96dbf7d",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_add_insert_6bdb6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "declined_ba_visit", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_id", "id", "instagram", "is_private", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (NEW."add_notes_shelter_details", NEW."add_notes_sleeping_details", NEW."bed_fees", NEW."city_council_district", NEW."created_at", NEW."curfew", NEW."declined_ba_visit", NEW."demographics_other", NEW."description", NEW."email", NEW."emergency_surge", NEW."entry_info", NEW."exit_policy_other", NEW."funders_other", NEW."geolocation", NEW."hero_image_id", NEW."id", NEW."instagram", NEW."is_private", NEW."location", NEW."max_stay", NEW."name", NEW."on_site_security", NEW."organization_id", NEW."other_rules", NEW."other_services", NEW."overall_rating", _pgh_attach_context(), NOW(), \'shelter.update\', NEW."id", NEW."phone", NEW."program_fees", NEW."room_styles_other", NEW."shelter_programs_other", NEW."shelter_types_other", NEW."status", NEW."subjective_review", NEW."supervisorial_district", NEW."total_beds", NEW."updated_at", NEW."visitors_allowed", NEW."website"); RETURN NULL;',
                    hash="14881ec7425344d4053749c9de2a0ecb17d0decc",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_update_update_086d2",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelter",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelterevent" ("add_notes_shelter_details", "add_notes_sleeping_details", "bed_fees", "city_council_district", "created_at", "curfew", "declined_ba_visit", "demographics_other", "description", "email", "emergency_surge", "entry_info", "exit_policy_other", "funders_other", "geolocation", "hero_image_id", "id", "instagram", "is_private", "location", "max_stay", "name", "on_site_security", "organization_id", "other_rules", "other_services", "overall_rating", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone", "program_fees", "room_styles_other", "shelter_programs_other", "shelter_types_other", "status", "subjective_review", "supervisorial_district", "total_beds", "updated_at", "visitors_allowed", "website") VALUES (OLD."add_notes_shelter_details", OLD."add_notes_sleeping_details", OLD."bed_fees", OLD."city_council_district", OLD."created_at", OLD."curfew", OLD."declined_ba_visit", OLD."demographics_other", OLD."description", OLD."email", OLD."emergency_surge", OLD."entry_info", OLD."exit_policy_other", OLD."funders_other", OLD."geolocation", OLD."hero_image_id", OLD."id", OLD."instagram", OLD."is_private", OLD."location", OLD."max_stay", OLD."name", OLD."on_site_security", OLD."organization_id", OLD."other_rules", OLD."other_services", OLD."overall_rating", _pgh_attach_context(), NOW(), \'shelter.remove\', OLD."id", OLD."phone", OLD."program_fees", OLD."room_styles_other", OLD."shelter_programs_other", OLD."shelter_types_other", OLD."status", OLD."subjective_review", OLD."supervisorial_district", OLD."total_beds", OLD."updated_at", OLD."visitors_allowed", OLD."website"); RETURN NULL;',
                    hash="151ba8712240825f46b73c19d8e8206b3ddd0e9b",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_remove_delete_928d6",
                    table="shelters_shelter",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="shelterphoto",
            name="shelter",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="photos", to="shelters.shelter"
            ),
        ),
        migrations.CreateModel(
            name="ExteriorShelterPhoto",
            fields=[],
            options={
                "verbose_name": "Exterior Photo",
                "verbose_name_plural": "Exterior Photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelterphoto",),
        ),
        migrations.CreateModel(
            name="InteriorShelterPhoto",
            fields=[],
            options={
                "verbose_name": "Interior Photo",
                "verbose_name_plural": "Interior Photos",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("shelters.shelterphoto",),
        ),
        migrations.AddField(
            model_name="shelter",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to="shelters.shelterphoto",
            ),
        ),
        migrations.AddField(
            model_name="shelterevent",
            name="hero_image",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="shelters.shelterphoto",
            ),
        ),
    ]
