# Generated by Django 6.0.4 on 2026-05-04 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0047_shelterphoto"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="interiorphoto",
            name="shelter",
        ),
        migrations.DeleteModel(
            name="ExteriorPhoto",
        ),
        migrations.DeleteModel(
            name="InteriorPhoto",
        ),
    ]
