# Generated by Django 6.0.4 on 2026-05-04 18:00

from django.db import migrations


def migrate_interior_exterior_photos_to_shelter_photo(apps, schema_editor):
    """Copy legacy ``InteriorPhoto`` / ``ExteriorPhoto`` rows into ``ShelterPhoto``.

    Runs after ``0047_shelterphoto``, which introduced ``ShelterPhoto`` and the
    ``Shelter.hero_image`` FK. Legacy photo tables are unchanged here; a later
    migration may drop them.

    Note: ``0047`` removes the generic hero fields before this runs, so explicit
    hero picks from the old GFK cannot be remapped automatically.
    """
    ExteriorPhoto = apps.get_model("shelters", "ExteriorPhoto")
    InteriorPhoto = apps.get_model("shelters", "InteriorPhoto")
    ShelterPhoto = apps.get_model("shelters", "ShelterPhoto")

    for ep in ExteriorPhoto.objects.all().iterator():
        row = ShelterPhoto.objects.create(
            shelter_id=ep.shelter_id,
            file=ep.file,
            type="exterior",
        )
        ShelterPhoto.objects.filter(pk=row.pk).update(created_at=ep.created_at, updated_at=ep.updated_at)

    for ip in InteriorPhoto.objects.all().iterator():
        row = ShelterPhoto.objects.create(
            shelter_id=ip.shelter_id,
            file=ip.file,
            type="interior",
        )
        ShelterPhoto.objects.filter(pk=row.pk).update(created_at=ip.created_at, updated_at=ip.updated_at)


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0047_shelterphoto"),
    ]

    operations = [
        migrations.RunPython(migrate_interior_exterior_photos_to_shelter_photo, migrations.RunPython.noop),
    ]
