# Generated by Django 6.0.4 on 2026-05-06 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0048_shelterphoto"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="shelterphoto",
            index=models.Index(fields=["shelter", "type"], name="shelters_sh_shelter_ebba69_idx"),
        ),
    ]
