# Generated by Django 6.0.4 on 2026-05-11 19:56

from django.db import migrations
from shelters.utils import remove_permissions_from_group_in_migration


def remove_deprecated_shelter_group_permissions(apps, schema_editor):
    ExteriorPhoto = apps.get_model("shelters", "ExteriorPhoto")
    InteriorPhoto = apps.get_model("shelters", "InteriorPhoto")

    permission_map = {
        ExteriorPhoto: [
            [
                "shelters.add_exteriorphoto",
                "shelters.change_exteriorphoto",
                "shelters.delete_exteriorphoto",
                "shelters.view_exteriorphoto",
            ]
        ],
        InteriorPhoto: [
            [
                "shelters.add_interiorphoto",
                "shelters.change_interiorphoto",
                "shelters.delete_interiorphoto",
                "shelters.view_interiorphoto",
            ]
        ],
    }

    remove_permissions_from_group_in_migration(apps, "Shelter Data Entry", permission_map)
    remove_permissions_from_group_in_migration(apps, "Shelter Administration", permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0049_shelterphoto_shelter_type_idx"),
    ]

    operations = [
        migrations.RunPython(remove_deprecated_shelter_group_permissions, migrations.RunPython.noop),
        migrations.RemoveField(
            model_name="interiorphoto",
            name="shelter",
        ),
        migrations.DeleteModel(
            name="ExteriorPhoto",
        ),
        migrations.DeleteModel(
            name="InteriorPhoto",
        ),
    ]
