# Generated by Django 6.0.4 on 2026-05-12 22:07

from django.db import migrations
from shelters.utils import assign_permissions_to_group_in_migration


def modify_shelter_group_permissions(apps, schema_editor):
    from shelters.permissions import InteriorShelterPhotoPermissions, ExteriorShelterPhotoPermissions

    InteriorShelterPhoto = apps.get_model("shelters", "InteriorShelterPhoto")
    ExteriorShelterPhoto = apps.get_model("shelters", "ExteriorShelterPhoto")

    permission_map = {
        InteriorShelterPhoto: [InteriorShelterPhotoPermissions],
        ExteriorShelterPhoto: [ExteriorShelterPhotoPermissions],
    }

    assign_permissions_to_group_in_migration(apps, "Shelter Data Entry", permission_map)
    assign_permissions_to_group_in_migration(apps, "Shelter Administration", permission_map)


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0050_remove_old_shelter_models"),
    ]

    operations = [
        migrations.RunPython(modify_shelter_group_permissions, migrations.RunPython.noop),
    ]
