# Generated by Django 6.0.4 on 2026-04-30 17:57

from django.db import migrations


def copy_cities_and_spa_to_served(apps, schema_editor):
    """Copy existing M2M relations from cities -> cities_served and spa -> spas_served."""
    Shelter = apps.get_model("shelters", "Shelter")

    ShelterCities = Shelter.cities.through
    ShelterCitiesServed = Shelter.cities_served.through
    ShelterSpa = Shelter.spa.through
    ShelterSpasServed = Shelter.spas_served.through

    cities_links = list(ShelterCities.objects.values("shelter_id", "city_id"))
    if cities_links:
        ShelterCitiesServed.objects.bulk_create(
            [ShelterCitiesServed(shelter_id=row["shelter_id"], city_id=row["city_id"]) for row in cities_links],
            ignore_conflicts=True,
        )

    spa_links = list(ShelterSpa.objects.values("shelter_id", "spa_id"))
    if spa_links:
        ShelterSpasServed.objects.bulk_create(
            [ShelterSpasServed(shelter_id=row["shelter_id"], spa_id=row["spa_id"]) for row in spa_links],
            ignore_conflicts=True,
        )


def reverse_copy(apps, schema_editor):
    """Reverse: copy cities_served -> cities and spas_served -> spa."""
    Shelter = apps.get_model("shelters", "Shelter")

    ShelterCities = Shelter.cities.through
    ShelterCitiesServed = Shelter.cities_served.through
    ShelterSpa = Shelter.spa.through
    ShelterSpasServed = Shelter.spas_served.through

    served_cities = list(ShelterCitiesServed.objects.values("shelter_id", "city_id"))
    if served_cities:
        ShelterCities.objects.bulk_create(
            [ShelterCities(shelter_id=row["shelter_id"], city_id=row["city_id"]) for row in served_cities],
            ignore_conflicts=True,
        )

    served_spas = list(ShelterSpasServed.objects.values("shelter_id", "spa_id"))
    if served_spas:
        ShelterSpa.objects.bulk_create(
            [ShelterSpa(shelter_id=row["shelter_id"], spa_id=row["spa_id"]) for row in served_spas],
            ignore_conflicts=True,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0051_add_cities_served_and_spas_served"),
    ]

    operations = [
        migrations.RunPython(copy_cities_and_spa_to_served, reverse_copy),
    ]
