# Generated by Django 6.0.4 on 2026-05-14 07:12

import django.core.validators
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pghistory", "0007_auto_20250421_0444"),
        ("shelters", "0055_populate_city_and_spa_fks"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ShelterAvailability",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "non_restrictive_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of non-restrictive beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restrictive_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of restrictive beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restriction_notes",
                    models.TextField(
                        blank=True, default="", help_text="Global restriction note for this availability record."
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="availabilities",
                        to="shelters.shelter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="shelter_availability_updates",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Shelter Availability",
                "verbose_name_plural": "Shelter Availabilities",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="ShelterAvailabilityEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "non_restrictive_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of non-restrictive beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restrictive_beds",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="Number of restrictive beds available.",
                        validators=[django.core.validators.MinValueValidator(0)],
                    ),
                ),
                (
                    "restriction_notes",
                    models.TextField(
                        blank=True, default="", help_text="Global restriction note for this availability record."
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="shelters.shelteravailability",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="shelters.shelter",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restrictive_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restriction_notes", "restrictive_beds", "shelter_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."id", NEW."non_restrictive_beds", _pgh_attach_context(), NOW(), \'shelter.availability.add\', NEW."id", NEW."restriction_notes", NEW."restrictive_beds", NEW."shelter_id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;',
                    hash="ef031307a4e830aad9981a214cfa9ddbf958495c",
                    operation="INSERT",
                    pgid="pgtrigger_shelter_availability_add_insert_81322",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restrictive_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restriction_notes", "restrictive_beds", "shelter_id", "updated_at", "updated_by_id") VALUES (NEW."created_at", NEW."id", NEW."non_restrictive_beds", _pgh_attach_context(), NOW(), \'shelter.availability.update\', NEW."id", NEW."restriction_notes", NEW."restrictive_beds", NEW."shelter_id", NEW."updated_at", NEW."updated_by_id"); RETURN NULL;',
                    hash="1f51b674a45fcaff9e2b47bc260377f71bba1035",
                    operation="UPDATE",
                    pgid="pgtrigger_shelter_availability_update_update_9991b",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="shelteravailability",
            trigger=pgtrigger.compiler.Trigger(
                name="shelter_availability_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "shelters_shelteravailabilityevent" ("created_at", "id", "non_restrictive_beds", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "restriction_notes", "restrictive_beds", "shelter_id", "updated_at", "updated_by_id") VALUES (OLD."created_at", OLD."id", OLD."non_restrictive_beds", _pgh_attach_context(), NOW(), \'shelter.availability.remove\', OLD."id", OLD."restriction_notes", OLD."restrictive_beds", OLD."shelter_id", OLD."updated_at", OLD."updated_by_id"); RETURN NULL;',
                    hash="467f191b5b098ef5db7de8a5cf15d014ae5cdbb7",
                    operation="DELETE",
                    pgid="pgtrigger_shelter_availability_remove_delete_d7472",
                    table="shelters_shelteravailability",
                    when="AFTER",
                ),
            ),
        ),
    ]
