# Generated by Django 6.0.4 on 2026-05-14 17:13

import django.utils.timezone
from django.db import migrations, models


def populate_spa_name_fields(apps, schema_editor):
    from shelters.deprecated.deprecated_enums import SPAChoices

    SPA = apps.get_model("shelters", "SPA")
    rows = []
    for spa in SPA.objects.all().iterator():
        name = spa.name
        if name is not None:
            try:
                spa.short_name = str(name)
                spa.long_name = str(SPAChoices(name).label)
            except ValueError:
                spa.short_name = (f"p{spa.pk}")[:10]
                spa.long_name = f"Unknown SPA (id={spa.pk})"
        else:
            # Unexpected name or null name: keep rows distinct for unique constraints.
            spa.short_name = (f"p{spa.pk}")[:10]
            spa.long_name = f"Unknown SPA (id={spa.pk})"
        rows.append(spa)
    if rows:
        SPA.objects.bulk_update(rows, ["short_name", "long_name"])


class Migration(migrations.Migration):

    dependencies = [
        ("shelters", "0055_populate_city_and_spa_fks"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="spa",
            options={"ordering": ["short_name"]},
        ),
        migrations.AddField(
            model_name="spa",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="spa",
            name="long_name",
            field=models.CharField(db_index=True, max_length=255, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="spa",
            name="short_name",
            field=models.CharField(db_index=True, max_length=10, null=True, unique=True),
        ),
        migrations.AddField(
            model_name="spa",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.RunPython(populate_spa_name_fields, migrations.RunPython.noop),
    ]
