from _typeshed import Incomplete
from collections.abc import Generator

def get_header(message, name): ...
def get_header_items(message) -> Generator[Incomplete, None, None]: ...
def get_headers(message) -> Generator[Incomplete, None, None]: ...
def get_httpmessage(headers): ...
