name: 'EAS Update'
description: 'Perform EAS Update for the project'

inputs:
  project:
    required: true
    type: string
  branch:
    required: true
    type: string
  slug:
    required: true
    type: string
  project-id:
    required: true
    type: string

outputs:
  android-update-id:
    description: 'Android update ID.'
    value: ${{ steps.perform-eas-update.outputs.android-update-id }}
  android-update-permalink:
    description: 'Permalink for Android update.'
    value: ${{ steps.perform-eas-update.outputs.android-update-permalink }}
  android-update-qr-url:
    description: 'QR URL for Android update.'
    value: ${{ steps.perform-eas-update.outputs.android-update-qr-url }}
  android-branch:
    description: 'Branch for Android update.'
    value: ${{ steps.perform-eas-update.outputs.android-branch }}
  android-update-commit:
    description: 'Commit hash for Android update.'
    value: ${{ steps.perform-eas-update.outputs.android-update-commit }}
  android-runtime-version:
    description: 'Runtime version for Android update.'
    value: ${{ steps.perform-eas-update.outputs.android-runtime-version }}
  ios-update-id:
    description: 'iOS update ID.'
    value: ${{ steps.perform-eas-update.outputs.ios-update-id }}
  ios-update-permalink:
    description: 'Permalink for iOS update.'
    value: ${{ steps.perform-eas-update.outputs.ios-update-permalink }}
  ios-update-qr-url:
    description: 'QR URL for iOS update.'
    value: ${{ steps.perform-eas-update.outputs.ios-update-qr-url }}
  ios-branch:
    description: 'Branch for iOS update.'
    value: ${{ steps.perform-eas-update.outputs.ios-branch }}
  ios-update-commit:
    description: 'Commit hash for iOS update.'
    value: ${{ steps.perform-eas-update.outputs.ios-update-commit }}
  ios-runtime-version:
    description: 'Runtime version for iOS update.'
    value: ${{ steps.perform-eas-update.outputs.ios-runtime-version }}
  group-id:
    description: 'EAS Update Group ID'
    value: ${{ steps.perform-eas-update.outputs.group-id }}

runs:
  using: 'composite'
  steps:
    - name: Perform EAS Update
      id: perform-eas-update
      shell: bash
      run: |
        platforms=("android" "ios")

        # Helper: emit only the first complete JSON value (object/array), then stop.
        extract_first_json() {
          awk 'BEGIN{p=0;d=0} /^[[:space:]]*[\[{]/{p=1} p{print; d+=gsub(/\[/,"[")+gsub(/\{/,"{"); d-=gsub(/\]/,"]")+gsub(/\}/,"}"); if(p&&d==0) exit}'
        }

        # Capture the raw output from the EAS update command.
        eas_update_raw=$(yarn nx run ${{ inputs.project }}:eas-update --branch "${{ inputs.branch }}" --auto --json --interactive false 2>&1) || {
          echo "Error running the EAS update command:"
          echo "$eas_update_raw"
          exit 1
        }

        # Extract only the first complete JSON block (handles pre/post noise)
        eas_update_output=$(echo "$eas_update_raw" | extract_first_json)

        # Validate JSON before proceeding
        if ! echo "$eas_update_output" | jq empty >/dev/null 2>&1; then
          echo "Error: Invalid JSON from EAS Update command"
          echo "Raw output was:"; echo "$eas_update_raw" | cat -v
          echo "Cleaned output was:"; echo "$eas_update_output"
          exit 1
        fi

        for platform in "${platforms[@]}"; do
          update_info=$(echo "$eas_update_output" | jq -r ".[] | select(.platform == \"$platform\")")
          branch=$(echo "$update_info" | jq -r '.branch')
          update_id=$(echo "$update_info" | jq -r '.id')
          group_id=$(echo "$update_info" | jq -r '.group')
          update_commit=$(echo "$update_info" | jq -r '.gitCommitHash')
          runtime_version=$(echo "$update_info" | jq -r '.runtimeVersion')
          update_permalink="https://expo.dev/projects/${{ inputs.project-id }}/updates/${update_id}"
          update_qr_url="https://qr.expo.dev/eas-update?appScheme=${{ inputs.slug }}&projectId=${{ inputs.project-id }}&groupId=${group_id}"

          # Set platform-specific outputs
          echo "${platform}-branch=$branch" >> $GITHUB_OUTPUT
          echo "${platform}-update-id=$update_id" >> $GITHUB_OUTPUT
          echo "${platform}-update-permalink=$update_permalink" >> $GITHUB_OUTPUT
          echo "${platform}-update-qr-url=$update_qr_url" >> $GITHUB_OUTPUT
          echo "${platform}-update-commit=$update_commit" >> $GITHUB_OUTPUT
          echo "${platform}-runtime-version=$runtime_version" >> $GITHUB_OUTPUT
          echo "group-id=$group_id" >> $GITHUB_OUTPUT
        done

    - name: Set Project and Group ID
      shell: bash
      working-directory: apps/${{ inputs.project }}
      run: |
        project_id="${{ inputs.project-id }}"
        group_id="${{ steps.perform-eas-update.outputs.group-id }}"
        echo "PROJECT_ID=$project_id" >> .env
        echo "GROUP_ID=$group_id" >> .env

