// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { TaskQuery } from './Task.generated';

export const taskOperationKey: keyof Omit<TaskQuery, '__typename'> = 'task';
export const taskSuccessTypename: Extract<
  NonNullable<TaskQuery['task']>,
  { __typename: 'TaskType' }
>['__typename'] = 'TaskType';

export const taskMeta = {
  operationKey: taskOperationKey,
  successTypename: taskSuccessTypename,
} as const;
