// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { PublicSheltersQuery } from './shelters.generated';
import type { ShelterServiceCategoriesQuery } from './shelters.generated';
import type { CreateShelterMutation } from './shelters.generated';

export const publicSheltersOperationKey: keyof Omit<PublicSheltersQuery, '__typename'> = 'shelters';
export const publicSheltersSuccessTypename: Extract<
  NonNullable<PublicSheltersQuery['shelters']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<PublicSheltersQuery['shelters']>,
  { __typename: 'ShelterTypeOffsetPaginated' }
>['__typename'] = 'ShelterTypeOffsetPaginated';

export const publicSheltersMeta = {
  operationKey: publicSheltersOperationKey,
  successTypename: publicSheltersSuccessTypename,
} as const;

export const shelterServiceCategoriesOperationKey: keyof Omit<ShelterServiceCategoriesQuery, '__typename'> = 'shelterServiceCategories';
export const shelterServiceCategoriesSuccessTypename: Extract<
  NonNullable<ShelterServiceCategoriesQuery['shelterServiceCategories']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<ShelterServiceCategoriesQuery['shelterServiceCategories']>,
  { __typename: 'ServiceCategoryTypeOffsetPaginated' }
>['__typename'] = 'ServiceCategoryTypeOffsetPaginated';

export const shelterServiceCategoriesMeta = {
  operationKey: shelterServiceCategoriesOperationKey,
  successTypename: shelterServiceCategoriesSuccessTypename,
} as const;

export const createShelterOperationKey: keyof Omit<CreateShelterMutation, '__typename'> = 'createShelter';
export const createShelterSuccessTypename: Extract<
  NonNullable<CreateShelterMutation['createShelter']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<CreateShelterMutation['createShelter']>,
  { __typename: 'ShelterType' }
>['__typename'] = 'ShelterType';

export const createShelterMeta = {
  operationKey: createShelterOperationKey,
  successTypename: createShelterSuccessTypename,
} as const;
