// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { CreateServiceRequestHmisMutation } from './ServiceRequestHmis.generated';
import type { RemoveServiceRequestHmisMutation } from './ServiceRequestHmis.generated';

export const createServiceRequestHmisOperationKey: keyof Omit<CreateServiceRequestHmisMutation, '__typename'> = 'createHmisNoteServiceRequest';
export const createServiceRequestHmisSuccessTypename: Extract<
  NonNullable<CreateServiceRequestHmisMutation['createHmisNoteServiceRequest']>,
  { __typename: 'ServiceRequestType' }
>['__typename'] = 'ServiceRequestType';

export const createServiceRequestHmisMeta = {
  operationKey: createServiceRequestHmisOperationKey,
  successTypename: createServiceRequestHmisSuccessTypename,
} as const;

export const removeServiceRequestHmisOperationKey: keyof Omit<RemoveServiceRequestHmisMutation, '__typename'> = 'removeHmisNoteServiceRequest';
export const removeServiceRequestHmisSuccessTypename: Extract<
  NonNullable<RemoveServiceRequestHmisMutation['removeHmisNoteServiceRequest']>,
  { __typename: 'HmisNoteType' }
>['__typename'] = 'HmisNoteType';

export const removeServiceRequestHmisMeta = {
  operationKey: removeServiceRequestHmisOperationKey,
  successTypename: removeServiceRequestHmisSuccessTypename,
} as const;
