from . import app_settings as app_settings
from ..account.app_settings import EmailVerificationMethod as EmailVerificationMethod
from ..account.models import EmailAddress as EmailAddress
from ..account.utils import user_email as user_email, user_field as user_field, user_username as user_username
from ..utils import deserialize_instance as deserialize_instance, email_address_exists as email_address_exists, import_attribute as import_attribute, serialize_instance as serialize_instance, valid_email_or_none as valid_email_or_none
from _typeshed import Incomplete

class DefaultSocialAccountAdapter:
    error_messages: Incomplete
    request: Incomplete
    def __init__(self, request: Incomplete | None = ...) -> None: ...
    def pre_social_login(self, request, sociallogin) -> None: ...
    def authentication_error(self, request, provider_id, error: Incomplete | None = ..., exception: Incomplete | None = ..., extra_context: Incomplete | None = ...) -> None: ...
    def new_user(self, request, sociallogin): ...
    def save_user(self, request, sociallogin, form: Incomplete | None = ...): ...
    def populate_user(self, request, sociallogin, data): ...
    def get_connect_redirect_url(self, request, socialaccount): ...
    def validate_disconnect(self, account, accounts) -> None: ...
    def is_auto_signup_allowed(self, request, sociallogin): ...
    def is_open_for_signup(self, request, sociallogin): ...
    def get_signup_form_initial_data(self, sociallogin): ...
    def deserialize_instance(self, model, data): ...
    def serialize_instance(self, instance): ...
    def get_app(self, request, provider, config: Incomplete | None = ...): ...

def get_adapter(request: Incomplete | None = ...): ...
