from django.db import models

class JSONField(models.TextField):
    def from_db_value(self, value, *args, **kwargs): ...
    def to_python(self, value): ...
    def validate(self, value, model_instance) -> None: ...
    def get_prep_value(self, value): ...
    def value_from_object(self, obj): ...
