from . import app_settings as app_settings, signals as signals
from .adapter import get_adapter as get_adapter
from .models import SocialLogin as SocialLogin
from .providers.base import AuthError as AuthError, AuthProcess as AuthProcess
from _typeshed import Incomplete
from allauth.account.utils import complete_signup as complete_signup, perform_login as perform_login, user_display as user_display, user_username as user_username
from allauth.exceptions import ImmediateHttpResponse as ImmediateHttpResponse

def render_authentication_error(request, provider_id, error=..., exception: Incomplete | None = ..., extra_context: Incomplete | None = ...): ...
def complete_social_login(request, sociallogin): ...
def complete_social_signup(request, sociallogin): ...
def import_path(path): ...
def socialaccount_user_display(socialaccount): ...
