// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { ReportSummaryQuery } from './reports.generated';

export const reportSummaryOperationKey: keyof Omit<ReportSummaryQuery, '__typename'> = 'reportSummary';
export const reportSummarySuccessTypename: Extract<
  NonNullable<ReportSummaryQuery['reportSummary']>,
  { __typename: 'ReportSummaryType' }
>['__typename'] = 'ReportSummaryType';

export const reportSummaryMeta = {
  operationKey: reportSummaryOperationKey,
  successTypename: reportSummarySuccessTypename,
} as const;
