# Generated by Django 5.2.7 on 2025-11-06 04:50

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hmis", "0001_initial"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_remove_delete",
        ),
        migrations.AddField(
            model_name="hmisclientprofile",
            name="hmis_id",
            field=models.CharField(db_index=True, default="0", max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="hmisclientprofileevent",
            name="hmis_id",
            field=models.CharField(default="0", max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="hmisclientprofile",
            name="personal_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="hmisclientprofileevent",
            name="personal_id",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity", "address", "birth_date", "california_id", "created_at", "date_of_birth", "different_identity_text", "dob_data_quality", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "middle_name", "name_data_quality", "name_suffix", "nickname", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_data_quality", "unique_identifier", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity", NEW."address", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."date_of_birth", NEW."different_identity_text", NEW."dob_data_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."height_in_inches", NEW."hmis_id", NEW."id", NEW."important_notes", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."middle_name", NEW."name_data_quality", NEW."name_suffix", NEW."nickname", NEW."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.add\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."race_ethnicity", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_data_quality", NEW."unique_identifier", NEW."updated_at", NEW."veteran_status"); RETURN NULL;',
                    hash="a28e5fccd09e4f956df091216f6d3d4d5f5ccba2",
                    operation="INSERT",
                    pgid="pgtrigger_hmisclientprofile_add_insert_482dd",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity", "address", "birth_date", "california_id", "created_at", "date_of_birth", "different_identity_text", "dob_data_quality", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "middle_name", "name_data_quality", "name_suffix", "nickname", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_data_quality", "unique_identifier", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity", NEW."address", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."date_of_birth", NEW."different_identity_text", NEW."dob_data_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."height_in_inches", NEW."hmis_id", NEW."id", NEW."important_notes", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."middle_name", NEW."name_data_quality", NEW."name_suffix", NEW."nickname", NEW."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.update\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."race_ethnicity", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_data_quality", NEW."unique_identifier", NEW."updated_at", NEW."veteran_status"); RETURN NULL;',
                    hash="c4d575eea8c0757f51c280b4b9f855193f5e460e",
                    operation="UPDATE",
                    pgid="pgtrigger_hmisclientprofile_update_update_e6981",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity", "address", "birth_date", "california_id", "created_at", "date_of_birth", "different_identity_text", "dob_data_quality", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "middle_name", "name_data_quality", "name_suffix", "nickname", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_data_quality", "unique_identifier", "updated_at", "veteran_status") VALUES (OLD."ada_accommodation", OLD."added_date", OLD."additional_race_ethnicity", OLD."address", OLD."birth_date", OLD."california_id", OLD."created_at", OLD."date_of_birth", OLD."different_identity_text", OLD."dob_data_quality", OLD."email", OLD."eye_color", OLD."first_name", OLD."gender", OLD."gender_other", OLD."hair_color", OLD."height_in_inches", OLD."hmis_id", OLD."id", OLD."important_notes", OLD."last_name", OLD."last_updated", OLD."living_situation", OLD."mailing_address", OLD."marital_status", OLD."middle_name", OLD."name_data_quality", OLD."name_suffix", OLD."nickname", OLD."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.remove\', OLD."id", OLD."phone_number", OLD."physical_description", OLD."place_of_birth", OLD."preferred_communication", OLD."preferred_language", OLD."profile_photo", OLD."pronouns", OLD."pronouns_other", OLD."race", OLD."race_ethnicity", OLD."residence_address", OLD."residence_geolocation", OLD."spoken_languages", OLD."ssn1", OLD."ssn2", OLD."ssn3", OLD."ssn_data_quality", OLD."unique_identifier", OLD."updated_at", OLD."veteran_status"); RETURN NULL;',
                    hash="7724c1c271152a2602a3af47f9a9899bac5c32c1",
                    operation="DELETE",
                    pgid="pgtrigger_hmisclientprofile_remove_delete_4ae9a",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
