# Generated by Django 5.2.7 on 2025-11-12 21:12

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hmis", "0002_add_hmis_id_update_fields"),
        ("pghistory", "0007_auto_20250421_0444"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HmisNote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hmis_id", models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True)),
                ("added_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("ref_client_program", models.CharField(blank=True, max_length=50, null=True)),
                ("client_hmis_id", models.CharField(blank=True, db_index=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmis_notes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hmis_client_profile",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="notes",
                        to="hmis.hmisclientprofile",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HmisNoteEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("hmis_id", models.CharField(blank=True, max_length=50, null=True)),
                ("added_date", models.DateTimeField(blank=True, null=True)),
                ("last_updated", models.DateTimeField(blank=True, null=True)),
                ("date", models.DateField(blank=True, null=True)),
                ("ref_client_program", models.CharField(blank=True, max_length=50, null=True)),
                ("client_hmis_id", models.CharField(blank=True, max_length=50, null=True)),
                ("title", models.CharField(blank=True, max_length=100, null=True)),
                ("note", models.TextField(blank=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "hmis_client_profile",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="hmis.hmisclientprofile",
                    ),
                ),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="hmis.hmisnote",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisnote",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisnote_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisnoteevent" ("added_date", "client_hmis_id", "created_at", "created_by_id", "date", "hmis_client_profile_id", "hmis_id", "id", "last_updated", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ref_client_program", "title", "updated_at") VALUES (NEW."added_date", NEW."client_hmis_id", NEW."created_at", NEW."created_by_id", NEW."date", NEW."hmis_client_profile_id", NEW."hmis_id", NEW."id", NEW."last_updated", NEW."note", _pgh_attach_context(), NOW(), \'hmisnote.add\', NEW."id", NEW."ref_client_program", NEW."title", NEW."updated_at"); RETURN NULL;',
                    hash="bebc50bd09b68046d74f3cac679a8da2a7c14833",
                    operation="INSERT",
                    pgid="pgtrigger_hmisnote_add_insert_1bbc9",
                    table="hmis_hmisnote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisnote",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisnote_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "hmis_hmisnoteevent" ("added_date", "client_hmis_id", "created_at", "created_by_id", "date", "hmis_client_profile_id", "hmis_id", "id", "last_updated", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ref_client_program", "title", "updated_at") VALUES (NEW."added_date", NEW."client_hmis_id", NEW."created_at", NEW."created_by_id", NEW."date", NEW."hmis_client_profile_id", NEW."hmis_id", NEW."id", NEW."last_updated", NEW."note", _pgh_attach_context(), NOW(), \'hmisnote.update\', NEW."id", NEW."ref_client_program", NEW."title", NEW."updated_at"); RETURN NULL;',
                    hash="f996d10a4b935aad200b3daa02a1b7dc38b208ad",
                    operation="UPDATE",
                    pgid="pgtrigger_hmisnote_update_update_2ee8d",
                    table="hmis_hmisnote",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisnote",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisnote_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisnoteevent" ("added_date", "client_hmis_id", "created_at", "created_by_id", "date", "hmis_client_profile_id", "hmis_id", "id", "last_updated", "note", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "ref_client_program", "title", "updated_at") VALUES (OLD."added_date", OLD."client_hmis_id", OLD."created_at", OLD."created_by_id", OLD."date", OLD."hmis_client_profile_id", OLD."hmis_id", OLD."id", OLD."last_updated", OLD."note", _pgh_attach_context(), NOW(), \'hmisnote.remove\', OLD."id", OLD."ref_client_program", OLD."title", OLD."updated_at"); RETURN NULL;',
                    hash="ed982e05f3aed9ff8f35d3460b74bdaa9028dabb",
                    operation="DELETE",
                    pgid="pgtrigger_hmisnote_remove_delete_07afe",
                    table="hmis_hmisnote",
                    when="AFTER",
                ),
            ),
        ),
    ]
