# Generated by Django 5.2.8 on 2025-11-25 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hmis", "0003_hmisnote"),
        ("notes", "0028_alter_organizationservicecategory_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="hmisnote",
            name="provided_services",
            field=models.ManyToManyField(blank=True, related_name="provided_hmis_notes", to="notes.servicerequest"),
        ),
        migrations.AddField(
            model_name="hmisnote",
            name="requested_services",
            field=models.ManyToManyField(blank=True, related_name="requested_hmis_notes", to="notes.servicerequest"),
        ),
    ]
