# Generated by Django 6.0.2 on 2026-02-27 01:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_remove_address_components_field"),
        ("hmis", "0005_hmisnote_location"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hmisnote",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hmis_notes",
                to="common.location",
            ),
        ),
    ]
