# Generated by Django 6.0.3 on 2026-04-01 21:45

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hmis", "0006_alter_hmisnote_location"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_remove_delete",
        ),
        migrations.AddField(
            model_name="hmisclientprofile",
            name="unhoused_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="hmisclientprofileevent",
            name="unhoused_start_date",
            field=models.DateField(blank=True, null=True),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "date_of_birth", "dob_quality", "email", "eye_color", "first_name", "gender", "gender_identity_text", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "name_middle", "name_quality", "name_suffix", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "unhoused_start_date", "unique_identifier", "updated_at", "veteran") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity_detail", NEW."address", NEW."age", NEW."alias", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."created_by_id", NEW."date_of_birth", NEW."dob_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_identity_text", NEW."hair_color", NEW."height_in_inches", NEW."hmis_id", NEW."id", NEW."important_notes", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."name_middle", NEW."name_quality", NEW."name_suffix", NEW."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.add\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race_ethnicity", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_quality", NEW."unhoused_start_date", NEW."unique_identifier", NEW."updated_at", NEW."veteran"); RETURN NULL;',
                    hash="9181c17f4cd012b73d152a3060898d0500d5905f",
                    operation="INSERT",
                    pgid="pgtrigger_hmisclientprofile_add_insert_482dd",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "date_of_birth", "dob_quality", "email", "eye_color", "first_name", "gender", "gender_identity_text", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "name_middle", "name_quality", "name_suffix", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "unhoused_start_date", "unique_identifier", "updated_at", "veteran") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity_detail", NEW."address", NEW."age", NEW."alias", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."created_by_id", NEW."date_of_birth", NEW."dob_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_identity_text", NEW."hair_color", NEW."height_in_inches", NEW."hmis_id", NEW."id", NEW."important_notes", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."name_middle", NEW."name_quality", NEW."name_suffix", NEW."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.update\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race_ethnicity", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_quality", NEW."unhoused_start_date", NEW."unique_identifier", NEW."updated_at", NEW."veteran"); RETURN NULL;',
                    hash="7fe8ad55dba7e37a2b6142dd82ea5da316aff5b8",
                    operation="UPDATE",
                    pgid="pgtrigger_hmisclientprofile_update_update_e6981",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "date_of_birth", "dob_quality", "email", "eye_color", "first_name", "gender", "gender_identity_text", "hair_color", "height_in_inches", "hmis_id", "id", "important_notes", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "name_middle", "name_quality", "name_suffix", "personal_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "residence_address", "residence_geolocation", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "unhoused_start_date", "unique_identifier", "updated_at", "veteran") VALUES (OLD."ada_accommodation", OLD."added_date", OLD."additional_race_ethnicity_detail", OLD."address", OLD."age", OLD."alias", OLD."birth_date", OLD."california_id", OLD."created_at", OLD."created_by_id", OLD."date_of_birth", OLD."dob_quality", OLD."email", OLD."eye_color", OLD."first_name", OLD."gender", OLD."gender_identity_text", OLD."hair_color", OLD."height_in_inches", OLD."hmis_id", OLD."id", OLD."important_notes", OLD."last_name", OLD."last_updated", OLD."living_situation", OLD."mailing_address", OLD."marital_status", OLD."name_middle", OLD."name_quality", OLD."name_suffix", OLD."personal_id", _pgh_attach_context(), NOW(), \'hmisclientprofile.remove\', OLD."id", OLD."phone_number", OLD."physical_description", OLD."place_of_birth", OLD."preferred_communication", OLD."preferred_language", OLD."profile_photo", OLD."pronouns", OLD."pronouns_other", OLD."race_ethnicity", OLD."residence_address", OLD."residence_geolocation", OLD."spoken_languages", OLD."ssn1", OLD."ssn2", OLD."ssn3", OLD."ssn_quality", OLD."unhoused_start_date", OLD."unique_identifier", OLD."updated_at", OLD."veteran"); RETURN NULL;',
                    hash="fcb8565965fb785e6cd7375010588cf6eff5b095",
                    operation="DELETE",
                    pgid="pgtrigger_hmisclientprofile_remove_delete_4ae9a",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
