# Generated by Django 6.0.2 on 2026-03-17 01:07

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hmis", "0007_client_attributes_from_abstract"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="hmisclientprofile",
            name="hmisclientprofile_remove_delete",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "adl_capacity", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "criminal_history", "date_of_birth", "destination", "destination_other", "dob_quality", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_identity_text", "hair_color", "harm_reduction", "height_in_inches", "hmis_id", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "name_middle", "name_quality", "name_suffix", "personal_id", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "status", "unique_identifier", "updated_at", "veteran") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity_detail", NEW."address", NEW."adl_capacity", NEW."age", NEW."alias", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."created_by_id", NEW."criminal_history", NEW."date_of_birth", NEW."destination", NEW."destination_other", NEW."dob_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."funding_source", NEW."funding_source_other", NEW."gender", NEW."gender_identity_text", NEW."hair_color", NEW."harm_reduction", NEW."height_in_inches", NEW."hmis_id", NEW."homelessness_notes", NEW."id", NEW."important_notes", NEW."income_annual", NEW."income_source", NEW."justice_involvement_details", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."medical_needs", NEW."medical_notes", NEW."name_middle", NEW."name_quality", NEW."name_suffix", NEW."personal_id", NEW."pets", NEW."pets_other", _pgh_attach_context(), NOW(), \'hmisclientprofile.add\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race_ethnicity", NEW."requires_transportation", NEW."residence_address", NEW."residence_geolocation", NEW."sexual_orientation", NEW."sexual_orientation_other", NEW."social_security_number", NEW."spa", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_quality", NEW."status", NEW."unique_identifier", NEW."updated_at", NEW."veteran"); RETURN NULL;',
                    hash="9dbb39d074b6ba36467020aca79bc022514d3717",
                    operation="INSERT",
                    pgid="pgtrigger_hmisclientprofile_add_insert_482dd",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "adl_capacity", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "criminal_history", "date_of_birth", "destination", "destination_other", "dob_quality", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_identity_text", "hair_color", "harm_reduction", "height_in_inches", "hmis_id", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "name_middle", "name_quality", "name_suffix", "personal_id", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "status", "unique_identifier", "updated_at", "veteran") VALUES (NEW."ada_accommodation", NEW."added_date", NEW."additional_race_ethnicity_detail", NEW."address", NEW."adl_capacity", NEW."age", NEW."alias", NEW."birth_date", NEW."california_id", NEW."created_at", NEW."created_by_id", NEW."criminal_history", NEW."date_of_birth", NEW."destination", NEW."destination_other", NEW."dob_quality", NEW."email", NEW."eye_color", NEW."first_name", NEW."funding_source", NEW."funding_source_other", NEW."gender", NEW."gender_identity_text", NEW."hair_color", NEW."harm_reduction", NEW."height_in_inches", NEW."hmis_id", NEW."homelessness_notes", NEW."id", NEW."important_notes", NEW."income_annual", NEW."income_source", NEW."justice_involvement_details", NEW."last_name", NEW."last_updated", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."medical_needs", NEW."medical_notes", NEW."name_middle", NEW."name_quality", NEW."name_suffix", NEW."personal_id", NEW."pets", NEW."pets_other", _pgh_attach_context(), NOW(), \'hmisclientprofile.update\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race_ethnicity", NEW."requires_transportation", NEW."residence_address", NEW."residence_geolocation", NEW."sexual_orientation", NEW."sexual_orientation_other", NEW."social_security_number", NEW."spa", NEW."spoken_languages", NEW."ssn1", NEW."ssn2", NEW."ssn3", NEW."ssn_quality", NEW."status", NEW."unique_identifier", NEW."updated_at", NEW."veteran"); RETURN NULL;',
                    hash="4e26949bdd291579097c4d6b25ddf83a99b25905",
                    operation="UPDATE",
                    pgid="pgtrigger_hmisclientprofile_update_update_e6981",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="hmisclientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="hmisclientprofile_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "hmis_hmisclientprofileevent" ("ada_accommodation", "added_date", "additional_race_ethnicity_detail", "address", "adl_capacity", "age", "alias", "birth_date", "california_id", "created_at", "created_by_id", "criminal_history", "date_of_birth", "destination", "destination_other", "dob_quality", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_identity_text", "hair_color", "harm_reduction", "height_in_inches", "hmis_id", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "last_updated", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "name_middle", "name_quality", "name_suffix", "personal_id", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race_ethnicity", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "ssn1", "ssn2", "ssn3", "ssn_quality", "status", "unique_identifier", "updated_at", "veteran") VALUES (OLD."ada_accommodation", OLD."added_date", OLD."additional_race_ethnicity_detail", OLD."address", OLD."adl_capacity", OLD."age", OLD."alias", OLD."birth_date", OLD."california_id", OLD."created_at", OLD."created_by_id", OLD."criminal_history", OLD."date_of_birth", OLD."destination", OLD."destination_other", OLD."dob_quality", OLD."email", OLD."eye_color", OLD."first_name", OLD."funding_source", OLD."funding_source_other", OLD."gender", OLD."gender_identity_text", OLD."hair_color", OLD."harm_reduction", OLD."height_in_inches", OLD."hmis_id", OLD."homelessness_notes", OLD."id", OLD."important_notes", OLD."income_annual", OLD."income_source", OLD."justice_involvement_details", OLD."last_name", OLD."last_updated", OLD."living_situation", OLD."mailing_address", OLD."marital_status", OLD."medical_needs", OLD."medical_notes", OLD."name_middle", OLD."name_quality", OLD."name_suffix", OLD."personal_id", OLD."pets", OLD."pets_other", _pgh_attach_context(), NOW(), \'hmisclientprofile.remove\', OLD."id", OLD."phone_number", OLD."physical_description", OLD."place_of_birth", OLD."preferred_communication", OLD."preferred_language", OLD."profile_photo", OLD."pronouns", OLD."pronouns_other", OLD."race_ethnicity", OLD."requires_transportation", OLD."residence_address", OLD."residence_geolocation", OLD."sexual_orientation", OLD."sexual_orientation_other", OLD."social_security_number", OLD."spa", OLD."spoken_languages", OLD."ssn1", OLD."ssn2", OLD."ssn3", OLD."ssn_quality", OLD."status", OLD."unique_identifier", OLD."updated_at", OLD."veteran"); RETURN NULL;',
                    hash="048438ad5bdd001b7b10c79108760e14ca766d5d",
                    operation="DELETE",
                    pgid="pgtrigger_hmisclientprofile_remove_delete_4ae9a",
                    table="hmis_hmisclientprofile",
                    when="AFTER",
                ),
            ),
        ),
    ]
