from allauth.socialaccount.providers.base import Provider as Provider

class OAuthProvider(Provider):
    def get_login_url(self, request, **kwargs): ...
    def get_auth_params(self, request, action): ...
    def get_auth_url(self, request, action) -> None: ...
    def get_scope(self, request): ...
    def get_default_scope(self): ...
