name: e2e-test-android

jobs:
  extract-vars:
    steps:
      - run: |
          grep '^RUNTIME_VERSION=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2- > runtime_version.txt
          grep '^MAESTRO_PROJECT_ID=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2- > maestro_project_id.txt
          grep '^MAESTRO_GROUP_ID=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2- > maestro_group_id.txt
          echo "RUNTIME_VERSION=$(cat runtime_version.txt)" >> $EAS_OUTPUTS
          echo "MAESTRO_PROJECT_ID=$(cat maestro_project_id.txt)" >> $EAS_OUTPUTS
          echo "MAESTRO_GROUP_ID=$(cat maestro_group_id.txt)" >> $EAS_OUTPUTS

  wait:
    needs: [extract-vars]
    type: get-build
    params:
      runtime_version: ${{ needs.extract-vars.outputs.RUNTIME_VERSION }}
      platform: android

  maestro_test:
    needs: [wait, extract-vars]
    type: maestro
    env:
      MAESTRO_GROUP_ID: ${{ needs.extract-vars.outputs.MAESTRO_GROUP_ID }}
      MAESTRO_PROJECT_ID: ${{ needs.extract-vars.outputs.MAESTRO_PROJECT_ID }}
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/android/landing.yml']
