name: e2e-test-android

jobs:
  get_vars:
    outputs:
      runtime_version: ${{ steps.set_vars.outputs.runtime_version }}
      maestro_group_id: ${{ steps.set_vars.outputs.maestro_group_id }}
      maestro_project_id: ${{ steps.set_vars.outputs.maestro_project_id }}
    steps:
      - id: set_vars
        run: |
          RUNTIME_VERSION=$(grep '^RUNTIME_VERSION=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2-)
          MAESTRO_GROUP_ID=$(grep '^MAESTRO_GROUP_ID=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2-)
          MAESTRO_PROJECT_ID=$(grep '^MAESTRO_PROJECT_ID=' /home/expo/workingdir/temporary-custom-build/apps/betterangels/.env | cut -d '=' -f2-)
          set-output runtime_version "$RUNTIME_VERSION"
          set-output maestro_group_id "$MAESTRO_GROUP_ID"
          set-output maestro_project_id "$MAESTRO_PROJECT_ID"

  get_build:
    needs: [get_vars]
    type: get-build
    params:
      runtime_version: ${{ needs.get_vars.outputs.runtime_version }}
      platform: android

  maestro_test:
    needs: [get_vars, get_build]
    type: maestro
    env:
      MAESTRO_GROUP_ID: ${{ needs.get_vars.outputs.maestro_group_id }}
      MAESTRO_PROJECT_ID: ${{ needs.get_vars.outputs.maestro_project_id }}
    params:
      build_id: ${{ needs.get_build.outputs.build_id }}
      flow_path: ['.maestro/android/landing.yml']
