name: e2e-test-android

jobs:
  wait:
    type: get-build
    params:
      build_id: ${{ env.BUILD_ID }}

  maestro_test:
    needs: [wait]
    type: maestro
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/android/landing.yml']
