name: e2e-test-android

env:
  MAESTRO_PROJECT_ID: $MAESTRO_PROJECT_ID
  MAESTRO_GROUP_ID: $MAESTRO_GROUP_ID
  RUNTIME_VERSION: $RUNTIME_VERSION

jobs:
  wait:
    type: get-build
    params:
      runtime_version: ${{ env.RUNTIME_VERSION }}
      platform: android

  maestro_test:
    needs: [wait]
    type: maestro
    env:
      MAESTRO_PROJECT_ID: ${{ env.MAESTRO_PROJECT_ID }}
      MAESTRO_GROUP_ID: ${{ env.MAESTRO_GROUP_ID }}
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/android/landing.yml']
