version: 0.1

jobs:
  build_ios_for_e2e:
    projectRoot: 'apps/betterangels'

    type: build
    params:
      platform: ios
      profile: development-simulator

  maestro_test:
    needs: [build_ios_for_e2e]
    type: maestro
    params:
      build_id: ${{ needs.build_ios_for_e2e.outputs.build_id }}
      flow_path: ['.maestro/landing.yml']
