name: e2e-test

jobs:
  get_vars:
    outputs:
      runtime_version: ${{ steps.set_vars.outputs.runtime_version }}
      group_id: ${{ steps.set_vars.outputs.group_id }}
      project_id: ${{ steps.set_vars.outputs.project_id }}
    steps:
      - id: set_vars
        run: |
          WORK_DIR="/home/expo/workingdir/temporary-custom-build/apps/betterangels"
          GROUP_ID=$(grep '^GROUP_ID=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          PROJECT_ID=$(grep '^PROJECT_ID=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          RUNTIME_VERSION=$(grep '^RUNTIME_VERSION=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          set-output group_id "$GROUP_ID"
          set-output project_id "$PROJECT_ID"
          set-output runtime_version "$RUNTIME_VERSION"

  get_android_build:
    needs: [get_vars]
    type: get-build
    params:
      runtime_version: ${{ needs.get_vars.outputs.runtime_version }}
      platform: android

  get_ios_build:
    needs: [get_vars]
    type: get-build
    params:
      runtime_version: ${{ needs.get_vars.outputs.runtime_version }}
      platform: ios

  maestro_android_test:
    needs: [get_vars, get_android_build]
    type: maestro
    env:
      MAESTRO_PLATFORM: android
      MAESTRO_GROUP_ID: ${{ needs.get_vars.outputs.group_id }}
      MAESTRO_PROJECT_ID: ${{ needs.get_vars.outputs.project_id }}
    params:
      build_id: ${{ needs.get_android_build.outputs.build_id }}
      flow_path: ['.maestro/landing.yml']

  maestro_ios_test:
    needs: [get_vars, get_ios_build]
    type: maestro
    env:
      MAESTRO_PLATFORM: ios
      MAESTRO_GROUP_ID: ${{ needs.get_vars.outputs.group_id }}
      MAESTRO_PROJECT_ID: ${{ needs.get_vars.outputs.project_id }}
    params:
      build_id: ${{ needs.get_ios_build.outputs.build_id }}
      flow_path: ['.maestro/landing.yml']

  github_dispatch:
    after: [maestro_android_test, maestro_ios_test]
    steps:
      - id: dispatch
        env:
          ANDROID_E2E_STATUS: ${{ after.maestro_android_test.status }}
          IOS_E2E_STATUS: ${{ after.maestro_ios_test.status }}
          GITHUB_DISPATCH_TOKEN: ${{ secrets.GITHUB_DISPATCH_TOKEN }}
          GITHUB_REPOSITORY: ${{ secrets.GITHUB_REPOSITORY }}
        run: |
          set -euo pipefail

          WORK_DIR="/home/expo/workingdir/temporary-custom-build/apps/betterangels"

          if [ -z "${GITHUB_DISPATCH_TOKEN:-}" ]; then
            echo "Missing GITHUB_DISPATCH_TOKEN"
            exit 1
          fi

          if [ -z "${GITHUB_REPOSITORY:-}" ]; then
            echo "Missing GITHUB_REPOSITORY (expected format: owner/repo)"
            exit 1
          fi

          WEBHOOK_PAYLOAD_B64="$(grep '^WEBHOOK_PAYLOAD_B64=' ${WORK_DIR}/.env | cut -d '=' -f2- || true)"
          if [ -z "${WEBHOOK_PAYLOAD_B64:-}" ]; then
            echo "Missing WEBHOOK_PAYLOAD_B64 in ${WORK_DIR}/.env"
            exit 1
          fi

          WEBHOOK_PAYLOAD="$(printf '%s' "$WEBHOOK_PAYLOAD_B64" | base64 -d)"
          export WEBHOOK_PAYLOAD

          BODY="$(python3 - <<'PY'
          import json, os

          payload = json.loads(os.environ["WEBHOOK_PAYLOAD"])
          android_status = os.environ.get("ANDROID_E2E_STATUS", "")
          ios_status = os.environ.get("IOS_E2E_STATUS", "")

          status = "success" if android_status == "success" and ios_status == "success" else "failure"
          payload["status"] = status
          payload["android-e2e-status"] = android_status
          payload["ios-e2e-status"] = ios_status

          print(json.dumps({
            "event_type": "e2e-tests-complete",
            "client_payload": payload
          }))
          PY
          )"

          curl -fsSL \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${GITHUB_DISPATCH_TOKEN}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            "https://api.github.com/repos/${GITHUB_REPOSITORY}/dispatches" \
            -d "${BODY}"
