name: e2e-test-ios

jobs:
  env:
    MAESTRO_GROUP_ID: ${{ env.MAESTRO_GROUP_ID }}
    MAESTRO_PROJECT_ID: ${{ env.MAESTRO_PROJECT_ID }}
  wait:
    type: get-build
    params:
      runtime_version: ${{ env.RUNTIME_VERSION }}
      platform: ios

  maestro_test:
    needs: [wait]
    type: maestro
    env:
      MAESTRO_PROJECT_ID: 53171ba4-60ca-40cb-b3e6-b0c2393677b8
      MAESTRO_GROUP_ID: 4eae1320-1f13-418b-9da2-cc1464dceee2
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/ios/landing.yml']
