name: e2e-test-ios

jobs:
  get_vars:
    outputs:
      runtime_version: ${{ steps.set_vars.outputs.runtime_version }}
      group_id: ${{ steps.set_vars.outputs.group_id }}
      project_id: ${{ steps.set_vars.outputs.project_id }}
    steps:
      - id: set_vars
        run: |
          WORK_DIR="/home/expo/workingdir/temporary-custom-build/apps/betterangels"
          GROUP_ID=$(grep '^GROUP_ID=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          PROJECT_ID=$(grep '^PROJECT_ID=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          RUNTIME_VERSION=$(grep '^RUNTIME_VERSION=' ${WORK_DIR}/.env | cut -d '=' -f2-)
          set-output group_id "$GROUP_ID"
          set-output project_id "$PROJECT_ID"
          set-output runtime_version "$RUNTIME_VERSION"

  get_build:
    needs: [get_vars]
    type: get-build
    params:
      runtime_version: ${{ needs.get_vars.outputs.runtime_version }}
      platform: ios

  maestro_test:
    needs: [get_vars, get_build]
    type: maestro
    env:
      MAESTRO_GROUP_ID: ${{ needs.get_vars.outputs.group_id }}
      MAESTRO_PROJECT_ID: ${{ needs.get_vars.outputs.project_id }}
    params:
      build_id: ${{ needs.get_build.outputs.build_id }}
      flow_path: ['.maestro/ios/landing.yml']
