name: e2e-test-ios

jobs:
  wait:
    type: get-build
    params:
      runtime_version: ${{ env.RUNTIME_VERSION }}
      platform: ios

  maestro_test:
    needs: [wait]
    type: maestro
    env:
      MAESTRO_ENV_PROJECT_ID: ${{ env.PROJECT_ID }}
      MAESTRO_ENV_GROUP_ID: ${{ env.GROUP_ID }}
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/ios/landing.yml']
