name: e2e-test-ios

on:
  workflow_dispatch:
    inputs:
      build_id:
        required: true

jobs:
  maestro_test:
    type: maestro
    params:
      build_id: ${{ fromJSON(env.WORKFLOW_DISPATCH_INPUTS).build_id }}
      flow_path: ['.maestro/ios/landing.yml']
