name: e2e-test-ios

jobs:
  env:
    MAESTRO_GROUP_ID: ${{ env.MAESTRO_GROUP_ID }}
    MAESTRO_PROJECT_ID: ${{ env.MAESTRO_PROJECT_ID }}
  wait:
    type: get-build
    params:
      runtime_version: ${{ env.RUNTIME_VERSION }}
      platform: ios

  maestro_test:
    needs: [wait]
    type: maestro
    params:
      build_id: ${{ needs.wait.outputs.build_id }}
      flow_path: ['.maestro/ios/landing.yml']
