import type * as Types from '@monorepo/ba-platform/types';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type ShelterOccupancyMetricsQueryVariables = Types.Exact<{
  shelterId: Types.Scalars['ID']['input'];
  startDate: Types.Scalars['Date']['input'];
  endDate: Types.Scalars['Date']['input'];
}>;


export type ShelterOccupancyMetricsQuery = { __typename: 'Query', shelterOccupancyMetrics: { __typename: 'ShelterOccupancyMetricsType', shelterId: string, startDate: any, endDate: any, avgDaysToOccupancy?: number | null, dailyOccupancy: Array<{ __typename: 'DailyOccupancyMetricsType', date: any, occupiedCount: number, totalBeds: number, occupancyPct: number }>, dailyBedStatus: Array<{ __typename: 'DailyBedStatusMetricsType', date: any, available: number, occupied: number, reserved: number, outOfService: number, inTurnaround: number }>, reservationMetrics: { __typename: 'ReservationMetricsType', checkInOverdue: number, cancelled: number, checkedIn: number, checkInOverdueToCheckedIn: number } } };


export const ShelterOccupancyMetricsDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"ShelterOccupancyMetrics"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"shelterId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Date"}}}},{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"Date"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shelterOccupancyMetrics"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"shelterId"},"value":{"kind":"Variable","name":{"kind":"Name","value":"shelterId"}}},{"kind":"Argument","name":{"kind":"Name","value":"startDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"startDate"}}},{"kind":"Argument","name":{"kind":"Name","value":"endDate"},"value":{"kind":"Variable","name":{"kind":"Name","value":"endDate"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"shelterId"}},{"kind":"Field","name":{"kind":"Name","value":"startDate"}},{"kind":"Field","name":{"kind":"Name","value":"endDate"}},{"kind":"Field","name":{"kind":"Name","value":"avgDaysToOccupancy"}},{"kind":"Field","name":{"kind":"Name","value":"dailyOccupancy"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"occupiedCount"}},{"kind":"Field","name":{"kind":"Name","value":"totalBeds"}},{"kind":"Field","name":{"kind":"Name","value":"occupancyPct"}}]}},{"kind":"Field","name":{"kind":"Name","value":"dailyBedStatus"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"date"}},{"kind":"Field","name":{"kind":"Name","value":"available"}},{"kind":"Field","name":{"kind":"Name","value":"occupied"}},{"kind":"Field","name":{"kind":"Name","value":"reserved"}},{"kind":"Field","name":{"kind":"Name","value":"outOfService"}},{"kind":"Field","name":{"kind":"Name","value":"inTurnaround"}}]}},{"kind":"Field","name":{"kind":"Name","value":"reservationMetrics"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"checkInOverdue"}},{"kind":"Field","name":{"kind":"Name","value":"cancelled"}},{"kind":"Field","name":{"kind":"Name","value":"checkedIn"}},{"kind":"Field","name":{"kind":"Name","value":"checkInOverdueToCheckedIn"}}]}}]}}]}}]} as unknown as DocumentNode<ShelterOccupancyMetricsQuery, ShelterOccupancyMetricsQueryVariables>;