from _typeshed import Incomplete
from allauth.socialaccount import providers as providers
from allauth.utils import get_request_param as get_request_param
from django import template

register: Incomplete

class ProviderLoginURLNode(template.Node):
    provider_id_var: Incomplete
    params: Incomplete
    def __init__(self, provider_id, params) -> None: ...
    def render(self, context): ...

def provider_login_url(parser, token): ...

class ProvidersMediaJSNode(template.Node):
    def render(self, context): ...

def providers_media_js(parser, token): ...
def get_social_accounts(user): ...
def get_providers(): ...
