import type * as Types from '../../../apollo/graphql/__generated__/types';

import type { TypedDocumentNode as DocumentNode } from '@graphql-typed-document-node/core';
export type GetAdminShelterOverviewQueryVariables = Types.Exact<{
  shelterId: Types.Scalars['ID']['input'];
}>;


export type GetAdminShelterOverviewQuery = { __typename?: 'Query', adminShelter: { __typename?: 'AdminShelterType', id: string, name: string, organization?: { __typename?: 'OrganizationType', id: string, name: string } | null, location?: { __typename?: 'ShelterLocationType', place: string } | null, bedsByStatus: { __typename?: 'BedsByStatusType', available: number, inTurnaround: number, occupied: number, outOfService: number, reserved: number }, roomsByStatus: { __typename?: 'RoomsByStatusType', available: number, inTurnaround: number, occupied: number, outOfService: number, reserved: number } } };


export const GetAdminShelterOverviewDocument = {"kind":"Document","definitions":[{"kind":"OperationDefinition","operation":"query","name":{"kind":"Name","value":"GetAdminShelterOverview"},"variableDefinitions":[{"kind":"VariableDefinition","variable":{"kind":"Variable","name":{"kind":"Name","value":"shelterId"}},"type":{"kind":"NonNullType","type":{"kind":"NamedType","name":{"kind":"Name","value":"ID"}}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"adminShelter"},"arguments":[{"kind":"Argument","name":{"kind":"Name","value":"pk"},"value":{"kind":"Variable","name":{"kind":"Name","value":"shelterId"}}}],"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}},{"kind":"Field","name":{"kind":"Name","value":"organization"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"id"}},{"kind":"Field","name":{"kind":"Name","value":"name"}}]}},{"kind":"Field","name":{"kind":"Name","value":"location"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"place"}}]}},{"kind":"Field","name":{"kind":"Name","value":"bedsByStatus"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"available"}},{"kind":"Field","name":{"kind":"Name","value":"inTurnaround"}},{"kind":"Field","name":{"kind":"Name","value":"occupied"}},{"kind":"Field","name":{"kind":"Name","value":"outOfService"}},{"kind":"Field","name":{"kind":"Name","value":"reserved"}}]}},{"kind":"Field","name":{"kind":"Name","value":"roomsByStatus"},"selectionSet":{"kind":"SelectionSet","selections":[{"kind":"Field","name":{"kind":"Name","value":"available"}},{"kind":"Field","name":{"kind":"Name","value":"inTurnaround"}},{"kind":"Field","name":{"kind":"Name","value":"occupied"}},{"kind":"Field","name":{"kind":"Name","value":"outOfService"}},{"kind":"Field","name":{"kind":"Name","value":"reserved"}}]}}]}}]}}]} as unknown as DocumentNode<GetAdminShelterOverviewQuery, GetAdminShelterOverviewQueryVariables>;