from _typeshed import Incomplete
from allauth import app_settings as app_settings

MAX_USERNAME_SUFFIX_LENGTH: int
USERNAME_SUFFIX_CHARS: Incomplete

def get_username_max_length(): ...
def generate_username_candidate(basename, suffix_length): ...
def generate_username_candidates(basename): ...
def generate_unique_username(txts, regex: Incomplete | None = ...): ...
def valid_email_or_none(email): ...
def email_address_exists(email, exclude_user: Incomplete | None = ...): ...
def import_attribute(path): ...
def import_callable(path_or_callable): ...

SERIALIZED_DB_FIELD_PREFIX: str

def serialize_instance(instance): ...
def deserialize_instance(model, data): ...
def set_form_field_order(form, field_order) -> None: ...
def build_absolute_uri(request, location, protocol: Incomplete | None = ...): ...
def get_form_class(forms, form_id, default_form): ...
def get_request_param(request, param, default: Incomplete | None = ...): ...
