# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.db.models.deletion
import django_choices_field.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('hmis', '0002_initial'),
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'To Do'), (1, 'In Progress'), (2, 'Completed')], default=0)),
                ('summary', models.CharField(max_length=100)),
                ('old_team', django_choices_field.fields.TextChoicesField(blank=True, choices=[('bowtie_riverside_outreach', 'Bowtie & Riverside Outreach'), ('echo_park_on_site', 'Echo Park On-site'), ('echo_park_outreach', 'Echo Park Outreach'), ('hollywood_on_site', 'Hollywood On-site'), ('hollywood_outreach', 'Hollywood Outreach'), ('la_river_outreach', 'LA River Outreach'), ('los_feliz_outreach', 'Los Feliz Outreach'), ('northeast_hollywood_outreach', 'Northeast Hollywood Outreach'), ('selah_staff', 'SELAH Staff'), ('silver_lake_outreach', 'Silver Lake Outreach'), ('slcc_on_site', 'SLCC On-site'), ('sunday_social_atwater_on_site', 'Sunday Social / Atwater On-site'), ('sunday_social_atwater_outreach', 'Sunday Social / Atwater Outreach'), ('wdi_on_site', 'WDI On-site'), ('wdi_outreach', 'WDI Outreach')], max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', django_choices_field.fields.IntegerChoicesField(choices=[(0, 'To Do'), (1, 'In Progress'), (2, 'Completed')], db_index=True, default=0)),
                ('summary', models.CharField(db_index=True, max_length=100)),
                ('old_team', django_choices_field.fields.TextChoicesField(blank=True, choices=[('bowtie_riverside_outreach', 'Bowtie & Riverside Outreach'), ('echo_park_on_site', 'Echo Park On-site'), ('echo_park_outreach', 'Echo Park Outreach'), ('hollywood_on_site', 'Hollywood On-site'), ('hollywood_outreach', 'Hollywood Outreach'), ('la_river_outreach', 'LA River Outreach'), ('los_feliz_outreach', 'Los Feliz Outreach'), ('northeast_hollywood_outreach', 'Northeast Hollywood Outreach'), ('selah_staff', 'SELAH Staff'), ('silver_lake_outreach', 'Silver Lake Outreach'), ('slcc_on_site', 'SLCC On-site'), ('sunday_social_atwater_on_site', 'Sunday Social / Atwater On-site'), ('sunday_social_atwater_outreach', 'Sunday Social / Atwater Outreach'), ('wdi_on_site', 'WDI On-site'), ('wdi_outreach', 'WDI Outreach')], db_index=True, max_length=30, null=True)),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='clients.clientprofile')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to=settings.AUTH_USER_MODEL)),
                ('hmis_client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='hmis.hmisclientprofile')),
                ('hmis_note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='hmis.hmisnote')),
                ('note', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='notes.note')),
                ('organization', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='organizations.organization')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
