# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.contrib.postgres.indexes
import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('hmis', '0002_initial'),
        ('notes', '0002_initial'),
        ('organizations', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('tasks', '0001_initial'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='client_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='hmis_client_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='hmis.hmisclientprofile'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='hmis_note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='hmis.hmisnote'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='note',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.note'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='tasks.task'),
        ),
        migrations.AddField(
            model_name='taskevent',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teams.team'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['description'], name='task_description_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddIndex(
            model_name='task',
            index=django.contrib.postgres.indexes.GinIndex(fields=['summary'], name='task_summary_trgm', opclasses=['gin_trgm_ops']),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(('note__isnull', True), ('hmis_note__isnull', True), _connector='OR'), name='task_single_parent_check'),
        ),
        migrations.AddConstraint(
            model_name='task',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('client_profile__isnull', False), ('hmis_client_profile__isnull', True)), models.Q(('client_profile__isnull', True), ('hmis_client_profile__isnull', False)), models.Q(('client_profile__isnull', True), ('hmis_client_profile__isnull', True)), _connector='OR'), name='task_only_one_client_link'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='task_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."hmis_client_profile_id", NEW."hmis_note_id", NEW."id", NEW."note_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'task.add\', NEW."id", NEW."status", NEW."summary", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='6e6b306117fed13c9f551aa8049412ab2fdbb17c', operation='INSERT', pgid='pgtrigger_task_add_insert_be0f1', table='tasks_task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='task_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."hmis_client_profile_id", NEW."hmis_note_id", NEW."id", NEW."note_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'task.update\', NEW."id", NEW."status", NEW."summary", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='47c1d8adfc5d611db5634b0e202473cd11a21fc3', operation='UPDATE', pgid='pgtrigger_task_update_update_1c3f7', table='tasks_task', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='task',
            trigger=pgtrigger.compiler.Trigger(name='task_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."description", OLD."hmis_client_profile_id", OLD."hmis_note_id", OLD."id", OLD."note_id", OLD."old_team", OLD."organization_id", _pgh_attach_context(), NOW(), \'task.remove\', OLD."id", OLD."status", OLD."summary", OLD."team_id", OLD."updated_at"); RETURN NULL;', hash='6c092423eb1d8144e65ea1203ff833059cf84999', operation='DELETE', pgid='pgtrigger_task_remove_delete_093f2', table='tasks_task', when='AFTER')),
        ),
    ]
