# Generated by Django 6.1 on 2026-08-27 23:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_created_by_alter_task_organization_and_more'),
        ('teams', '0003_remove_team_unique_team_slug_per_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.RESTRICT, to='teams.team'),
        ),
    ]
