# Generated by Django 6.0.6 on 2026-06-18 22:39

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

from common.enums import SelahTeamEnum


def _backfill_teams_and_copy(apps, schema_editor):
    """Create Team objects per org for each SelahTeamEnum value, then copy task.old_team -> task.team FK."""
    Task = apps.get_model("tasks", "Task")
    Team = apps.get_model("teams", "Team")
    Organization = apps.get_model("organizations", "Organization")

    org_ids = (
        Task.objects.exclude(old_team__isnull=True)
        .exclude(old_team="")
        .values_list("organization_id", flat=True)
        .distinct()
    )

    for org_id in org_ids:
        try:
            org = Organization.objects.get(pk=org_id)
        except Organization.DoesNotExist:
            continue
        for enum_member in SelahTeamEnum:
            Team.objects.get_or_create(
                organization=org,
                slug=enum_member.value,
                defaults={"name": enum_member.label},
            )

    for task in Task.objects.exclude(old_team__isnull=True).exclude(old_team="").iterator():
        try:
            team = Team.objects.get(
                organization_id=task.organization_id,
                slug=task.old_team,
            )
            task.team = team
            task.save(update_fields=["team"])
        except Team.DoesNotExist:
            pass


def _reverse_backfill(apps, schema_editor):
    Task = apps.get_model("tasks", "Task")
    Task.objects.all().update(team=None)


class Migration(migrations.Migration):

    dependencies = [
        ("tasks", "0005_remove_task_task_add_insert_and_more"),
        ("teams", "0001_initial"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        # -- Rename old enum column to preserve data --
        migrations.RenameField(
            model_name="task",
            old_name="team",
            new_name="old_team",
        ),
        migrations.RenameField(
            model_name="taskevent",
            old_name="team",
            new_name="old_team",
        ),
        # -- Add new FK column --
        migrations.AddField(
            model_name="task",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="taskevent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="teams.team",
            ),
        ),
        # -- Re-add pghistory triggers referencing new team_id column --
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="task_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."hmis_client_profile_id", NEW."hmis_note_id", NEW."id", NEW."note_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'task.add\', NEW."id", NEW."status", NEW."summary", NEW."team_id", NEW."updated_at"); RETURN NULL;',
                    hash="6e6b306117fed13c9f551aa8049412ab2fdbb17c",
                    operation="INSERT",
                    pgid="pgtrigger_task_add_insert_be0f1",
                    table="tasks_task",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="task_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."description", NEW."hmis_client_profile_id", NEW."hmis_note_id", NEW."id", NEW."note_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'task.update\', NEW."id", NEW."status", NEW."summary", NEW."team_id", NEW."updated_at"); RETURN NULL;',
                    hash="47c1d8adfc5d611db5634b0e202473cd11a21fc3",
                    operation="UPDATE",
                    pgid="pgtrigger_task_update_update_1c3f7",
                    table="tasks_task",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="task",
            trigger=pgtrigger.compiler.Trigger(
                name="task_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "tasks_taskevent" ("client_profile_id", "created_at", "created_by_id", "description", "hmis_client_profile_id", "hmis_note_id", "id", "note_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "status", "summary", "team_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."description", OLD."hmis_client_profile_id", OLD."hmis_note_id", OLD."id", OLD."note_id", OLD."old_team", OLD."organization_id", _pgh_attach_context(), NOW(), \'task.remove\', OLD."id", OLD."status", OLD."summary", OLD."team_id", OLD."updated_at"); RETURN NULL;',
                    hash="6c092423eb1d8144e65ea1203ff833059cf84999",
                    operation="DELETE",
                    pgid="pgtrigger_task_remove_delete_093f2",
                    table="tasks_task",
                    when="AFTER",
                ),
            ),
        ),
        # -- Data migration: backfill Team objects and copy old_team FK --
        migrations.RunPython(_backfill_teams_and_copy, _reverse_backfill),
    ]
