from _typeshed import Incomplete
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth2.provider import OAuth2Provider as OAuth2Provider

class ShopifyAccount(ProviderAccount): ...

class ShopifyProvider(OAuth2Provider):
    id: str
    name: str
    account_class = ShopifyAccount
    @property
    def is_per_user(self): ...
    def get_auth_params(self, request, action): ...
    def get_default_scope(self): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...

provider_classes: Incomplete
