from _typeshed import Incomplete

class AppSettings:
    class AuthenticationMethod:
        USERNAME: str
        EMAIL: str
        USERNAME_EMAIL: str
    class EmailVerificationMethod:
        MANDATORY: str
        OPTIONAL: str
        NONE: str
    prefix: Incomplete
    def __init__(self, prefix) -> None: ...
    @property
    def PREVENT_ENUMERATION(self): ...
    @property
    def DEFAULT_HTTP_PROTOCOL(self): ...
    @property
    def EMAIL_CONFIRMATION_EXPIRE_DAYS(self): ...
    @property
    def EMAIL_CONFIRMATION_AUTHENTICATED_REDIRECT_URL(self): ...
    @property
    def EMAIL_CONFIRMATION_ANONYMOUS_REDIRECT_URL(self): ...
    @property
    def EMAIL_CONFIRMATION_COOLDOWN(self): ...
    @property
    def EMAIL_REQUIRED(self): ...
    @property
    def EMAIL_VERIFICATION(self): ...
    @property
    def MAX_EMAIL_ADDRESSES(self): ...
    @property
    def AUTHENTICATION_METHOD(self): ...
    @property
    def EMAIL_MAX_LENGTH(self): ...
    @property
    def UNIQUE_EMAIL(self): ...
    @property
    def SIGNUP_EMAIL_ENTER_TWICE(self): ...
    @property
    def SIGNUP_PASSWORD_ENTER_TWICE(self): ...
    @property
    def SIGNUP_REDIRECT_URL(self): ...
    @property
    def PASSWORD_MIN_LENGTH(self): ...
    @property
    def RATE_LIMITS(self): ...
    @property
    def EMAIL_SUBJECT_PREFIX(self): ...
    @property
    def SIGNUP_FORM_CLASS(self): ...
    @property
    def USERNAME_REQUIRED(self): ...
    @property
    def USERNAME_MIN_LENGTH(self): ...
    @property
    def USERNAME_BLACKLIST(self): ...
    @property
    def PASSWORD_INPUT_RENDER_VALUE(self): ...
    @property
    def ADAPTER(self): ...
    @property
    def CONFIRM_EMAIL_ON_GET(self): ...
    @property
    def AUTHENTICATED_LOGIN_REDIRECTS(self): ...
    @property
    def LOGIN_ON_EMAIL_CONFIRMATION(self): ...
    @property
    def LOGIN_ON_PASSWORD_RESET(self): ...
    @property
    def LOGOUT_REDIRECT_URL(self): ...
    @property
    def LOGOUT_ON_GET(self): ...
    @property
    def LOGOUT_ON_PASSWORD_CHANGE(self): ...
    @property
    def USER_MODEL_USERNAME_FIELD(self): ...
    @property
    def USER_MODEL_EMAIL_FIELD(self): ...
    @property
    def SESSION_COOKIE_AGE(self): ...
    @property
    def SESSION_REMEMBER(self): ...
    @property
    def TEMPLATE_EXTENSION(self): ...
    @property
    def FORMS(self): ...
    @property
    def LOGIN_ATTEMPTS_LIMIT(self): ...
    @property
    def LOGIN_ATTEMPTS_TIMEOUT(self): ...
    @property
    def EMAIL_CONFIRMATION_HMAC(self): ...
    @property
    def SALT(self): ...
    @property
    def PRESERVE_USERNAME_CASING(self): ...
    @property
    def USERNAME_VALIDATORS(self): ...

app_settings: Incomplete
