"""Generate TypeScript permission consts from Django enums."""

from pathlib import Path

from common.permissions.utils import get_registered_permission_enums
from django.core.management.base import BaseCommand

HEADER = """\
// Auto-generated by `manage.py generate_permission_enums` — do not edit.
// Source: Django permission enums registered via @permission_enum or
// permissions_enum_from_model.

"""


class Command(BaseCommand):
    help = "Generate TypeScript permission consts from Django enums."

    def add_arguments(self, parser):
        parser.add_argument(
            "output",
            nargs="?",
            default="libs/ba-permissions/src/index.ts",
            help="Output path relative to repo root.",
        )

    def handle(self, *args, **options):
        repo_root = Path(__file__).resolve().parents[5]  # common/management/commands/ → repo root
        output_path = repo_root / options["output"]
        output_path.parent.mkdir(parents=True, exist_ok=True)

        enums = get_registered_permission_enums()
        if not enums:
            self.stderr.write("No registered permission enums found.")
            return

        lines = [HEADER]
        for enum_cls in sorted(enums, key=lambda e: e.__name__):
            name = enum_cls.__name__
            lines.append(f"export const {name} = {{")
            for member in enum_cls:
                lines.append(f"  {member.name}: '{member.value}',")
            lines.append("} as const;\n")

        union_members = " | ".join(
            f"typeof {e.__name__}[keyof typeof {e.__name__}]" for e in enums
        )
        lines.append(f"export type PermissionEnum = {union_members};\n")

        output_path.write_text("\n".join(lines) + "\n")
        self.stdout.write(
            self.style.SUCCESS(f"Wrote {len(enums)} permission enums to {output_path}")
        )
