from .util import read_body as read_body
from _typeshed import Incomplete

log: Incomplete

def method(r1, r2) -> None: ...
def uri(r1, r2) -> None: ...
def host(r1, r2) -> None: ...
def scheme(r1, r2) -> None: ...
def port(r1, r2) -> None: ...
def path(r1, r2) -> None: ...
def query(r1, r2) -> None: ...
def raw_body(r1, r2) -> None: ...
def body(r1, r2) -> None: ...
def headers(r1, r2) -> None: ...
def requests_match(r1, r2, matchers): ...
def get_matchers_results(r1, r2, matchers): ...
def get_assertion_message(assertion_details): ...
