from . import request as request
from .serialize import serialize as serialize
from .serializers import jsonserializer as jsonserializer, yamlserializer as yamlserializer
from .stubs.compat import get_httpmessage as get_httpmessage
from _typeshed import Incomplete

def preprocess_yaml(cassette): ...

PARTS: Incomplete

def build_uri(**parts): ...
def migrate_json(in_fp, out_fp): ...
def migrate_yml(in_fp, out_fp): ...
def migrate(file_path, migration_fn): ...
def try_migrate(path): ...
def main() -> None: ...
