from .stubs import VCRHTTPConnection as VCRHTTPConnection, VCRHTTPSConnection as VCRHTTPSConnection
from _typeshed import Incomplete
from collections.abc import Generator

log: Incomplete
cpool: Incomplete
conn: Incomplete

class CassettePatcherBuilder:
    def __init__(self, cassette) -> None: ...
    def build(self): ...

class ConnectionRemover:
    def __init__(self, connection_class) -> None: ...
    def add_connection_to_pool_entry(self, pool, connection) -> None: ...
    def remove_connection_to_pool_entry(self, pool, connection) -> None: ...
    def __enter__(self): ...
    def __exit__(self, *args) -> None: ...

def reset_patchers() -> Generator[Incomplete, None, None]: ...
def force_reset() -> Generator[None, None, None]: ...
