from .util import CaseInsensitiveDict as CaseInsensitiveDict
from _typeshed import Incomplete

log: Incomplete

class Request:
    method: Incomplete
    uri: Incomplete
    def __init__(self, method, uri, body, headers) -> None: ...
    @property
    def headers(self): ...
    @property
    def body(self): ...
    def add_header(self, key, value) -> None: ...
    @property
    def scheme(self): ...
    @property
    def host(self): ...
    @property
    def port(self): ...
    @property
    def path(self): ...
    @property
    def query(self): ...
    @property
    def url(self): ...
    @property
    def protocol(self): ...

class HeadersDict(CaseInsensitiveDict):
    def __setitem__(self, key, value) -> None: ...
