"""
This type stub file was generated by pyright.
"""

from collections.abc import MutableMapping

"""Docker-style file variable support module."""

class FileAwareMapping(MutableMapping):

    """
    A mapping that wraps os.environ, first checking for the existence of a key
    appended with ``_FILE`` whenever reading a value. If a matching file key is
    found then the value is instead read from the file system at this location.

    By default, values read from the file system are cached so future lookups
    do not hit the disk again.

    A ``_FILE`` key has higher precedence than a value is set directly in the
    environment, and an exception is raised if the file can not be found.
    """

    def __init__(self, env=..., cache=...) -> None:
        """
        Initialize the mapping.

        :param env:
            where to read environment variables from (defaults to
            ``os.environ``)
        :param cache:
            cache environment variables read from the file system (defaults to
            ``True``)
        """
        ...
    def __getitem__(self, key): ...
    def __iter__(self):  # -> Generator[Unknown | str, Any, None]:
        """
        Iterate all keys, also always including the shortened key if ``_FILE``
        keys are found.
        """
        ...
    def __len__(self):  # -> int:
        """
        Return the length of the file, also always counting shortened keys for
        any ``_FILE`` key found.
        """
        ...
    def __setitem__(self, key, value): ...
    def __delitem__(self, key): ...
