from _typeshed import Incomplete
from django.db import models
from django.db.models import QuerySet
from simple_history.utils import get_app_model_primary_key_name as get_app_model_primary_key_name, get_change_reason_from_object as get_change_reason_from_object

SIMPLE_HISTORY_REVERSE_ATTR_NAME: str

class HistoricalQuerySet(QuerySet):
    def __init__(self, *args, **kwargs) -> None: ...
    def as_instances(self): ...
    def filter(self, *args, **kwargs): ...
    def latest_of_each(self): ...

class HistoryDescriptor:
    model: Incomplete
    def __init__(self, model) -> None: ...
    def __get__(self, instance, owner): ...

class HistoryManager(models.Manager):
    model: Incomplete
    instance: Incomplete
    def __init__(self, model, instance: Incomplete | None = ...) -> None: ...
    def get_super_queryset(self): ...
    def get_queryset(self): ...
    def most_recent(self): ...
    def as_of(self, date): ...
    def bulk_history_create(self, objs, batch_size: Incomplete | None = ..., update: bool = ..., default_user: Incomplete | None = ..., default_change_reason: str = ..., default_date: Incomplete | None = ...): ...
