from _typeshed import Incomplete

pre_create_historical_record: Incomplete
post_create_historical_record: Incomplete
pre_create_historical_m2m_records: Incomplete
post_create_historical_m2m_records: Incomplete
