# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.db.models.deletion
import django.utils.timezone
import django_choices_field.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    replaces = []
    dependencies = [
        ('clients', '0002_initial'),
        ('common', '0001_initial'),
        ('organizations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NoteDataImport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
                ('source_file', models.CharField(max_length=255)),
                ('notes', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='NoteEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interacted_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_submitted', models.BooleanField(default=False)),
                ('private_details', models.TextField(blank=True)),
                ('public_details', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('old_team', django_choices_field.fields.TextChoicesField(blank=True, choices=[('bowtie_riverside_outreach', 'Bowtie & Riverside Outreach'), ('echo_park_on_site', 'Echo Park On-site'), ('echo_park_outreach', 'Echo Park Outreach'), ('hollywood_on_site', 'Hollywood On-site'), ('hollywood_outreach', 'Hollywood Outreach'), ('la_river_outreach', 'LA River Outreach'), ('los_feliz_outreach', 'Los Feliz Outreach'), ('northeast_hollywood_outreach', 'Northeast Hollywood Outreach'), ('selah_staff', 'SELAH Staff'), ('silver_lake_outreach', 'Silver Lake Outreach'), ('slcc_on_site', 'SLCC On-site'), ('sunday_social_atwater_on_site', 'Sunday Social / Atwater On-site'), ('sunday_social_atwater_outreach', 'Sunday Social / Atwater Outreach'), ('wdi_on_site', 'WDI On-site'), ('wdi_outreach', 'WDI Outreach')], max_length=30, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteImportRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.CharField(max_length=255)),
                ('source_name', models.CharField(max_length=255)),
                ('raw_data', models.JSONField()),
                ('success', models.BooleanField(default=False)),
                ('error_message', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='NoteProvidedServicesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteRequestedServicesEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NoteUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Service Categories',
                'ordering': ('priority',),
            },
        ),
        migrations.CreateModel(
            name='OrganizationServiceCategoryEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrganizationServiceEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('label', models.CharField(max_length=100)),
                ('priority', models.PositiveIntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('completed', 'Completed'), ('to_do', 'To Do')], max_length=9)),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestEvent',
            fields=[
                ('pgh_id', models.AutoField(primary_key=True, serialize=False)),
                ('pgh_created_at', models.DateTimeField(auto_now_add=True)),
                ('pgh_label', models.TextField(help_text='The event label.')),
                ('id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', django_choices_field.fields.TextChoicesField(choices=[('completed', 'Completed'), ('to_do', 'To Do')], max_length=9)),
                ('due_by', models.DateTimeField(blank=True, null=True)),
                ('completed_on', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestGroupObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceRequestUserObjectPermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('interacted_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('is_submitted', models.BooleanField(default=False)),
                ('private_details', models.TextField(blank=True)),
                ('public_details', models.TextField(blank=True)),
                ('purpose', models.CharField(blank=True, max_length=100, null=True)),
                ('old_team', django_choices_field.fields.TextChoicesField(blank=True, choices=[('bowtie_riverside_outreach', 'Bowtie & Riverside Outreach'), ('echo_park_on_site', 'Echo Park On-site'), ('echo_park_outreach', 'Echo Park Outreach'), ('hollywood_on_site', 'Hollywood On-site'), ('hollywood_outreach', 'Hollywood Outreach'), ('la_river_outreach', 'LA River Outreach'), ('los_feliz_outreach', 'Los Feliz Outreach'), ('northeast_hollywood_outreach', 'Northeast Hollywood Outreach'), ('selah_staff', 'SELAH Staff'), ('silver_lake_outreach', 'Silver Lake Outreach'), ('slcc_on_site', 'SLCC On-site'), ('sunday_social_atwater_on_site', 'Sunday Social / Atwater On-site'), ('sunday_social_atwater_outreach', 'Sunday Social / Atwater Outreach'), ('wdi_on_site', 'WDI On-site'), ('wdi_outreach', 'WDI Outreach')], db_index=True, max_length=30, null=True)),
                ('client_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile_notes', to='clients.clientprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notes', to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='notes', to='common.location')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organizations.organization')),
            ],
            options={
                'ordering': ['-interacted_at'],
                'permissions': (('view_note_private_details', 'Can view note private details'),),
            },
        ),
    ]
