# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    replaces = [
        ("notes", "0002_remove_note_note_add_insert_and_more"),
        ("notes", "0003_remove_note_note_add_insert_and_more"),
        ("notes", "0004_alter_note_interacted_at"),
        ("notes", "0005_servicerequest_service_request_update_update_and_more"),
        ("notes", "0006_fix_caseworker_template_servicerequest_permissions"),
        ("notes", "0007_alter_note_options_alter_servicerequest_options_and_more"),
        ("notes", "0008_alter_moodevent_id_alter_noteevent_id_and_more"),
        ("notes", "0009_remove_note_note_add_insert_and_more"),
        ("notes", "0010_alter_note_title_alter_noteevent_title"),
        ("notes", "0011_remove_servicerequest_service_request_add_insert_and_more"),
        ("notes", "0012_alter_note_purpose_alter_noteevent_purpose"),
        ("notes", "0013_add_note_team"),
        ("notes", "0014_notedataimport_noteimportrecord_and_more"),
        ("notes", "0015_add_client_profile_field"),
        ("notes", "0016_note_client_profile_data"),
        ("notes", "0017_remove_note_note_add_insert_and_more"),
        ("notes", "0018_delete_task_permissions"),
        ("notes", "0019_remove_notenextstepsevent_note_and_more"),
        ("notes", "0020_remove_note_next_steps_remove_note_purposes_and_more"),
        ("notes", "0021_organizationservicecategory_organizationservice_and_more"),
        ("notes", "0022_seed_services"),
        ("notes", "0023_add_service_enum_field"),
        ("notes", "0024_copy_service_to_service_enum"),
        ("notes", "0025_servicerequest_service_use_fk"),
        ("notes", "0026_rename_service_to_label"),
        ("notes", "0027_data_copy_service_enum_to_service"),
        ("notes", "0028_alter_organizationservicecategory_options"),
        ("notes", "0029_remove_servicerequest_enum_fields"),
        ("notes", "0030_remove_mood_model"),
        ("notes", "0031_alter_note_location"),
        ("notes", "0032_remove_note_note_add_insert_and_more"),
        ("notes", "0033_alter_note_team_alter_noteevent_team_and_more"),
    ]

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('clients', '0002_initial'),
        ('common', '0001_initial'),
        ('notes', '0001_initial'),
        ('organizations', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('teams', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='team',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='teams.team'),
        ),
        migrations.AddField(
            model_name='notedataimport',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='client_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='created_by',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='location',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='common.location'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notes.note'),
        ),
        migrations.AddField(
            model_name='noteevent',
            name='team',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='teams.team'),
        ),
        migrations.AddField(
            model_name='notegroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AddField(
            model_name='notegroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='notegroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='noteimportrecord',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='notes.notedataimport'),
        ),
        migrations.AddField(
            model_name='noteimportrecord',
            name='note',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.note'),
        ),
        migrations.AddField(
            model_name='noteprovidedservicesevent',
            name='note',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.note'),
        ),
        migrations.AddField(
            model_name='noteprovidedservicesevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='noterequestedservicesevent',
            name='note',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.note'),
        ),
        migrations.AddField(
            model_name='noterequestedservicesevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='noteuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.note'),
        ),
        migrations.AddField(
            model_name='noteuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='noteuserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationservicecategory',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationservice',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='services', to='notes.organizationservicecategory'),
        ),
        migrations.AddField(
            model_name='organizationservicecategoryevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationservicecategoryevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='organizationservicecategoryevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notes.organizationservicecategory'),
        ),
        migrations.AddField(
            model_name='organizationserviceevent',
            name='category',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.organizationservicecategory'),
        ),
        migrations.AddField(
            model_name='organizationserviceevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='organizationserviceevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='organizationserviceevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notes.organizationservice'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client_profile_service_requests', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_requests', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequest',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='service_requests', to='notes.organizationservice'),
        ),
        migrations.AddField(
            model_name='noterequestedservicesevent',
            name='servicerequest',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='noteprovidedservicesevent',
            name='servicerequest',
            field=models.ForeignKey(db_constraint=False, db_tablespace='', on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='note',
            name='provided_services',
            field=models.ManyToManyField(blank=True, related_name='provided_notes', to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='note',
            name='requested_services',
            field=models.ManyToManyField(blank=True, related_name='requested_notes', to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='client_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestevent',
            name='service',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='notes.organizationservice'),
        ),
        migrations.AddField(
            model_name='servicerequestgroupobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestgroupobjectpermission',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.group'),
        ),
        migrations.AddField(
            model_name='servicerequestgroupobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='servicerequestuserobjectpermission',
            name='content_object',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notes.servicerequest'),
        ),
        migrations.AddField(
            model_name='servicerequestuserobjectpermission',
            name='permission',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='auth.permission'),
        ),
        migrations.AddField(
            model_name='servicerequestuserobjectpermission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='notegroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
        migrations.AddIndex(
            model_name='noteimportrecord',
            index=models.Index(fields=['import_job', 'success', 'source_name', 'source_id'], name='notes_notei_import__56a0cc_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='noteuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        migrations.AddConstraint(
            model_name='organizationservicecategory',
            constraint=models.UniqueConstraint(models.F('name'), models.F('organization'), name='unique_name_org'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservicecategory',
            trigger=pgtrigger.compiler.Trigger(name='org_service_category_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_organizationservicecategoryevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'org_service_category.add\', NEW."id", NEW."priority", NEW."updated_at"); RETURN NULL;', hash='9a66af6627eba798f0a7ec14e2b5e92d80d91931', operation='INSERT', pgid='pgtrigger_org_service_category_add_insert_8b251', table='notes_organizationservicecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservicecategory',
            trigger=pgtrigger.compiler.Trigger(name='org_service_category_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notes_organizationservicecategoryevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (NEW."created_at", NEW."id", NEW."name", NEW."organization_id", _pgh_attach_context(), NOW(), \'org_service_category.update\', NEW."id", NEW."priority", NEW."updated_at"); RETURN NULL;', hash='5afeb4e49528d6193fc6e89b2d3a3b72c702825f', operation='UPDATE', pgid='pgtrigger_org_service_category_update_update_e8440', table='notes_organizationservicecategory', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservicecategory',
            trigger=pgtrigger.compiler.Trigger(name='org_service_category_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_organizationservicecategoryevent" ("created_at", "id", "name", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (OLD."created_at", OLD."id", OLD."name", OLD."organization_id", _pgh_attach_context(), NOW(), \'org_service_category.remove\', OLD."id", OLD."priority", OLD."updated_at"); RETURN NULL;', hash='7304823a3a0d8ad6852e9a8e47895b088d951543', operation='DELETE', pgid='pgtrigger_org_service_category_remove_delete_aaac1', table='notes_organizationservicecategory', when='AFTER')),
        ),
        migrations.AddConstraint(
            model_name='organizationservice',
            constraint=models.UniqueConstraint(models.F('label'), models.F('organization'), name='unique_label_org'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservice',
            trigger=pgtrigger.compiler.Trigger(name='org_service_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_organizationserviceevent" ("category_id", "created_at", "id", "label", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (NEW."category_id", NEW."created_at", NEW."id", NEW."label", NEW."organization_id", _pgh_attach_context(), NOW(), \'org_service.add\', NEW."id", NEW."priority", NEW."updated_at"); RETURN NULL;', hash='064e642b6374f88cbc00928007912d1ec8c3c3c2', operation='INSERT', pgid='pgtrigger_org_service_add_insert_aa515', table='notes_organizationservice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservice',
            trigger=pgtrigger.compiler.Trigger(name='org_service_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notes_organizationserviceevent" ("category_id", "created_at", "id", "label", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (NEW."category_id", NEW."created_at", NEW."id", NEW."label", NEW."organization_id", _pgh_attach_context(), NOW(), \'org_service.update\', NEW."id", NEW."priority", NEW."updated_at"); RETURN NULL;', hash='ec28cd95966e192b1385c009290861dd33520be3', operation='UPDATE', pgid='pgtrigger_org_service_update_update_f2016', table='notes_organizationservice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='organizationservice',
            trigger=pgtrigger.compiler.Trigger(name='org_service_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_organizationserviceevent" ("category_id", "created_at", "id", "label", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "priority", "updated_at") VALUES (OLD."category_id", OLD."created_at", OLD."id", OLD."label", OLD."organization_id", _pgh_attach_context(), NOW(), \'org_service.remove\', OLD."id", OLD."priority", OLD."updated_at"); RETURN NULL;', hash='449318344ae8eb1100823d4c8257e02355c604bc', operation='DELETE', pgid='pgtrigger_org_service_remove_delete_14722', table='notes_organizationservice', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicerequest',
            trigger=pgtrigger.compiler.Trigger(name='service_request_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."completed_on", NEW."created_at", NEW."created_by_id", NEW."due_by", NEW."id", _pgh_attach_context(), NOW(), \'service_request.add\', NEW."id", NEW."service_id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='f078af1b4d1fd52db21b265a8060e983d04ef7fe', operation='INSERT', pgid='pgtrigger_service_request_add_insert_f5d42', table='notes_servicerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicerequest',
            trigger=pgtrigger.compiler.Trigger(name='service_request_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."completed_on", NEW."created_at", NEW."created_by_id", NEW."due_by", NEW."id", _pgh_attach_context(), NOW(), \'service_request.update\', NEW."id", NEW."service_id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='30ef56e625bccdce84e55522f247b3f0d2ea1c35', operation='UPDATE', pgid='pgtrigger_service_request_update_update_261d7', table='notes_servicerequest', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='servicerequest',
            trigger=pgtrigger.compiler.Trigger(name='service_request_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service_id", "status", "updated_at") VALUES (OLD."client_profile_id", OLD."completed_on", OLD."created_at", OLD."created_by_id", OLD."due_by", OLD."id", _pgh_attach_context(), NOW(), \'service_request.remove\', OLD."id", OLD."service_id", OLD."status", OLD."updated_at"); RETURN NULL;', hash='1cd77b29b875060e55140c4e63489e627b5c6bfb', operation='DELETE', pgid='pgtrigger_service_request_remove_delete_53389', table='notes_servicerequest', when='AFTER')),
        ),
        migrations.CreateModel(
            name='NoteProvidedServices',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notes.note_provided_services',),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.add\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='b43d6d3cb1a7a83e1fce2ed1edd446a72b879bd9', operation='INSERT', pgid='pgtrigger_note_add_insert_e05e6', table='notes_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."old_team", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.update\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='b4861552278f13a73588ba09fb05b35400c16132', operation='UPDATE', pgid='pgtrigger_note_update_update_ac81f', table='notes_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "old_team", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."id", OLD."interacted_at", OLD."is_submitted", OLD."location_id", OLD."old_team", OLD."organization_id", _pgh_attach_context(), NOW(), \'note.remove\', OLD."id", OLD."private_details", OLD."public_details", OLD."purpose", OLD."team_id", OLD."updated_at"); RETURN NULL;', hash='e66f2b4a8c5262df00ee85be082ef2188ed0986f', operation='DELETE', pgid='pgtrigger_note_remove_delete_dd722', table='notes_note', when='AFTER')),
        ),
        migrations.CreateModel(
            name='NoteRequestedServices',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('notes.note_requested_services',),
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestgroupobjectpermission',
            unique_together={('group', 'permission', 'content_object')},
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestuserobjectpermission',
            unique_together={('user', 'permission', 'content_object')},
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noteprovidedservices',
            trigger=pgtrigger.compiler.Trigger(name='note_provided_services_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteprovidedservicesevent" ("id", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "servicerequest_id") VALUES (NEW."id", NEW."note_id", _pgh_attach_context(), NOW(), \'note_provided_services.add\', NEW."servicerequest_id"); RETURN NULL;', hash='609d058ed697cb14e6dd519cde60c15fd968e138', operation='INSERT', pgid='pgtrigger_note_provided_services_add_insert_c8860', table='notes_note_provided_services', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noteprovidedservices',
            trigger=pgtrigger.compiler.Trigger(name='note_provided_services_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteprovidedservicesevent" ("id", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "servicerequest_id") VALUES (OLD."id", OLD."note_id", _pgh_attach_context(), NOW(), \'note_provided_services.remove\', OLD."servicerequest_id"); RETURN NULL;', hash='1c4d44d2790dac31828a1ae933628adc05747275', operation='DELETE', pgid='pgtrigger_note_provided_services_remove_delete_46d32', table='notes_note_provided_services', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noterequestedservices',
            trigger=pgtrigger.compiler.Trigger(name='note_requested_services_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noterequestedservicesevent" ("id", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "servicerequest_id") VALUES (NEW."id", NEW."note_id", _pgh_attach_context(), NOW(), \'note_requested_services.add\', NEW."servicerequest_id"); RETURN NULL;', hash='42724de35837c902d807e71a5561dcc75f793acb', operation='INSERT', pgid='pgtrigger_note_requested_services_add_insert_54897', table='notes_note_requested_services', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='noterequestedservices',
            trigger=pgtrigger.compiler.Trigger(name='note_requested_services_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noterequestedservicesevent" ("id", "note_id", "pgh_context_id", "pgh_created_at", "pgh_label", "servicerequest_id") VALUES (OLD."id", OLD."note_id", _pgh_attach_context(), NOW(), \'note_requested_services.remove\', OLD."servicerequest_id"); RETURN NULL;', hash='2001696ad18650cee44f5a8d45d24d9d0df42bec', operation='DELETE', pgid='pgtrigger_note_requested_services_remove_delete_1a764', table='notes_note_requested_services', when='AFTER')),
        ),
    ]
