# Generated by Django 6.0.6 on 2026-08-13 16:12

import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_initial'),
        # Must run after the backfill in teams.0002, which reads old_team.
        ('teams', '0001_initial'),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='note_add_insert',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='note_update_update',
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name='note',
            name='note_remove_delete',
        ),
        migrations.RemoveField(
            model_name='note',
            name='old_team',
        ),
        migrations.RemoveField(
            model_name='noteevent',
            name='old_team',
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.add\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='de46651001be754f65fe1059f55e71b77cbf8bc0', operation='INSERT', pgid='pgtrigger_note_add_insert_e05e6', table='notes_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.update\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;', hash='64274b33e7a107270b4e0f0f193f5c3f970d4c10', operation='UPDATE', pgid='pgtrigger_note_update_update_ac81f', table='notes_note', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='note',
            trigger=pgtrigger.compiler.Trigger(name='note_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."id", OLD."interacted_at", OLD."is_submitted", OLD."location_id", OLD."organization_id", _pgh_attach_context(), NOW(), \'note.remove\', OLD."id", OLD."private_details", OLD."public_details", OLD."purpose", OLD."team_id", OLD."updated_at"); RETURN NULL;', hash='40ebc9f82add010f91b0e884991006942fba547b', operation='DELETE', pgid='pgtrigger_note_remove_delete_dd722', table='notes_note', when='AFTER')),
        ),
    ]
