# Generated by Django 4.2.9 on 2024-01-30 02:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0002_noteuserobjectpermission_notegroupobjectpermission"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notegroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="group_object_permissions",
                to="notes.note",
            ),
        ),
        migrations.AlterField(
            model_name="noteuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_object_permissions",
                to="notes.note",
            ),
        ),
    ]
