# Generated by Django 4.2.9 on 2024-02-06 21:00

from django.db import migrations


MOODS = [
    "Agitated",
    "Agreeable",
    "Anxious",
    "Depressed",
    "Detached",
    "Disorganized Thought",
    "Disoriented",
    "Escalated",
    "Euthymic",
    "Flat/blunted",
    "Happy",
    "Hopeless",
    "Indifferent",
    "Manic",
    "Motivated",
    "Optimistic",
    "Personable",
    "Pleasant",
    "Restless",
    "Suicidal",
]

SERVICES = [
    "Blanket",
    "Book",
    "Clothes",
    "Dental",
    "Food",
    "Harm Reduction",
    "Hygiene Kit",
    "Medical",
    "Pet Care",
    "Pet Food",
    "Shelter",
    "Shoes",
    "Shower",
    "Stabilize",
    "Storage",
    "Transport",
    "Water",
    "Other",
]


def seed_moods(apps, schema_editor):
    Mood = apps.get_model("notes", "Mood")
    mood_instances = [Mood(title=mood_title) for mood_title in MOODS]

    Mood.objects.bulk_create(mood_instances)


def reverse_seed_moods(apps, schema_editor):
    Mood = apps.get_model("notes", "Mood")
    Mood.objects.filter(title__in=MOODS).delete()


def seed_services(apps, schema_editor):
    Service = apps.get_model("notes", "Service")
    service_instances = [Service(title=service_title) for service_title in SERVICES]

    Service.objects.bulk_create(service_instances)


def reverse_seed_services(apps, schema_editor):
    Service = apps.get_model("notes", "Service")
    Service.objects.filter(title__in=SERVICES).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_add_note_component_models"),
    ]

    operations = [
        migrations.RunPython(seed_moods, reverse_seed_moods),
        migrations.RunPython(seed_services, reverse_seed_services),
    ]
