# Generated by Django 4.2.9 on 2024-02-06 21:00

from django.db import migrations


moods = [
    "Agitated",
    "Agreeable",
    "Anxious",
    "Depressed",
    "Detached",
    "Disorganized Thought",
    "Disoriented",
    "Escalated",
    "Euthymic",
    "Flat/blunted",
    "Happy",
    "Hopeless",
    "Indifferent",
    "Manic",
    "Motivated",
    "Optimistic",
    "Personable",
    "Pleasant",
    "Restless",
    "Suicidal",
]


def seed_moods(apps, schema_editor):
    Mood = apps.get_model("notes", "Mood")
    mood_instances = [Mood(title=mood_name) for mood_name in moods]

    Mood.objects.bulk_create(mood_instances)


def reverse_seed_moods(apps, schema_editor):
    Mood = apps.get_model("notes", "Mood")
    Mood.objects.filter(title__in=moods).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_add_note_component_models"),
    ]

    operations = [
        migrations.RunPython(seed_moods, reverse_seed_moods),
    ]
