# Generated by Django 4.2.9 on 2024-02-02 04:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_add_casemanager_note_permissions"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="created_by",
        ),
        migrations.AddField(
            model_name="note",
            name="deleted_at",
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
