# Generated by Django 4.2.9 on 2024-02-02 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0003_location_mood_service_remove_note_body_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="notes.location",
            ),
        ),
    ]
