# Generated by Django 4.2.9 on 2024-02-08 22:59

from django.db import migrations, models
import django.db.models.deletion


def create_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    caseworker_template = PermissionGroupTemplate.objects.create(name="Caseworker")

    perm_map = [
        perm.split(".")[1]
        for perm in [
            "notes.view_note",
            "notes.change_note",
            "notes.delete_note",
            "notes.add_note",
        ]
    ]

    permission = Permission.objects.filter(codename__in=perm_map)
    caseworker_template.permissions.set(permission)


def delete_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    PermissionGroupTemplate.objects.get("Caseworker")


def delete_old_caseworker_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    caseworker_group = Group.objects.get(name="Caseworker")
    caseworker_group.delete()


def delete_all_notes(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    Note.objects.all().delete()


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("notes", "0003_add_casemanager_note_permissions"),
    ]

    operations = [
        migrations.RunPython(delete_old_caseworker_group),
        migrations.RunPython(delete_all_notes),
        migrations.RunPython(
            create_caseworker_permission_template, delete_caseworker_permission_template
        ),
        migrations.AlterModelOptions(
            name="note",
            options={
                "permissions": (
                    ("view_private_note", "Can add private note"),
                    ("change_private_note", "Can change private note"),
                    ("delete_private_note", "Can delete private note"),
                    ("add_private_note", "Can view private note"),
                )
            },
        ),
        migrations.AddField(
            model_name="note",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="organizations.organization",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="notegroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.note"
            ),
        ),
        migrations.AlterField(
            model_name="noteuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="notes.note"
            ),
        ),
    ]
