# Generated by Django 4.2.9 on 2024-02-06 21:00

from django.db import migrations


services = [
    "Blanket",
    "Book",
    "Clothes",
    "Dental",
    "Food",
    "Harm Reduction",
    "Hygiene Kit",
    "Medical",
    "Pet Care",
    "Pet Food",
    "Shelter",
    "Shoes",
    "Shower",
    "Stabilize",
    "Storage",
    "Transport",
    "Water",
    "Other",
]


def seed_services(apps, schema_editor):
    Service = apps.get_model("notes", "Service")
    service_instances = [Service(title=service_name) for service_name in services]

    Service.objects.bulk_create(service_instances)


def reverse_seed_services(apps, schema_editor):
    Service = apps.get_model("notes", "Service")
    Service.objects.filter(title__in=services).delete()


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_seed_moods"),
    ]

    operations = [
        migrations.RunPython(seed_services, reverse_seed_services),
    ]
