# Generated by Django 6.1 on 2026-10-08 02:36

from django.db import migrations


class Migration(migrations.Migration):
    """Drop the per-model guardian permission tables (ADR 0001 §2.5, step 5).

    These were Django-guardian's per-model ``UserObjectPermission`` /
    ``GroupObjectPermission`` subclasses.  They have never held data under the
    current configuration: ``GUARDIAN_USER_OBJ_PERMS_MODEL`` and
    ``GUARDIAN_GROUP_OBJ_PERMS_MODEL`` route *every* guardian write to
    ``accounts.BigUserObjectPermission`` / ``BigGroupObjectPermission``, which is
    why nothing in the codebase references these models.  The grant model is now
    the only authority, and Attachment is SHARED-tier with no per-record
    permissions at all (docs/adr/0005-client-document-authority.md).
    """

    dependencies = [
        ('notes', '0004_alter_note_team'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='noteuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='noteuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='noteuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='noteuserobjectpermission',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestgroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicerequestgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='servicerequestgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='servicerequestgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='servicerequestuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='servicerequestuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='servicerequestuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='servicerequestuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='NoteGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='NoteUserObjectPermission',
        ),
        migrations.DeleteModel(
            name='ServiceRequestGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='ServiceRequestUserObjectPermission',
        ),
    ]
