# Generated by Django 4.2.9 on 2024-02-04 02:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0004_alter_note_location"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="child_tasks",
        ),
        migrations.RemoveField(
            model_name="task",
            name="parent_tasks",
        ),
        migrations.AddField(
            model_name="note",
            name="child_tasks",
            field=models.ManyToManyField(
                related_name="notes_next_task", to="notes.task"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="parent_tasks",
            field=models.ManyToManyField(related_name="notes_created", to="notes.task"),
        ),
    ]
