# Generated by Django 5.0.6 on 2024-06-17 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_servicerequest_service_request_update_update_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="task",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="taskevent",
            name="title",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
