# Generated by Django 4.2.9 on 2024-02-06 21:10

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_note_organization_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="note",
            options={
                "permissions": (
                    ("notes.add_note", "Can add note"),
                    ("notes.change_note", "Can change note"),
                    ("notes.delete_note", "Can delete note"),
                    ("notes.view_note", "Can view note"),
                    ("notes.add_private_note", "Can add private note"),
                    ("notes.change_private_note", "Can change private note"),
                    ("notes.delete_private_note", "Can delete private note"),
                    ("notes.view_private_note", "Can view private note"),
                )
            },
        ),
    ]
