# Generated by Django 4.2.9 on 2024-02-04 02:53

from django.db import migrations, models
import notes.enums


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0005_remove_note_tasks_remove_task_child_tasks_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="status",
            field=models.CharField(
                choices=[
                    (notes.enums.TaskStatusEnum["IN_PROGRESS"], "In Progress"),
                    (notes.enums.TaskStatusEnum["COMPLETED"], "Completed"),
                    (notes.enums.TaskStatusEnum["CANCELED"], "Cancel"),
                ],
                default=notes.enums.TaskStatusEnum["IN_PROGRESS"],
            ),
        ),
    ]
