# Generated by Django 5.0.6 on 2024-06-19 19:18

from django.db import migrations


def update_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    caseworker_template = PermissionGroupTemplate.objects.get(name="Caseworker")

    permission_to_add = Permission.objects.get(codename="add_servicerequest")
    # This migration is fixing a typo left in by a bad squash. Using .filter() here
    # because this permission only exists in the live db, not in local dev
    permission_to_remove = Permission.objects.filter(codename="add_service_request").first()

    caseworker_template.permissions.add(permission_to_add)
    caseworker_template.permissions.remove(permission_to_remove)


def delete_old_permission(apps, schema_editor):
    Permission = apps.get_model("auth", "Permission")
    Permission.objects.filter(codename="add_service_request").delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0005_servicerequest_service_request_update_update_and_more"),
    ]

    operations = [
        migrations.RunPython(update_caseworker_permission_template),
        migrations.RunPython(delete_old_permission),
    ]
