# Generated by Django 4.2.9 on 2024-02-20 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0007_add_private_note_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="historicalnote",
            name="private_details_source_perm",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="note",
            name="private_details_source_perm",
            field=models.TextField(null=True),
        ),
    ]
