# Generated by Django 4.2.10 on 2024-03-04 05:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0002_location"),
        ("tasks", "0001_initial"),
        ("notes", "0007_add_private_note_permissions"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="child_tasks",
            field=models.ManyToManyField(
                related_name="notes_next_task", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="parent_tasks",
            field=models.ManyToManyField(related_name="notes_created", to="tasks.task"),
        ),
        migrations.AlterField(
            model_name="historicalnote",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.location",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="common.location",
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
