# Generated by Django 4.2.11 on 2024-03-05 06:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_add_task"),
        ("notes", "0008_move_location_to_common"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="purposes",
            field=models.ManyToManyField(to="tasks.task"),
        ),
    ]
