# Generated by Django 4.2.10 on 2024-03-04 17:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_historicalnote_history_relation_alter_mood_note_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnote",
            name="location",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="common.location",
            ),
        ),
        migrations.AlterField(
            model_name="note",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="notes",
                to="common.location",
            ),
        ),
        migrations.DeleteModel(
            name="Location",
        ),
    ]
