# Generated by Django 4.2.9 on 2024-02-20 17:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0008_historicalnote_private_details_source_perm_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="historicalnote",
            name="private_details_source_perm",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="note",
            name="private_details_source_perm",
            field=models.TextField(blank=True, null=True),
        ),
    ]
