# Generated by Django 4.2.11 on 2024-03-05 08:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_add_task"),
        ("notes", "0008_move_location_to_common"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="next_steps",
            field=models.ManyToManyField(
                related_name="next_step_notes", to="tasks.task"
            ),
        ),
        migrations.AddField(
            model_name="note",
            name="purposes",
            field=models.ManyToManyField(related_name="purpose_notes", to="tasks.task"),
        ),
    ]
