# Generated by Django 4.2.10 on 2024-02-20 20:11

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0009_alter_historicalnote_private_details_source_perm_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="privatenotedetailgroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="privatenotedetailgroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="privatenotedetailgroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="privatenotedetailgroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="privatenotedetailuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="privatenotedetailuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="privatenotedetailuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="privatenotedetailuserobjectpermission",
            name="user",
        ),
        migrations.RenameField(
            model_name="historicalnote",
            old_name="private_details_source_perm",
            new_name="private_details",
        ),
        migrations.RenameField(
            model_name="note",
            old_name="private_details_source_perm",
            new_name="private_details",
        ),
        migrations.DeleteModel(
            name="PrivateNoteDetail",
        ),
        migrations.DeleteModel(
            name="PrivateNoteDetailGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="PrivateNoteDetailUserObjectPermission",
        ),
    ]
