# Generated by Django 5.1.3 on 2024-11-22 17:52

import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_add_note_team"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="notenextstepsevent",
            name="note",
        ),
        migrations.RemoveField(
            model_name="notenextstepsevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="notenextstepsevent",
            name="task",
        ),
        migrations.RemoveField(
            model_name="notepurposesevent",
            name="note",
        ),
        migrations.RemoveField(
            model_name="notepurposesevent",
            name="pgh_context",
        ),
        migrations.RemoveField(
            model_name="notepurposesevent",
            name="task",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notenextsteps",
            name="note_next_steps_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notenextsteps",
            name="note_next_steps_remove_delete",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notepurposes",
            name="note_purposes_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="notepurposes",
            name="note_purposes_remove_delete",
        ),
        migrations.DeleteModel(
            name="NoteNextSteps",
        ),
        migrations.DeleteModel(
            name="NotePurposes",
        ),
        migrations.RemoveField(
            model_name="note",
            name="next_steps",
        ),
        migrations.RemoveField(
            model_name="note",
            name="purposes",
        ),
        migrations.DeleteModel(
            name="NoteNextStepsEvent",
        ),
        migrations.DeleteModel(
            name="NotePurposesEvent",
        ),
    ]
