# Generated by Django 5.1.2 on 2024-10-14 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_phonenumber"),
        ("notes", "0013_add_note_team"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="client_documents",
            field=models.ManyToManyField(blank=True, related_name="client_documents", to="common.attachment"),
        ),
    ]
