# Generated by Django 5.1.2 on 2024-11-05 21:04

from django.db import migrations
from django.db.models.query import Q


def migrate_title_to_purpose(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    notes = Note.objects.exclude(Q(purpose__isnull=True) | Q(purpose__exact=""))
    for note in notes:
        note.purpose = note.title
        note.save()


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0013_add_note_team"),
    ]

    operations = [
        migrations.RunPython(migrate_title_to_purpose),
    ]
