# Generated by Django 4.2.11 on 2024-03-23 05:17

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0015_remove_historicalnote_client_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="next_steps",
        ),
        migrations.RemoveField(
            model_name="note",
            name="provided_services",
        ),
        migrations.RemoveField(
            model_name="note",
            name="purposes",
        ),
        migrations.RemoveField(
            model_name="note",
            name="requested_services",
        ),
    ]
