# Generated by Django 4.2.11 on 2024-04-02 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notes", "0018_add_point_to_note_and_task"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="next_steps",
            field=models.ManyToManyField(blank=True, related_name="next_step_notes", to="notes.task"),
        ),
        migrations.AlterField(
            model_name="note",
            name="provided_services",
            field=models.ManyToManyField(blank=True, related_name="provided_notes", to="notes.servicerequest"),
        ),
        migrations.AlterField(
            model_name="note",
            name="purposes",
            field=models.ManyToManyField(blank=True, related_name="purpose_notes", to="notes.task"),
        ),
        migrations.AlterField(
            model_name="note",
            name="requested_services",
            field=models.ManyToManyField(blank=True, related_name="requested_notes", to="notes.servicerequest"),
        ),
    ]
