# Generated by Django 5.2.4 on 2025-07-31 02:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0019_remove_notenextstepsevent_note_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="note",
            name="next_steps",
        ),
        migrations.RemoveField(
            model_name="note",
            name="purposes",
        ),
        migrations.RemoveField(
            model_name="taskevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="taskevent",
            name="client_profile",
        ),
        migrations.RemoveField(
            model_name="taskevent",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="taskevent",
            name="location",
        ),
        migrations.RemoveField(
            model_name="taskevent",
            name="pgh_context",
        ),
        migrations.DeleteModel(
            name="Task",
        ),
        migrations.DeleteModel(
            name="TaskEvent",
        ),
    ]
