# Generated by Django 5.2.4 on 2025-08-12 16:03

from accounts.groups import GroupTemplateNames
from django.db import migrations

service_by_category = [
    {
        "title": "Immediate Needs",
        "items": [
            "Food",
            "Water",
            "Bag(s)",
            "Batteries",
            "Blanket",
            "Book",
            "Clothes",
            "Feminine Hygiene",
            "First Aid",
            "Hygiene Kit",
            "Pet Food",
            "Shoes",
            "Shower",
            "Sleeping Bag",
            "Tarp",
            "Tent",
        ],
    },
    {
        "title": "Communication",
        "items": [
            "Mail Pick Up",
            "California Lifeline Phone",
            "Internet Access",
            "LAHOP",
            "HMIS Consent",
            "Consent to Connect (CM or Council District)",
        ],
    },
    {
        "title": "Identity",
        "items": [
            "Birth Certificate",
            "DMV No Fee ID Form",
            "Social Security Card Replacement",
        ],
    },
    {
        "title": "Income",
        "items": [
            "Stimulus Assistance",
            "EBT",
            "SSI/SSDI",
            "Public Benefits Programs",
            "Medi-Cal",
            "Unemployment Certification",
        ],
    },
    {
        "title": "Housing",
        "items": [
            "Shelter",
            "Storage - Documents",
            "Storage - Belongings",
            "Safe Parking",
        ],
    },
    {
        "title": "Medical",
        "items": [
            "Dental",
            "Harm Reduction",
            "Medical",
            "Pet Care",
            "Vaccine Passport",
        ],
    },
    {
        "title": "Mental",
        "items": ["DMH Evaluation", "Therapist Appointment"],
    },
    {
        "title": "Social",
        "items": ["Family Reunification", "Contact Friend"],
    },
    {
        "title": "Transportation",
        "items": [
            "Metro LIFE Tap",
            "Discount Scooter Rides",
            "Ride",
            "Bicycle",
            "Bicycle Repair",
        ],
    },
    {
        "title": "Legal",
        "items": ["Contact DPSS", "Legal Counsel", "Notary"],
    },
]


def seed_service_tables(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationService = apps.get_model("notes", "OrganizationService")
    OrganizationServiceCategory = apps.get_model("notes", "OrganizationServiceCategory")

    ba_org, _ = Organization.objects.get_or_create(name="Better Angels")

    for idx, category in enumerate(service_by_category):
        cat, _ = OrganizationServiceCategory.objects.get_or_create(
            name=category["title"],
            organization=ba_org,
            priority=idx,
        )

        for idx, svc in enumerate(category["items"]):
            OrganizationService.objects.get_or_create(
                service=svc,
                category=cat,
                organization=ba_org,
                priority=idx,
            )


def unseed_service_tables(apps, schema_editor):
    OrganizationService = apps.get_model("notes", "OrganizationService")
    OrganizationServiceCategory = apps.get_model("notes", "OrganizationServiceCategory")

    OrganizationService.objects.all().delete()
    OrganizationServiceCategory.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0021_organizationservicecategory_organizationservice_and_more"),
    ]

    operations = [migrations.RunPython(seed_service_tables, unseed_service_tables)]
