# Generated by Django 5.2.5 on 2025-08-14 19:24

import django_choices_field.fields
import notes.enums
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models
from django.utils.translation import gettext_lazy as _


class ServiceEnum(models.TextChoices):
    BAG = "bag", _("Bag(s)")
    BATTERIES = "batteries", _("Batteries")
    BICYCLE = "bicycle", _("Bicycle")
    BICYCLE_REPAIR = "bicycle_repair", _("Bicycle Repair")
    BIRTH_CERTIFICATE = "birth_certificate", _("Birth Certificate")
    BLANKET = "blanket", _("Blanket")
    BOOK = "book", _("Book")
    CALIFORNIA_LIFELINE_PHONE = "california_lifeline_phone", _("California Lifeline Phone")
    CLOTHES = "clothes", _("Clothes")
    CONSENT_TO_CONNECT = "consent_to_connect", _("Consent to Connect (CM or Council District)")
    CONTACT_DPSS = "contact_dpss", _("Contact DPSS")
    CONTACT_FRIEND = "contact_friend", _("Contact Friend")
    DENTAL = "dental", _("Dental")
    DISCOUNT_SCOOTER_RIDES = "discount_scooter_rides", _("Discount Scooter Rides")
    DMH_EVALUATION = "dmh_evaluation", _("DMH Evaluation")
    DMV_NO_FEE_ID_FORM = "dmv_no_fee_id_form", _("DMV No Fee ID Form")
    EBT = "ebt", _("EBT")
    FAMILY_REUNIFICATION = "family_reunification", _("Family Reunification")
    FEMININE_HYGIENE = "feminine_hygiene", _("Feminine Hygiene")
    FIRST_AID = "first_aid", _("First Aid")
    FOOD = "food", _("Food")
    HARM_REDUCTION = "harm_reduction", _("Harm Reduction")
    HMIS_CONSENT = "hmis_consent", _("HMIS Consent")
    HYGIENE_KIT = "hygiene_kit", _("Hygiene Kit")
    INTERNET_ACCESS = "internet_access", _("Internet Access")
    LAHOP = "lahop", _("LAHOP")
    LEGAL_COUNSEL = "legal_counsel", _("Legal Counsel")
    MAIL_PICK_UP = "mail_pick_up", _("Mail Pick Up")
    MEDICAL = "medical", _("Medical")
    MEDI_CAL = "medi_cal", _("Medi-Cal")
    METRO_LIFE_TAP = "metro_life_tap", _("Metro LIFE Tap")
    NOTARY = "notary", _("Notary")
    OTHER = "other", _("Other")
    PET_CARE = "pet_care", _("Pet Care")
    PET_FOOD = "pet_food", _("Pet Food")
    PUBLIC_BENEFITS_PROGRAMS = "public_benefits_programs", _("Public Benefits Programs")
    RIDE = "ride", _("Ride")
    SAFE_PARKING = "safe_parking", _("Safe Parking")
    SHELTER = "shelter", _("Shelter")
    SHOES = "shoes", _("Shoes")
    SHOWER = "shower", _("Shower")
    SLEEPING_BAG = "sleeping_bag", _("Sleeping Bag")
    SOCIAL_SECURITY_CARD_REPLACEMENT = "social_security_card_replacement", _("Social Security Card Replacement")
    SSI_SSDI = "ssi_ssdi", _("SSI/SSDI")
    STIMULUS_ASSISTANCE = "stimulus_assistance", _("Stimulus Assistance")
    STORAGE_BELONGINGS = "storage_belongings", _("Storage - Belongings")
    STORAGE_DOCUMENTS = "storage_documents", _("Storage - Documents")
    TARP = "tarp", _("Tarp")
    TENT = "tent", _("Tent")
    THERAPIST_APPOINTMENT = "therapist_appointment", _("Therapist Appointment")
    UNEMPLOYMENT_CERTIFICATION = "unemployment_certification", _("Unemployment Certification")
    VACCINE_PASSPORT = "vaccine_passport", _("Vaccine Passport")
    WATER = "water", _("Water")


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0022_seed_services"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="servicerequest",
            name="service_request_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="servicerequest",
            name="service_request_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="servicerequest",
            name="service_request_remove_delete",
        ),
        migrations.AddField(
            model_name="servicerequest",
            name="service_enum",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("bag", "Bag(s)"),
                    ("batteries", "Batteries"),
                    ("bicycle", "Bicycle"),
                    ("bicycle_repair", "Bicycle Repair"),
                    ("birth_certificate", "Birth Certificate"),
                    ("blanket", "Blanket"),
                    ("book", "Book"),
                    ("california_lifeline_phone", "California Lifeline Phone"),
                    ("clothes", "Clothes"),
                    ("consent_to_connect", "Consent to Connect (CM or Council District)"),
                    ("contact_dpss", "Contact DPSS"),
                    ("contact_friend", "Contact Friend"),
                    ("dental", "Dental"),
                    ("discount_scooter_rides", "Discount Scooter Rides"),
                    ("dmh_evaluation", "DMH Evaluation"),
                    ("dmv_no_fee_id_form", "DMV No Fee ID Form"),
                    ("ebt", "EBT"),
                    ("family_reunification", "Family Reunification"),
                    ("feminine_hygiene", "Feminine Hygiene"),
                    ("first_aid", "First Aid"),
                    ("food", "Food"),
                    ("harm_reduction", "Harm Reduction"),
                    ("hmis_consent", "HMIS Consent"),
                    ("hygiene_kit", "Hygiene Kit"),
                    ("internet_access", "Internet Access"),
                    ("lahop", "LAHOP"),
                    ("legal_counsel", "Legal Counsel"),
                    ("mail_pick_up", "Mail Pick Up"),
                    ("medical", "Medical"),
                    ("medi_cal", "Medi-Cal"),
                    ("metro_life_tap", "Metro LIFE Tap"),
                    ("notary", "Notary"),
                    ("other", "Other"),
                    ("pet_care", "Pet Care"),
                    ("pet_food", "Pet Food"),
                    ("public_benefits_programs", "Public Benefits Programs"),
                    ("ride", "Ride"),
                    ("safe_parking", "Safe Parking"),
                    ("shelter", "Shelter"),
                    ("shoes", "Shoes"),
                    ("shower", "Shower"),
                    ("sleeping_bag", "Sleeping Bag"),
                    ("social_security_card_replacement", "Social Security Card Replacement"),
                    ("ssi_ssdi", "SSI/SSDI"),
                    ("stabilize", "Stabilize"),
                    ("stimulus_assistance", "Stimulus Assistance"),
                    ("storage", "Storage"),
                    ("storage_belongings", "Storage - Belongings"),
                    ("storage_documents", "Storage - Documents"),
                    ("tarp", "Tarp"),
                    ("tent", "Tent"),
                    ("therapist_appointment", "Therapist Appointment"),
                    ("transport", "Transport"),
                    ("unemployment_certification", "Unemployment Certification"),
                    ("vaccine_passport", "Vaccine Passport"),
                    ("water", "Water"),
                ],
                choices_enum=notes.enums.ServiceEnum,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="servicerequestevent",
            name="service_enum",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("bag", "Bag(s)"),
                    ("batteries", "Batteries"),
                    ("bicycle", "Bicycle"),
                    ("bicycle_repair", "Bicycle Repair"),
                    ("birth_certificate", "Birth Certificate"),
                    ("blanket", "Blanket"),
                    ("book", "Book"),
                    ("california_lifeline_phone", "California Lifeline Phone"),
                    ("clothes", "Clothes"),
                    ("consent_to_connect", "Consent to Connect (CM or Council District)"),
                    ("contact_dpss", "Contact DPSS"),
                    ("contact_friend", "Contact Friend"),
                    ("dental", "Dental"),
                    ("discount_scooter_rides", "Discount Scooter Rides"),
                    ("dmh_evaluation", "DMH Evaluation"),
                    ("dmv_no_fee_id_form", "DMV No Fee ID Form"),
                    ("ebt", "EBT"),
                    ("family_reunification", "Family Reunification"),
                    ("feminine_hygiene", "Feminine Hygiene"),
                    ("first_aid", "First Aid"),
                    ("food", "Food"),
                    ("harm_reduction", "Harm Reduction"),
                    ("hmis_consent", "HMIS Consent"),
                    ("hygiene_kit", "Hygiene Kit"),
                    ("internet_access", "Internet Access"),
                    ("lahop", "LAHOP"),
                    ("legal_counsel", "Legal Counsel"),
                    ("mail_pick_up", "Mail Pick Up"),
                    ("medical", "Medical"),
                    ("medi_cal", "Medi-Cal"),
                    ("metro_life_tap", "Metro LIFE Tap"),
                    ("notary", "Notary"),
                    ("other", "Other"),
                    ("pet_care", "Pet Care"),
                    ("pet_food", "Pet Food"),
                    ("public_benefits_programs", "Public Benefits Programs"),
                    ("ride", "Ride"),
                    ("safe_parking", "Safe Parking"),
                    ("shelter", "Shelter"),
                    ("shoes", "Shoes"),
                    ("shower", "Shower"),
                    ("sleeping_bag", "Sleeping Bag"),
                    ("social_security_card_replacement", "Social Security Card Replacement"),
                    ("ssi_ssdi", "SSI/SSDI"),
                    ("stabilize", "Stabilize"),
                    ("stimulus_assistance", "Stimulus Assistance"),
                    ("storage", "Storage"),
                    ("storage_belongings", "Storage - Belongings"),
                    ("storage_documents", "Storage - Documents"),
                    ("tarp", "Tarp"),
                    ("tent", "Tent"),
                    ("therapist_appointment", "Therapist Appointment"),
                    ("transport", "Transport"),
                    ("unemployment_certification", "Unemployment Certification"),
                    ("vaccine_passport", "Vaccine Passport"),
                    ("water", "Water"),
                ],
                choices_enum=notes.enums.ServiceEnum,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequest",
            name="service",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("bag", "Bag(s)"),
                    ("batteries", "Batteries"),
                    ("bicycle", "Bicycle"),
                    ("bicycle_repair", "Bicycle Repair"),
                    ("birth_certificate", "Birth Certificate"),
                    ("blanket", "Blanket"),
                    ("book", "Book"),
                    ("california_lifeline_phone", "California Lifeline Phone"),
                    ("clothes", "Clothes"),
                    ("consent_to_connect", "Consent to Connect (CM or Council District)"),
                    ("contact_dpss", "Contact DPSS"),
                    ("contact_friend", "Contact Friend"),
                    ("dental", "Dental"),
                    ("discount_scooter_rides", "Discount Scooter Rides"),
                    ("dmh_evaluation", "DMH Evaluation"),
                    ("dmv_no_fee_id_form", "DMV No Fee ID Form"),
                    ("ebt", "EBT"),
                    ("family_reunification", "Family Reunification"),
                    ("feminine_hygiene", "Feminine Hygiene"),
                    ("first_aid", "First Aid"),
                    ("food", "Food"),
                    ("harm_reduction", "Harm Reduction"),
                    ("hmis_consent", "HMIS Consent"),
                    ("hygiene_kit", "Hygiene Kit"),
                    ("internet_access", "Internet Access"),
                    ("lahop", "LAHOP"),
                    ("legal_counsel", "Legal Counsel"),
                    ("mail_pick_up", "Mail Pick Up"),
                    ("medical", "Medical"),
                    ("medi_cal", "Medi-Cal"),
                    ("metro_life_tap", "Metro LIFE Tap"),
                    ("notary", "Notary"),
                    ("other", "Other"),
                    ("pet_care", "Pet Care"),
                    ("pet_food", "Pet Food"),
                    ("public_benefits_programs", "Public Benefits Programs"),
                    ("ride", "Ride"),
                    ("safe_parking", "Safe Parking"),
                    ("shelter", "Shelter"),
                    ("shoes", "Shoes"),
                    ("shower", "Shower"),
                    ("sleeping_bag", "Sleeping Bag"),
                    ("social_security_card_replacement", "Social Security Card Replacement"),
                    ("ssi_ssdi", "SSI/SSDI"),
                    ("stabilize", "Stabilize"),
                    ("stimulus_assistance", "Stimulus Assistance"),
                    ("storage", "Storage"),
                    ("storage_belongings", "Storage - Belongings"),
                    ("storage_documents", "Storage - Documents"),
                    ("tarp", "Tarp"),
                    ("tent", "Tent"),
                    ("therapist_appointment", "Therapist Appointment"),
                    ("transport", "Transport"),
                    ("unemployment_certification", "Unemployment Certification"),
                    ("vaccine_passport", "Vaccine Passport"),
                    ("water", "Water"),
                ],
                choices_enum=notes.enums.ServiceEnum,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="servicerequestevent",
            name="service",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("bag", "Bag(s)"),
                    ("batteries", "Batteries"),
                    ("bicycle", "Bicycle"),
                    ("bicycle_repair", "Bicycle Repair"),
                    ("birth_certificate", "Birth Certificate"),
                    ("blanket", "Blanket"),
                    ("book", "Book"),
                    ("california_lifeline_phone", "California Lifeline Phone"),
                    ("clothes", "Clothes"),
                    ("consent_to_connect", "Consent to Connect (CM or Council District)"),
                    ("contact_dpss", "Contact DPSS"),
                    ("contact_friend", "Contact Friend"),
                    ("dental", "Dental"),
                    ("discount_scooter_rides", "Discount Scooter Rides"),
                    ("dmh_evaluation", "DMH Evaluation"),
                    ("dmv_no_fee_id_form", "DMV No Fee ID Form"),
                    ("ebt", "EBT"),
                    ("family_reunification", "Family Reunification"),
                    ("feminine_hygiene", "Feminine Hygiene"),
                    ("first_aid", "First Aid"),
                    ("food", "Food"),
                    ("harm_reduction", "Harm Reduction"),
                    ("hmis_consent", "HMIS Consent"),
                    ("hygiene_kit", "Hygiene Kit"),
                    ("internet_access", "Internet Access"),
                    ("lahop", "LAHOP"),
                    ("legal_counsel", "Legal Counsel"),
                    ("mail_pick_up", "Mail Pick Up"),
                    ("medical", "Medical"),
                    ("medi_cal", "Medi-Cal"),
                    ("metro_life_tap", "Metro LIFE Tap"),
                    ("notary", "Notary"),
                    ("other", "Other"),
                    ("pet_care", "Pet Care"),
                    ("pet_food", "Pet Food"),
                    ("public_benefits_programs", "Public Benefits Programs"),
                    ("ride", "Ride"),
                    ("safe_parking", "Safe Parking"),
                    ("shelter", "Shelter"),
                    ("shoes", "Shoes"),
                    ("shower", "Shower"),
                    ("sleeping_bag", "Sleeping Bag"),
                    ("social_security_card_replacement", "Social Security Card Replacement"),
                    ("ssi_ssdi", "SSI/SSDI"),
                    ("stabilize", "Stabilize"),
                    ("stimulus_assistance", "Stimulus Assistance"),
                    ("storage", "Storage"),
                    ("storage_belongings", "Storage - Belongings"),
                    ("storage_documents", "Storage - Documents"),
                    ("tarp", "Tarp"),
                    ("tent", "Tent"),
                    ("therapist_appointment", "Therapist Appointment"),
                    ("transport", "Transport"),
                    ("unemployment_certification", "Unemployment Certification"),
                    ("vaccine_passport", "Vaccine Passport"),
                    ("water", "Water"),
                ],
                choices_enum=notes.enums.ServiceEnum,
                max_length=32,
                null=True,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="service_request_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service", "service_enum", "service_other", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."completed_on", NEW."created_at", NEW."created_by_id", NEW."due_by", NEW."id", _pgh_attach_context(), NOW(), \'service_request.add\', NEW."id", NEW."service", NEW."service_enum", NEW."service_other", NEW."status", NEW."updated_at"); RETURN NULL;',
                    hash="8df3674873481487e3d7287d967c1bcdbbe20ced",
                    operation="INSERT",
                    pgid="pgtrigger_service_request_add_insert_f5d42",
                    table="notes_servicerequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="service_request_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service", "service_enum", "service_other", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."completed_on", NEW."created_at", NEW."created_by_id", NEW."due_by", NEW."id", _pgh_attach_context(), NOW(), \'service_request.update\', NEW."id", NEW."service", NEW."service_enum", NEW."service_other", NEW."status", NEW."updated_at"); RETURN NULL;',
                    hash="c70796a5bb4e37526d0261a3ae2e3782efc10e82",
                    operation="UPDATE",
                    pgid="pgtrigger_service_request_update_update_261d7",
                    table="notes_servicerequest",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="servicerequest",
            trigger=pgtrigger.compiler.Trigger(
                name="service_request_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_servicerequestevent" ("client_profile_id", "completed_on", "created_at", "created_by_id", "due_by", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "service", "service_enum", "service_other", "status", "updated_at") VALUES (OLD."client_profile_id", OLD."completed_on", OLD."created_at", OLD."created_by_id", OLD."due_by", OLD."id", _pgh_attach_context(), NOW(), \'service_request.remove\', OLD."id", OLD."service", OLD."service_enum", OLD."service_other", OLD."status", OLD."updated_at"); RETURN NULL;',
                    hash="22035d7e32a9fd32efdd70158cd07bbe8c60092f",
                    operation="DELETE",
                    pgid="pgtrigger_service_request_remove_delete_53389",
                    table="notes_servicerequest",
                    when="AFTER",
                ),
            ),
        ),
    ]
