# Generated by Django 5.2.5 on 2025-08-15 18:52

from django.db import migrations
from django.db.models import F


def copy_service_to_service_enum(apps, schema_editor):
    ServiceRequest = apps.get_model("notes", "ServiceRequest")
    ServiceRequest.objects.all().update(service_enum=F("service"))


def clear_service_enum(apps, schema_editor):
    ServiceRequest = apps.get_model("notes", "ServiceRequest")
    ServiceRequest.objects.all().update(service_enum=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0023_add_service_enum_field"),
    ]

    operations = [
        migrations.RunPython(
            copy_service_to_service_enum,
            clear_service_enum,
        )
    ]
