# Generated by Django 5.2.5 on 2025-09-03 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0027_data_copy_service_enum_to_service"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="organizationservicecategory",
            options={"ordering": ("priority",), "verbose_name_plural": "Service Categories"},
        ),
    ]
