# Generated by Django 6.0.2 on 2026-02-13 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0029_remove_servicerequest_enum_fields"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="moodevent",
            name="pgh_obj",
        ),
        migrations.RemoveField(
            model_name="moodevent",
            name="note",
        ),
        migrations.RemoveField(
            model_name="moodevent",
            name="pgh_context",
        ),
        migrations.DeleteModel(
            name="Mood",
        ),
        migrations.DeleteModel(
            name="MoodEvent",
        ),
    ]
