# Generated by Django 6.0.2 on 2026-03-02 23:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_remove_address_components_add_unique_formatted_address"),
        ("notes", "0030_remove_mood_model"),
    ]

    operations = [
        migrations.AlterField(
            model_name="note",
            name="location",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="notes",
                to="common.location",
            ),
        ),
    ]
