# Generated by Django 6.0.6 on 2026-06-18 22:39

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations, models

from common.enums import SelahTeamEnum


def _backfill_teams_and_copy(apps, schema_editor):
    """Create Team objects per org for each SelahTeamEnum value, then copy note.old_team -> note.team FK."""
    Note = apps.get_model("notes", "Note")
    Team = apps.get_model("teams", "Team")
    Organization = apps.get_model("organizations", "Organization")

    org_ids = (
        Note.objects.exclude(old_team__isnull=True)
        .exclude(old_team="")
        .values_list("organization_id", flat=True)
        .distinct()
    )

    for org_id in org_ids:
        try:
            org = Organization.objects.get(pk=org_id)
        except Organization.DoesNotExist:
            continue
        for enum_member in SelahTeamEnum:
            Team.objects.get_or_create(
                organization=org,
                slug=enum_member.value,
                defaults={"name": enum_member.label},
            )

    for note in Note.objects.exclude(old_team__isnull=True).exclude(old_team="").iterator():
        try:
            team = Team.objects.get(
                organization_id=note.organization_id,
                slug=note.old_team,
            )
            note.team = team
            note.save(update_fields=["team"])
        except Team.DoesNotExist:
            pass


def _reverse_backfill(apps, schema_editor):
    Note = apps.get_model("notes", "Note")
    Note.objects.all().update(team=None)


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0032_remove_note_note_add_insert_and_more"),
        ("teams", "0001_initial"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        # -- Rename old enum column to preserve data --
        migrations.RenameField(
            model_name="note",
            old_name="team",
            new_name="old_team",
        ),
        migrations.RenameField(
            model_name="noteevent",
            old_name="team",
            new_name="old_team",
        ),
        # -- Add new FK column --
        migrations.AddField(
            model_name="note",
            name="team",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="teams.team",
            ),
        ),
        migrations.AddField(
            model_name="noteevent",
            name="team",
            field=models.ForeignKey(
                blank=True,
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="teams.team",
            ),
        ),
        # -- Re-add pghistory triggers referencing new team_id column --
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="note_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.add\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;',
                    hash="de46651001be754f65fe1059f55e71b77cbf8bc0",
                    operation="INSERT",
                    pgid="pgtrigger_note_add_insert_e05e6",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="note_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."interacted_at", NEW."is_submitted", NEW."location_id", NEW."organization_id", _pgh_attach_context(), NOW(), \'note.update\', NEW."id", NEW."private_details", NEW."public_details", NEW."purpose", NEW."team_id", NEW."updated_at"); RETURN NULL;',
                    hash="64274b33e7a107270b4e0f0f193f5c3f970d4c10",
                    operation="UPDATE",
                    pgid="pgtrigger_note_update_update_ac81f",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="note",
            trigger=pgtrigger.compiler.Trigger(
                name="note_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "notes_noteevent" ("client_profile_id", "created_at", "created_by_id", "id", "interacted_at", "is_submitted", "location_id", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "private_details", "public_details", "purpose", "team_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."id", OLD."interacted_at", OLD."is_submitted", OLD."location_id", OLD."organization_id", _pgh_attach_context(), NOW(), \'note.remove\', OLD."id", OLD."private_details", OLD."public_details", OLD."purpose", OLD."team_id", OLD."updated_at"); RETURN NULL;',
                    hash="40ebc9f82add010f91b0e884991006942fba547b",
                    operation="DELETE",
                    pgid="pgtrigger_note_remove_delete_dd722",
                    table="notes_note",
                    when="AFTER",
                ),
            ),
        ),
        # -- Data migration: backfill Team objects and copy old_team FK --
        migrations.RunPython(_backfill_teams_and_copy, _reverse_backfill),
    ]
