# Generated by Django 6.0.6 on 2026-06-18 22:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("notes", "0032_remove_note_note_add_insert_and_more"),
        ("teams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="note",
            old_name="team",
            new_name="old_team",
        ),
        migrations.RenameField(
            model_name="noteevent",
            old_name="team",
            new_name="old_team",
        ),
    ]
