# Generated by Django 4.2.7 on 2023-11-16 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_organization_slug"),
        ("accounts", "0004_historicaluser"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExtendedOrganizationInvitation",
            fields=[
                ("accepted", models.BooleanField(default=False)),
                (
                    "organization_invitation",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        related_name="extended_invitation",
                        serialize=False,
                        to="organizations.organizationinvitation",
                    ),
                ),
            ],
            options={
                "verbose_name": "Organization Invitation",
                "verbose_name_plural": "Organization Invitations",
            },
            bases=("organizations.organizationinvitation",),
        ),
    ]
