# Generated by Django 4.2.9 on 2024-01-30 02:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("accounts", "0005_extendedorganizationinvitation"),
    ]

    operations = [
        migrations.CreateModel(
            name="BigUserObjectPermission",
            fields=[
                (
                    "object_pk",
                    models.CharField(max_length=255, verbose_name="object ID"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_pk"],
                        name="accounts_bi_content_4594f9_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_pk", "user"],
                        name="accounts_bi_content_664112_idx",
                    ),
                ],
                "unique_together": {("user", "permission", "object_pk")},
            },
        ),
        migrations.CreateModel(
            name="BigGroupObjectPermission",
            fields=[
                (
                    "object_pk",
                    models.CharField(max_length=255, verbose_name="object ID"),
                ),
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_pk"],
                        name="accounts_bi_content_1492d4_idx",
                    ),
                    models.Index(
                        fields=["content_type", "object_pk", "group"],
                        name="accounts_bi_content_060208_idx",
                    ),
                ],
                "unique_together": {("group", "permission", "object_pk")},
            },
        ),
    ]
