# Generated by Django 6.0.7 on 2026-08-26 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_permission_group_is_a_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='permissiongrouptemplate',
            name='bypasses_org_scoping',
            field=models.BooleanField(default=False, help_text='Holders of this role bypass organization scoping. See common.permissions.utils.user_holds_org_bypass_perms.'),
        ),
    ]
