# Generated by Django 6.1 on 2026-09-01 21:50

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_permission_group_is_a_group"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0006_alter_organization_slug"),
        ("pghistory", "0007_auto_20250421_0444"),
    ]

    operations = [
        migrations.CreateModel(
            name="Role",
            fields=[
                (
                    "group_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="auth.group",
                    ),
                ),
                ("is_global", models.BooleanField(default=False)),
            ],
            bases=("auth.group",),
        ),
        migrations.CreateModel(
            name="Grant",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("scope_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "principal_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="delegated_grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_object_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "scope_org",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="grants",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="grants", to="accounts.role"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GrantEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.BigIntegerField()),
                ("scope_object_id", models.PositiveBigIntegerField(blank=True, null=True)),
                (
                    "pgh_context",
                    models.ForeignKey(
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        to="pghistory.context",
                    ),
                ),
                (
                    "pgh_obj",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="events",
                        to="accounts.grant",
                    ),
                ),
                (
                    "principal_org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "principal_user",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "scope_object_type",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "scope_org",
                    models.ForeignKey(
                        blank=True,
                        db_constraint=False,
                        null=True,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="organizations.organization",
                    ),
                ),
                (
                    "role",
                    models.ForeignKey(
                        db_constraint=False,
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        related_name="+",
                        related_query_name="+",
                        to="accounts.role",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("principal_user__isnull", False), ("principal_org__isnull", False), _connector="XOR"
                ),
                name="grant_has_exactly_one_principal",
                violation_error_message="A grant needs exactly one principal: a user or an organization.",
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("scope_org__isnull", False), ("scope_object_type__isnull", True)),
                    models.Q(
                        ("scope_org__isnull", True),
                        ("scope_object_type__isnull", False),
                        ("scope_object_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="grant_has_exactly_one_scope",
                violation_error_message="A grant needs exactly one scope: an organization or an object.",
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("principal_org__isnull", True),
                    models.Q(("principal_org", models.F("scope_org")), _negated=True),
                    _connector="OR",
                ),
                name="grant_org_principal_is_not_scope",
                violation_error_message="An organization cannot delegate a role to itself.",
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                fields=("principal_user", "role", "scope_org", "scope_object_type", "scope_object_id"),
                name="unique_user_grant",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                fields=("principal_org", "role", "scope_org", "scope_object_type", "scope_object_id"),
                name="unique_org_grant",
                nulls_distinct=False,
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="grant",
            trigger=pgtrigger.compiler.Trigger(
                name="grant_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "accounts_grantevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "principal_org_id", "principal_user_id", "role_id", "scope_object_id", "scope_object_type_id", "scope_org_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'grant.add\', NEW."id", NEW."principal_org_id", NEW."principal_user_id", NEW."role_id", NEW."scope_object_id", NEW."scope_object_type_id", NEW."scope_org_id"); RETURN NULL;',
                    hash="80558659b2ae7af4dc22cc3a548c37fe2f7fc1b0",
                    operation="INSERT",
                    pgid="pgtrigger_grant_add_insert_69d04",
                    table="accounts_grant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="grant",
            trigger=pgtrigger.compiler.Trigger(
                name="grant_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "accounts_grantevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "principal_org_id", "principal_user_id", "role_id", "scope_object_id", "scope_object_type_id", "scope_org_id") VALUES (NEW."id", _pgh_attach_context(), NOW(), \'grant.update\', NEW."id", NEW."principal_org_id", NEW."principal_user_id", NEW."role_id", NEW."scope_object_id", NEW."scope_object_type_id", NEW."scope_org_id"); RETURN NULL;',
                    hash="019ceee0ef0864320fd260ada3c2d42f7ddf2821",
                    operation="UPDATE",
                    pgid="pgtrigger_grant_update_update_e7b69",
                    table="accounts_grant",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="grant",
            trigger=pgtrigger.compiler.Trigger(
                name="grant_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "accounts_grantevent" ("id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "principal_org_id", "principal_user_id", "role_id", "scope_object_id", "scope_object_type_id", "scope_org_id") VALUES (OLD."id", _pgh_attach_context(), NOW(), \'grant.remove\', OLD."id", OLD."principal_org_id", OLD."principal_user_id", OLD."role_id", OLD."scope_object_id", OLD."scope_object_type_id", OLD."scope_org_id"); RETURN NULL;',
                    hash="09f8d3af2bd89c3e6d085a180001d99a335235b8",
                    operation="DELETE",
                    pgid="pgtrigger_grant_remove_delete_e2ce5",
                    table="accounts_grant",
                    when="AFTER",
                ),
            ),
        ),
    ]
