# Generated by Django 6.1 on 2026-09-01 22:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_role_grant_grantevent_and_more"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="grant",
            name="unique_user_grant",
        ),
        migrations.RemoveConstraint(
            model_name="grant",
            name="unique_org_grant",
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_user__isnull", False)),
                fields=("principal_user", "role", "scope_org", "scope_object_type", "scope_object_id"),
                name="unique_user_grant",
                nulls_distinct=False,
            ),
        ),
        migrations.AddConstraint(
            model_name="grant",
            constraint=models.UniqueConstraint(
                condition=models.Q(("principal_org__isnull", False)),
                fields=("principal_org", "role", "scope_org", "scope_object_type", "scope_object_id"),
                name="unique_org_grant",
                nulls_distinct=False,
            ),
        ),
    ]
