# Generated by Django 6.1 on 2026-09-30 20:15
"""Give every organization that owns a Shelter a profile declaring the shelter type.

An organization is a tenant by virtue of its ``OrganizationProfile.org_types``, so a
shelter-owning organization without the ``shelter`` type is a misconfiguration: it can
hold no shelter roles and accept no members for the shelters it owns.  This backfills
the type from the evidence already in the database — the ``Shelter.organization`` FK —
rather than a blanket default.

Only organizations that own at least one Shelter are considered.  Among those, an
organization with no profile gets one; an organization whose profile exists but
lacks the type (e.g. ``["outreach"]``) has the type added, since a bare ``create``
would violate the ``OneToOneField`` there.  Organizations already carrying the type
are left as they are, and shelter-less organizations are never visited, which also
makes this safe to re-run.

The forward step only ever adds data, so the reverse is a no-op: it cannot tell a
profile this migration created from one that was already correctly typed, and deleting
either would destroy a configuration we cannot reconstruct.  Reversing therefore
leaves the added profiles and types in place.
"""

from django.db import migrations

# Frozen value of OrgTypeChoices.SHELTER — migrations must not import live model code.
SHELTER = "shelter"


def backfill_org_profiles(apps, schema_editor):
    Organization = apps.get_model("organizations", "Organization")
    OrganizationProfile = apps.get_model("accounts", "OrganizationProfile")
    Shelter = apps.get_model("shelters", "Shelter")

    # ``pk__in`` (a semi-join) rather than ``shelter__isnull=False`` (a join), so an
    # organization owning several shelters is visited once.
    shelter_org_ids = Shelter.objects.values("organization_id")
    profiles = {profile.organization_id: profile for profile in OrganizationProfile.objects.all()}

    to_create = []
    updated = 0

    for organization in Organization.objects.filter(pk__in=shelter_org_ids):
        profile = profiles.get(organization.pk)
        if profile is None:
            to_create.append(
                OrganizationProfile(organization=organization, org_types=[SHELTER])
            )
        elif SHELTER not in profile.org_types:
            profile.org_types = [*profile.org_types, SHELTER]
            profile.save(update_fields=["org_types"])
            updated += 1

    OrganizationProfile.objects.bulk_create(to_create)

    print(f"\n  org profiles: {len(to_create)} created, {updated} given the shelter type")


class Migration(migrations.Migration):
    dependencies = [
        ('accounts', '0009_remove_grant_unique_user_grant_and_more'),
        ('shelters', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(backfill_org_profiles, migrations.RunPython.noop),
    ]
