# Generated by Django 6.1 on 2026-10-07 21:41

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_backfill_org_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='organizationprofile',
            name='time_zone',
            field=models.CharField(blank=True, default='', help_text="IANA name for the calendar this organization's report days are cut on, e.g. America/Los_Angeles. Blank falls back to the site's TIME_ZONE.", max_length=64, validators=[accounts.models.validate_iana_time_zone]),
        ),
    ]
