# Generated by Django 4.2.11 on 2024-04-18 00:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0012_clientprofile_hmis_id"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="clientprofile",
            index=models.Index(fields=["hmis_id"], name="accounts_client_hmis_id_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["first_name"], name="accounts_user_first_name_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["last_name"], name="accounts_user_last_name_idx"),
        ),
    ]
