# Generated by Django 5.0.4 on 2024-05-10 20:10

from accounts.permissions import ClientProfilePermissions
from django.db import migrations, models


# Functions from the following migrations need manual copying.
# Move them and any dependencies into this file, then update the
# RunPython operations to refer to the local versions:
# accounts.migrations.0014_casemanager_client_permissions
# accounts.migrations.0017_client_profile_permissions
def create_permissions_if_not_exist(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ClientProfileContentType = ContentType.objects.get_for_model(ClientProfile)
    db_alias = schema_editor.connection.alias

    # Generate readable names based on the enum
    PERM_MAP = {perm.split(".")[1]: perm.label for perm in ClientProfilePermissions}
    for codename, name in PERM_MAP.items():
        Permission.objects.using(db_alias).get_or_create(
            codename=codename,
            content_type=ClientProfileContentType,
            defaults={"name": name, "content_type": ClientProfileContentType},
        )


def update_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    ClientProfileContentType = ContentType.objects.get_for_model(ClientProfile)
    caseworker_template = PermissionGroupTemplate.objects.get(name="Caseworker")

    perm_map = [
        perm.split(".")[1]
        for perm in [
            "accounts.add_clientprofile",
        ]
    ]

    permissions = Permission.objects.filter(codename__in=perm_map, content_type=ClientProfileContentType)
    caseworker_template.permissions.add(*permissions)

class Migration(migrations.Migration):

    replaces = [('accounts', '0014_casemanager_client_permissions'), ('accounts', '0015_alter_clientprofile_hmis_id_alter_user_first_name_and_more'), ('accounts', '0016_alter_clientprofile_hmis_id'), ('accounts', '0017_client_profile_permissions'), ('accounts', '0018_alter_clientgroupobjectpermission_unique_together_and_more')]

    dependencies = [
        ('accounts', '0013_clientuserobjectpermission_and_more'),
        ('notes', '0001_squash_through_0020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, db_index=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='first_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='userevent',
            name='last_name',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='hmis_id',
            field=models.CharField(blank=True, db_index=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='clientgroupobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientgroupobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='clientgroupobjectpermission',
            name='group',
        ),
        migrations.RemoveField(
            model_name='clientgroupobjectpermission',
            name='permission',
        ),
        migrations.AlterUniqueTogether(
            name='clientuserobjectpermission',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='clientuserobjectpermission',
            name='content_object',
        ),
        migrations.RemoveField(
            model_name='clientuserobjectpermission',
            name='permission',
        ),
        migrations.RemoveField(
            model_name='clientuserobjectpermission',
            name='user',
        ),
        migrations.DeleteModel(
            name='Client',
        ),
        migrations.DeleteModel(
            name='ClientGroupObjectPermission',
        ),
        migrations.DeleteModel(
            name='ClientUserObjectPermission',
        ),
        migrations.RunPython(create_permissions_if_not_exist),
        migrations.RunPython(update_caseworker_permission_template),
    ]
