# Generated by Django 5.0.5 on 2024-05-07 17:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0017_client_profile_permissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="clientgroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clientgroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="clientgroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="clientgroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="clientuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="clientuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="clientuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="clientuserobjectpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="Client",
        ),
        migrations.DeleteModel(
            name="ClientGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="ClientUserObjectPermission",
        ),
    ]
