# Generated by Django 5.0.6 on 2024-06-03 16:24

import accounts.enums
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0019_clientprofile_date_of_birth_clientprofile_gender_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="gender",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[("male", "Male"), ("female", "Female"), ("nonbinary", "Non-binary")],
                choices_enum=accounts.enums.GenderEnum,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="preferred_language",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[("english", "English"), ("spanish", "Spanish")],
                choices_enum=accounts.enums.LanguageEnum,
                max_length=7,
                null=True,
            ),
        ),
    ]
