# Generated by Django 5.0.6 on 2024-06-20 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0023_alter_clientprofile_gender"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="middle_name",
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
