# Generated by Django 5.0.6 on 2024-07-24 05:40

import accounts.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


def add_hmis_profile(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    HmisProfile = apps.get_model("accounts", "HmisProfile")

    for client_profile in ClientProfile.objects.all():
        HmisProfile.objects.create(
            client_profile=client_profile,
            hmis_id=client_profile.hmis_id,
            agency=accounts.enums.HmisAgencyEnum.LAHSA,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0025_alter_clientprofile_gender"),
    ]

    operations = [
        migrations.CreateModel(
            name="HmisProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hmis_id", models.CharField(max_length=50)),
                (
                    "agency",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("lahsa", "LAHSA"),
                            ("santa_monica", "Santa Monica"),
                            ("pasadena", "Pasadena"),
                            ("champ", "CHAMP"),
                            ("vash", "VASH"),
                        ],
                        choices_enum=accounts.enums.HmisAgencyEnum,
                        max_length=12,
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmis_profile",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
        ),
        migrations.RunPython(add_hmis_profile),
    ]
