# Generated by Django 5.0.6 on 2024-07-24 07:53

import clients.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models
from django.db.models.query import Q


def add_hmis_profile(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    HmisProfile = apps.get_model("accounts", "HmisProfile")

    client_profiles_with_hmis_id = ClientProfile.objects.exclude(Q(hmis_id=None) | Q(hmis_id=""))

    for client_profile in client_profiles_with_hmis_id:
        HmisProfile.objects.create(
            client_profile=client_profile,
            hmis_id=client_profile.hmis_id,
            agency=clients.enums.HmisAgencyEnum.LAHSA,
        )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0026_alter_user_email_alter_user_username_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HmisProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("hmis_id", models.CharField(max_length=50)),
                (
                    "agency",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("lahsa", "LAHSA"),
                            ("santa_monica", "Santa Monica"),
                            ("pasadena", "Pasadena"),
                            ("champ", "CHAMP"),
                            ("vash", "VASH"),
                        ],
                        choices_enum=clients.enums.HmisAgencyEnum,
                        max_length=12,
                    ),
                ),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hmis_profiles",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
        ),
            migrations.AddConstraint(
            model_name="hmisprofile",
            constraint=models.UniqueConstraint(fields=("hmis_id", "agency"), name="unique_hmis_id_agency"),
        ),
        migrations.RunPython(add_hmis_profile),
    ]
