# Generated by Django 5.0.6 on 2024-07-24 22:21

import clients.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0027_hmisprofile_hmisprofile_unique_hmis_id_agency"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClientContact",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone_number", models.CharField(blank=True, max_length=15, null=True)),
                ("mailing_address", models.TextField(blank=True, null=True)),
                (
                    "relationship_to_client",
                    django_choices_field.fields.TextChoicesField(
                        blank=True,
                        choices=[
                            ("current_case_manager", "Current Case Manager"),
                            ("past_case_manager", "Past Case Manager"),
                            ("organization", "Organization"),
                            ("aunt", "Aunt"),
                            ("child", "Child"),
                            ("cousin", "Cousin"),
                            ("father", "Father"),
                            ("friend", "Friend"),
                            ("grandparent", "Grandparent"),
                            ("mother", "Mother"),
                            ("pet", "Pet"),
                            ("sibling", "Sibling"),
                            ("uncle", "Uncle"),
                            ("other", "Other"),
                        ],
                        choices_enum=clients.enums.RelationshipTypeEnum,
                        max_length=20,
                        null=True,
                    ),
                ),
                ("relationship_to_client_other", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="contacts",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
        ),
    ]
