# Generated by Django 5.0.7 on 2024-08-15 18:46

import accounts.enums
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0029_clienthouseholdmember"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="city_of_birth",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="eye_color",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("blue", "Blue"),
                    ("brown", "Brown"),
                    ("green", "Green"),
                    ("gray", "Gray"),
                    ("hazel", "Hazel"),
                    ("other", "Other"),
                ],
                choices_enum=accounts.enums.EyeColorEnum,
                max_length=5,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="hair_color",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("black", "Black"),
                    ("blonde", "Blonde"),
                    ("brown", "Brown"),
                    ("gray", "Gray"),
                    ("red", "Red"),
                    ("white", "White"),
                    ("bald", "Bald"),
                    ("other", "Other"),
                ],
                choices_enum=accounts.enums.HairColorEnum,
                max_length=6,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="height_in_inches",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="marital_status",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("divorced", "Divorced"),
                    ("married", "Married"),
                    ("separated", "Separated"),
                    ("single", "Single"),
                    ("widowed", "Widowed"),
                ],
                choices_enum=accounts.enums.MaritalStatusEnum,
                max_length=9,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="physical_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="pronouns_other",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="race",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("american_indian_alaska_native", "American Indian/Alaska Native"),
                    ("asian", "Asian"),
                    ("black_african_american", "Black/African American"),
                    ("hispanic_latino", "Hispanic/Latino"),
                    ("native_hawaiian_pacific_islander", "Native Hawaiian/Pacific Islander"),
                    ("white_caucasian", "White/Caucasian"),
                    ("other", "Other"),
                ],
                choices_enum=accounts.enums.RaceEnum,
                max_length=32,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="pronouns",
            field=django_choices_field.fields.TextChoicesField(
                blank=True,
                choices=[
                    ("he_him_his", "He/Him/His"),
                    ("she_her_hers", "She/Her/Hers"),
                    ("they_them_theirs", "They/Them/Theirs"),
                    ("other", "Other"),
                ],
                choices_enum=accounts.enums.PronounEnum,
                max_length=16,
                null=True,
            ),
        ),
    ]
