# Generated by Django 5.0.7 on 2024-08-22 20:16

from django.db import migrations


def clear_pronouns(apps, schema_editor):
    ClientProfile = apps.get_model("accounts", "ClientProfile")
    ClientProfile.objects.update(pronouns=None)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0031_clientcontact_demo_fields"),
    ]

    operations = [migrations.RunPython(clear_pronouns)]
