# Generated by Django 5.0.7 on 2024-08-28 00:26

import accounts.enums
import accounts.models
import django.contrib.postgres.fields
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0032_clientprofile_clear_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="profile_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to=accounts.models.get_client_profile_photo_file_path
            ),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="vehicles",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_choices_field.fields.TextChoicesField(
                    choices=[
                        ("bicycle", "Bicycle"),
                        ("car", "Car"),
                        ("motorcycle", "Motorcycle"),
                        ("rv", "RV"),
                        ("other", "Other"),
                    ],
                    choices_enum=accounts.enums.VehicleEnum,
                    max_length=10,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
