# Generated by Django 5.0.7 on 2024-08-29 20:56

import accounts.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0034_clientprofile_clientcontact_clear_phonenumber"),
    ]

    operations = [
        migrations.CreateModel(
            name="SocialMediaProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("snapchat", "Snapchat"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        choices_enum=accounts.enums.SocialMediaEnum,
                        max_length=9,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_profiles",
                        to="accounts.clientprofile",
                    ),
                ),
            ],
        ),
    ]
