# Generated by Django 5.0.7 on 2024-09-10 16:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_clientprofile_living_situation_and_profile_photo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={"ordering": ["user__first_name"]},
        ),
    ]
