# Generated by Django 5.0.7 on 2024-08-30 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0035_socialmediaprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="mailing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="residence_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
