# Generated by Django 5.1.3 on 2024-11-20 18:36

from django.db import migrations


def create_demo_group(apps, schema_editor):
    Group = apps.get_model("auth", "Group")
    Group.objects.get_or_create(name="Demo")


def create_demo_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    PermissionGroupTemplate.objects.create(name="Demo")


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0038_alter_userevent_id"),
    ]

    operations = [
        migrations.RunPython(create_demo_group),
        migrations.RunPython(create_demo_permission_template),
    ]
