# Generated by Django 5.2.4 on 2025-07-08 20:47

from django.db import migrations


def create_org_admin_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    PermissionGroupTemplate.objects.create(name="Organization Admin")


def create_org_superuser_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    PermissionGroupTemplate.objects.create(name="Organization Superuser")


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0038_alter_userevent_id"),
    ]

    operations = [
        migrations.RunPython(create_org_admin_permission_template),
        migrations.RunPython(create_org_superuser_permission_template),
    ]
