# Generated by Django 5.2.4 on 2025-07-31 21:29

from accounts.groups import GroupTemplateNames
from accounts.utils import create_missing_groups_for_org
from django.db import migrations


def create_missing_org_admin_groups(apps, schema_editor):
    create_missing_groups_for_org(
        apps=apps,
        current_perm_group_templates=[GroupTemplateNames.CASEWORKER],
        new_perm_group_templates=[GroupTemplateNames.ORG_ADMIN, GroupTemplateNames.ORG_SUPERUSER],
    )


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_update_org_admin_permissions_view_members"),
    ]

    operations = [
        migrations.RunPython(
            create_missing_org_admin_groups,
        ),
    ]
