# Generated by Django 5.2.4 on 2025-07-31 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0041_update_org_admin_permissions_view_members"),
    ]

    operations = []
