# Generated by Django 6.0.4 on 2026-06-03 20:35

import annoying.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_add_view_reports_permission"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "organization",
                    annoying.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="organizations.organization",
                    ),
                ),
                (
                    "org_types",
                    models.ManyToManyField(blank=True, related_name="organization_profiles", to="accounts.orgtype"),
                ),
            ],
        ),
    ]
