# Generated by Django 6.0.4 on 2026-06-04 16:57

import annoying.fields
import django.contrib.postgres.fields
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


def create_profiles_for_existing_orgs(apps, schema_editor):
    OrganizationProfile = apps.get_model("accounts", "OrganizationProfile")
    Organization = apps.get_model("organizations", "Organization")

    for org in Organization.objects.all():
        OrganizationProfile.objects.get_or_create(organization=org)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0045_add_view_reports_permission"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrganizationProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "org_types",
                    django.contrib.postgres.fields.ArrayField(
                        base_field=django_choices_field.fields.TextChoicesField(
                            choices=[("outreach", "Outreach"), ("shelter", "Shelter")], max_length=8
                        ),
                        blank=True,
                        default=list,
                    ),
                ),
                (
                    "organization",
                    annoying.fields.AutoOneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to="organizations.organization",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RunPython(create_profiles_for_existing_orgs, migrations.RunPython.noop),
    ]
