# Generated by Django 6.0.4

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0048_backfill_organization_profiles"),
    ]

    operations = [
        migrations.CreateModel(
            name="OrgType",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("key", models.CharField(max_length=50, unique=True)),
                ("label", models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="org_types",
            field=models.ManyToManyField(blank=True, related_name="organization_profiles", to="accounts.orgtype"),
        ),
    ]
