# Generated by Django 6.0.4

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0050_populate_org_types"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="org_type",
        ),
    ]
