# Generated by Django 6.0.6 on 2026-06-24 01:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_backfill_organization_profiles'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('organizations', '0006_alter_organization_slug'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='permissiongroup',
            unique_together={('organization', 'group'), ('organization', 'template')},
        ),
    ]
