# Generated by Django 6.0.6 on 2026-06-23 19:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0050_backfill_organization_profiles'),
    ]

    operations = [
    ]
