# Generated by Django 6.0.4 on 2026-05-19 21:32

import annoying.fields
import django.db.models.deletion
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0051_remove_org_type_charfield"),
        ("organizations", "0006_alter_organization_slug"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organizationprofile",
            name="organization",
            field=annoying.fields.AutoOneToOneField(
                on_delete=django.db.models.deletion.CASCADE, related_name="profile", to="organizations.organization"
            ),
        ),
    ]
