# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.db.models.deletion
import django.db.models.functions.text
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True
    replaces = [
        ("clients", "0002_clientprofile_contact_info"),
        ("clients", "0003_clientprofile_gender_other"),
        ("clients", "0004_clienthouseholdmember_gender_other"),
        ("clients", "0005_clientprofile_ada_accommodation"),
        ("clients", "0006_alter_clientprofile_preferred_communication"),
        ("clients", "0007_clientprofile_important_notes"),
        ("clients", "0008_clientprofile_california_id"),
        ("clients", "0009_clientprofile_caseworker_crud_permissions"),
        ("clients", "0010_alter_hmisprofile_agency"),
        ("clients", "0011_remove_clientprofile_hmis_id"),
        ("clients", "0012_alter_clientprofile_veteran_status"),
        ("clients", "0013_profiledataimport_profileimportrecord"),
        ("clients", "0014_rename_profiledataimport_clientprofiledataimport_and_more"),
        ("clients", "0015_remove_clientprofileimportrecord_clients_cli_import__774cc6_idx_and_more"),
        ("clients", "0016_alter_clientprofile_california_id_regex"),
        ("clients", "0017_clientcontactevent_clienthouseholdmemberevent_and_more"),
        ("clients", "0018_clientdocument_proxy"),
        ("clients", "0019_hmisprofile_permissions"),
        ("clients", "0020_clientprofile_name_email_fields"),
        ("clients", "0021_clientprofile_ordering_make_user_optional"),
        ("clients", "0022_clientprofile_name_email_fields_data"),
        ("clients", "0023_clientprofile_user_required"),
        ("clients", "0024_clientcontact_permissions"),
        ("clients", "0025_alter_clientprofile_user_and_more"),
        ("clients", "0026_clienthouseholdmember_permissions"),
        ("clients", "0027_socialmediaprofile_permissions"),
        ("clients", "0028_hmisprofile_case_insensitive_unique_constraint"),
        ("clients", "0029_clientprofile_residence_geolocation"),
        ("clients", "0030_remove_clientprofile_client_profile_add_insert_and_more"),
        ("clients", "0031_remove_clientprofile_client_profile_add_insert_and_more"),
        ("clients", "0032_unhoused_start_date"),
        ("clients", "0033_add_client_merge_fields"),
    ]

    dependencies = [
        ('clients', '0001_initial'),
        ('common', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientDocument',
            fields=[
            ],
            options={
                'verbose_name': 'Client Document',
                'verbose_name_plural': 'Client Documents',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('common.attachment',),
        ),
        migrations.AddField(
            model_name='clientcontactevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='clientcontactevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.clientcontact'),
        ),
        migrations.AddField(
            model_name='clienthouseholdmemberevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='clienthouseholdmemberevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.clienthouseholdmember'),
        ),
        migrations.AddField(
            model_name='clientprofile',
            name='merged_into',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='merged_from', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clienthouseholdmemberevent',
            name='client_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clienthouseholdmember',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='household_members', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientcontactevent',
            name='client_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientcontact',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientprofiledataimport',
            name='imported_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='clientprofileevent',
            name='merged_into',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientprofileevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='clientprofileevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientprofileimportrecord',
            name='client_profile',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='clientprofileimportrecord',
            name='import_job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='records', to='clients.clientprofiledataimport'),
        ),
        migrations.AddField(
            model_name='hmisprofile',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hmis_profiles', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='hmisprofileevent',
            name='client_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='hmisprofileevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='hmisprofileevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.hmisprofile'),
        ),
        migrations.AddField(
            model_name='socialmediaprofile',
            name='client_profile',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_media_profiles', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='socialmediaprofileevent',
            name='client_profile',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='socialmediaprofileevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='socialmediaprofileevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='clients.socialmediaprofile'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientprofile',
            trigger=pgtrigger.compiler.Trigger(name='client_profile_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "california_id", "created_at", "date_of_birth", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "id", "important_notes", "last_name", "living_situation", "mailing_address", "marital_status", "merged_at", "merged_data", "merged_into_id", "middle_name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "residence_address", "residence_geolocation", "spoken_languages", "unhoused_start_date", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."address", NEW."california_id", NEW."created_at", NEW."date_of_birth", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."height_in_inches", NEW."id", NEW."important_notes", NEW."last_name", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."merged_at", NEW."merged_data", NEW."merged_into_id", NEW."middle_name", NEW."nickname", _pgh_attach_context(), NOW(), \'client_profile.add\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."unhoused_start_date", NEW."updated_at", NEW."veteran_status"); RETURN NULL;', hash='3ef26a402caa18e84ec33cbe684ec738a766ac23', operation='INSERT', pgid='pgtrigger_client_profile_add_insert_4c2ed', table='clients_clientprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientprofile',
            trigger=pgtrigger.compiler.Trigger(name='client_profile_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "california_id", "created_at", "date_of_birth", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "id", "important_notes", "last_name", "living_situation", "mailing_address", "marital_status", "merged_at", "merged_data", "merged_into_id", "middle_name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "residence_address", "residence_geolocation", "spoken_languages", "unhoused_start_date", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."address", NEW."california_id", NEW."created_at", NEW."date_of_birth", NEW."email", NEW."eye_color", NEW."first_name", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."height_in_inches", NEW."id", NEW."important_notes", NEW."last_name", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."merged_at", NEW."merged_data", NEW."merged_into_id", NEW."middle_name", NEW."nickname", _pgh_attach_context(), NOW(), \'client_profile.update\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."residence_address", NEW."residence_geolocation", NEW."spoken_languages", NEW."unhoused_start_date", NEW."updated_at", NEW."veteran_status"); RETURN NULL;', hash='8c153cf9eea1b356311190c6b436c6b9ff3557bb', operation='UPDATE', pgid='pgtrigger_client_profile_update_update_858fb', table='clients_clientprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientprofile',
            trigger=pgtrigger.compiler.Trigger(name='client_profile_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "california_id", "created_at", "date_of_birth", "email", "eye_color", "first_name", "gender", "gender_other", "hair_color", "height_in_inches", "id", "important_notes", "last_name", "living_situation", "mailing_address", "marital_status", "merged_at", "merged_data", "merged_into_id", "middle_name", "nickname", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "residence_address", "residence_geolocation", "spoken_languages", "unhoused_start_date", "updated_at", "veteran_status") VALUES (OLD."ada_accommodation", OLD."address", OLD."california_id", OLD."created_at", OLD."date_of_birth", OLD."email", OLD."eye_color", OLD."first_name", OLD."gender", OLD."gender_other", OLD."hair_color", OLD."height_in_inches", OLD."id", OLD."important_notes", OLD."last_name", OLD."living_situation", OLD."mailing_address", OLD."marital_status", OLD."merged_at", OLD."merged_data", OLD."merged_into_id", OLD."middle_name", OLD."nickname", _pgh_attach_context(), NOW(), \'client_profile.remove\', OLD."id", OLD."phone_number", OLD."physical_description", OLD."place_of_birth", OLD."preferred_communication", OLD."preferred_language", OLD."profile_photo", OLD."pronouns", OLD."pronouns_other", OLD."race", OLD."residence_address", OLD."residence_geolocation", OLD."spoken_languages", OLD."unhoused_start_date", OLD."updated_at", OLD."veteran_status"); RETURN NULL;', hash='342102915ec50d145862c9b2652d12fbfb427008', operation='DELETE', pgid='pgtrigger_client_profile_remove_delete_ade5a', table='clients_clientprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clienthouseholdmember',
            trigger=pgtrigger.compiler.Trigger(name='client_household_member_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clienthouseholdmemberevent" ("client_profile_id", "created_at", "date_of_birth", "gender", "gender_other", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."date_of_birth", NEW."gender", NEW."gender_other", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'client_household_member.add\', NEW."id", NEW."relationship_to_client", NEW."relationship_to_client_other", NEW."updated_at"); RETURN NULL;', hash='b2a018e4bf94c468ff54df9b474fe735510f62ac', operation='INSERT', pgid='pgtrigger_client_household_member_add_insert_13024', table='clients_clienthouseholdmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clienthouseholdmember',
            trigger=pgtrigger.compiler.Trigger(name='client_household_member_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_clienthouseholdmemberevent" ("client_profile_id", "created_at", "date_of_birth", "gender", "gender_other", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."date_of_birth", NEW."gender", NEW."gender_other", NEW."id", NEW."name", _pgh_attach_context(), NOW(), \'client_household_member.update\', NEW."id", NEW."relationship_to_client", NEW."relationship_to_client_other", NEW."updated_at"); RETURN NULL;', hash='57919a2ab6e6e2ba7010d00775a3482c9036e7d8', operation='UPDATE', pgid='pgtrigger_client_household_member_update_update_cd31b', table='clients_clienthouseholdmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clienthouseholdmember',
            trigger=pgtrigger.compiler.Trigger(name='client_household_member_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clienthouseholdmemberevent" ("client_profile_id", "created_at", "date_of_birth", "gender", "gender_other", "id", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."date_of_birth", OLD."gender", OLD."gender_other", OLD."id", OLD."name", _pgh_attach_context(), NOW(), \'client_household_member.remove\', OLD."id", OLD."relationship_to_client", OLD."relationship_to_client_other", OLD."updated_at"); RETURN NULL;', hash='ad8e87ae3b98c490bc47134f4dab7c175cc63c25', operation='DELETE', pgid='pgtrigger_client_household_member_remove_delete_b6be6', table='clients_clienthouseholdmember', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientcontact',
            trigger=pgtrigger.compiler.Trigger(name='client_contact_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clientcontactevent" ("client_profile_id", "created_at", "email", "id", "mailing_address", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."email", NEW."id", NEW."mailing_address", NEW."name", _pgh_attach_context(), NOW(), \'client_contact.add\', NEW."id", NEW."phone_number", NEW."relationship_to_client", NEW."relationship_to_client_other", NEW."updated_at"); RETURN NULL;', hash='4c1bc3509a601b67bdf1e7ebc66654df29715d88', operation='INSERT', pgid='pgtrigger_client_contact_add_insert_1ed2a', table='clients_clientcontact', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientcontact',
            trigger=pgtrigger.compiler.Trigger(name='client_contact_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_clientcontactevent" ("client_profile_id", "created_at", "email", "id", "mailing_address", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."email", NEW."id", NEW."mailing_address", NEW."name", _pgh_attach_context(), NOW(), \'client_contact.update\', NEW."id", NEW."phone_number", NEW."relationship_to_client", NEW."relationship_to_client_other", NEW."updated_at"); RETURN NULL;', hash='0213c302391e6f8aa8ad36d2f2c703e098f581e9', operation='UPDATE', pgid='pgtrigger_client_contact_update_update_466d4', table='clients_clientcontact', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='clientcontact',
            trigger=pgtrigger.compiler.Trigger(name='client_contact_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_clientcontactevent" ("client_profile_id", "created_at", "email", "id", "mailing_address", "name", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "relationship_to_client", "relationship_to_client_other", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."email", OLD."id", OLD."mailing_address", OLD."name", _pgh_attach_context(), NOW(), \'client_contact.remove\', OLD."id", OLD."phone_number", OLD."relationship_to_client", OLD."relationship_to_client_other", OLD."updated_at"); RETURN NULL;', hash='6b46378ffda90c7e06120ecb7e7005678309c286', operation='DELETE', pgid='pgtrigger_client_contact_remove_delete_74c1b', table='clients_clientcontact', when='AFTER')),
        ),
        migrations.AddIndex(
            model_name='clientprofileimportrecord',
            index=models.Index(fields=['import_job', 'success', 'source_name', 'source_id'], name='clients_cli_import__dad092_idx'),
        ),
        migrations.AddConstraint(
            model_name='hmisprofile',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('hmis_id'), models.F('agency'), name='unique_hmis_id_agency'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hmisprofile',
            trigger=pgtrigger.compiler.Trigger(name='hmis_profile_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_hmisprofileevent" ("agency", "client_profile_id", "created_at", "hmis_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."agency", NEW."client_profile_id", NEW."created_at", NEW."hmis_id", NEW."id", _pgh_attach_context(), NOW(), \'hmis_profile.add\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='1b69ab5be08cbb60aa8ee2bfe5d2a9eececcf028', operation='INSERT', pgid='pgtrigger_hmis_profile_add_insert_cf767', table='clients_hmisprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hmisprofile',
            trigger=pgtrigger.compiler.Trigger(name='hmis_profile_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_hmisprofileevent" ("agency", "client_profile_id", "created_at", "hmis_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (NEW."agency", NEW."client_profile_id", NEW."created_at", NEW."hmis_id", NEW."id", _pgh_attach_context(), NOW(), \'hmis_profile.update\', NEW."id", NEW."updated_at"); RETURN NULL;', hash='0737cbe4cb6ee205f19f5ff61b3af0e99c63f9a2', operation='UPDATE', pgid='pgtrigger_hmis_profile_update_update_994eb', table='clients_hmisprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='hmisprofile',
            trigger=pgtrigger.compiler.Trigger(name='hmis_profile_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_hmisprofileevent" ("agency", "client_profile_id", "created_at", "hmis_id", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at") VALUES (OLD."agency", OLD."client_profile_id", OLD."created_at", OLD."hmis_id", OLD."id", _pgh_attach_context(), NOW(), \'hmis_profile.remove\', OLD."id", OLD."updated_at"); RETURN NULL;', hash='1e859a27534120b81a34c4ab2458b3900182649a', operation='DELETE', pgid='pgtrigger_hmis_profile_remove_delete_d3bb1', table='clients_hmisprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='socialmediaprofile',
            trigger=pgtrigger.compiler.Trigger(name='social_media_profile_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_socialmediaprofileevent" ("client_profile_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "platform_user_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'social_media_profile.add\', NEW."id", NEW."platform", NEW."platform_user_id", NEW."updated_at"); RETURN NULL;', hash='fc7294eacbd873d10ea26592aa8570e92663190e', operation='INSERT', pgid='pgtrigger_social_media_profile_add_insert_e7fca', table='clients_socialmediaprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='socialmediaprofile',
            trigger=pgtrigger.compiler.Trigger(name='social_media_profile_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "clients_socialmediaprofileevent" ("client_profile_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "platform_user_id", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."id", _pgh_attach_context(), NOW(), \'social_media_profile.update\', NEW."id", NEW."platform", NEW."platform_user_id", NEW."updated_at"); RETURN NULL;', hash='40af4970d03c5d3ad710f45815da164e1eb53f28', operation='UPDATE', pgid='pgtrigger_social_media_profile_update_update_1c76a', table='clients_socialmediaprofile', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='socialmediaprofile',
            trigger=pgtrigger.compiler.Trigger(name='social_media_profile_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "clients_socialmediaprofileevent" ("client_profile_id", "created_at", "id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "platform", "platform_user_id", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."id", _pgh_attach_context(), NOW(), \'social_media_profile.remove\', OLD."id", OLD."platform", OLD."platform_user_id", OLD."updated_at"); RETURN NULL;', hash='d95593f74d584c2552a845613d737e059100895b', operation='DELETE', pgid='pgtrigger_social_media_profile_remove_delete_4c47e', table='clients_socialmediaprofile', when='AFTER')),
        ),
    ]
