# Generated by Django 5.1.1 on 2024-09-17 22:09

import clients.enums
import django.db.models.deletion
import django_choices_field.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="mailing_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="clientprofile",
            name="residence_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name="SocialMediaProfile",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "platform",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("facebook", "Facebook"),
                            ("instagram", "Instagram"),
                            ("linkedin", "LinkedIn"),
                            ("snapchat", "Snapchat"),
                            ("tiktok", "TikTok"),
                            ("twitter", "Twitter"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        choices_enum=clients.enums.SocialMediaEnum,
                        max_length=9,
                    ),
                ),
                ("platform_user_id", models.CharField(max_length=100)),
                (
                    "client_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_media_profiles",
                        to="clients.clientprofile",
                    ),
                ),
            ],
        ),
    ]
