# Generated by Django 5.1.1 on 2024-09-18 14:59

import clients.enums
import django.contrib.postgres.fields
import django_choices_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0004_clienthouseholdmember_gender_other"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="ada_accommodation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_choices_field.fields.TextChoicesField(
                    choices=[
                        ("hearing", "Hearing"),
                        ("mobility", "Mobility"),
                        ("visual", "Visual"),
                        ("other", "Other"),
                    ],
                    choices_enum=clients.enums.AdaAccommodationEnum,
                    max_length=8,
                ),
                blank=True,
                null=True,
                size=None,
            ),
        ),
    ]
