# Generated by Django 5.1.3 on 2024-11-12 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0007_clientprofile_important_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="california_id",
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
