# Generated by Django 5.1.3 on 2024-11-21 00:08

from django.db import migrations


def update_demo_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ClientProfile = apps.get_model("clients", "ClientProfile")
    ClientProfileContentType = ContentType.objects.get_for_model(ClientProfile)
    demo_template = PermissionGroupTemplate.objects.get(name="Demo")

    perm_map = [
        perm.split(".")[1]
        for perm in [
            "clients.add_clientprofile",
        ]
    ]

    permissions = Permission.objects.filter(codename__in=perm_map, content_type=ClientProfileContentType)
    demo_template.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0039_add_demo_group"),
        ("clients", "0009_clientprofile_caseworker_crud_permissions"),
    ]

    operations = [
        migrations.RunPython(update_demo_permission_template),
    ]
