# Generated by Django 5.1.6 on 2025-02-07 00:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0011_remove_clientprofile_hmis_id"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProfileDataImport",
            fields=[
                ("id", models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ("imported_at", models.DateTimeField(auto_now_add=True)),
                ("source_file", models.CharField(max_length=255)),
                ("notes", models.TextField(blank=True, default="")),
                (
                    "imported_by",
                    models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProfileImportRecord",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_id", models.CharField(max_length=255)),
                ("raw_data", models.JSONField()),
                ("success", models.BooleanField(default=False)),
                ("error_message", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "client_profile",
                    models.ForeignKey(
                        blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to="clients.clientprofile"
                    ),
                ),
                (
                    "import_job",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="records",
                        to="clients.profiledataimport",
                    ),
                ),
            ],
            options={
                "indexes": [models.Index(fields=["import_job", "success"], name="clients_pro_import__eb8365_idx")],
                "unique_together": {("import_job", "source_id")},
            },
        ),
    ]
