# Generated by Django 5.1.6 on 2025-02-11 02:36

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0012_profiledataimport_profileimportrecord"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name="ProfileDataImport",
            new_name="ClientProfileDataImport",
        ),
        migrations.RenameModel(
            old_name="ProfileImportRecord",
            new_name="ClientProfileImportRecord",
        ),
        migrations.RenameIndex(
            model_name="clientprofileimportrecord",
            new_name="clients_cli_import__774cc6_idx",
            old_name="clients_pro_import__eb8365_idx",
        ),
    ]
