# Generated by Django 5.1.6 on 2025-02-25 21:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0015_remove_clientprofileimportrecord_clients_cli_import__774cc6_idx_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clientprofile",
            name="california_id",
            field=models.CharField(
                blank=True,
                max_length=8,
                null=True,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="California ID must be 1 letter followed by 7 numbers", regex="^[a-zA-Z]\\d{7}$"
                    )
                ],
            ),
        ),
    ]
