# Generated by Django 5.1.7 on 2025-03-28 18:31

from django.db import migrations


def copy_name_and_email_fields(apps, schema_editor):
    ClientProfile = apps.get_model("clients", "ClientProfile")

    # Copy name and email fields from client_profile.user to client_profile
    for client_profile in ClientProfile.objects.all():
        client_profile.first_name = client_profile.user.first_name
        client_profile.last_name = client_profile.user.last_name
        client_profile.middle_name = client_profile.user.middle_name
        client_profile.email = client_profile.user.email
        client_profile.save()


def clear_name_and_email_fields(apps, schema_editor):
    ClientProfile = apps.get_model("clients", "ClientProfile")

    # Clear name and email fields from client_profile.user to client_profile
    for client_profile in ClientProfile.objects.all():
        client_profile.first_name = None
        client_profile.last_name = None
        client_profile.middle_name = None
        client_profile.email = None
        client_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0020_clientprofile_name_email_fields"),
    ]

    operations = [
        migrations.RunPython(copy_name_and_email_fields, clear_name_and_email_fields),
    ]
