# Generated by Django 5.1.7 on 2025-03-28 18:31

from django.db import migrations

USER_FIELDS = ["first_name", "last_name", "middle_name", "email"]


def copy_name_and_email_fields(apps, schema_editor):
    ClientProfile = apps.get_model("clients", "ClientProfile")

    # Copy name and email fields from client_profile.user to client_profile
    for client_profile in ClientProfile.objects.all():
        for field in USER_FIELDS:
            if getattr(client_profile.user, field) is not None:
                setattr(client_profile, field, getattr(client_profile.user, field).strip())

        client_profile.save()


def clear_name_and_email_fields(apps, schema_editor):
    ClientProfile = apps.get_model("clients", "ClientProfile")

    # Clear name and email fields from client_profile.user to client_profile
    for client_profile in ClientProfile.objects.all():
        for field in USER_FIELDS:
            setattr(client_profile, field, None)

        client_profile.save()


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_clientprofile_ordering_make_user_optional"),
    ]

    operations = [
        migrations.RunPython(copy_name_and_email_fields, clear_name_and_email_fields),
    ]
