# Generated by Django 5.1.7 on 2025-03-30 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0021_clientprofile_name_email_fields_data"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clientprofile",
            options={"ordering": ["first_name"]},
        ),
    ]
