# Generated by Django 5.1.7 on 2025-03-25 18:03

from clients.permissions import ClientContactPermissions
from django.db import migrations


def create_permissions_if_not_exist(apps, schema_editor):
    ClientContact = apps.get_model("clients", "ClientContact")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ClientContactContentType = ContentType.objects.get_for_model(ClientContact)
    db_alias = schema_editor.connection.alias

    # Generate readable names based on the enum
    PERM_MAP = {perm.split(".")[1]: perm.label for perm in ClientContactPermissions}
    for codename, name in PERM_MAP.items():
        Permission.objects.using(db_alias).get_or_create(
            codename=codename,
            content_type=ClientContactContentType,
            defaults={"name": name, "content_type": ClientContactContentType},
        )


def update_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    ClientContact = apps.get_model("clients", "ClientContact")
    ClientContactContentType = ContentType.objects.get_for_model(ClientContact)
    caseworker_template = PermissionGroupTemplate.objects.get(name="Caseworker")

    perm_map = [
        perm.split(".")[1]
        for perm in [
            "clients.add_clientcontact",
            "clients.view_clientcontact",
            "clients.change_clientcontact",
            "clients.delete_clientcontact",
        ]
    ]

    permissions = Permission.objects.filter(codename__in=perm_map, content_type=ClientContactContentType)
    caseworker_template.permissions.add(*permissions)


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0023_clientprofile_user_required"),
    ]

    operations = [
        migrations.RunPython(create_permissions_if_not_exist),
        migrations.RunPython(update_caseworker_permission_template),
    ]
