# Generated by Django 5.2 on 2025-05-15 16:14

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0028_hmisprofile_case_insensitive_unique_constraint"),
    ]

    operations = [
        migrations.AddField(
            model_name="clientprofile",
            name="residence_geolocation",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name="clientprofileevent",
            name="residence_geolocation",
            field=django.contrib.gis.db.models.fields.PointField(blank=True, geography=True, null=True, srid=4326),
        ),
    ]
