# Generated by Django 6.0.2 on 2026-03-17 01:07

import django.contrib.postgres.fields
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("clients", "0032_remove_clientprofile_client_profile_add_insert_and_more"),
    ]

    operations = [
        pgtrigger.migrations.RemoveTrigger(
            model_name="clientprofile",
            name="client_profile_add_insert",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="clientprofile",
            name="client_profile_update_update",
        ),
        pgtrigger.migrations.RemoveTrigger(
            model_name="clientprofile",
            name="client_profile_remove_delete",
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="clientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="client_profile_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "adl_capacity", "california_id", "created_at", "criminal_history", "date_of_birth", "destination", "destination_other", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_other", "hair_color", "harm_reduction", "height_in_inches", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "middle_name", "nickname", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "status", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."address", NEW."adl_capacity", NEW."california_id", NEW."created_at", NEW."criminal_history", NEW."date_of_birth", NEW."destination", NEW."destination_other", NEW."email", NEW."eye_color", NEW."first_name", NEW."funding_source", NEW."funding_source_other", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."harm_reduction", NEW."height_in_inches", NEW."homelessness_notes", NEW."id", NEW."important_notes", NEW."income_annual", NEW."income_source", NEW."justice_involvement_details", NEW."last_name", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."medical_needs", NEW."medical_notes", NEW."middle_name", NEW."nickname", NEW."pets", NEW."pets_other", _pgh_attach_context(), NOW(), \'client_profile.add\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."requires_transportation", NEW."residence_address", NEW."residence_geolocation", NEW."sexual_orientation", NEW."sexual_orientation_other", NEW."social_security_number", NEW."spa", NEW."spoken_languages", NEW."status", NEW."updated_at", NEW."veteran_status"); RETURN NULL;',
                    hash="b6ae19d8dd766ba9c69875c47bb7840f88deb66a",
                    operation="INSERT",
                    pgid="pgtrigger_client_profile_add_insert_4c2ed",
                    table="clients_clientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="clientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="client_profile_update_update",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    condition="WHEN (OLD.* IS DISTINCT FROM NEW.*)",
                    func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "adl_capacity", "california_id", "created_at", "criminal_history", "date_of_birth", "destination", "destination_other", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_other", "hair_color", "harm_reduction", "height_in_inches", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "middle_name", "nickname", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "status", "updated_at", "veteran_status") VALUES (NEW."ada_accommodation", NEW."address", NEW."adl_capacity", NEW."california_id", NEW."created_at", NEW."criminal_history", NEW."date_of_birth", NEW."destination", NEW."destination_other", NEW."email", NEW."eye_color", NEW."first_name", NEW."funding_source", NEW."funding_source_other", NEW."gender", NEW."gender_other", NEW."hair_color", NEW."harm_reduction", NEW."height_in_inches", NEW."homelessness_notes", NEW."id", NEW."important_notes", NEW."income_annual", NEW."income_source", NEW."justice_involvement_details", NEW."last_name", NEW."living_situation", NEW."mailing_address", NEW."marital_status", NEW."medical_needs", NEW."medical_notes", NEW."middle_name", NEW."nickname", NEW."pets", NEW."pets_other", _pgh_attach_context(), NOW(), \'client_profile.update\', NEW."id", NEW."phone_number", NEW."physical_description", NEW."place_of_birth", NEW."preferred_communication", NEW."preferred_language", NEW."profile_photo", NEW."pronouns", NEW."pronouns_other", NEW."race", NEW."requires_transportation", NEW."residence_address", NEW."residence_geolocation", NEW."sexual_orientation", NEW."sexual_orientation_other", NEW."social_security_number", NEW."spa", NEW."spoken_languages", NEW."status", NEW."updated_at", NEW."veteran_status"); RETURN NULL;',
                    hash="d05c4805af5ce8ebf90ab653d4fa9816d23e56db",
                    operation="UPDATE",
                    pgid="pgtrigger_client_profile_update_update_858fb",
                    table="clients_clientprofile",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="clientprofile",
            trigger=pgtrigger.compiler.Trigger(
                name="client_profile_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "clients_clientprofileevent" ("ada_accommodation", "address", "adl_capacity", "california_id", "created_at", "criminal_history", "date_of_birth", "destination", "destination_other", "email", "eye_color", "first_name", "funding_source", "funding_source_other", "gender", "gender_other", "hair_color", "harm_reduction", "height_in_inches", "homelessness_notes", "id", "important_notes", "income_annual", "income_source", "justice_involvement_details", "last_name", "living_situation", "mailing_address", "marital_status", "medical_needs", "medical_notes", "middle_name", "nickname", "pets", "pets_other", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "phone_number", "physical_description", "place_of_birth", "preferred_communication", "preferred_language", "profile_photo", "pronouns", "pronouns_other", "race", "requires_transportation", "residence_address", "residence_geolocation", "sexual_orientation", "sexual_orientation_other", "social_security_number", "spa", "spoken_languages", "status", "updated_at", "veteran_status") VALUES (OLD."ada_accommodation", OLD."address", OLD."adl_capacity", OLD."california_id", OLD."created_at", OLD."criminal_history", OLD."date_of_birth", OLD."destination", OLD."destination_other", OLD."email", OLD."eye_color", OLD."first_name", OLD."funding_source", OLD."funding_source_other", OLD."gender", OLD."gender_other", OLD."hair_color", OLD."harm_reduction", OLD."height_in_inches", OLD."homelessness_notes", OLD."id", OLD."important_notes", OLD."income_annual", OLD."income_source", OLD."justice_involvement_details", OLD."last_name", OLD."living_situation", OLD."mailing_address", OLD."marital_status", OLD."medical_needs", OLD."medical_notes", OLD."middle_name", OLD."nickname", OLD."pets", OLD."pets_other", _pgh_attach_context(), NOW(), \'client_profile.remove\', OLD."id", OLD."phone_number", OLD."physical_description", OLD."place_of_birth", OLD."preferred_communication", OLD."preferred_language", OLD."profile_photo", OLD."pronouns", OLD."pronouns_other", OLD."race", OLD."requires_transportation", OLD."residence_address", OLD."residence_geolocation", OLD."sexual_orientation", OLD."sexual_orientation_other", OLD."social_security_number", OLD."spa", OLD."spoken_languages", OLD."status", OLD."updated_at", OLD."veteran_status"); RETURN NULL;',
                    hash="6cdefe90fd04990f635efe8e11555b0c5188763f",
                    operation="DELETE",
                    pgid="pgtrigger_client_profile_remove_delete_ade5a",
                    table="clients_clientprofile",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AlterField(
            model_name="clientprofile",
            name="sexual_orientation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_choices_field.fields.TextChoicesField(
                    choices=[
                        ("asexual", "Asexual"),
                        ("bisexual", "Bisexual"),
                        ("gay", "Gay"),
                        ("straight", "Straight (heterosexual)"),
                        ("lesbian", "Lesbian"),
                        ("pansexual", "Pansexual"),
                        ("queer", "Queer"),
                        ("other", "Other"),
                        ("prefer_not_to_say", "Prefer Not to Say"),
                    ],
                    max_length=17,
                ),
                blank=True,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="clientprofileevent",
            name="sexual_orientation",
            field=django.contrib.postgres.fields.ArrayField(
                base_field=django_choices_field.fields.TextChoicesField(
                    choices=[
                        ("asexual", "Asexual"),
                        ("bisexual", "Bisexual"),
                        ("gay", "Gay"),
                        ("straight", "Straight (heterosexual)"),
                        ("lesbian", "Lesbian"),
                        ("pansexual", "Pansexual"),
                        ("queer", "Queer"),
                        ("other", "Other"),
                        ("prefer_not_to_say", "Prefer Not to Say"),
                    ],
                    max_length=17,
                ),
                blank=True,
                null=True,
            ),
        ),
    ]
