from _typeshed import Incomplete
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth.provider import OAuthProvider as OAuthProvider

class TrelloAccount(ProviderAccount):
    def get_profile_url(self) -> None: ...
    def get_avatar_url(self) -> None: ...

class TrelloProvider(OAuthProvider):
    id: str
    name: str
    account_class = TrelloAccount
    def get_default_scope(self): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...
    def get_auth_params(self, request, action): ...

provider_classes: Incomplete
