# Generated by Django 6.0.6 on 2026-08-17 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('teams', '0003_remove_team_unique_team_slug_per_org_and_more'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='team',
            constraint=models.UniqueConstraint(models.F('id'), models.F('organization'), name='unique_team_id_per_org'),
        ),
    ]
