# Generated by Django 6.1 on 2026-09-01 13:02

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0006_alter_organization_slug'),
        ('teams', '0003_remove_team_unique_team_slug_per_org_and_more'),
    ]

    operations = [
        migrations.AlterConstraint(
            model_name='team',
            name='unique_team_name_per_org',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('name'), models.F('organization'), name='unique_team_name_per_org', violation_error_message='A team with this name already exists in this organization.'),
        ),
    ]
