query OperatorShelters(
  $pagination: OffsetPaginationInput
  $filters: ShelterFilter
  $ordering: [ShelterOrder!]! = []
) {
  operatorShelters(
    filters: $filters
    ordering: $ordering
    pagination: $pagination
  ) {
    totalCount
    results {
      id
      name
      location {
        place
      }
      status
      totalBeds
      bedCounts {
        available
        inTurnaround
        occupied
        outOfService
        reserved
        total
      }
      demographics {
        name
      }
      specialSituationRestrictions {
        name
      }
      shelterTypes {
        name
      }
      city {
        name
      }
      spa {
        id
        name
      }
    }
  }
}

query OperatorShelterSummary($id: ID!) {
  operatorShelter(pk: $id) {
    id
    name
    location {
      place
    }
  }
}
