# Generated by Django 4.2.4 on 2023-08-25 23:30

from django.contrib.postgres.operations import CreateExtension
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = []

    operations = [CreateExtension("postgis")]
