# Generated by Django 6.0.6 on 2026-07-16 21:03

import django.db.models.deletion
import pgtrigger.compiler
import pgtrigger.migrations
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients', '0002_initial'),
        ('organizations', '0001_initial'),
        ('pghistory', '0007_auto_20250421_0444'),
        ('referrals', '0001_initial'),
        ('shelters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='referral',
            name='shelter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='referrals', to='shelters.shelter'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='client_profile',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='clients.clientprofile'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='created_by',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='organization',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='organizations.organization'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='pgh_context',
            field=models.ForeignKey(db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='pghistory.context'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='pgh_obj',
            field=models.ForeignKey(db_constraint=False, on_delete=django.db.models.deletion.DO_NOTHING, related_name='events', to='referrals.referral'),
        ),
        migrations.AddField(
            model_name='referralevent',
            name='shelter',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', related_query_name='+', to='shelters.shelter'),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='referral_add_insert', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "referrals_referralevent" ("client_profile_id", "created_at", "created_by_id", "id", "notes", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."notes", NEW."organization_id", _pgh_attach_context(), NOW(), \'referral.add\', NEW."id", NEW."shelter_id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='cc4db81fbbd0cd6053b7f321b339b73e473a4bf2', operation='INSERT', pgid='pgtrigger_referral_add_insert_76a5f', table='referrals_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='referral_update_update', sql=pgtrigger.compiler.UpsertTriggerSql(condition='WHEN (OLD.* IS DISTINCT FROM NEW.*)', func='INSERT INTO "referrals_referralevent" ("client_profile_id", "created_at", "created_by_id", "id", "notes", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id", "status", "updated_at") VALUES (NEW."client_profile_id", NEW."created_at", NEW."created_by_id", NEW."id", NEW."notes", NEW."organization_id", _pgh_attach_context(), NOW(), \'referral.update\', NEW."id", NEW."shelter_id", NEW."status", NEW."updated_at"); RETURN NULL;', hash='869539e743851d27280841717a2af9e2cb5b4b25', operation='UPDATE', pgid='pgtrigger_referral_update_update_f9df9', table='referrals_referral', when='AFTER')),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name='referral',
            trigger=pgtrigger.compiler.Trigger(name='referral_remove_delete', sql=pgtrigger.compiler.UpsertTriggerSql(func='INSERT INTO "referrals_referralevent" ("client_profile_id", "created_at", "created_by_id", "id", "notes", "organization_id", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "shelter_id", "status", "updated_at") VALUES (OLD."client_profile_id", OLD."created_at", OLD."created_by_id", OLD."id", OLD."notes", OLD."organization_id", _pgh_attach_context(), NOW(), \'referral.remove\', OLD."id", OLD."shelter_id", OLD."status", OLD."updated_at"); RETURN NULL;', hash='0a2addd3fd886697a51e308e0405ee4a428f9db5', operation='DELETE', pgid='pgtrigger_referral_remove_delete_c327f', table='referrals_referral', when='AFTER')),
        ),
    ]
