# Generated by Django 6.0.6 on 2026-09-08 00:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('referrals', '0002_initial'),
        ('shelters', '0002_shelter_schedule_idx'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralTestShelter',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('key', models.CharField(max_length=64, primary_key=True, serialize=False)),
                ('shelter', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='shelters.shelter')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
