from _typeshed import Incomplete

class AppSettings:
    prefix: Incomplete
    def __init__(self, prefix) -> None: ...
    @property
    def QUERY_EMAIL(self): ...
    @property
    def AUTO_SIGNUP(self): ...
    @property
    def PROVIDERS(self): ...
    @property
    def EMAIL_REQUIRED(self): ...
    @property
    def EMAIL_VERIFICATION(self): ...
    @property
    def ADAPTER(self): ...
    @property
    def FORMS(self): ...
    @property
    def LOGIN_ON_GET(self): ...
    @property
    def STORE_TOKENS(self): ...
    @property
    def UID_MAX_LENGTH(self): ...
    @property
    def SOCIALACCOUNT_STR(self): ...

app_settings: Incomplete
