// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { HmisNoteQuery } from './getClientNoteHmis.generated';

export const hmisNoteOperationKey: keyof Omit<HmisNoteQuery, '__typename'> = 'hmisNote';
export const hmisNoteSuccessTypename: Extract<
  NonNullable<HmisNoteQuery['hmisNote']>,
  { __typename: 'HmisNoteType' }
>['__typename'] = 'HmisNoteType';

export const hmisNoteMeta = {
  operationKey: hmisNoteOperationKey,
  successTypename: hmisNoteSuccessTypename,
} as const;
