// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { ClientProfileQuery } from './Client.generated';
import type { UpdateClientDocumentMutation } from './Client.generated';
import type { DeleteClientDocumentMutation } from './Client.generated';
import type { UpdateClientProfilePhotoMutation } from './Client.generated';

export const clientProfileOperationKey: keyof Omit<ClientProfileQuery, '__typename'> = 'clientProfile';
export const clientProfileSuccessTypename: Extract<
  NonNullable<ClientProfileQuery['clientProfile']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<ClientProfileQuery['clientProfile']>,
  { __typename: 'ClientProfileType' }
>['__typename'] = 'ClientProfileType';

export const clientProfileMeta = {
  operationKey: clientProfileOperationKey,
  successTypename: clientProfileSuccessTypename,
} as const;

export const updateClientDocumentOperationKey: keyof Omit<UpdateClientDocumentMutation, '__typename'> = 'updateClientDocument';
export const updateClientDocumentSuccessTypename: Extract<
  NonNullable<UpdateClientDocumentMutation['updateClientDocument']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<UpdateClientDocumentMutation['updateClientDocument']>,
  { __typename: 'ClientDocumentType' }
>['__typename'] = 'ClientDocumentType';

export const updateClientDocumentMeta = {
  operationKey: updateClientDocumentOperationKey,
  successTypename: updateClientDocumentSuccessTypename,
} as const;

export const deleteClientDocumentOperationKey: keyof Omit<DeleteClientDocumentMutation, '__typename'> = 'deleteClientDocument';
export const deleteClientDocumentSuccessTypename: Extract<
  NonNullable<DeleteClientDocumentMutation['deleteClientDocument']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<DeleteClientDocumentMutation['deleteClientDocument']>,
  { __typename: 'ClientDocumentType' }
>['__typename'] = 'ClientDocumentType';

export const deleteClientDocumentMeta = {
  operationKey: deleteClientDocumentOperationKey,
  successTypename: deleteClientDocumentSuccessTypename,
} as const;

export const updateClientProfilePhotoOperationKey: keyof Omit<UpdateClientProfilePhotoMutation, '__typename'> = 'updateClientProfilePhoto';
export const updateClientProfilePhotoSuccessTypename: Extract<
  NonNullable<UpdateClientProfilePhotoMutation['updateClientProfilePhoto']> extends readonly (infer _T)[]
    ? _T
    : NonNullable<UpdateClientProfilePhotoMutation['updateClientProfilePhoto']>,
  { __typename: 'ClientProfileType' }
>['__typename'] = 'ClientProfileType';

export const updateClientProfilePhotoMeta = {
  operationKey: updateClientProfilePhotoOperationKey,
  successTypename: updateClientProfilePhotoSuccessTypename,
} as const;
