from ..base import AuthError as AuthError
from .forms import LoginForm as LoginForm
from .provider import OpenIDProvider as OpenIDProvider
from .utils import AXAttributes as AXAttributes, DBOpenIDStore as DBOpenIDStore, JSONSafeSession as JSONSafeSession, SRegFields as SRegFields
from _typeshed import Incomplete
from allauth.socialaccount import providers as providers
from allauth.socialaccount.app_settings import QUERY_EMAIL as QUERY_EMAIL
from allauth.socialaccount.helpers import complete_social_login as complete_social_login, render_authentication_error as render_authentication_error
from allauth.socialaccount.models import SocialLogin as SocialLogin
from django.views import View

class OpenIDLoginView(View):
    template_name: str
    form_class = LoginForm
    provider = OpenIDProvider
    def get(self, request): ...
    def post(self, request): ...
    def get_form(self): ...
    def get_client(self, provider, endpoint): ...
    def get_realm(self, provider): ...
    def get_callback_url(self): ...
    def perform_openid_auth(self, form): ...

login: Incomplete

class OpenIDCallbackView(View):
    provider = OpenIDProvider
    def get(self, request): ...
    post = get
    def complete_login(self, login): ...
    def render_error(self, error): ...
    def get_client(self, provider, endpoint): ...
    def get_openid_response(self, client): ...

callback: Incomplete
