"""
This type stub file was generated by pyright.
"""

"""
Native thread-based hostname resolver.
"""
__all__ = ['Resolver']
class Resolver:
    """
    Implementation of the resolver API using native threads and native resolution
    functions.

    Using the native resolution mechanisms ensures the highest
    compatibility with what a non-gevent program would return
    including good support for platform specific configuration
    mechanisms. The use of native (non-greenlet) threads ensures that
    a caller doesn't block other greenlets.

    This implementation also has the benefit of being very simple in comparison to
    :class:`gevent.resolver_ares.Resolver`.

    .. tip::

        Most users find this resolver to be quite reliable in a
        properly monkey-patched environment. However, there have been
        some reports of long delays, slow performance or even hangs,
        particularly in long-lived programs that make many, many DNS
        requests. If you suspect that may be happening to you, try the
        dnspython or ares resolver (and submit a bug report).
    """
    def __init__(self, hub=...) -> None:
        ...
    
    def __repr__(self): # -> str:
        ...
    
    def close(self): # -> None:
        ...
    
    def gethostbyname(self, *args):
        ...
    
    def gethostbyname_ex(self, *args):
        ...
    
    def getaddrinfo(self, *args, **kwargs):
        ...
    
    def gethostbyaddr(self, *args, **kwargs):
        ...
    
    def getnameinfo(self, *args, **kwargs):
        ...
    


