name: 'Check env'
description: 'Verify .env contents'

inputs:
  project:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Perform env check
      id: perform-env-check
      run: |
        echo pwd $pwd
        echo ls
        ls -al

        cat .env_2

      shell: bash
      working-directory: apps/${{ inputs.project }}
