name: 'Check env'
description: 'Verify .env contents'

inputs:
  project:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Perform env check
      id: perform-env-check
      run: |
        echo pwd $pwd
        echo ls
        ls -al

        MAESTRO_GROUP_ID=$(grep '^MAESTRO_GROUP_ID=' .env | cut -d '=' -f2-)
        echo MAESTRO_GROUP_ID $MAESTRO_GROUP_ID
        MAESTRO_PROJECT_ID=$(grep '^MAESTRO_PROJECT_ID=' .env | cut -d '=' -f2-)
        echo MAESTRO_PROJECT_ID $MAESTRO_PROJECT_ID
        RUNTIME_VERSION=$(grep '^RUNTIME_VERSION=' .env | cut -d '=' -f2-)
        echo RUNTIME_VERSION $RUNTIME_VERSION
      shell: bash
      working-directory: apps/${{ inputs.project }}
