from allauth.socialaccount.providers.oauth2.views import OAuth2Adapter as OAuth2Adapter

class OpenIDConnectAdapter(OAuth2Adapter):
    supports_state: bool
    provider_id: str
    @property
    def openid_config(self): ...
    @property
    def basic_auth(self): ...
    @property
    def access_token_url(self): ...
    @property
    def authorize_url(self): ...
    @property
    def profile_url(self): ...
    def complete_login(self, request, app, token, response): ...
