from _typeshed import Incomplete

def default_org_model(): ...
def model_field_names(model): ...
def create_organization(user, name, slug: Incomplete | None = ..., is_active: Incomplete | None = ..., org_defaults: Incomplete | None = ..., org_user_defaults: Incomplete | None = ..., **kwargs): ...
def model_field_attr(model, model_field, attr): ...
