// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { TeamsQuery } from './teams.generated';

export const teamsOperationKey: keyof Omit<TeamsQuery, '__typename'> = 'teams';
export const teamsSuccessTypename: Extract<
  NonNullable<TeamsQuery['teams']>,
  { __typename: 'TeamTypeOffsetPaginated' }
>['__typename'] = 'TeamTypeOffsetPaginated';

export const teamsMeta = {
  operationKey: teamsOperationKey,
  successTypename: teamsSuccessTypename,
} as const;
