from _typeshed import Incomplete
from allauth.socialaccount.providers.base import AuthAction as AuthAction, ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth.provider import OAuthProvider as OAuthProvider

class TwitterAccount(ProviderAccount):
    def get_screen_name(self): ...
    def get_profile_url(self): ...
    def get_avatar_url(self): ...
    def to_str(self): ...

class TwitterProvider(OAuthProvider):
    id: str
    name: str
    account_class = TwitterAccount
    def get_auth_url(self, request, action): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...

provider_classes: Incomplete
