from _typeshed import Incomplete
from allauth.socialaccount.providers.openid.provider import OpenIDAccount as OpenIDAccount, OpenIDProvider as OpenIDProvider

class SteamAccount(OpenIDAccount):
    def to_str(self): ...
    def get_profile_url(self): ...
    def get_avatar_url(self): ...

def extract_steam_id(url): ...
def request_steam_account_summary(api_key, steam_id): ...

class SteamOpenIDProvider(OpenIDProvider):
    id: str
    name: str
    account_class = SteamAccount
    def get_login_url(self, request, **kwargs): ...
    def sociallogin_from_response(self, request, response): ...
    def extract_uid(self, response): ...
    def extract_extra_data(self, response): ...
    def extract_common_fields(self, response): ...

provider_classes: Incomplete
