# Generated by Django 4.2.11 on 2024-03-14 18:42

import common.enums
import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("contenttypes", "0002_remove_content_type_name"),
        ("common", "0004_remove_simplemodel"),
    ]

    operations = [
        migrations.CreateModel(
            name="Attachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        editable=False, primary_key=True, serialize=False, unique=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=common.utils.get_unique_file_path)),
                (
                    "file_type",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("unknown", "Unknown"),
                        ],
                        choices_enum=common.enums.FileType,
                        max_length=8,
                    ),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("namespace", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AttachmentGroupObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.attachment",
                    ),
                ),
                (
                    "group",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="auth.group"
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("group", "permission", "content_object")},
            },
        ),
        migrations.CreateModel(
            name="AttachmentUserObjectPermission",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "content_object",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="common.attachment",
                    ),
                ),
                (
                    "permission",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="auth.permission",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
                "unique_together": {("user", "permission", "content_object")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="simplemodelgroupobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="simplemodelgroupobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="simplemodelgroupobjectpermission",
            name="group",
        ),
        migrations.RemoveField(
            model_name="simplemodelgroupobjectpermission",
            name="permission",
        ),
        migrations.AlterUniqueTogether(
            name="simplemodeluserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="simplemodeluserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="simplemodeluserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="simplemodeluserobjectpermission",
            name="user",
        ),
        migrations.AlterField(
            model_name="location",
            name="id",
            field=models.BigAutoField(
                editable=False, primary_key=True, serialize=False, unique=True
            ),
        ),
        migrations.DeleteModel(
            name="SimpleModel",
        ),
        migrations.DeleteModel(
            name="SimpleModelGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="SimpleModelUserObjectPermission",
        ),
        migrations.AddIndex(
            model_name="attachment",
            index=models.Index(
                fields=["object_id", "content_type_id", "namespace", "file_type"],
                name="attachment_comp_idx",
            ),
        ),
    ]
