# Generated by Django 4.2.11 on 2024-04-01 22:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0006_address_and_address_permissions"),
        ("auth", "0012_alter_user_first_name_max_length"),
        ("notes", "0018_add_point_to_note_and_task"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Location",
        ),
        migrations.AddField(
            model_name="addressuserobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.address"
            ),
        ),
        migrations.AddField(
            model_name="addressuserobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddField(
            model_name="addressuserobjectpermission",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="addressgroupobjectpermission",
            name="content_object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="common.address"
            ),
        ),
        migrations.AddField(
            model_name="addressgroupobjectpermission",
            name="group",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.group"
            ),
        ),
        migrations.AddField(
            model_name="addressgroupobjectpermission",
            name="permission",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="auth.permission"
            ),
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(
                fields=[
                    "street",
                    "city",
                    "state",
                    "zip_code",
                    "address_components",
                    "formatted_address",
                ],
                name="address_index",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="addressuserobjectpermission",
            unique_together={("user", "permission", "content_object")},
        ),
        migrations.AlterUniqueTogether(
            name="addressgroupobjectpermission",
            unique_together={("group", "permission", "content_object")},
        ),
    ]
