# Generated by Django 4.2.11 on 2024-04-03 02:16

import common.enums
import common.utils
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django_choices_field.fields
import pgtrigger.compiler
import pgtrigger.migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("pghistory", "0006_delete_aggregateevent"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("common", "0007_delete_location_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttachmentEvent",
            fields=[
                ("pgh_id", models.AutoField(primary_key=True, serialize=False)),
                ("pgh_created_at", models.DateTimeField(auto_now_add=True)),
                ("pgh_label", models.TextField(help_text="The event label.")),
                ("id", models.IntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("file", models.FileField(upload_to=common.utils.get_unique_file_path)),
                (
                    "attachment_type",
                    django_choices_field.fields.TextChoicesField(
                        choices=[
                            ("image", "Image"),
                            ("document", "Document"),
                            ("audio", "Audio"),
                            ("video", "Video"),
                            ("unknown", "Unknown"),
                        ],
                        choices_enum=common.enums.AttachmentType,
                        max_length=8,
                    ),
                ),
                (
                    "original_filename",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("object_id", models.PositiveIntegerField()),
                ("namespace", models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="attachment",
            trigger=pgtrigger.compiler.Trigger(
                name="attachment_add_insert",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "common_attachmentevent" ("associated_with_id", "attachment_type", "content_type_id", "created_at", "file", "id", "namespace", "object_id", "original_filename", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "uploaded_by_id") VALUES (NEW."associated_with_id", NEW."attachment_type", NEW."content_type_id", NEW."created_at", NEW."file", NEW."id", NEW."namespace", NEW."object_id", NEW."original_filename", _pgh_attach_context(), NOW(), \'attachment.add\', NEW."id", NEW."updated_at", NEW."uploaded_by_id"); RETURN NULL;',
                    hash="585c9f2c7c00cafa6b1f962554abfbbc85eefd75",
                    operation="INSERT",
                    pgid="pgtrigger_attachment_add_insert_7c67a",
                    table="common_attachment",
                    when="AFTER",
                ),
            ),
        ),
        pgtrigger.migrations.AddTrigger(
            model_name="attachment",
            trigger=pgtrigger.compiler.Trigger(
                name="attachment_remove_delete",
                sql=pgtrigger.compiler.UpsertTriggerSql(
                    func='INSERT INTO "common_attachmentevent" ("associated_with_id", "attachment_type", "content_type_id", "created_at", "file", "id", "namespace", "object_id", "original_filename", "pgh_context_id", "pgh_created_at", "pgh_label", "pgh_obj_id", "updated_at", "uploaded_by_id") VALUES (OLD."associated_with_id", OLD."attachment_type", OLD."content_type_id", OLD."created_at", OLD."file", OLD."id", OLD."namespace", OLD."object_id", OLD."original_filename", _pgh_attach_context(), NOW(), \'attachment.remove\', OLD."id", OLD."updated_at", OLD."uploaded_by_id"); RETURN NULL;',
                    hash="da553e83577b66a477c40d7612ea9a670f6a12ff",
                    operation="DELETE",
                    pgid="pgtrigger_attachment_remove_delete_e6350",
                    table="common_attachment",
                    when="AFTER",
                ),
            ),
        ),
        migrations.AddField(
            model_name="attachmentevent",
            name="associated_with",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="attachmentevent",
            name="content_type",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AddField(
            model_name="attachmentevent",
            name="pgh_context",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                to="pghistory.context",
            ),
        ),
        migrations.AddField(
            model_name="attachmentevent",
            name="pgh_obj",
            field=models.ForeignKey(
                db_constraint=False,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="events",
                to="common.attachment",
            ),
        ),
        migrations.AddField(
            model_name="attachmentevent",
            name="uploaded_by",
            field=models.ForeignKey(
                db_constraint=False,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="+",
                related_query_name="+",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
