# Generated by Django 5.0.4 on 2024-05-10 18:29

from django.db import migrations


def update_caseworker_permission_template(apps, schema_editor):
    PermissionGroupTemplate = apps.get_model("accounts", "PermissionGroupTemplate")
    Permission = apps.get_model("auth", "Permission")
    ContentType = apps.get_model("contenttypes", "ContentType")
    caseworker_template = PermissionGroupTemplate.objects.get(name="Caseworker")

    Address = apps.get_model("common", "Address")
    AddressContentType = ContentType.objects.get_for_model(Address)
    address_perm_map = [
        perm.split(".")[1]
        for perm in [
            "common.add_address",
            "common.view_address",
        ]
    ]
    permissions = list(Permission.objects.filter(codename__in=address_perm_map, content_type=AddressContentType))

    Location = apps.get_model("common", "Location")
    LocationContentType = ContentType.objects.get_for_model(Location)
    location_perm_map = [
        perm.split(".")[1]
        for perm in [
            "common.add_location",
            "common.view_location",
        ]
    ]
    permissions.extend(Permission.objects.filter(codename__in=location_perm_map, content_type=LocationContentType))

    caseworker_template.permissions.remove(*permissions)


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0001_squashed_0010_location_and_location_permissions"),
    ]

    operations = [migrations.RunPython(update_caseworker_permission_template)]
