# Generated by Django 5.0.4 on 2024-05-10 18:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("common", "0011_remove_caseworker_location_permissions"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="locationuserobjectpermission",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="locationuserobjectpermission",
            name="content_object",
        ),
        migrations.RemoveField(
            model_name="locationuserobjectpermission",
            name="permission",
        ),
        migrations.RemoveField(
            model_name="locationuserobjectpermission",
            name="user",
        ),
        migrations.DeleteModel(
            name="LocationGroupObjectPermission",
        ),
        migrations.DeleteModel(
            name="LocationUserObjectPermission",
        ),
    ]
