# Generated by Django 5.0.6 on 2024-07-10 22:29

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0012_alter_locationuserobjectpermission_unique_together_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="confidential",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attachment",
            name="associated_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="location",
            name="point",
            field=django.contrib.gis.db.models.fields.PointField(default=0, geography=True, srid=4326),
            preserve_default=False,
        ),
    ]
