# Generated by Django 5.0.6 on 2024-07-11 01:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0013_alter_location_point"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="confidential",
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="attachment",
            name="associated_with",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="associated_attachments",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
