# Generated by Django 5.0.6 on 2024-07-04 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0014_alter_attachment_associated_with"),
    ]

    operations = [
        migrations.AddField(
            model_name="attachment",
            name="mime_type",
            field=models.CharField(default=""),
            preserve_default=False,
        ),
    ]
