# Generated by Django 5.0.6 on 2024-07-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0015_attachment_mime_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="confidential",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
