# Generated by Django 5.0.6 on 2024-07-10 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_location_confidential"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="location",
            name="confidential",
        ),
        migrations.AddField(
            model_name="address",
            name="confidential",
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
