# Generated by Django 5.2 on 2025-04-21 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0016_auto_20241121_1844"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="attachment",
            name="associated_with",
        ),
    ]
