# Generated by Django 5.2 on 2025-05-27 19:13

import mimetypes
from django.db import migrations


def append_correct_extension(apps, schema_editor):
    Attachment = apps.get_model("common", "Attachment")
    table = Attachment._meta.db_table
    cursor = schema_editor.connection.cursor()

    for (mime_type,) in Attachment.objects.values_list("mime_type").distinct():
        ext = mimetypes.guess_extension(mime_type)
        if not ext:
            continue

        cursor.execute(
            f"""
            UPDATE "{table}"
            SET original_filename = original_filename || {ext}
            WHERE mime_type = {mime_type}
            AND original_filename IS NOT NULL
            AND RIGHT(original_filename, CHAR_LENGTH({ext})) <> {ext};
            """
        )


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0017_remove_attachment_associated_with"),
    ]

    operations = [migrations.RunPython(append_correct_extension, migrations.RunPython.noop)]
