# Generated by Django 6.0.2 on 2026-02-11 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_fix_file_extensions"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="address",
            name="address_index",
        ),
        migrations.AddIndex(
            model_name="address",
            index=models.Index(fields=["street", "city", "state", "zip_code"], name="address_lookup_idx"),
        ),
        migrations.RemoveField(
            model_name="address",
            name="address_components",
        ),
    ]
