# Generated by Django 6.0.2 on 2026-02-06 03:45

import common.utils
import s3_file_field.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0018_fix_file_extensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attachment",
            name="file",
            field=s3_file_field.fields.S3FileField(upload_to=common.utils.get_unique_file_path),
        ),
    ]
