# Generated by Django 6.0.2

import django.db.models.functions.text
from django.db import migrations, models


def deduplicate_formatted_addresses(apps, schema_editor):
    """Merge Address rows that share the same formatted_address (case-insensitive).

    For each group of duplicates, keeps the row with the most non-null
    component fields (street, city, state, zip_code), re-points all
    Location FKs to it, and deletes the rest.
    """
    Address = apps.get_model("common", "Address")
    Location = apps.get_model("common", "Location")

    from django.db.models import Count
    from django.db.models.functions import Lower

    dupes = (
        Address.objects.filter(formatted_address__isnull=False)
        .values(lower_fa=Lower("formatted_address"))
        .annotate(cnt=Count("id"))
        .filter(cnt__gt=1)
    )

    for group in dupes:
        rows = list(Address.objects.filter(formatted_address__iexact=group["lower_fa"]).order_by("id"))
        if len(rows) < 2:
            continue

        def richness(addr):
            return sum(1 for f in ("street", "city", "state", "zip_code") if getattr(addr, f))

        rows.sort(key=lambda a: (-richness(a), a.pk))
        keeper = rows[0]

        for dup in rows[1:]:
            Location.objects.filter(address_id=dup.pk).update(address_id=keeper.pk)
            dup.delete()


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_address_functional_index"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_components",
        ),
        migrations.RunPython(
            deduplicate_formatted_addresses,
            migrations.RunPython.noop,
            elidable=True,
        ),
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("formatted_address"),
                condition=models.Q(("formatted_address__isnull", False)),
                name="unique_formatted_address",
            ),
        ),
    ]
