# Generated by Django 6.0.2 on 2026-02-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0020_address_functional_index"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(fields=("point",), name="unique_location_point"),
        ),
    ]
