# Generated by Django 6.0.2 on 2026-02-26 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_location_unique_location_point"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="address",
            name="address_components",
        ),
    ]
