# Generated by Django 6.0.2

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0021_remove_address_components_add_unique_formatted_address"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="address",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("formatted_address"),
                condition=models.Q(("formatted_address__isnull", False)),
                name="unique_formatted_address",
            ),
        ),
    ]
