# Generated by Django 6.0.2 on 2026-02-26 22:26

from django.db import migrations


def remove_address_components_if_exists(apps, schema_editor):
    """Remove address_components column only if it exists (idempotent)."""
    schema_editor.execute(
        "ALTER TABLE common_address DROP COLUMN IF EXISTS address_components"
    )


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ("common", "0022_add_unique_formatted_address_constraint"),
    ]

    operations = [
        migrations.SeparateDatabaseAndState(
            state_operations=[],
            database_operations=[
                migrations.RunPython(remove_address_components_if_exists, reverse_code=noop),
            ],
        ),
    ]
