# Generated by Django 6.0.6 on 2026-06-29 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0022_add_unique_formatted_address_constraint'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='attachment',
            index=models.Index(fields=['content_type', 'object_id'], name='attachment_gfk_idx'),
        ),
        migrations.AddIndex(
            model_name='phonenumber',
            index=models.Index(fields=['content_type', 'object_id'], name='phonenumber_gfk_idx'),
        ),
    ]
