compressionLevel: mixed

enableGlobalCache: false

nodeLinker: node-modules

cacheFolder: './../../.yarn/cache'
deferredVersionFolder: './../../.yarn/versions'
patchFolder: '../../.yarn/patches'
pnpUnpluggedFolder: '../../.yarn/unplugged'
virtualFolder: './../../.yarn/__virtual__'
