from _typeshed import Incomplete
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth2.provider import OAuth2Provider as OAuth2Provider

class TwitterOAuth2Account(ProviderAccount):
    def get_username(self): ...
    def get_profile_url(self): ...
    def get_avatar_url(self): ...
    def to_str(self): ...

class TwitterOAuth2Provider(OAuth2Provider):
    id: str
    name: str
    account_class = TwitterOAuth2Account
    pkce_enabled_default: bool
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...
    def get_fields(self): ...
    def get_default_scope(self): ...

provider_classes: Incomplete
