// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { RoomsQuery } from './useRooms.generated';

export const roomsOperationKey: keyof Omit<RoomsQuery, '__typename'> = 'rooms';
export const roomsSuccessTypename: Extract<
  NonNullable<RoomsQuery['rooms']>,
  { __typename: 'RoomTypeOffsetPaginated' }
>['__typename'] = 'RoomTypeOffsetPaginated';

export const roomsMeta = {
  operationKey: roomsOperationKey,
  successTypename: roomsSuccessTypename,
} as const;
