// Auto-generated by tools/codegen/plugins/operation-meta-plugin.cjs — do not edit

import type { UpdateClientContactMutation } from './clientContact.generated';
import type { CreateClientContactMutation } from './clientContact.generated';

export const updateClientContactOperationKey: keyof Omit<UpdateClientContactMutation, '__typename'> = 'updateClientContact';
export const updateClientContactSuccessTypename: Extract<
  NonNullable<UpdateClientContactMutation['updateClientContact']>,
  { __typename: 'ClientContactType' }
>['__typename'] = 'ClientContactType';

export const updateClientContactMeta = {
  operationKey: updateClientContactOperationKey,
  successTypename: updateClientContactSuccessTypename,
} as const;

export const createClientContactOperationKey: keyof Omit<CreateClientContactMutation, '__typename'> = 'createClientContact';
export const createClientContactSuccessTypename: Extract<
  NonNullable<CreateClientContactMutation['createClientContact']>,
  { __typename: 'ClientContactType' }
>['__typename'] = 'ClientContactType';

export const createClientContactMeta = {
  operationKey: createClientContactOperationKey,
  successTypename: createClientContactSuccessTypename,
} as const;
