export const FILE_CATEGORIES = [
  { id: 1, name: 'Personal Identification', status: 1 },
  { id: 9, name: 'HPRP Documentation', status: 1 },
  { id: 10, name: 'Finances and Income', status: 1 },
  { id: 11, name: 'Health and Medical', status: 1 },
  { id: 12, name: 'Family, Social and Legal', status: 1 },
] as const;

export const FILE_SUBCATEGORIES = [
  // ref_category: 1 (Personal Identification)
  { id: 1, name: 'Birth Certificate', ref_category: 1, status: 1 },
  {
    id: 2,
    name: "Driver's License or State ID Card",
    ref_category: 1,
    status: 1,
  },
  { id: 3, name: 'Hospital Record of Birth', ref_category: 1, status: 1 },
  { id: 11, name: 'Photo ID Card', ref_category: 1, status: 1 },
  {
    id: 12,
    name: 'Listing in Telephone Directory',
    ref_category: 1,
    status: 1,
  },
  { id: 13, name: 'Naturalization Certificate', ref_category: 1, status: 1 },
  { id: 14, name: 'Passport or Visa', ref_category: 1, status: 1 },
  { id: 15, name: 'School Identification Card', ref_category: 1, status: 1 },
  { id: 16, name: 'Social Security Card', ref_category: 1, status: 1 },
  { id: 17, name: 'Voter Registration Card', ref_category: 1, status: 1 },

  // ref_category: 9 (HPRP Documentation)
  { id: 18, name: 'Supplemental Application', ref_category: 9, status: 1 },
  { id: 19, name: 'ID Photo Cards', ref_category: 9, status: 1 },
  { id: 20, name: 'Social Security Cards', ref_category: 9, status: 1 },
  { id: 21, name: 'Birth Certificates', ref_category: 9, status: 1 },
  { id: 22, name: 'Client Contract', ref_category: 9, status: 1 },
  {
    id: 23,
    name: 'Consent to Exchange Information',
    ref_category: 9,
    status: 1,
  },
  { id: 24, name: 'Shared Care Agreement', ref_category: 9, status: 1 },
  { id: 25, name: 'Housing Needs Matrix', ref_category: 9, status: 1 },
  { id: 26, name: 'Evidence of Crisis', ref_category: 9, status: 1 },
  { id: 27, name: 'Third Party Verification', ref_category: 9, status: 1 },
  {
    id: 28,
    name: 'Proof of Income (30 to 90 days)',
    ref_category: 9,
    status: 1,
  },
  {
    id: 29,
    name: 'Food Stamp Card or Award Letter',
    ref_category: 9,
    status: 1,
  },
  { id: 30, name: 'Income and Assets Declaration', ref_category: 9, status: 1 },
  { id: 31, name: 'Budgets', ref_category: 9, status: 1 },
  { id: 32, name: 'Evidence of Sustainability', ref_category: 9, status: 1 },
  { id: 33, name: 'Lease', ref_category: 9, status: 1 },
  {
    id: 34,
    name: 'Lead Screening (child 0-5 in home)',
    ref_category: 9,
    status: 1,
  },
  { id: 35, name: 'Eviction/Forclosure Notice', ref_category: 9, status: 1 },
  { id: 36, name: 'Utility Bill', ref_category: 9, status: 1 },
  { id: 37, name: 'W-9 for Landlord', ref_category: 9, status: 1 },

  // ref_category: 10 (Finances and Income)
  { id: 50, name: 'Alimony Agreement', ref_category: 10, status: 1 },
  { id: 51, name: 'Bank Records', ref_category: 10, status: 1 },
  { id: 52, name: 'IRS Form Letter', ref_category: 10, status: 1 },
  { id: 53, name: 'Cancelled Check', ref_category: 10, status: 1 },
  { id: 54, name: 'Dividends Statement', ref_category: 10, status: 1 },
  { id: 55, name: 'Home Mortgage', ref_category: 10, status: 1 },
  { id: 56, name: 'Lease', ref_category: 10, status: 1 },
  { id: 57, name: 'Pay Check Stub', ref_category: 10, status: 1 },
  { id: 58, name: 'Pension Statement', ref_category: 10, status: 1 },
  {
    id: 59,
    name: 'Pink Slip (Notice of Job Termination)',
    ref_category: 10,
    status: 1,
  },
  { id: 60, name: 'Public Assistance Check Stub', ref_category: 10, status: 1 },
  { id: 61, name: 'W-2 Form', ref_category: 10, status: 1 },
  {
    id: 62,
    name: 'Social Security Benefit Check',
    ref_category: 10,
    status: 1,
  },
  { id: 63, name: 'Utility Bill', ref_category: 10, status: 1 },
  { id: 64, name: 'Letter from Employer', ref_category: 10, status: 1 },
  {
    id: 65,
    name: 'Letter from Workers Compensation',
    ref_category: 10,
    status: 1,
  },
  { id: 66, name: 'Insurance Policy', ref_category: 10, status: 1 },
  { id: 67, name: 'Other Financial Document', ref_category: 10, status: 1 },
  { id: 68, name: 'Tax Return', ref_category: 10, status: 1 },
  { id: 69, name: 'Unemployment Check Stub', ref_category: 10, status: 1 },

  // ref_category: 11 (Health and Medical)
  { id: 78, name: 'Hospital Record of Birth', ref_category: 11, status: 1 },
  { id: 79, name: 'Letter from Physician', ref_category: 11, status: 1 },
  { id: 80, name: 'Medical Records', ref_category: 11, status: 1 },
  { id: 81, name: 'Medical Bill', ref_category: 11, status: 1 },
  {
    id: 82,
    name: 'Health Insurance Documentation',
    ref_category: 11,
    status: 1,
  },
  { id: 83, name: 'Letter or Records from VA', ref_category: 11, status: 1 },
  { id: 84, name: 'MedicAid or MediCare Card', ref_category: 11, status: 1 },
  {
    id: 85,
    name: 'Observable Disability or Health Condition',
    ref_category: 11,
    status: 1,
  },
  { id: 86, name: 'Rehabilitation Evaluation', ref_category: 11, status: 1 },
  {
    id: 87,
    name: 'Letter from Therapist or Psychiatrist',
    ref_category: 11,
    status: 1,
  },
  {
    id: 88,
    name: 'Other Health and Medical Document',
    ref_category: 11,
    status: 1,
  },

  // ref_category: 12 (Family, Social and Legal)
  { id: 89, name: 'Alimony Agreement', ref_category: 12, status: 1 },
  { id: 90, name: 'Court Order or Records', ref_category: 12, status: 1 },
  { id: 91, name: 'Divorce Decree', ref_category: 12, status: 1 },
  {
    id: 92,
    name: 'Letter from Social Service Agency',
    ref_category: 12,
    status: 1,
  },
  {
    id: 93,
    name: 'Marriage License or Certificate',
    ref_category: 12,
    status: 1,
  },
  { id: 94, name: 'Letter from Parole Board', ref_category: 12, status: 1 },
  { id: 95, name: 'Naturalization Record', ref_category: 12, status: 1 },
  { id: 96, name: 'Police Citations', ref_category: 12, status: 1 },
  { id: 97, name: 'Passport or Visa', ref_category: 12, status: 1 },
  { id: 98, name: 'Voter Registration Card', ref_category: 12, status: 1 },
  { id: 99, name: 'Other Family Document', ref_category: 12, status: 1 },
  { id: 100, name: 'Other Social Document', ref_category: 12, status: 1 },
  { id: 101, name: 'Other Legal Document', ref_category: 12, status: 1 },
] as const;
