from clients.models import ClientProfile
from common.models import Address
from common.permissions.config import TemplateConfig

from shelters.models.availability import ShelterAvailability
from shelters.models.lookups import (
    Accessibility,
    City,
    Demographic,
    EntryRequirement,
    ExitPolicy,
    Funder,
    Parking,
    Pet,
    ReferralRequirement,
    RoomStyle,
    ShelterProgram,
    ShelterType,
    SPA,
    SpecialSituationRestriction,
    Storage,
    VaccinationRequirement,
)
from shelters.models.media import (
    ExteriorShelterPhoto,
    InteriorShelterPhoto,
    MediaLink,
    ShelterPhoto,
    Video,
)
from shelters.models.reservation import Reservation
from shelters.models.schedule import Schedule
from shelters.models.service import Service, ServiceCategory
from shelters.models.shelter import Bed, ContactInfo, Room, Shelter

SHELTER_OPERATOR = TemplateConfig(
    name="Shelter Operator",
    permissions=[
        Shelter.perms.ADD,
        Shelter.perms.CHANGE,
        Shelter.perms.DELETE,
        Shelter.perms.VIEW,
        Bed.perms.ADD,
        Bed.perms.CHANGE,
        Bed.perms.DELETE,
        Bed.perms.VIEW,
        Room.perms.ADD,
        Room.perms.CHANGE,
        Room.perms.DELETE,
        Room.perms.VIEW,
        Reservation.perms.ADD,
        Reservation.perms.CHANGE,
        Reservation.perms.DELETE,
        Reservation.perms.VIEW,
        Shelter.perms.VIEW_PRIVATE,
        ClientProfile.perms.VIEW,
    ],
    invite_html="account/email/shelter_operator_invite.html",
    invite_txt="account/messages/shelter_operator_invite.txt",
    welcome_html="shelters/email/shelter_operator_welcome.html",
    welcome_txt="shelters/email/shelter_operator_welcome.txt",
    base_url_setting="SHELTER_WEB_BASE_URL",
)

GLOBAL_SHELTER_OPERATOR = TemplateConfig(
    name="Global Shelter Operator",
    permissions=[
        # ── Core shelter models: full CRUD ──
        Shelter.perms.ADD,
        Shelter.perms.CHANGE,
        Shelter.perms.DELETE,
        Shelter.perms.VIEW,
        Bed.perms.ADD,
        Bed.perms.CHANGE,
        Bed.perms.DELETE,
        Bed.perms.VIEW,
        Room.perms.ADD,
        Room.perms.CHANGE,
        Room.perms.DELETE,
        Room.perms.VIEW,
        Reservation.perms.ADD,
        Reservation.perms.CHANGE,
        Reservation.perms.DELETE,
        Reservation.perms.VIEW,
        # ── Custom perms ──
        Shelter.perms.VIEW_PRIVATE,
        ClientProfile.perms.VIEW,
        # ── common ──
        Address.perms.ADD,
        Address.perms.CHANGE,
        Address.perms.DELETE,
        Address.perms.VIEW,
        # ── shelters.lookups ──
        Accessibility.perms.ADD,
        Accessibility.perms.CHANGE,
        Accessibility.perms.DELETE,
        Accessibility.perms.VIEW,
        City.perms.ADD,
        City.perms.CHANGE,
        City.perms.DELETE,
        City.perms.VIEW,
        Demographic.perms.ADD,
        Demographic.perms.CHANGE,
        Demographic.perms.DELETE,
        Demographic.perms.VIEW,
        EntryRequirement.perms.ADD,
        EntryRequirement.perms.CHANGE,
        EntryRequirement.perms.DELETE,
        EntryRequirement.perms.VIEW,
        ExitPolicy.perms.ADD,
        ExitPolicy.perms.CHANGE,
        ExitPolicy.perms.DELETE,
        ExitPolicy.perms.VIEW,
        Funder.perms.ADD,
        Funder.perms.CHANGE,
        Funder.perms.DELETE,
        Funder.perms.VIEW,
        Parking.perms.ADD,
        Parking.perms.CHANGE,
        Parking.perms.DELETE,
        Parking.perms.VIEW,
        Pet.perms.ADD,
        Pet.perms.CHANGE,
        Pet.perms.DELETE,
        Pet.perms.VIEW,
        ReferralRequirement.perms.ADD,
        ReferralRequirement.perms.CHANGE,
        ReferralRequirement.perms.DELETE,
        ReferralRequirement.perms.VIEW,
        RoomStyle.perms.ADD,
        RoomStyle.perms.CHANGE,
        RoomStyle.perms.DELETE,
        RoomStyle.perms.VIEW,
        ShelterProgram.perms.ADD,
        ShelterProgram.perms.CHANGE,
        ShelterProgram.perms.DELETE,
        ShelterProgram.perms.VIEW,
        ShelterType.perms.ADD,
        ShelterType.perms.CHANGE,
        ShelterType.perms.DELETE,
        ShelterType.perms.VIEW,
        SPA.perms.ADD,
        SPA.perms.CHANGE,
        SPA.perms.DELETE,
        SPA.perms.VIEW,
        SpecialSituationRestriction.perms.ADD,
        SpecialSituationRestriction.perms.CHANGE,
        SpecialSituationRestriction.perms.DELETE,
        SpecialSituationRestriction.perms.VIEW,
        Storage.perms.ADD,
        Storage.perms.CHANGE,
        Storage.perms.DELETE,
        Storage.perms.VIEW,
        VaccinationRequirement.perms.ADD,
        VaccinationRequirement.perms.CHANGE,
        VaccinationRequirement.perms.DELETE,
        VaccinationRequirement.perms.VIEW,
        # ── shelters.media ──
        ExteriorShelterPhoto.perms.ADD,
        ExteriorShelterPhoto.perms.CHANGE,
        ExteriorShelterPhoto.perms.DELETE,
        ExteriorShelterPhoto.perms.VIEW,
        InteriorShelterPhoto.perms.ADD,
        InteriorShelterPhoto.perms.CHANGE,
        InteriorShelterPhoto.perms.DELETE,
        InteriorShelterPhoto.perms.VIEW,
        MediaLink.perms.ADD,
        MediaLink.perms.CHANGE,
        MediaLink.perms.DELETE,
        MediaLink.perms.VIEW,
        ShelterPhoto.perms.ADD,
        ShelterPhoto.perms.CHANGE,
        ShelterPhoto.perms.DELETE,
        ShelterPhoto.perms.VIEW,
        Video.perms.ADD,
        Video.perms.CHANGE,
        Video.perms.DELETE,
        Video.perms.VIEW,
        # ── shelters misc ──
        ContactInfo.perms.ADD,
        ContactInfo.perms.CHANGE,
        ContactInfo.perms.DELETE,
        ContactInfo.perms.VIEW,
        Schedule.perms.ADD,
        Schedule.perms.CHANGE,
        Schedule.perms.DELETE,
        Schedule.perms.VIEW,
        Service.perms.ADD,
        Service.perms.CHANGE,
        Service.perms.DELETE,
        Service.perms.VIEW,
        ServiceCategory.perms.ADD,
        ServiceCategory.perms.CHANGE,
        ServiceCategory.perms.DELETE,
        ServiceCategory.perms.VIEW,
        ShelterAvailability.perms.ADD,
        ShelterAvailability.perms.CHANGE,
        ShelterAvailability.perms.DELETE,
        ShelterAvailability.perms.VIEW,
    ],
    is_invitable=False,
    welcome_html="shelters/email/shelter_operator_welcome.html",
    welcome_txt="shelters/email/shelter_operator_welcome.txt",
    base_url_setting="SHELTER_WEB_BASE_URL",
)
