from allauth.account.models import EmailAddress as EmailAddress
from allauth.socialaccount import providers as providers
from allauth.socialaccount.providers.base import ProviderAccount as ProviderAccount
from allauth.socialaccount.providers.oauth2.provider import OAuth2Provider as OAuth2Provider

class FigmaAccount(ProviderAccount):
    def to_str(self): ...
    def get_avatar_url(self): ...

class FigmaProvider(OAuth2Provider):
    id: str
    name: str
    account_class = FigmaAccount
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...
    def extract_email_addresses(self, data): ...
