"""
This type stub file was generated by pyright.
"""

def bind_and_listen(sock, address=..., backlog=..., reuse_addr=...): # -> None:
    ...

def tcp_listener(address=..., backlog=..., reuse_addr=...):
    """A shortcut to create a TCP socket, bind it and put it into listening state."""
    ...

def udp_listener(address=..., reuse_addr=...):
    """A shortcut to create a UDF socket, bind it and put it into listening state."""
    ...

