from .app_settings import api_settings as api_settings
from _typeshed import Incomplete
from rest_framework_simplejwt.authentication import JWTAuthentication
from rest_framework_simplejwt.serializers import TokenRefreshSerializer

def set_jwt_access_cookie(response, access_token) -> None: ...
def set_jwt_refresh_cookie(response, refresh_token) -> None: ...
def set_jwt_cookies(response, access_token, refresh_token) -> None: ...
def unset_jwt_cookies(response) -> None: ...

class CookieTokenRefreshSerializer(TokenRefreshSerializer):
    refresh: Incomplete
    def extract_refresh_token(self): ...
    def validate(self, attrs): ...

def get_refresh_view(): ...

class JWTCookieAuthentication(JWTAuthentication):
    def enforce_csrf(self, request) -> None: ...
    def authenticate(self, request): ...
