from _typeshed import Incomplete

class AuthenticationMiddleware:
    get_response: Incomplete
    def __init__(self, get_response) -> None: ...
    def __call__(self, request): ...
    def process_request(self, request): ...
    @staticmethod
    def is_safari(request): ...
    @staticmethod
    def get_redirect(request): ...
