from _typeshed import Incomplete

def get_token(user, scope: str = ...): ...
def get_parameters(user, scope: str = ...): ...
def get_query_string(user, scope: str = ...): ...
def get_user(request_or_sesame, scope: str = ..., max_age: Incomplete | None = ..., *, update_last_login: Incomplete | None = ...): ...
