from _typeshed import Incomplete
from django.contrib.auth import REDIRECT_FIELD_NAME
from django.contrib.auth.views import RedirectURLMixin
from django.views.generic import View

class RedirectURLMixin:
    next_page: Incomplete
    redirect_field_name = REDIRECT_FIELD_NAME
    success_url_allowed_hosts: Incomplete
    def get_success_url(self): ...
    def get_redirect_url(self): ...
    def get_success_url_allowed_hosts(self): ...
    def get_default_redirect_url(self): ...

class LoginView(RedirectURLMixin, View):
    scope: str
    max_age: Incomplete
    next_page: Incomplete
    def get(self, request): ...
    def login_failed(self) -> None: ...
    def login_success(self): ...
