from _typeshed import Incomplete
from allauth.account.models import EmailAddress as EmailAddress
from allauth.socialaccount.providers.base import Provider as Provider, ProviderAccount as ProviderAccount

class PersonaAccount(ProviderAccount):
    def to_str(self): ...

class PersonaProvider(Provider):
    id: str
    name: str
    account_class = PersonaAccount
    def media_js(self, request): ...
    def get_login_url(self, request, **kwargs): ...
    def extract_uid(self, data): ...
    def extract_common_fields(self, data): ...
    def extract_email_addresses(self, data): ...

provider_classes: Incomplete
