from _typeshed import Incomplete
from typing import NamedTuple

class Rate(NamedTuple):
    amount: Incomplete
    duration: Incomplete

def parse(rate): ...
def clear(request, *, action, key: Incomplete | None = ..., user: Incomplete | None = ...) -> None: ...
def consume(request, *, action, key: Incomplete | None = ..., amount: Incomplete | None = ..., duration: Incomplete | None = ..., user: Incomplete | None = ...): ...
def consume_or_429(request, *args, **kwargs): ...
