name: ESLint
on:
  pull_request:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18'
    - name: Install dependencies
      run: yarn install
    - name: Run ESLint for App 1
      run: yarn nx lint undefined
    - name: Run ESLint for App 2
      run: yarn nx lint undefined-e2e
