"""Shelter GraphQL types, inputs, filters, and ordering definitions."""

from shelters.types.filters import (BedFilter, BedOrder, GeolocationInput,
                                    MapBoundsInput, ReservationFilter,
                                    ReservationOrder, RoomFilter, RoomOrder,
                                    ShelterFilter, ShelterOrder,
                                    ShelterPropertyInput)
from shelters.types.inputs import (CreateBedInput, CreateReservationInput,
                                   CreateRoomInput, CreateShelterInput,
                                   GenerateShelterPhotoUploadsInput,
                                   ResolveShelterPhotoUploadsInput,
                                   ScheduleInput, ServiceInput,
                                   ShelterLocationInput,
                                   ShelterPhotoFromUploadInput,
                                   ShelterPhotoUploadItemInput, UpdateBedInput,
                                   UpdateReservationInput, UpdateRoomInput,
                                   UpdateShelterInput, UpdateShelterPhotoInput)
from shelters.types.lookups import (AccessibilityType, CityType,
                                    ContactInfoType, DemographicType,
                                    EntryRequirementType, FunderType,
                                    ParkingType, PetType, RoomStyleType,
                                    ScheduleType, ServiceCategoryType,
                                    ServiceType, ShelterProgramType,
                                    ShelterTypeType, SPAType,
                                    SpecialSituationRestrictionType,
                                    StorageType)
from shelters.types.outputs import (BedType, OperatorShelterType,
                                    ReservationType, RoomType,
                                    ShelterAvailabilityType,
                                    ShelterLocationType, ShelterPhotoType,
                                    ShelterPhotoUploadsType, ShelterType,
                                    ShelterTypeMixin)
from shelters.types.reporting import (DailyBedStatusMetricsType,
                                      DailyOccupancyMetricsType,
                                      ReservationMetricsType,
                                      ShelterOccupancyMetricsType)

__all__ = [
    # lookups
    "AccessibilityType",
    "CityType",
    "ContactInfoType",
    "DemographicType",
    "EntryRequirementType",
    "FunderType",
    "ParkingType",
    "PetType",
    "RoomStyleType",
    "ScheduleType",
    "ShelterProgramType",
    "ShelterTypeType",
    "SPAType",
    "SpecialSituationRestrictionType",
    "ServiceCategoryType",
    "ServiceType",
    "StorageType",
    # filters
    "BedFilter",
    "BedOrder",
    "GeolocationInput",
    "MapBoundsInput",
    "ReservationFilter",
    "ReservationOrder",
    "RoomFilter",
    "RoomOrder",
    "ShelterFilter",
    "ShelterOrder",
    "ShelterPropertyInput",
    # inputs
    "CreateBedInput",
    "CreateRoomInput",
    "CreateReservationInput",
    "CreateShelterInput",
    "GenerateShelterPhotoUploadsInput",
    "ResolveShelterPhotoUploadsInput",
    "UpdateShelterPhotoInput",
    "UpdateBedInput",
    "UpdateReservationInput",
    "UpdateRoomInput",
    "UpdateShelterInput",
    "ServiceInput",
    "ScheduleInput",
    "ShelterLocationInput",
    "ShelterPhotoFromUploadInput",
    "ShelterPhotoUploadItemInput",
    # outputs
    "BedType",
    "OperatorShelterType",
    "ReservationType",
    "RoomType",
    "ShelterAvailabilityType",
    "ShelterLocationType",
    "ShelterPhotoType",
    "ShelterPhotoUploadsType",
    "ShelterType",
    "ShelterTypeMixin",
    # reporting
    "DailyBedStatusMetricsType",
    "DailyOccupancyMetricsType",
    "ReservationMetricsType",
    "ShelterOccupancyMetricsType",
]
