"""Shelter GraphQL types, inputs, filters, and ordering definitions."""

from shelters.types.filters import (
    BedFilter,
    GeolocationInput,
    MapBoundsInput,
    RoomFilter,
    ShelterFilter,
    ShelterOrder,
    ShelterPropertyInput,
)
from shelters.types.inputs import (
    AcceptShelterInviteInput,
    CreateBedInput,
    CreateRoomInput,
    CreateShelterInput,
    RegisterShelterOperatorInput,
    ScheduleInput,
    ServiceInput,
    ShelterLocationInput,
)
from shelters.types.lookups import (
    AccessibilityType,
    CityType,
    ContactInfoType,
    DemographicType,
    EntryRequirementType,
    FunderType,
    ParkingType,
    PetType,
    RoomStyleType,
    ScheduleType,
    ServiceCategoryType,
    ServiceType,
    ShelterProgramType,
    ShelterTypeType,
    SPAType,
    SpecialSituationRestrictionType,
    StorageType,
)
from shelters.types.outputs import (
    AdminShelterType,
    BedType,
    RoomType,
    ShelterLocationType,
    ShelterPhotoType,
    ShelterType,
    ShelterTypeMixin,
)

__all__ = [
    # lookups
    "AccessibilityType",
    "CityType",
    "ContactInfoType",
    "DemographicType",
    "EntryRequirementType",
    "FunderType",
    "ParkingType",
    "PetType",
    "RoomStyleType",
    "ScheduleType",
    "ShelterProgramType",
    "ShelterTypeType",
    "SPAType",
    "SpecialSituationRestrictionType",
    "ServiceCategoryType",
    "ServiceType",
    "StorageType",
    # filters
    "BedFilter",
    "GeolocationInput",
    "MapBoundsInput",
    "RoomFilter",
    "ShelterFilter",
    "ShelterOrder",
    "ShelterPropertyInput",
    # inputs
    "AcceptShelterInviteInput",
    "CreateBedInput",
    "CreateRoomInput",
    "CreateShelterInput",
    "RegisterShelterOperatorInput",
    "ServiceInput",
    "ScheduleInput",
    "ShelterLocationInput",
    # outputs
    "AdminShelterType",
    "BedType",
    "RoomType",
    "ShelterLocationType",
    "ShelterPhotoType",
    "ShelterType",
    "ShelterTypeMixin",
]
