name: 'Setup Secrets'
description: 'Load secrets into .env file'

inputs:
  project:
    required: true
    type: string
  profile:
    required: true
    type: string
  secrets:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Clear All .env files and load eas.json
      run: |
        find . -name '*.env*' -delete
        cat eas.json | jq -r '.build["'"${{ inputs.profile }}"'"].env | select(. != null) | to_entries | .[] | "\(.key)=\(.value)"' >> .env
      shell: bash
      working-directory: apps/${{ inputs.project }}

    - name: Load Application Secrets
      run: |
        echo "Filtering secrets with prefix 'EXPO_PUBLIC'"
        # Filter secrets with the prefix 'EXPO_PUBLIC' which are not necessarily real secrets
        # but include items such as API keys and configurations (e.g., Google API keys)
        # that we prefer not to commit directly into our GitHub repository.
        secrets=$(echo '${{ inputs.secrets }}' | jq -r 'to_entries | map(select(.key | startswith("EXPO_PUBLIC"))) | .[] | "\(.key)=\(.value)"')

        echo "secrets"
        # Write the filtered secrets to the .env file
        while IFS= read -r line; do
          echo "$line"
          echo "$line" >> .env
        done <<< "$secrets"
      shell: bash
      working-directory: apps/${{ inputs.project }}

    - name: Delete .env file at end of job
      if: always()
      run: |
        rm -f .env
      shell: bash
      working-directory: apps/${{ inputs.project }}
