name: 'Setup Secrets'
description: 'Load secrets into .env file'

inputs:
  project:
    required: true
    type: string
  profile:
    required: true
    type: string

runs:
  using: 'composite'
  steps:
    - name: Clear All .env files and load eas.json
      run: |
        find . -name '*.env*' -delete
        cat eas.json | jq -r '.build["'"${{ inputs.profile }}"'"].env | select(. != null) | to_entries | .[] | "\(.key)=\(.value)"' >> .env
      shell: bash
      working-directory: apps/${{ inputs.project }}

    - name: Load Application Secrets
      run: |
        echo "Loading secrets prefixed with 'EXPO_PUBLIC_'"
        printenv
        for var in $(printenv | grep '^EXPO_PUBLIC_'); do
          echo "$var" >> .env
        done
      shell: bash
      working-directory: apps/${{ inputs.project }}

    - name: Delete .env file at end of job
      if: always()
      run: |
        rm -f .env
      shell: bash
      working-directory: apps/${{ inputs.project }}
